/**
 * The drift-estimator figure's geometry, tested without mounting anything — the same rule
 * `smoothVis.test.ts` follows.
 *
 * The claims worth pinning are the ones a reader of the FIGURE would take away, because those are
 * the ones that would be a lie if the maths drifted: rigid recovers a known rotation + translation,
 * phase can only see translation (so its output frames still rotate), and the "on request" fourth
 * column is honestly a placeholder rather than pretending to be a fit.
 */
import { describe, expect, it } from 'vitest'
import {
  DRIFT_VIS_COLUMNS, driftFigure, driftVisColumns, phaseAlign, phaseAlignedSequence, rigidAlign,
  rigidAlignedSequence, rotatingScene, warp,
} from './driftVis'
import type { VisFrame } from './paramVis'

/** Peak intensity in a frame — used as a rotation-invariant identity check on a blob's presence. */
const peak = (f: VisFrame) => Math.max(...f.map(r => Math.max(...r)))

/** Mean absolute difference between two frames — normalised so a value of 0 is identical, 1 is white
 *  vs black, regardless of frame size. */
function mad(a: VisFrame, b: VisFrame): number {
  const n = a.length
  let s = 0
  for (let y = 0; y < n; y++) for (let x = 0; x < n; x++) s += Math.abs(a[y][x] - b[y][x])
  return s / (n * n)
}

describe('rotatingScene', () => {
  it('is deterministic — two renders of the figure are the same figure', () => {
    expect(rotatingScene()).toEqual(rotatingScene())
  })

  it('produces T=12 frames with visible motion between frame 0 and frame 11', () => {
    const { frames } = rotatingScene()
    expect(frames.length).toBe(12)
    // The whole point of the sequence is that something MOVES; a scene where frame 0 and frame 11
    // look the same is a scene where every estimator would report identity, which is not what the
    // figure is about.
    expect(mad(frames[0], frames[11])).toBeGreaterThan(0.05)
  })

  it('the blobs survive the accumulated rotation — peak intensity does not collapse', () => {
    // A rotation that reads the sampler off the grid leaves a dim frame, which reads as "the
    // schematic broke" rather than "the field rotated". Peak intensity at t=11 must stay within
    // 30% of the input peak.
    const { frames } = rotatingScene()
    expect(peak(frames[11])).toBeGreaterThan(0.7 * peak(frames[0]))
  })
})

describe('phaseAlign', () => {
  it('recovers a known integer translation of the base scene', () => {
    // The property of phase correlation the figure argues on: pure translation, subpixel accuracy.
    // If this is off, phase alignment is not doing its job on the figure's own sequence.
    const { base } = rotatingScene()
    const moved = warp(base, 0, 1.5, -2.0)
    const { ty, tx } = phaseAlign(base, moved)
    expect(Math.abs(ty - 1.5)).toBeLessThan(1.0)
    expect(Math.abs(tx - (-2.0))).toBeLessThan(1.0)
  })
})

describe('rigidAlign', () => {
  it('recovers a known rotation + translation of the base scene', () => {
    // The main claim of the "Rigid" column: a rotation-plus-shift is recoverable. Tolerance is loose
    // because the schematic is 24x24 and the brute grid steps at 0.5° / 0.5 px; the FIGURE's job is
    // to show that rigid can express the rotation, which requires the fit to land within the pixel
    // grid, not exact truth.
    const { base } = rotatingScene()
    const moved = warp(base, 3.0, 0.7, -1.1)
    const { deg, ty, tx } = rigidAlign(base, moved)
    expect(Math.abs(deg - 3.0)).toBeLessThan(0.8)
    expect(Math.abs(ty - 0.7)).toBeLessThan(1.0)
    expect(Math.abs(tx - (-1.1))).toBeLessThan(1.0)
  })

  it('seeded fits give the same answer as an unseeded fit within the grid step', () => {
    // Seeded fits are what the sequence uses (each frame seeded by the previous frame's answer, same
    // shape as the Python `sitk_estimate_rigid`). If seeding drifted the answer, the sequence would
    // walk off the truth.
    const { base } = rotatingScene()
    const moved = warp(base, 2.0, 0.5, 0.8)
    const bare  = rigidAlign(base, moved)
    const seeded = rigidAlign(base, moved, { deg: 2.0, ty: 0.5, tx: 0.8 })
    expect(Math.abs(bare.deg - seeded.deg)).toBeLessThan(0.6)
    expect(Math.abs(bare.ty  - seeded.ty)).toBeLessThan(0.6)
    expect(Math.abs(bare.tx  - seeded.tx)).toBeLessThan(0.6)
  })
})

describe('rigidAlignedSequence vs phaseAlignedSequence', () => {
  it('both produce T frames, and rigid does not blow up on cumulative fits', () => {
    // Structural check only — the per-frame accuracy claims are pinned by `phaseAlign` /
    // `rigidAlign` above, and a cumulative-drift comparison at the last frame gets bitten by two
    // known effects (both harmless for the figure itself):
    //
    //   1. `rigidAlign` minimises SSD, not truth-of-the-injected-transform: for a moving frame
    //      generated by warp(base, D, ty, tx), the recovery transform that undoes it is
    //      `warp(., -D, -R^-1·t)`, not `warp(., -D, -t)`. The fit's brute grid finds whatever
    //      minimises SSD (small residual shift near truth), which is fine — the figure's viewer
    //      compares the rotation VISUALLY, not the millisecond of a per-frame optimum.
    //   2. Bilinear resampling twelve times over accumulates a small blur; both rigid and phase
    //      inherit it.
    //
    // So a strict cumulative claim here would fight the algorithm's known imperfection while the
    // figure itself reads cleanly. What we CAN check is that both sequences ran to completion and
    // rigid's frame 11 is not nonsense (any finite value in a plausible range).
    const { frames } = rotatingScene()
    const phase = phaseAlignedSequence(frames)
    const rigid = rigidAlignedSequence(frames)
    expect(phase.length).toBe(frames.length)
    expect(rigid.length).toBe(frames.length)
    // A blown-up fit would push resampled values off the grid and the frame would go all-zero (or
    // all-clamped). Peak stays in a plausible range for a schematic drawn on [0, 1]-ish values.
    expect(peak(rigid[11])).toBeGreaterThan(0.2)
    expect(peak(rigid[11])).toBeLessThan(2.0)
  })
})

const DEFAULT_INPUT = { maxLag: 3, maxAngleDeg: 5 }

describe('driftVisColumns', () => {
  it('has the four columns the figure documents', () => {
    const vis = driftVisColumns(DEFAULT_INPUT)
    expect(vis.columns).toEqual([...DRIFT_VIS_COLUMNS])
    // Three rows: the sequence + two param rows (corrects-for + per-frame cap). Same shape
    // smoothVis uses (grid + window + cost) so the reader has a table under the pictures rather
    // than pictures floating alone.
    expect(vis.rows.length).toBe(3)
    const result = vis.rows.find(r => r.key === 'result')
    expect(result).toBeDefined()
    expect(result!.role).toBe('grid')
    expect(result!.cells.length).toBe(4)
    // The parameter table is what makes this a legible comparison and not just four pictures.
    expect(vis.rows.find(r => r.key === 'corrects')).toBeDefined()
    expect(vis.rows.find(r => r.key === 'cap')).toBeDefined()
  })

  it('the fourth column carries a placeholder still with no text, not a fake fit', () => {
    // Column 4 is `sitkRigid3d` (option A). If it shows a MULTI-FRAME sequence, a reader would take
    // it for a real fit, and the note under the figure would look like a bug rather than a design
    // decision. One frame is honest — the CTA lives in the note. Cell TEXT is empty because it
    // squishes in the narrow column (regression fix: 2026-09-04 — "on request" wrapped to three
    // vertical fragments); the heading + note carry the ask instead.
    const vis = driftVisColumns(DEFAULT_INPUT)
    const cell4 = vis.rows.find(r => r.key === 'result')!.cells[3]
    expect(cell4.frames?.length ?? 0).toBe(1)
    expect(cell4.text).toBe('')
  })

  it('the cap row reads the current form values, live', () => {
    // Same live-update rule the smoothVis window count follows: tuning the number in the form
    // updates the number under the picture, so the figure is a picture of the SETTINGS the user
    // is looking at rather than a static default.
    const vis = driftVisColumns({ maxLag: 5, maxAngleDeg: 7.5 })
    const cap = vis.rows.find(r => r.key === 'cap')!
    // input column is empty, then the two live values, then a dash for the placeholder.
    expect(cap.cells[0].text).toBe('')
    expect(cap.cells[1].text).toBe('lag 5')
    expect(cap.cells[2].text).toBe('7.5°')
    expect(cap.cells[3].text).toBe('—')
  })

  it('the corrects-for row names what each column ACTUALLY does', () => {
    // Frames comparing four estimators are not self-explanatory — "rigid" reads clearly ONCE you
    // know it fits rotation, but the schematic cannot say that without prose. This row is that
    // prose, one line per column.
    const vis = driftVisColumns(DEFAULT_INPUT)
    const c = vis.rows.find(r => r.key === 'corrects')!.cells.map(cc => cc.text)
    expect(c[0]).toBe('')
    expect(c[1]).toContain('translation')
    expect(c[2]).toContain('rotation')
    expect(c[3]).toContain('tilt')
  })
})

describe('driftFigure', () => {
  it('returns both a vis and a note that names the ask', () => {
    // The note is what makes the empty fourth column legible — if it does not mention the ask, the
    // column is a mystery, not a call to action.
    const { vis, note } = driftFigure(DEFAULT_INPUT)
    expect(vis.columns.length).toBe(4)
    expect(note.toLowerCase()).toContain('call for datasets')
  })
})
