---
title: "Behaviour GCAMP"
output: html_document
date: '2022-08-15'
---

```{r setup, include=FALSE}
renv::load("~/R-workspace/cecelia/")
knitr::opts_chunk$set(echo = TRUE)
```

## Show transition states of live cell imaging

```{r}
Sys.setenv(KMP_DUPLICATE_LIB_OK = "TRUE")
devtools::load_all("../")
cciaUse("~/cecelia/dev")

library(ggplot2)
library(tidyverse)
```

```{r}
# set test variables
pID <- "8BR53W"
versionID <- 1
projectsDir <- "/Volumes/Analysis_SSD/Dominik/cecelia/projects/"
hpcDir <- "/data/scratch/projects/punim1124/cecelia/USERS/schienstockd/"
```

```{r}
# # get info on training images
# devtools::load_all("../")
# cciaUse("~/cecelia/dev", initConda = FALSE)
# 
# # init ccia object
# cciaObj <- initCciaObject(
#   pID = pID, uID = "LT47lJ", versionID = versionID, initReactivity = FALSE # Training
# )
# 
# # get experimental info
# exp.info <- as.data.table(cciaObj$summary(withSelf = FALSE, fields = c("Attr")))
# 
# length(unique(exp.info$uID))
# length(unique(exp.info$originUID))
```

```{r}
# rename
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# sIDs <- c("BeddcR", "ZXcUMO", "0Oenks", "YJRfCW")
# sIDs <- c("0Oenks", "YJRfCW")
sIDs <- c("LT47lJ")

backupDir <- "/Volumes/QUACK1/DOHERTY/CECELIA/projects/8BR53W/ANALYSIS"
```

```{r}
# rename
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

pID <- "QZwVFQ"
sIDs <- c("efgRsn")

backupDir <- "/Volumes/QUACK1/DOHERTY/CECELIA/projects/QZwVFQ/ANALYSIS"
```


```{r}
for (i in sIDs) {
# init ccia object
  cciaObj <- initCciaObject(
    pID = pID, uID = i, versionID = versionID, initReactivity = FALSE
  )
  
  print(paste(">>", cciaObj$getUID()))
  
  # analysis
  file.copy(
    cciaObj$persistentObjectDirectory(zero = FALSE),
    file.path(backupDir, "1"),
    recursive = TRUE, overwrite = TRUE
  )
  
  # go through images and copy 
  for (x in cciaObj$cciaObjects()) {
    # image
    file.copy(
      x$persistentObjectDirectory(zero = TRUE, uID = x$getUID()),
      file.path(backupDir, "0"),
      recursive = TRUE, overwrite = TRUE
    )
    
    # analysis
    file.copy(
      x$persistentObjectDirectory(zero = FALSE, uID = x$getUID()),
      file.path(backupDir, "1"),
      recursive = TRUE, overwrite = TRUE
    )
  }
}
```