---
title: "Behaviour GCAMP"
output: html_document
date: '2022-08-15'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Show transition states of live cell imaging

```{r}
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia")

library(ggplot2)
library(tidyverse)
```

```{r}
# set test variables
pID <- "8BR53W"
versionID <- 1
projectsDir <- "/Volumes/Analysis_SSD/Dominik/cecelia/projects/"
hpcDir <- "/data/scratch/projects/punim1124/cecelia/USERS/schienstockd/"
```

```{r}
anaDir <- "/Volumes/USER_data/Dominik/Experiments/DS_N030/ANALYSIS/IMAGE/clustering/skip3/"
```

```{r}
# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "BeddcR", versionID = versionID, initReactivity = FALSE #  GCAMP
)

# GCAMP
uIDs <- names(cciaObj$cciaObjects())
uIDs <- uIDs[!uIDs %in% c(
  # failed tracking
  "eSfB5I", "O3IRaQ", "a60Xzu",
  # did not work
  "aLtS86", "UR4NMo", "TwslTE",
  "KIzHom",
  # no TRITC cells
  "5rIRkE", "HLCoCr", "34Ow8s",
  "jAndy6", "RH7IVY",
  # exclude clustering
  "e5aJmm", "ALSjh5",
  # did not work for HMM
  # "nu0Nmo"
  # exclude
  "vbjZ4j"
)]
# remove clustering movies
uIDs <- uIDs[!uIDs %in% c(
  "mb2ri1", "GtMP6S", "RhxGrZ",
  "gatECw", "1Q16NA", "Itpddx",
  "KIzHom", "f5KlXo"
)]

# get experimental info
exp.info <- cciaObj$summary(
  withSelf = FALSE, fields = c("Attr"), uIDs = uIDs
)

# get clustering
tcells.sc <- as.data.table(cciaEnv()$LabelPropsUtils(
  cciaObj$persistentObjectDirectory(),
  value_name = "tracks.clusters.tcells.skip3.sc")$label_props_view()$as_df())

# get popDTs for set
popDTs <- cciaObj$popDT(
  popType = "live", pops = c(
    "tcells.gBT/tracked",
    "tcells.OTI/tracked"
    ),
  includeFiltered = TRUE,
  flushCache = TRUE,
  uIDs = uIDs)
```

```{r}
# how many movies and mice per treatment?
# exp.info %>% group_by(Treatment, DTx, Date) %>%
exp.info %>% group_by(Treatment, DTx) %>%
  summarise(movies = n()) %>%
  group_by(interaction(Treatment, DTx)) %>%
  summarise(
    mice = n(),
    sum_movies = sum(movies)
    ) 
  # mutate(movies_per_mouse = sum_movies/mice)
```


```{r fig_umap, fig.height=3, fig.width=3}
dfToPlot <- copy(tcells.sc) %>% left_join(exp.info)

# get mean positions of clusters
meanClusterPos <- dfToPlot %>%
  group_by(clusters) %>%
  summarise(
    UMAP_1 = mean(UMAP_1),
    UMAP_2 = mean(UMAP_2)
  )

# plot UMAP
ggplot(
  dfToPlot,
  aes(UMAP_1, UMAP_2)
  ) +
  geom_point(aes(color = clusters)) +
  theme_classic() +
  scale_color_brewer(name = NULL, palette = "Set1") +
  theme(
    axis.text = element_text(size = 15),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    legend.justification = "right",
    # legend.position = "bottom"
    legend.position = "none",
    axis.line = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
    )
  # geom_label(
  #   data = meanClusterPos,
  #   aes(label = clusters),
  #   label.size = 0.25,
  #   color = "black"
  #   )

ggsave(file.path(anaDir, "umap.tiff"), width = 5, height = 5)
```

```{r}
# show measurements of clusters to compare
colsToPlot <- rev(c(
  "GCAMP (ratio)",
  "angle",
  "speed",
  "compactness",
  "extent",
  "oblate",
  "prolate",
  "solidity",
  "sphericity",
  "surface_area",
  "volume"
))

# convert angle to degrees
popDTs[, live.cell.angle_deg := pracma::rad2deg(live.cell.angle)]

propsToPlot <- popDTs[exp.info, on = "uID"] %>%
  dplyr::rename(
    "GCAMP (ratio)" = "live.cell.peak.ratio.GCAMP",
    "speed" = "live.cell.speed",
    "angle" = "live.cell.angle_deg",
    "oblate" = "ellipticity_interm_oblate",
    "prolate" = "ellipticity_interm_prolate"
  ) %>%
  # drop_na(live.cell.hmm.state.hybrid_pop) %>%
  pivot_longer(
    cols = colsToPlot, names_to = "prop", values_to = "value"
    ) %>%
  pivot_longer(
    cols = c(
      "live.cell.hmm.state.gcamp"
    ), names_to = "hmm_type", values_to = "hmm_value"
    ) %>%
  dplyr::filter(!is.na(hmm_value))

propsToPlot$prop <- factor(propsToPlot$prop, levels = colsToPlot)

# rename
propsToPlot$hmm_name <- "High"
propsToPlot[propsToPlot$hmm_value == 1,]$hmm_name <- "Low"
propsToPlot[propsToPlot$hmm_value == 2,]$hmm_name <- "Negative"
```


```{r fig_hmm_props, fig.height=2, fig.width=2.5}
# show heatmap for HMM
propsSummary <- propsToPlot %>%
  group_by(hmm_type, hmm_name, prop) %>%
  replace_na(list(value = 0)) %>%
  summarise(mean = mean(value)) %>%
  group_by(hmm_type, prop) %>%
  mutate(freq = (mean - min(mean)) / (max(mean) - min(mean))) %>%
  arrange(-prop)

ggplot(propsSummary, aes(as.factor(hmm_name), prop)) +
  theme_classic() +
  geom_tile(aes(fill = freq), colour = "white", size = 0.5) +
  viridis::scale_fill_viridis(
    breaks = c(0, 1),
    labels = c(0, 1)
  ) +
  theme(
    # legend.position = "none",
    legend.title = element_blank(),
    legend.text = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    # axis.text.x = element_text(size = 12),
    axis.text.x = element_text(size = 12, angle = 45, hjust = 1, vjust = 1),
    strip.background = element_blank(),
    strip.text.x = element_blank(),
    ) +
  xlab("") + ylab("") +
  facet_grid(.~hmm_type)

ggsave(file.path(anaDir, "HMM_heat.pdf"), width = 3, height = 3)
```

```{r fig_GCAMP_trace, fig.height=2, fig.width=2}
# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "2b5uDC", versionID = versionID, initReactivity = FALSE
)

popDT <- cciaObj$popDT(
  "live", pops = c("tcells.gBT/tracked"),
  includeFiltered = TRUE)

# convert angle to degrees
popDT[, live.cell.angle_deg := pracma::rad2deg(live.cell.angle)]
popDT[, live.cell.hmm.state.gcamp.ordered := 0]
popDT[live.cell.hmm.state.gcamp == 2, live.cell.hmm.state.gcamp.ordered := 0]
popDT[live.cell.hmm.state.gcamp == 1, live.cell.hmm.state.gcamp.ordered := 1]
popDT[live.cell.hmm.state.gcamp == 3, live.cell.hmm.state.gcamp.ordered := 2]

colsToPlot <- list(
  "GCAMP HMM" = "live.cell.hmm.state.gcamp.ordered",
  "GCAMP/CTV" = "live.cell.peak.ratio.GCAMP",
  "Speed (um/min)" = "live.cell.speed",
  "Sphericity" = "sphericity"
)

trackToPlot <- popDT[track_id == 37, ] %>%
  pivot_longer(
    cols = unname(unlist(colsToPlot)), names_to = "measure", values_to = "value"
  ) %>%
  mutate(measure = factor(measure, levels = unname(unlist(colsToPlot))))

ggplot(
  trackToPlot,
  aes(x = (centroid_t * cciaObj$omeXMLTimelapseInfo()$interval))) +
  geom_line(aes(y = value), colour = "black") +
  theme_classic() +
  xlab("Time (min)") + ylab("") +
  theme(
    strip.background = element_blank(),
    strip.text.x = element_blank(),
    axis.text.y = element_text(size = 11),
    axis.text.x = element_text(size = 11),
    ) +
  facet_wrap(measure~., scales = "free_y", ncol = 1)
  
ggsave(file.path(anaDir, "2b5uDC_track-37.pdf"), width = 3, height = 3)
```

```{r fig_hmm_state_in_clusters, fig.height=1, fig.width=4}
# plot scanning v migrating cells for treatments
stainingCombinations <- stack(sapply(
  cciaObj$cciaObjects(uIDs = uIDs),
  function(x) paste(x$imChannelNames(), collapse = ",")
))
setnames(stainingCombinations, "values", "staining")
setnames(stainingCombinations, "ind", "uID")

# get track clusters for tracks with at least >= x GCAMP+
summaryDF <- popDTs %>%
# popDTs %>%
  group_by(uID, pop, live.cell.hmm.state.gcamp, live.cell.track.clusters.skip3) %>%
  summarise(n.clust = n()) %>%
  mutate(freq.clust = n.clust/sum(n.clust) * 100) %>%
  ungroup() %>%
  complete(
    uID, pop, live.cell.hmm.state.gcamp, live.cell.track.clusters.skip3,
    fill = list(freq.clust = 0)
    ) %>%
  dplyr::filter(
    !live.cell.track.clusters.skip3 %in% c("NA", NA),
    live.cell.hmm.state.gcamp == 3,
    live.cell.track.clusters.skip3 != 3
    ) %>%
  left_join(exp.info) %>%
  left_join(stainingCombinations)

summaryDF$cell_type <- str_extract(summaryDF$pop, "(?<=\\.)[:alnum:]+(?=/)")
summaryDF$stain <- str_extract(
  summaryDF$staining, sprintf("%s-[:alnum:]+", summaryDF$cell_type)
  )
# drop NA stain
summaryDF <- summaryDF %>% drop_na(stain)

# summaryDF$stain[is.na(summaryDF$stain)] <- "gBT-CTV"

# summaryDF[summaryDF$Treatment == "Uninfected",]$DTx <- ""
summaryDF[summaryDF$Treatment == "Uninfected",]$Treatment <- "PBS"

summaryDF$Treatment.DTx <- 0
summaryDF[summaryDF$Treatment == "PBS" & summaryDF$DTx == "PBS",]$Treatment.DTx <- 0
summaryDF[summaryDF$Treatment == "HSV" & summaryDF$DTx == "PBS",]$Treatment.DTx <- 1
summaryDF[summaryDF$Treatment == "HSV" & summaryDF$DTx == "DTx",]$Treatment.DTx <- 2

summaryDF$Stain.ID <- 0
summaryDF[summaryDF$stain == "OTI-CTV",]$Stain.ID <- 2
summaryDF[summaryDF$stain == "gBT-CTDR",]$Stain.ID <- 1

# plot
ggplot(summaryDF,
       aes(
         interaction(Treatment, DTx, stain), freq.clust,
         fill = as.factor(live.cell.track.clusters.skip3)
         )) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    # width = 0.3, alpha = 0.6) +
  # stat_summary(fun=mean, geom="point", size=3, shape=18, color="Magenta") +
  ylab("Frequency GCAMP+") + xlab("") +
  # ylim(0, 1) +
  scale_fill_brewer(name = NULL, palette = "Set3")

write.csv(summaryDF %>%
            dplyr::filter(live.cell.track.clusters.skip3 == 0),
          file.path(anaDir, "gcamp_behaviour_Mea.csv"))
write.csv(summaryDF %>%
            dplyr::filter(live.cell.track.clusters.skip3 == 1),
          file.path(anaDir, "gcamp_behaviour_Dir.csv"))
write.csv(summaryDF %>%
            dplyr::filter(live.cell.track.clusters.skip3 == 2),
          file.path(anaDir, "gcamp_behaviour_Sca.csv"))
write.csv(summaryDF %>%
            dplyr::filter(Treatment.DTx == 0),
          file.path(anaDir, "gcamp_behaviour_Uninf.csv"))
write.csv(summaryDF %>%
            dplyr::filter(Treatment.DTx == 1),
          file.path(anaDir, "gcamp_behaviour_PBS.csv"))
write.csv(summaryDF %>%
            dplyr::filter(Treatment.DTx == 2),
          file.path(anaDir, "gcamp_behaviour_DTx.csv"))
```

```{r fig_hmm_state_in_clusters, fig.height=1, fig.width=4}
# plot plot GCAMP for behaviour
stainingCombinations <- stack(sapply(
  cciaObj$cciaObjects(uIDs = uIDs),
  function(x) paste(x$imChannelNames(), collapse = ",")
))
setnames(stainingCombinations, "values", "staining")
setnames(stainingCombinations, "ind", "uID")

# get track clusters for tracks with at least >= x GCAMP+
summaryDF <- popDTs %>%
# popDTs %>%
  group_by(uID, pop, live.cell.track.clusters.skip3, live.cell.hmm.state.gcamp) %>%
  summarise(n.clust = n()) %>%
  mutate(freq.clust = n.clust/sum(n.clust) * 100) %>%
  ungroup() %>%
  complete(
    uID, pop, live.cell.track.clusters.skip3, live.cell.hmm.state.gcamp,
    fill = list(freq.clust = 0)
    ) %>%
  dplyr::filter(
    !live.cell.track.clusters.skip3 %in% c("NA", NA),
    live.cell.hmm.state.gcamp == 3,
    live.cell.track.clusters.skip3 != 3
    ) %>%
  left_join(exp.info) %>%
  left_join(stainingCombinations)

summaryDF$cell_type <- str_extract(summaryDF$pop, "(?<=\\.)[:alnum:]+(?=/)")
summaryDF$stain <- str_extract(
  summaryDF$staining, sprintf("%s-[:alnum:]+", summaryDF$cell_type)
  )
# drop NA stain
summaryDF <- summaryDF %>% drop_na(stain)

# summaryDF$stain[is.na(summaryDF$stain)] <- "gBT-CTV"

# summaryDF[summaryDF$Treatment == "Uninfected",]$DTx <- ""
summaryDF[summaryDF$Treatment == "Uninfected",]$Treatment <- "PBS"

summaryDF$Treatment.DTx <- 0
summaryDF[summaryDF$Treatment == "PBS" & summaryDF$DTx == "PBS",]$Treatment.DTx <- 0
summaryDF[summaryDF$Treatment == "HSV" & summaryDF$DTx == "PBS",]$Treatment.DTx <- 1
summaryDF[summaryDF$Treatment == "HSV" & summaryDF$DTx == "DTx",]$Treatment.DTx <- 2

summaryDF$Stain.ID <- 0
summaryDF[summaryDF$stain == "OTI-CTV",]$Stain.ID <- 2
summaryDF[summaryDF$stain == "gBT-CTDR",]$Stain.ID <- 1

# plot
ggplot(summaryDF,
       aes(
         interaction(Treatment, DTx, stain), freq.clust,
         fill = as.factor(live.cell.track.clusters.skip3)
         )) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    # width = 0.3, alpha = 0.6) +
  # stat_summary(fun=mean, geom="point", size=3, shape=18, color="Magenta") +
  ylab("Frequency GCAMP+") + xlab("") +
  # ylim(0, 1) +
  scale_fill_brewer(name = NULL, palette = "Set3")

write.csv(summaryDF %>%
            dplyr::filter(live.cell.track.clusters.skip3 == 0),
          file.path(anaDir, "Mea_gcamp.csv"))
write.csv(summaryDF %>%
            dplyr::filter(live.cell.track.clusters.skip3 == 1),
          file.path(anaDir, "Dir_gcamp.csv"))
write.csv(summaryDF %>%
            dplyr::filter(live.cell.track.clusters.skip3 == 2),
          file.path(anaDir, "Sca_gcamp.csv"))
```

```{r fig_flashing_freq, fig.height=1, fig.width=4}
# can you show the time between GCAMP peaks?
# for each track, get time for first/last GCAMP peak
# then count peaks within that range
stainingCombinations <- stack(sapply(
  cciaObj$cciaObjects(uIDs = uIDs),
  function(x) paste(x$imChannelNames(), collapse = ",")
))
setnames(stainingCombinations, "values", "staining")
setnames(stainingCombinations, "ind", "uID")

summaryDF <- popDTs %>%
  dplyr::filter(live.cell.hmm.state.gcamp == 3) %>%
  group_by(uID, pop, live.cell.track.clusters.skip3, track_id) %>%
  summarise(
    n = n(),
    first = min(centroid_t),
    last = max(centroid_t),
    median.diff = median(diff(centroid_t), na.rm = TRUE),
    mean.diff = mean(diff(centroid_t), na.rm = TRUE)
  ) %>%
  mutate(
    time = last - first,
    freq = n / time
    ) %>%
  mutate_all(function(x) ifelse(is.infinite(x), NA, x)) %>%
  dplyr::filter(
    !live.cell.track.clusters.skip3 %in% c("NA", NA),
    # live.cell.hmm.state.gcamp == 3,
    live.cell.track.clusters.skip3 != 3
    ) %>%
  left_join(exp.info) %>%
  left_join(stainingCombinations)

summaryDF$cell_type <- str_extract(summaryDF$pop, "(?<=\\.)[:alnum:]+(?=/)")
summaryDF$stain <- str_extract(
  summaryDF$staining, sprintf("%s-[:alnum:]+", summaryDF$cell_type)
  )
# drop NA stain
# summaryDF <- summaryDF %>% drop_na(stain)

# summaryDF$stain[is.na(summaryDF$stain)] <- "gBT-CTV"

# summaryDF[summaryDF$Treatment == "Uninfected",]$DTx <- ""
summaryDF[summaryDF$Treatment == "Uninfected",]$Treatment <- "PBS"

summaryDF$Treatment.DTx <- 0
summaryDF[summaryDF$Treatment == "PBS" & summaryDF$DTx == "PBS",]$Treatment.DTx <- 0
summaryDF[summaryDF$Treatment == "HSV" & summaryDF$DTx == "PBS",]$Treatment.DTx <- 1
summaryDF[summaryDF$Treatment == "HSV" & summaryDF$DTx == "DTx",]$Treatment.DTx <- 2

summaryDF$Stain.ID <- 0
summaryDF[summaryDF$stain == "OTI-CTV",]$Stain.ID <- 2
summaryDF[summaryDF$stain == "gBT-CTDR",]$Stain.ID <- 1

# plot
ggplot(summaryDF,
       aes(
         # interaction(Treatment, DTx, stain), freq,
         # interaction(Treatment, DTx, stain), median.diff,
         # interaction(Treatment, DTx, stain), n,
         interaction(Treatment, DTx, stain), time,
         fill = as.factor(live.cell.track.clusters.skip3)
         )) +
  theme_classic() +
  # geom_boxplot(outlier.alpha = 0) +
  geom_violin(scale = "width") +
  geom_jitter(
    position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    # width = 0.3, alpha = 0.6) +
  # stat_summary(fun=mean, geom="point", size=3, shape=18, color="Magenta") +
  ylab("Frequency GCAMP+") + xlab("") +
  # ylim(0, 100) +
  scale_fill_brewer(name = NULL, palette = "Set3")
```