---
title: "Behaviour GCAMP"
output: html_document
date: '2022-08-15'
---

```{r setup, include=FALSE}
renv::load("~/R-workspace/cecelia/")
knitr::opts_chunk$set(echo = TRUE)
```

## Show transition states of live cell imaging

```{r}
Sys.setenv(KMP_DUPLICATE_LIB_OK = "TRUE")
devtools::load_all("../")
cciaUse("~/cecelia/dev")

library(ggplot2)
library(tidyverse)
```

```{r}
# set test variables
pID <- "QZwVFQ"
versionID <- 1
projectsDir <- "/Volumes/USER/Dominik/cecelia/projects/"
hpcDir <- "/data/scratch/projects/punim1124/cecelia/USER_data/schienstockd/"
```

```{r}
anaDir <- "/Volumes/Lab-Mueller/Dominik Schienstock/Notebook/Experiments/3P_TESTS/Spleen/ANALYSIS"
```

```{r}
# HPC config
HPC_CONF <-  list(
  hpc = list(
    conf = list(
      email = "schienstockd@student.unimelb.edu.au",
      emailOnBegin = FALSE,
      emailOnEnd = FALSE,
      emailOnFail = TRUE,
      numNodes = 1,
      numTasks = 1,
      numCPUperTask = 1,
      numGPUperTask = 1,
      memory = 50,
      walltime = "00-02:00:00",
      projectPartitions = "gpu-a100",
      projectID = "punim1031",
      projectQos = "",
      useGPU = TRUE
    )
  ),
  utils = list(
    ssh = list(
      username = "schienstockd",
      address = "spartan.hpc.unimelb.edu.au",
      keyfile = "/Users/Dominik/.ssh/spartan_rsa"
    ),
    python = list(
      condaEnv = cciaConf()$python$conda$source$env,
      condaDir = cciaConf()$python$conda$dir
    )
  )
)
```

```{r}
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "efgRsn", versionID = versionID, initReactivity = FALSE
)

# the pixel resolution is wrong. Can you change this for all images ..
# to replace PhysicalSizeX="1.058" and PhysicalSizeY="1.058"
for (x in cciaObj$cciaObjects()) {
  for (i in x$valueNames("imFilepath")) {
    omeXMLFilepath <- file.path(x$imFilepath(i), "OME", "METADATA.ome.xml")

    # read xml and replace
    # https://stackoverflow.com/a/68919673
    readLines(omeXMLFilepath) |>
      stringr::str_replace(
        pattern = "PhysicalSizeX=\"1.058\"",
        replace = "PhysicalSizeX=\"0.529\"") |>
      stringr::str_replace(
        pattern = "PhysicalSizeY=\"1.058\"",
        replace = "PhysicalSizeY=\"0.529\"") |>
      # not sure why this is different in some images ..
      stringr::str_replace(
        pattern = "PhysicalSizeX=\"1.013\"",
        replace = "PhysicalSizeX=\"0.5065\"") |>
      stringr::str_replace(
        pattern = "PhysicalSizeY=\"1.013\"",
        replace = "PhysicalSizeY=\"0.5065\"") |>
      writeLines(con = omeXMLFilepath)
  }
}
```

```{r}
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "kEHa3K", versionID = versionID, initReactivity = FALSE # DTx
)

cciaObj$omeXMLTimelapseInfo()
```

```{r}
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "efgRsn", versionID = versionID, initReactivity = FALSE # DTx
)

# get experimental info
exp.info <- as.data.table(cciaObj$summary(
  withSelf = FALSE, fields = c("Attr", "oriFilepath")
))

# data.table::fwrite(exp.info, file.path(anaDir, "exp_info.csv"))

uIDs <- exp.info[Include == "Y" & Type == "Live"]$uID
# uIDs <- exp.info[Include == "Y" & Type == "Live" & Location == "WP"]$uID

# get clustering for WP
# tcells.sc <- as.data.table(cciaEnv()$LabelPropsUtils(
#   cciaObj$persistentObjectDirectory(),
#   value_name = "tracks.clusters.tom.wp_movement.sc")$label_props_view()$as_df())
# 
# clusterMapping <- list(
#   Directed = c(2),
#   Crawling = c(0,3,4),
#   Sessile = c(1)
#   # Other = c(4)
# )
# 
# tcells.sc <- .mapClustNames(tcells.sc, clusterMapping, "clusters", nameCol = "pop")

tcells.sc <- cciaObj$popDT(
  popType = "clust", pops = c("Directed", "Sessile", "Crawling", "Fast",
                              "Crawl directed", "Crawl undirected", "Confined"),
                              # "Other"),
  includeFiltered = TRUE,
  flushCache = TRUE,
  uIDs = uIDs, valueName = "tracks.clusters.tom.movement")

# get popDTs for set
popDTs <- cciaObj$popDT(
  popType = "live", pops = c("Tom/tracked"),
  includeFiltered = TRUE,
  flushCache = TRUE,
  uIDs = uIDs)

# track measures
# tracksMeasures <- cciaObj$tracksMeasures(pops = c("Tom/tracked"), uIDs = uIDs)

# paramsToGet <- c(
#   "live.cell.contact#branch.SHG.branch",
#   "live.cell.min_distance#branch.SHG.branch",
#   "live.cell.contact#branch.SHG.branch__two",
#   "live.cell.min_distance#branch.SHG.branch__two"
#   )
# tracksMeasures <- rbindlist(list(
#   gBT = cciaObj$tracksInfo(paramsToGet, parentPop = "Tom/tracked", uIDs = uIDs)
# ), idcol = "pop") %>% left_join(
#   cciaObj$tracksMeasures(pops = c("Tom/tracked"), uIDs = uIDs)
# )
```

```{r}
# can you show the flow patterns of SHG and then the movement of cells
# TODO these could be multiple. Only one for now
unsLabels <- c("SHG.branch", "DCs.branch")
uns <- list()

for (i in unsLabels) {
  uns[[i]] <- list()
  
  for (x in cciaObj$cciaObjects(uIDs = uIDs)) {
    labels <- x$labelProps(valueName = i)
    
    if (!is.null(labels)) {
      uns[[i]][[x$getUID()]] <- labels$values_uns()
      labels$close()
    }
  }
}

# get coords for quiver plots
coords <- lapply(uns, function(x) {
  lapply(x, function(y) {
    coords <- data.frame(
      y = as.vector(y$ilee_coor_list[1,,,1]),
      x = as.vector(y$ilee_coor_list[1,,,2])
    )
    u <- as.vector(y$ilee_eigval[1,,,2]) * as.vector(y$ilee_eigvec[1,,,2,1])
    v <- as.vector(y$ilee_eigval[1,,,1]) * as.vector(y$ilee_eigvec[1,,,1,1])
    
    list(coords = coords, u = u, v = v)
  })
})

sum.SHG <- rbindlist(lapply(uns$SHG, function(x) x$ilee_summary), idcol = "uID")
sum.DCs <- rbindlist(lapply(uns$DCs, function(x) x$ilee_summary), idcol = "uID")
data.table::setnames(sum.SHG, paste0("SHG.", names(sum.SHG)))
data.table::setnames(sum.DCs, paste0("DCs.", names(sum.DCs)))
data.table::setnames(sum.SHG, "SHG.uID", "uID")
data.table::setnames(sum.DCs, "DCs.uID", "uID")

# merge summary
exp.info <- exp.info[sum.SHG, on = c("uID")]
exp.info <- exp.info[sum.DCs, on = c("uID")]
```

```{r fig_hmm_props, fig.height=4, fig.width=12}
# show tracking measures
colsToPlot <- colnames(tracksMeasures)
colsToPlot <- colsToPlot[!startsWith(colsToPlot, "live.")]
colsToPlot <- colsToPlot[!colsToPlot %in% c("pop", "uID", "track_id", "cell_type")]
datToPlot <- tracksMeasures %>%
  pivot_longer(cols = colsToPlot, values_to = "value", names_to = "measure")

# take median for each uID
datToPlot <- datToPlot %>%
  group_by(uID, measure) %>%
  summarise(median = median(value))

# ggplot(datToPlot %>% left_join(exp.info), aes(Location, value)) +
ggplot(datToPlot %>% left_join(exp.info), aes(Location, median)) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    # position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    width = 0.3, alpha = 0.6) +
  # geom_violin(scale = "width") +
  # stat_summary(fun=mean, geom="point", size=3, shape=18, color="Magenta") +
  # ylim(0, 1) +
  scale_color_brewer(name = NULL, palette = "Set1") +
  facet_wrap(.~measure, ncol = 5, scales = "free_y") +
  expand_limits(y = 0)

# data.table::fwrite(datToPlot %>% left_join(exp.info), file.path(anaDir, "track_measures.csv"))
data.table::fwrite(datToPlot %>% left_join(exp.info), file.path(anaDir, "track_measures_median.csv"))
```


# show clustering parameters to highlight analysis process

```{r fig_hmm_props, fig.height=3, fig.width=3}
# show measurements of clusters to compare
colsToPlot <- rev(c(
  "angle",
  "speed",
  "compactness",
  "extent",
  "oblate",
  "prolate",
  "solidity",
  "sphericity",
  "surface_area",
  "volume"
))

# convert angle to degrees
popDTs[, live.cell.angle_deg := pracma::rad2deg(live.cell.angle)]

propsToPlot <- popDTs[exp.info, on = "uID"] %>%
  dplyr::rename(
    "speed" = "live.cell.speed",
    "angle" = "live.cell.angle_deg",
    "oblate" = "ellipticity_interm_oblate",
    "prolate" = "ellipticity_interm_prolate"
  ) %>%
  # drop_na(live.cell.hmm.state.hybrid_pop) %>%
  pivot_longer(
    cols = colsToPlot, names_to = "prop", values_to = "value"
    ) %>%
  pivot_longer(
    cols = c(
      # "live.cell.hmm.state.movement"
      "live.cell.hmm.state.wp_movement"
      # "live.cell.hmm.state.shape"
    ), names_to = "hmm_type", values_to = "hmm_value"
    )

propsToPlot$prop <- factor(propsToPlot$prop, levels = colsToPlot)

# show heatmap for HMM
propsSummary <- propsToPlot %>%
  dplyr::filter(!is.na(hmm_value)) %>%
  group_by(hmm_type, hmm_value, prop) %>%
  replace_na(list(value = 0)) %>%
  summarise(mean = mean(value)) %>%
  group_by(hmm_type, prop) %>%
  mutate(freq = (mean - min(mean)) / (max(mean) - min(mean))) %>%
  arrange(-prop)

ggplot(propsSummary, aes(as.factor(hmm_value), prop)) +
  theme_classic() +
  geom_tile(aes(fill = freq), colour = "white", size = 0.5) +
  viridis::scale_fill_viridis(
    breaks = c(0, 1),
    labels = c(0, 1)
  ) +
  theme(
    legend.position = "none",
    legend.title = element_blank(),
    legend.text = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    axis.text.x = element_text(size = 12),
    strip.background = element_blank(),
    strip.text.x = element_blank(),
    # axis.text.x = element_text(size = 12, angle = 45, hjust = 1, vjust = 1)
    ) +
  xlab("") + ylab("") +
  facet_grid(.~hmm_type)

# ggsave(file.path(anaDir, "HMM_heat.pdf"), width = 2.3, height = 3)
ggsave(file.path(anaDir, "HMM_wp_heat.pdf"), width = 2.3, height = 3)
```

```{r fig_clusters_heat, fig.height=8, fig.width=6}
# show measurements of clusters to compare
propsToPlot <- copy(tcells.sc)

colsToPlot <- colnames(propsToPlot)[!colnames(propsToPlot) %in% c(
  "pop", "uID", "track_id", "clusters", "clusters.id", "clusters.name", "UMAP_1", "UMAP_2", "value_name"
  )]

propsToPlot <- propsToPlot %>%
  pivot_longer(
    cols = colsToPlot, names_to = "prop", values_to = "value"
    )

propsToPlot$prop <- factor(propsToPlot$prop, levels = sort(colsToPlot, decreasing = TRUE))

# show heatmap for clusters
propsSummary <- propsToPlot %>%
  group_by(pop, prop) %>%
  # group_by(clusters, prop) %>%
  summarise(mean = mean(value, rm.na = TRUE)) %>%
  group_by(prop) %>%
  mutate(freq = (mean - min(mean)) / (max(mean) - min(mean))) %>%
  arrange(-prop)
ggplot(propsSummary %>%
         dplyr::filter(!str_detect(prop, "live.cell")) %>%
         drop_na(pop), aes(pop, prop)) +
         # drop_na(clusters), aes(clusters, prop)) +
  theme_classic() +
  geom_tile(aes(fill = freq), colour = "white", size = 0.5) +
  viridis::scale_fill_viridis(
    breaks = c(0, 1),
    labels = c(0, 1)
  ) +
  theme(
    legend.position = "none",
    legend.key.size = unit(8, "mm"),
    legend.title = element_blank(),
    legend.text = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    # axis.text.x = element_text(size = 12),
    axis.text.x = element_text(size = 12, angle = 45, hjust = 1, vjust = 1),
    strip.background = element_blank(),
    strip.text.x = element_blank()
    ) +
  xlab("") + ylab("")

# ggsave(file.path(anaDir, "clusters_heat.pdf"), width = 2.8, height = 3)
ggsave(file.path(anaDir, "clusters_wp_heat.pdf"), width = 2.8, height = 3)
# ggsave(file.path(anaDir, "clusters_wp_raw_heat.pdf"), width = 5, height = 5)
```

```{r fig_umap, fig.height=8, fig.width=8}
dfToPlot <- copy(tcells.sc) %>% drop_na(pop) %>% left_join(exp.info)
# dfToPlot <- copy(tcells.sc) %>% drop_na(clusters.name) %>% left_join(exp.info)

# get mean positions of clusters
meanClusterPos <- dfToPlot %>%
  # group_by(pop) %>%
  group_by(Location) %>%
  # group_by(clusters) %>%
  summarise(
    UMAP_1 = median(UMAP_1),
    UMAP_2 = median(UMAP_2)
  )
dfToPlot$clusters <- factor(dfToPlot$clusters)

colPal <- list(
  "Directed" = "#ff1493",
  "Crawl directed" = "#e89478",
  "Sessile" = "#00bfff",
  "Crawling" = "#ffd700",
  "Other" = "#00fa9a",
  "Fast" = "#00fa9a",
  "WP" = "black",
  "RP" = "#FF7E79",
  "iLN" = "#A9A9A9"
)


# plot UMAP
ggplot(
  dfToPlot,
  aes(UMAP_1, UMAP_2)
  ) +
  # geom_point(aes(color = pop)) +
  geom_point(aes(color = Location)) +
  # geom_point(aes(color = clusters)) +
  theme_classic() +
  scale_color_manual(values = colPal) +
  # scale_color_brewer(palette = "Set1") +
  theme(
    axis.text = element_text(size = 15),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    legend.justification = "right",
    # legend.position = "bottom"
    legend.position = "none",
    axis.line = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
    ) 
  # geom_label(
  #   data = meanClusterPos,
  #   aes(label = pop),
  #   # aes(label = Location),
  #   # aes(label = clusters),
  #   label.size = 0.25,
  #   color = "black"
  #   )

# ggsave(file.path(anaDir, "umap.png"), width = 3, height = 3)
# ggsave(file.path(anaDir, "umap_location.png"), width = 3, height = 3)
# ggsave(file.path(anaDir, "umap_wp.png"), width = 3, height = 3)
# ggsave(file.path(anaDir, "umap_wo_labels.png"), width = 3, height = 3)
ggsave(file.path(anaDir, "umap_location_wo_labels.png"), width = 3, height = 3)
# ggsave(file.path(anaDir, "umap_wp_wo_labels.png"), width = 3, height = 3)
```

```{r fig_freq, fig.height=2.5, fig.width=6}
# save behaviour freq
datToPlot <- tcells.sc %>%
  dplyr::filter(pop != "Other") %>%
  group_by(uID, pop) %>%
  summarise(n = n()) %>%
  mutate(freq = n/sum(n) * 100) %>%
  ungroup() %>%
  complete(uID, pop, fill = list(freq = 0)) %>%
  left_join(exp.info)

ggplot(datToPlot, aes(pop, freq, color = Location)) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
  expand_limits(y = 0)

data.table::fwrite(datToPlot, file.path(anaDir, "behaviour_freq.csv"))
# data.table::fwrite(datToPlot, file.path(anaDir, "behaviour_wp_freq.csv"))
```

```{r fig_aniso_SHG_DCs, fig.height=4, fig.width=4}
# plot SHG v DCs
ggplot(exp.info, aes(SHG.anisotropy, DCs.anisotropy)) +
  theme_classic() +
  geom_point() +
  geom_smooth(method="lm") +
  xlim(0, 1) + ylim(0, 1)

ggsave(file.path(anaDir, "aniso_SHG_DCs.png"), height = 3, width = 3)
```


```{r fig_aniso_tracks, fig.height=6, fig.width=10}
# can you show the flow of SHG/DCs in relation to cell movement?
colsToPlot <- colnames(tracksMeasures)
colsToPlot <- colsToPlot[!colsToPlot %in% c("uID", "pop", "cell_type", "track_id")]
colsToPlot <- colsToPlot[!startsWith(colsToPlot, "live.")]

datToPlot <- as.data.table(tracksMeasures[uID %in% exp.info[Location == "WP"]$uID] %>%
  left_join(tcells.sc[, c("uID", "track_id", "pop")]) %>%
  dplyr::filter(pop != "Other") %>%
  pivot_longer(cols = colsToPlot, names_to = "measure", values_to = "value") %>%
  group_by(uID, cell_type, measure) %>%
  summarise(median = median(value, na.rm = TRUE)) %>%
  left_join(exp.info))

ggplot(datToPlot, aes(SHG.anisotropy, median)) +
  theme_classic() +
  geom_point() +
  geom_smooth(method="lm") +
  facet_wrap(.~measure, ncol = 4, scales = "free_y") +
  expand_limits(y = 0, x = 0) +
  xlim(0, 1)

data.table::fwrite(datToPlot, file.path(anaDir, "aniso_measures.csv"))
ggsave(file.path(anaDir, "aniso_measures.png"), height = 4, width = 10)
```

```{r fig_aniso_hmm, fig.height=3, fig.width=10}
# can you show the flow of SHG/DCs in relation to cell movement?
datToPlot <- tcells.sc %>%
  dplyr::filter(pop != "Other") %>%
  group_by(uID, pop) %>%
  summarise(n = n()) %>%
  mutate(freq = n/sum(n) * 100) %>%
  left_join(exp.info)

ggplot(datToPlot, aes(SHG.anisotropy, freq)) +
  theme_classic() +
  geom_point() +
  geom_smooth(method="lm") +
  facet_wrap(.~pop, ncol = 5, scales = "free") +
  xlim(0, 1) + ylim(0, 100)

data.table::fwrite(datToPlot, file.path(anaDir, "aniso_clusters.csv"))
ggsave(file.path(anaDir, "aniso_clusters.png"), height = 2, width = 8)
```

```{r fig_umap, fig.height=6, fig.width=12}
colPal <- list(
  "Directed" = "#ff1493",
  "Sessile" = "#00bfff",
  "Crawling" = "#ffd700",
  "Other" = "#00fa9a"
)

for (i in uIDs) {
  for (j in names(coords)) {
    p1 <- ggplot(popDTs[uID == i, -c("pop")] %>% left_join(
      # tcells.sc[, c("uID", "track_id", "pop")] %>% rename(cluster_pop = pop), by = c("uID", "track_id"))) +
      tcells.sc[, c("uID", "track_id", "pop")], by = c("uID", "track_id"))) +
        # dplyr::filter(cluster_pop != "Other")) + 
      # scale_color_brewer(palette = "Set1") +
      theme_classic() +
      plotThemeDark(bgColor = "#000000") +
      coord_fixed() +
      xlim(-20, x$omeXMLPixels()$SizeX + 20) +
      ylim(x$omeXMLPixels()$SizeY + 20, -20) +
      theme(
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.line = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.position = "none"
      ) 
      # ggtitle(paste(i, j))
    
    yCoords <- coords[[j]][[i]]
    
    if (all(c(!is.null(yCoords)))) {
      quiver.data <- cbind(yCoords$coords, yCoords$u, yCoords$v)
      colnames(quiver.data) <- c("x", "y", "u", "v")
      
      p1 <- p1 + 
        # geom_path(aes(centroid_x, centroid_y, group = track_id, colour = as.factor(track_id)),
        # linewidth = 2, alpha = 1) +
        # geom_segment(
        #   data = branchDT[uID == x$getUID() & pop == structuresPop],
        #   aes(x = `coord-src-1`, y = `coord-src-0`,
        #       xend = `coord-dst-1`, yend = `coord-dst-0`),
        #   # color = "#ebd441", linewidth = 1, alpha = 1) +
        #   color = "#AA1F5E", linewidth = 1, alpha = 1) +
        # quiver doesn't work with Cairo
        # ggquiver::geom_quiver(
        #   data = yCoords$coords, aes(x = x, y = y, u = -yCoords$u, v = yCoords$v), color = "#4682b4") 
        # https://jtr13.github.io/cc22tt/tutorial-for-vector-fields-in-r.html
        geom_segment(data = quiver.data, aes(
          y = x, x = y,
          yend = x + (v * 0.1), 
          xend = y + (u * 0.1)), 
          arrow = arrow(length = unit(0.2, "cm")),
          size = 0.8, color = "#4682b4") +
        # geom_path(aes(centroid_x, centroid_y, group = track_id, color = cluster_pop),
        # geom_path(aes(centroid_x, centroid_y, group = track_id, color = clusters.name),
        geom_path(aes(centroid_x, centroid_y, group = track_id),
                  # color = "#AA1F5E", linewidth = 1, alpha = 1) +
                  color = "white", linewidth = 1.5, alpha = 1) +
                  # linewidth = 1, alpha = 1) +
        scale_color_manual(values = colPal) +
        coord_fixed() +
        # facet_wrap(.~cluster_pop, nrow = 1)
        facet_wrap(.~pop, nrow = 2) 
    }
    
    # print(p1)
    ggsave(file.path(anaDir, "flows", paste0(i, "_", j, ".png")), height = 12, width = 12, plot = p1)
  }
}

```