---
title: "Behaviour GCAMP"
output: html_document
date: '2022-08-15'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Show transition states of live cell imaging

```{r}
Sys.setenv(KMP_DUPLICATE_LIB_OK = "TRUE")
devtools::load_all("../")
cciaUse("~/cecelia/dev")

library(ggplot2)
library(tidyverse)
```

```{r}
# set test variables
pID <- "8BR53W"
versionID <- 1
# projectsDir <- "/Volumes/Analysis_SSD/Dominik/cecelia/projects/"
projectsDir <- "/Volumes/USER_data/Dominik/CECELIA_BACKUP/"
hpcDir <- "/data/scratch/projects/punim1124/cecelia/USERS/schienstockd/"
```

```{r}
anaDir <- "/Volumes/USER_data/Dominik/Experiments/Immunemap_expID_49/CECELIA"
```

```{r}
# # add positive LV pop
# devtools::load_all("../")
# cciaUse("~/cecelia/dev", initConda = FALSE)
# 
# # init ccia object
# cciaObj <- initCciaObject(
#   pID = pID, uID = "mrMpi5", versionID = versionID, initReactivity = FALSE # Immunemap
# )
# 
# popType <- "live"
# parentPops <- c("LV")
# valueName <- "LV"
# pops <- list(
#   "accepted" = list(
#     filterMeasure = "volume",
#     # filterValues = 60000,
#     # filterValues = 20000, # 01MS5C
#     filterValues = 40000, # AcTxRT
#     filterFun = "gt",
#     colour = "white"
#   )
# )
# 
# # go through all children
# for (x in cciaObj$cciaObjects()["AcTxRT"]) {
#   x$delPopsByPath(popType, paste(parentPops, names(pops), sep = "/"),
#            includeFiltered = TRUE)
#   x$addFilteredPops(popType, parentPops, pops, valueName = valueName)
#   x$saveState()
# }
```

```{r}
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "mrMpi5", versionID = versionID, initReactivity = FALSE # Immunemap
)

cciaObj$tracks("T")
```


```{r}
# HMM
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "mrMpi5", versionID = versionID, initReactivity = FALSE # Immunemap
)

uIDs <- names(cciaObj$cciaObjects())

# run task
funParams <- list(
  popType = "live",
  # pops = c("T/tracked", "DC/tracked"),
  pops = c("T/tracked"),
  modelMeasurements = c("live.cell.speed", "live.cell.angle"),
  scaleMeasurements = c("live.cell.speed", "live.cell.angle"),
  colName = "movement",
  # appendStates = list(live.cell.is.clust = TRUE),
  appendStates = list(),
  skipTimesteps = 0,
  subtrackOverlap = TRUE,
  noiseFilterMeasurements = 5,
  postFiltering = 2,
  postIterations = 2,
  numStates = 3,
  uIDs = uIDs
)

# run task
task <- cciaObj$runTask(
  funName = "behaviourAnalysis.hmmStates",
  funParams = funParams,
  env = "local",
  runInplace = TRUE,
  taskID = 1
)
```

```{r}
# get HMM transitions
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "mrMpi5", versionID = versionID, initReactivity = FALSE # Immunemap
)

uIDs <- names(cciaObj$cciaObjects())

# run task
funParams <- list(
  popType = "live",
  # pops = c("T/tracked", "DC/tracked"),
  pops = c("T/tracked"),
  colName = "movement",
  hmmStates = c("movement"),
  includeStart = FALSE,
  includeSelfTransitions = TRUE,
  uIDs = uIDs
)

# run task
task <- cciaObj$runTask(
  funName = "behaviourAnalysis.hmmTransitions",
  funParams = funParams,
  env = "local",
  runInplace = TRUE,
  taskID = 1
)
```

```{r}
# cluster tracks based on transitions
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "mrMpi5", versionID = versionID, initReactivity = FALSE # Immunemap
)

uIDs <- names(cciaObj$cciaObjects())

# run task
funParams <- list(
  popType = "live",
  # popsToCluster = c("T/tracked", "DC/tracked"),
  popsToCluster = c("T/tracked"),
  valueName = "tracks.clusters.tcells.hmm_transitions_movement",
  clusterColName = "hmm_transitions_movement",
  resolution = 0.3,
  percentile = 99.5,
  trackMeasures = c(
    "speed",
    "duration",
    "trackLength",
    "meanTurningAngle",
    "displacement",
    "straightness",
    "displacementRatio",
    "outreachRatio",
    "asphericity",
    "overallAngle"
  ),
  objectMeasures = c(
    # "extent",
    # "solidity",
    # "integral_mean_curvature",
    # "ellipticity_oblate",
    # "ellipticity_prolate",
    # "ellipticity_interm_oblate",
    # "ellipticity_interm_prolate",
    # "sphericity",
    # HMM states
    "live.cell.hmm.state.movement",
    "live.cell.hmm.transitions.movement",
    "live.cell.min_distance#live.LV/accepted"
    ),
  nMeasures = c(
    ),
  sumMeasures = c(
    ),
  calcMeasures = list(
  ),
  addPops = c(
    ),
  calcLabelProps = TRUE,
  # usePaga = FALSE,
  usePaga = TRUE,
  pagaThreshold = 0.1,
  minTracklength = 6,
  # minTracklength = 50,
  uIDs = uIDs
)

# run task
task <- cciaObj$runTask(
  funName = "behaviourAnalysis.clusterTracks",
  funParams = funParams,
  env = "local",
  runInplace = TRUE,
  taskID = 1
)
```


```{r}
# adjust segmentation names
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "mrMpi5", versionID = versionID, initReactivity = FALSE # Immunemap
)

# get experimental info
exp.info <- cciaObj$summary(
  withSelf = FALSE, fields = c("Attr")
)

uIDs <- names(cciaObj$cciaObjects())

# get clustering
tcells.sc <- as.data.table(cciaEnv()$LabelPropsUtils(
  cciaObj$persistentObjectDirectory(),
  # value_name = "tracks.clusters.tcells.movement.sc")$label_props_view()$as_df())
  value_name = "tracks.clusters.tcells.hmm_transitions_movement.sc")$label_props_view()$as_df())

# get popDTs for set
popDTs <- cciaObj$popDT(
  # popType = "live", pops = c("T/tracked", "DC/tracked"),
  popType = "live", pops = c("T/tracked"),
  includeFiltered = TRUE,
  flushCache = TRUE,
  uIDs = uIDs)
```

```{r fig_hmm_props, fig.height=3, fig.width=3}
# show measurements of clusters to compare
colsToPlot <- rev(c(
  "angle",
  "speed",
  "compactness",
  "extent",
  "oblate",
  "prolate",
  "solidity",
  "sphericity",
  "surface_area",
  "volume"
))

# convert angle to degrees
popDTs[, live.cell.angle_deg := pracma::rad2deg(live.cell.angle)]

propsToPlot <- popDTs[exp.info, on = "uID"] %>%
  dplyr::rename(
    "speed" = "live.cell.speed",
    "angle" = "live.cell.angle_deg",
    "oblate" = "ellipticity_interm_oblate",
    "prolate" = "ellipticity_interm_prolate"
  ) %>%
  # drop_na(live.cell.hmm.state.hybrid_pop) %>%
  pivot_longer(
    cols = colsToPlot, names_to = "prop", values_to = "value"
    ) %>%
  pivot_longer(
    cols = c(
      "live.cell.hmm.state.movement"
      # "live.cell.hmm.state.shape"
    ), names_to = "hmm_type", values_to = "hmm_value"
    )

propsToPlot$prop <- factor(propsToPlot$prop, levels = colsToPlot)

# show heatmap for HMM
propsSummary <- propsToPlot %>%
  dplyr::filter(!is.na(hmm_value)) %>%
  group_by(hmm_type, hmm_value, prop) %>%
  replace_na(list(value = 0)) %>%
  summarise(mean = mean(value)) %>%
  group_by(hmm_type, prop) %>%
  mutate(freq = (mean - min(mean)) / (max(mean) - min(mean))) %>%
  arrange(-prop)

ggplot(propsSummary %>% dplyr::filter(hmm_value != "Clustering"), aes(as.factor(hmm_value), prop)) +
  theme_classic() +
  geom_tile(aes(fill = freq), colour = "white", size = 0.5) +
  viridis::scale_fill_viridis(
    breaks = c(0, 1),
    labels = c(0, 1)
  ) +
  theme(
    legend.position = "none",
    legend.title = element_blank(),
    legend.text = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    axis.text.x = element_text(size = 12),
    strip.background = element_blank(),
    strip.text.x = element_blank(),
    # axis.text.x = element_text(size = 12, angle = 45, hjust = 1, vjust = 1)
    ) +
  xlab("") + ylab("") +
  facet_grid(.~hmm_type)

ggsave(file.path(anaDir, "HMM_heat.pdf"), width = 2.1, height = 3)
```

```{r fig_umap, fig.height=4, fig.width=4}
dfToPlot <- copy(tcells.sc) %>% drop_na(clusters) %>% left_join(exp.info)

clusterMapping <- list(
  `Scanning close` = c(3),
  `Meandering close` = c(1,4),
  `Meandering away` = c(0),
  `Directed away` = c(2)
)

dfToPlot <- .mapClustNames(dfToPlot, clusterMapping, "clusters")

# get mean positions of clusters
meanClusterPos <- dfToPlot %>%
  # group_by(clusters) %>%
  group_by(clusters.name) %>%
  summarise(
    UMAP_1 = mean(UMAP_1),
    UMAP_2 = mean(UMAP_2)
  )
dfToPlot$clusters <- factor(dfToPlot$clusters)

colPal <- randomcoloR::distinctColorPalette(length(unique(dfToPlot$clusters)))

# plot UMAP
ggplot(
  dfToPlot,
  aes(UMAP_1, UMAP_2)
  ) +
  # geom_point(aes(color = clusters)) +
  geom_point(aes(color = clusters.name)) +
  theme_classic() +
  # scale_color_brewer(name = NULL, palette = "Set1") +
  scale_color_brewer(name = NULL, palette = "Dark2") +
  # scale_color_manual(values = colPal) +
  theme(
    axis.text = element_text(size = 15),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    legend.justification = "right",
    # legend.position = "bottom"
    legend.position = "none",
    axis.line = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
    ) 
  # geom_label(
  #   data = meanClusterPos,
  #   aes(label = clusters),
  #   # aes(label = clusters.name),
  #   label.size = 0.25,
  #   color = "black"
  #   )

# ggsave(file.path(anaDir, "umap.tiff"), width = 2, height = 2)
ggsave(file.path(anaDir, "umap_wo_labels.tiff"), width = 2, height = 2)
```
```{r fig_umap_props, fig.height=4, fig.width=4}
datToPlot <- copy(tcells.sc) %>%
  drop_na(clusters) %>%
  left_join(exp.info) 

# plot UMAP
ggplot(datToPlot, aes(UMAP_1, UMAP_2)) +
  theme_classic() +
  geom_point(aes(color = speed), size = 1, alpha = 1) +
  # geom_point(aes(color = meanTurningAngle), size = 1, alpha = 1) +
  # geom_point(aes(color = `live.cell.min_distance#live.LV/accepted.qUp`), size = 1, alpha = 1) +
  viridis::scale_color_viridis() +
  theme(
    axis.text = element_text(size = 15),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    legend.justification = "right",
    # legend.position = "bottom"
    legend.position = "none",
    axis.line = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
    )

ggsave(file.path(anaDir, paste0("umap_Velocity.tiff")), width = 2, height = 2)
# ggsave(file.path(anaDir, paste0("umap_Angle.tiff")), width = 2, height = 2)
# ggsave(file.path(anaDir, paste0("umap_LV_dist.tiff")), width = 2, height = 2)
```

```{r}
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# show measurements of clusters to compare
propsToPlot <- copy(tcells.sc)

# propsToPlot <- propsToPlot %>%
#   dplyr::rename(
#     "Movement HMM 1" = "live.cell.hmm.state.movement.1",
#     "Movement HMM 2" = "live.cell.hmm.state.movement.2",
#     "Movement HMM 3" = "live.cell.hmm.state.movement.3",
#     "Movement HMM 4" = "live.cell.hmm.state.movement.4",
#   )

colsToPlot <- colnames(propsToPlot)[!colnames(propsToPlot) %in% c(
  "pop", "uID", "track_id", "clusters", "UMAP_1", "UMAP_2"
  )]

propsToPlot <- propsToPlot %>%
  pivot_longer(
    cols = colsToPlot, names_to = "prop", values_to = "value"
    )

propsToPlot$prop <- factor(propsToPlot$prop, levels = sort(colsToPlot, decreasing = TRUE))

# propsList <- c(
#   'Movement HMM 1',
#   'Movement HMM 2',
#   'Movement HMM 3',
#   'Movement HMM 4',
#   'asphericity',
#   'displacement',
#   'displacementRatio',
#   'duration',
#   'meanTurningAngle',
#   'outreachRatio',
#   'overallAngle',
#   'speed',
#   'straightness',
#   'trackLength'
# )

propsToPlot <- .mapClustNames(propsToPlot, clusterMapping, removeNone = FALSE)

# show heatmap for clusters
propsSummary <- propsToPlot %>%
  dplyr::filter(
    # clusters.name != "NONE",
    # prop %in% propsList
    ) %>%
  # group_by(clusters, prop) %>%
  group_by(clusters.name, prop) %>%
  summarise(mean = mean(value, rm.na = TRUE)) %>%
  group_by(prop) %>%
  mutate(freq = (mean - min(mean)) / (max(mean) - min(mean)))
  # arrange(-prop) %>%
```


```{r fig_clusters_heat, fig.height=8, fig.width=6}
# propsSummary$prop <- factor(
#   propsSummary$prop, levels = rev(propsList))
# propsSummary$clusters.name <- factor(
#   propsSummary$clusters.name, levels = c(
#     "Directed", "Meandering", "Scanning", "Clustering"
#   ))

# # sort states
# propsSummary[!propsSummary$clusters %in% clusterOrder[clusterOrder != 1],]$clusters <- NA
# # propsSummary$clusters <- factor(propsSummary$clusters, levels = clusterOrder)
# propsSummary$clusters <- case_match(
#   as.character(propsSummary$clusters),
#   c("3") ~ "1",
#   c("6") ~ "2",
#   c("0") ~ "3",
#   c("7") ~ "4",
#   c("2") ~ "5",
#   c("5") ~ "6",
#   c("4") ~ "7",
# )

# ggplot(propsSummary, aes(as.factor(clusters.name), prop)) +
# ggplot(propsSummary, aes(as.factor(clusters), prop)) +
ggplot(propsSummary %>%
         # dplyr::filter(!str_detect(prop, "live.cell")) %>%
         dplyr::filter(!str_detect(prop, "live.cell.hmm")) %>%
         # dplyr::filter(str_detect(prop, "live.cell"), !str_detect(prop, "live.cell.hmm")) %>%
         mutate(prop = stringr::str_replace(
           prop, "live.cell.min_distance#live.LV/accepted.", "distance to lymphatics ")) %>%
         # drop_na(clusters), aes(clusters, prop)) +
         drop_na(clusters.name), aes(clusters.name, prop)) +
  theme_classic() +
  geom_tile(aes(fill = freq), colour = "white", size = 0.5) +
  viridis::scale_fill_viridis(
    breaks = c(0, 1),
    labels = c(0, 1)
  ) +
  theme(
    legend.position = "none",
    legend.key.size = unit(8, "mm"),
    legend.title = element_blank(),
    legend.text = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    # axis.text.x = element_text(size = 12),
    axis.text.x = element_text(size = 12, angle = 45, hjust = 1, vjust = 1),
    strip.background = element_blank(),
    strip.text.x = element_blank()
    ) +
  xlab("") + ylab("")

ggsave(file.path(anaDir, "clusters_heat.pdf"), width = 3.7, height = 4.5)
# ggsave(file.path(anaDir, "clusters_heat_dist.pdf"), width = 3.7, height = 2)
# ggsave(file.path(anaDir, "clusters_heat.pdf"), width = 5, height = 14)
```

```{r fig_clusters_heat, fig.height=2, fig.width=6}
# get frequencies of HMM for each cluster
# and plot as bar graphs
datToPlot <- popDTs %>%
  mutate(live.cell.track.clusters.hmm_transitions_movement = as.numeric(as.character(
    live.cell.track.clusters.hmm_transitions_movement))) %>%
  drop_na(live.cell.track.clusters.hmm_transitions_movement) %>%
  drop_na(live.cell.hmm.state.movement) %>%
  group_by(live.cell.track.clusters.hmm_transitions_movement, live.cell.hmm.state.movement) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n) * 1) %>%
  ungroup() %>%
  complete(live.cell.track.clusters.hmm_transitions_movement, live.cell.hmm.state.movement, fill = list(freq = 0))

write.csv(datToPlot, file = file.path(anaDir, "freq_hmm.csv"))

ggplot(datToPlot, aes(as.factor(live.cell.track.clusters.hmm_transitions_movement), freq,
                      fill = as.factor(live.cell.hmm.state.movement))) +
  theme_classic() +
  # scale_fill_brewer(palette = "Accent") +
  scale_fill_manual(values = wesanderson::wes_palette(name = "Darjeeling2")) +
  theme_classic() +
  geom_bar(stat = "identity", width = 1, color = "black", size = 0.4) +
  theme(
    # legend.position = "none",
    legend.position = "right",
    legend.key.size = unit(6, "mm"),
    legend.title = element_blank(),
    legend.text = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    axis.text.x = element_text(size = 12),
    # axis.text.x = element_text(size = 12, angle = 45, hjust = 1, vjust = 1),
    strip.background = element_blank(),
    # strip.text.x = element_blank()
    strip.text.x = element_text(size = 12)
    ) +
  scale_y_continuous(breaks = c(0, 0.5, 1)) +
  # scale_fill_discrete(name = "HMM State") +
  xlab("") + ylab("") 

ggsave(file.path(anaDir, "clusters_hmm_heat.pdf"), width = 2.5, height = 1.5)
```

```{r fig_clusters_heat, fig.height=3, fig.width=8}
# get frequencies of HMM for each cluster
# and plot as bar graphs
datToPlot <- popDTs %>%
  mutate(
    live.cell.track.clusters.hmm_transitions_movement = as.numeric(as.character(
      live.cell.track.clusters.hmm_transitions_movement)),
    live.cell.hmm.transitions.movement = as.character(
      live.cell.hmm.transitions.movement)
    ) %>%
  drop_na(live.cell.track.clusters.hmm_transitions_movement) %>%
  dplyr::filter(live.cell.hmm.transitions.movement != "NA") %>%
  # group_by(live.cell.track.clusters.hmm_transitions_movement, from, to) %>%
  # dplyr::filter(!live.cell.hmm.transitions.movement %in% paste0(seq(4), "_", seq(4))) %>%
  group_by(live.cell.track.clusters.hmm_transitions_movement, live.cell.hmm.transitions.movement) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n) * 1) %>%
  separate_wider_delim(
    live.cell.hmm.transitions.movement, delim = "_", names = c("from", "to"))
  # ungroup() %>%
  # complete(live.cell.track.clusters.hmm_transitions_movement, from, to, fill = list(freq = 0))

ggplot(datToPlot, aes(as.factor(from), as.factor(to), size = freq * 2, fill = freq)) +
  theme_classic() +
  # scale_fill_brewer(palette = "Accent") +
  # scale_y_continuous(breaks = c(0, 0.5, 1)) +
  geom_vline(xintercept = as.factor(1:4), color = "#d3d3d3") +
  geom_hline(yintercept = as.factor(1:4), color = "#d3d3d3") +
  geom_point(pch = 21, color = "black") +
  # viridis::scale_fill_viridis() +
  scale_fill_gradient2(
    midpoint = 0.5, low="blue", mid="white", high="red", space ="Lab") +
  theme(
    legend.position = "none",
    # legend.position = "right",
    legend.key.size = unit(6, "mm"),
    legend.title = element_blank(),
    legend.text = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    axis.text.x = element_text(size = 12),
    # axis.text.x = element_text(size = 12, angle = 45, hjust = 1, vjust = 1),
    strip.background = element_blank(),
    # strip.text.x = element_blank()
    strip.text.x = element_text(size = 12)
    ) +
  # scale_fill_discrete(name = "HMM State") +
  xlab("From state") + ylab("To state") +
  facet_wrap(.~live.cell.track.clusters.hmm_transitions_movement, nrow = 2)

ggsave(file.path(anaDir, "clusters_transitions_heat.pdf"), width = 3.5, height = 3)
```

```{r fig_clusters_freq, fig.height=4, fig.width=8}
# save frequencies of track clusters
summaryDF <- copy(tcells.sc)

summaryDF <- .mapClustNames(summaryDF, clusterMapping, "clusters")

# show frequency of clusters
# summaryDF <- summaryDF[, .(n.clusters = .N), by = .(uID, pop, clusters)] %>%
summaryDF <- summaryDF[, .(n.clusters = .N), by = .(uID, pop, clusters.name)] %>%
  droplevels() %>%
  group_by(uID, pop) %>%
  mutate(freq.clusters = n.clusters/sum(n.clusters) * 100) %>%
  ungroup() %>%
  # complete(uID, pop, clusters, fill = list(freq.clusters = 0)) %>%
  complete(uID, pop, clusters.name, fill = list(freq.clusters = 0)) %>%
  left_join(exp.info)

# ggplot(summaryDF, aes(clusters, freq.clusters, color = clusters)) +
ggplot(summaryDF, aes(clusters.name, freq.clusters, color = clusters.name)) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_point() +
  # geom_jitter(
  #   position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
  scale_color_brewer(name = "Treatment", palette = "Set1") +
  facet_grid(.~pop) +
  theme(legend.position = "none")

ggsave(file.path(anaDir, "clusters_freq.pdf"), width = 10, height = 3)

# summaryDF$Treatment.DTx <- 0
# summaryDF[summaryDF$Treatment == "PBS" & summaryDF$DTx == "PBS",]$Treatment.DTx <- 0
# summaryDF[summaryDF$Treatment == "HSV" & summaryDF$DTx == "PBS",]$Treatment.DTx <- 1
# summaryDF[summaryDF$Treatment == "HSV" & summaryDF$DTx == "DTx",]$Treatment.DTx <- 2

write.csv(
  summaryDF,
  file = file.path(anaDir, "freq_clusters.csv")
)
```

```{r fig_states_dist, fig.height = 3, fig.width = 4}
# get frequencies of clusters at distance
hmmDist <- tcells.sc %>%
  drop_na(clusters) %>%
  mutate(LV.dist = cut(`live.cell.min_distance#live.LV/accepted.qLow`, breaks = 5)) %>%
  group_by(uID, LV.dist, clusters) %>%
  summarise(n = n()) %>%
  mutate(
    clusters = as.factor(clusters),
    freq = n/sum(n)
    ) 

# # TODO this is not nice
# # set NA for each object after completion with 0
# for (x in cciaObj$cciaObjects(uIDs = uIDs)) {
#   hmmTime[hmmTime$uID == x$getUID() &
#             hmmTime$centroid_t > x$omeXMLPixels()$SizeT, ]$freq = NA
# }
```

```{r fig_states_time, fig.height = 3, fig.width = 5}
datToPlot <- copy(popDTs)

datToPlot <- .mapClustNames(datToPlot, clusterMapping,
                            "live.cell.track.clusters.hmm_transitions_movement")

datToPlot <- datToPlot %>%
  # group_by(uID, track_id, `live.cell.track.clusters.hmm_transitions_movement`) %>%
  group_by(uID, track_id, clusters.name, clusters.id) %>%
  summarise(
    max.dist = quantile(`live.cell.min_distance#live.LV/accepted`, 0.95),
    min.dist = quantile(`live.cell.min_distance#live.LV/accepted`, 0.05),
    median.dist = median(`live.cell.min_distance#live.LV/accepted`)
    ) %>%
  drop_na() %>%
  dplyr::filter(
    # `live.cell.track.clusters.hmm_transitions_movement` != "NA") 
    clusters.name != "NA") 

# ggplot(datToPlot, aes(`live.cell.track.clusters.hmm_transitions_movement`, min.dist,
#                      color = `live.cell.track.clusters.hmm_transitions_movement`)) +
ggplot(datToPlot, aes(clusters.name, min.dist,
                     color = clusters.name)) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    # position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    width = 0.3, alpha = 0.6) +
  ylab("Distance from lymphatics (μm)") + xlab("") +
  # ylim(0, 5) +
  scale_color_brewer(name = NULL, palette = "Set1")

# ggplot(datToPlot, aes(`live.cell.track.clusters.hmm_transitions_movement`, max.dist,
#                      color = `live.cell.track.clusters.hmm_transitions_movement`)) +
ggplot(datToPlot, aes(clusters.name, max.dist,
                     color = clusters.name)) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    # position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    width = 0.3, alpha = 0.6) +
  ylab("Distance from lymphatics (μm)") + xlab("") +
  # ylim(0, 5) +
  scale_color_brewer(name = NULL, palette = "Set1")

# ggplot(datToPlot, aes(`live.cell.track.clusters.hmm_transitions_movement`, median.dist,
#                      color = `live.cell.track.clusters.hmm_transitions_movement`)) +
ggplot(datToPlot, aes(clusters.name, median.dist,
                     color = clusters.name)) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    # position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    width = 0.3, alpha = 0.6) +
  ylab("Distance from lymphatics (μm)") + xlab("") +
  # ylim(0, 5) +
  scale_color_brewer(name = NULL, palette = "Set1")
write.csv(datToPlot, file = file.path(anaDir, "hmm_dist.csv"))
```

```{r fig_hmm_props, fig.height=3, fig.width=3}
# show measurements of clusters to compare
colsToPlot <- rev(c(
  "angle",
  "speed",
  "compactness",
  "extent",
  "oblate",
  "prolate",
  "solidity",
  "sphericity",
  "surface_area",
  "volume"
))

# convert angle to degrees
popDTs[, live.cell.angle_deg := pracma::rad2deg(live.cell.angle)]

propsToPlot <- popDTs[exp.info, on = "uID"] %>%
  dplyr::rename(
    "speed" = "live.cell.speed",
    "angle" = "live.cell.angle_deg",
    "oblate" = "ellipticity_interm_oblate",
    "prolate" = "ellipticity_interm_prolate"
  ) %>%
  # drop_na(live.cell.hmm.state.hybrid_pop) %>%
  pivot_longer(
    cols = colsToPlot, names_to = "prop", values_to = "value"
    ) %>%
  pivot_longer(
    cols = c(
      "live.cell.hmm.state.movement"
      # "live.cell.hmm.state.shape"
    ), names_to = "hmm_type", values_to = "hmm_value"
    )

propsToPlot$prop <- factor(propsToPlot$prop, levels = colsToPlot)

# show heatmap for HMM
propsSummary <- propsToPlot %>%
  dplyr::filter(!is.na(hmm_value)) %>%
  group_by(hmm_type, hmm_value, prop) %>%
  replace_na(list(value = 0)) %>%
  summarise(mean = mean(value)) %>%
  group_by(hmm_type, prop) %>%
  mutate(freq = (mean - min(mean)) / (max(mean) - min(mean))) %>%
  arrange(-prop)

ggplot(propsSummary %>% dplyr::filter(hmm_value != "Clustering"), aes(as.factor(hmm_value), prop)) +
  theme_classic() +
  geom_tile(aes(fill = freq), colour = "white", size = 0.5) +
  viridis::scale_fill_viridis(
    breaks = c(0, 1),
    labels = c(0, 1)
  ) +
  theme(
    legend.position = "none",
    legend.title = element_blank(),
    legend.text = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    axis.text.x = element_text(size = 12),
    strip.background = element_blank(),
    strip.text.x = element_blank(),
    # axis.text.x = element_text(size = 12, angle = 45, hjust = 1, vjust = 1)
    ) +
  xlab("") + ylab("") +
  facet_grid(.~hmm_type)

ggsave(file.path(anaDir, "HMM_heat.pdf"), width = 2.1, height = 3)
```

```{r fig_umap, fig.height=3, fig.width=3}
dfToPlot <- copy(tcells.sc) %>% left_join(exp.info)

dfToPlot$type <- "Away from lymphatics"
dfToPlot[dfToPlot$clusters %in% lymphatic.clusters, ]$type <- "Close to lymphatics"
dfToPlot$behaviour <- "Directed"
dfToPlot[dfToPlot$clusters %in% behaviour.meandering, ]$behaviour <- "Meandering"
dfToPlot[dfToPlot$clusters %in% behaviour.scanning, ]$behaviour <- "Scanning"

# plot UMAP
ggplot(
  dfToPlot,
  aes(UMAP_1, UMAP_2)
  ) +
  geom_point(aes(color = clusters)) +
  theme_classic() +
  scale_color_brewer(name = NULL, palette = "Set1") +
  theme(
    axis.text = element_text(size = 15),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    legend.justification = "right",
    legend.position = "bottom",
    # legend.position = "none",
    axis.line = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
    )

ggsave(file.path(anaDir, "umap.tiff"), width = 5, height = 5)
```

```{r}
# show measurements of clusters to compare
propsToPlot <- copy(tcells.sc)

propsToPlot <- propsToPlot %>%
  dplyr::rename(
    # "Close to lymphatics" = "live.cell.contact#live.LV/accepted.TRUE",
    # "Away from lymphatics" = "live.cell.contact#live.LV/accepted.FALSE",
    "Distance to lymphatics" = "live.cell.min_distance#live.LV/accepted.mean",
    "Movement HMM 1" = "live.cell.hmm.state.movement.1",
    "Movement HMM 2" = "live.cell.hmm.state.movement.2",
    "Movement HMM 3" = "live.cell.hmm.state.movement.3"
  )

colsToPlot <- colnames(propsToPlot)[!colnames(propsToPlot) %in% c(
  "pop", "uID", "track_id", "clusters", "UMAP_1", "UMAP_2"
  )]

propsToPlot <- propsToPlot %>%
  pivot_longer(
    cols = colsToPlot, names_to = "prop", values_to = "value"
    )

propsToPlot$prop <- factor(propsToPlot$prop, levels = sort(colsToPlot, decreasing = TRUE))

propsToPlot$clusters.name <- "NONE"
propsToPlot[propsToPlot$clusters == 0, ]$clusters.name <- "Meandering"
propsToPlot[propsToPlot$clusters == 1, ]$clusters.name <- "Scanning"
propsToPlot[propsToPlot$clusters == 2, ]$clusters.name <- "Directed"

# show heatmap for clusters
propsSummary <- propsToPlot %>%
  # dplyr::filter(!is.na(live.cell.hmm.state.movement)) %>%
  # group_by(live.cell.hmm.state.movement, prop) %>%
  # group_by(clusters, prop) %>%
  group_by(clusters.name, prop) %>%
  summarise(mean = mean(value, rm.na = TRUE)) %>%
  group_by(prop) %>%
  mutate(freq = (mean - min(mean)) / (max(mean) - min(mean))) %>%
  arrange(-prop)
```


```{r fig_clusters_heat, fig.height=3, fig.width=5}
propsSummary$prop <- factor(propsSummary$prop, levels = rev(c(
  # 'Close to lymphatics',
  # 'Away from lymphatics',
  'Distance to lymphatics',
  'Movement HMM 1',
  'Movement HMM 2',
  'Movement HMM 3',
  'asphericity',
  'displacement',
  'displacementRatio',
  'duration',
  'meanTurningAngle',
  'outreachRatio',
  'overallAngle',
  'speed',
  'straightness',
  'trackLength'
)))

# ggplot(propsSummary, aes(prop, as.factor(clusters))) +
ggplot(propsSummary %>% drop_na(), aes(as.factor(clusters), prop)) +
  theme_classic() +
  geom_tile(aes(fill = freq), colour = "white", size = 0.5) +
  viridis::scale_fill_viridis(
    breaks = c(0, 1),
    labels = c(0, 1)
  ) +
  theme(
    # legend.position = "none",
    legend.title = element_blank(),
    legend.text = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    axis.text.x = element_text(size = 12),
    # axis.text.x = element_text(size = 12, angle = 45, hjust = 1, vjust = 1),
    strip.background = element_blank(),
    strip.text.x = element_blank()
    ) +
  xlab("") + ylab("")

ggsave(file.path(anaDir, "clusters_heat.pdf"), width = 4, height = 3.5)
```

```{r fig_clusters_freq, fig.height=1, fig.width=1}
# show HMM states for clusters
dfToPlot <- popDTs %>%
  group_by(uID, live.cell.track.clusters.movement) %>%
  summarise(n = n()) %>%
  mutate(freq = n/sum(n) * 100)

write.csv(dfToPlot, file.path(anaDir, "clusters_freq.csv"))

ggplot(dfToPlot,
       aes(
         live.cell.track.clusters.movement, freq
         )) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    # position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    width = 0.3, alpha = 0.6) +
  ylab("Behaviour (%)") + xlab("") +
  # ylim(0, 60) +
  scale_fill_brewer(name = NULL, palette = "Set3")
```

```{r fig_track_DC_contact, fig.height=1, fig.width=1}
# show contact of T cells to DCs
tracksInfo <- cciaObj$tracksInfo(
  "live.cell.contact#live.DC/tracked",
  parentPop = "T/tracked", uIDs = uIDs
)

time.interval <- cciaObj$cciaObjects(uIDs = uIDs)[[1]]$omeXMLTimelapseInfo()$interval

# plot individual tracks
dfToPlot <- tracksInfo %>%
  left_join(unique(popDTs[, c(
    "uID", "live.cell.track.clusters.movement", "track_id")])) %>%
  mutate(DC.contact = time.interval * `live.cell.contact#live.DC/tracked.TRUE.n`)
  # group_by(uID, live.cell.track.clusters.movement) %>%
  # summarise(mean.contact = time.interval * mean(`live.cell.contact#live.DC/tracked.TRUE.n`))

write.csv(dfToPlot, file.path(anaDir, "tracks_contact_DC.csv"))

ggplot(dfToPlot, aes(live.cell.track.clusters.movement, DC.contact)) +
  theme_classic() +
  geom_jitter(
    # position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    width = 0.3, alpha = 0.6) +
  geom_boxplot(outlier.alpha = 0) +
  ylab("DC contact time (min)") + xlab("") +
  # ylim(0, 5) +
  scale_fill_brewer(name = NULL, palette = "Set3")
```

```{r}
cciaObj$popPaths(popType = "live", includeFiltered = TRUE)
```


```{r}
# now can you plot how much a DC is in contact with a T cell?
# get all DC contact IDs and set for DC
popDTs$has_contact <- FALSE
popDTs$contact_label <- NA
contactLabels <- unique(popDTs$`live.cell.contact_id#live.DC/tracked`)
popDTs[value_name == "DC" & label %in% contactLabels, has_contact := TRUE]

# merge which T cell type is contacting DCs
popDC <- copy(popDTs[value_name == "DC", c("uID", "track_id", "label")])
popDC[popDTs[value_name == "T", c("uID", "track_id", "label", "live.cell.contact_id#live.DC/tracked")],
      on = c("label" = "live.cell.contact_id#live.DC/tracked"),
      `:=` (T_label = i.label, T_track_id = i.track_id)]

# now add T cell type
popDC[tcells.sc[, c("uID", "track_id", "clusters")],
      on = c("uID", "T_track_id" = "track_id"), clusters := clusters]
```


```{r}
# get occupancy for DC tracks
occupancyDT <- popDC %>%
  group_by(uID, track_id, clusters) %>%
  summarise(n = n()) %>%
  mutate(freq = n/sum(n) * 100) %>%
  ungroup() %>%
  complete(uID, track_id, clusters, fill = list(freq = 0)) %>%
  dplyr::filter(!is.na(clusters))
```

```{r fig_DC_occupancy, fig.height=1, fig.width=1}
# plot out
write.csv(occupancyDT, file.path(anaDir, "DC_occupancy.csv"))

ggplot(occupancyDT, aes(clusters, freq)) +
  theme_classic() +
  geom_jitter(
    width = 0.3, alpha = 0.6) +
  ylab("DC occupancy (%)") + xlab("") +
  ylim(0, 100) +
  geom_boxplot(outlier.alpha = 0) 
```



```{r fig_clusters_DC_contact, fig.height=1, fig.width=1}
# show contact of T cells to DCs
tracksInfo <- cciaObj$tracksInfo(
  "live.cell.contact#live.DC/tracked",
  parentPop = "T/tracked", uIDs = uIDs
)

time.interval <- cciaObj$cciaObjects(uIDs = uIDs)[[1]]$omeXMLTimelapseInfo()$interval

dfToPlot <- tracksInfo %>%
  left_join(unique(popDTs[, c(
    "uID", "live.cell.track.clusters.movement", "track_id")])) %>%
  group_by(uID, live.cell.track.clusters.movement) %>%
  summarise(mean.contact = time.interval * mean(`live.cell.contact#live.DC/tracked.TRUE.n`))

write.csv(dfToPlot, file.path(anaDir, "clusters_contact_DC.csv"))

ggplot(dfToPlot,
       aes(
         live.cell.track.clusters.movement, mean.contact
         )) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    # position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    width = 0.3, alpha = 0.6) +
  ylab("DC contact time (min)") + xlab("") +
  ylim(0, 5) +
  scale_fill_brewer(name = NULL, palette = "Set3")
```

```{r}
# get DCs for image
DCs <- cciaObj$popDT(
  popType = "live", pops = c(
    "DC/tracked"
    ),
  includeFiltered = TRUE,
  flushCache = TRUE,
  uIDs = uIDs)
```

```{r fig_clusters_DC_contacts, fig.height=1, fig.width=1}
# show number of T contacts with DCs
tracksInfo <- cciaObj$tracksInfo(
  "live.cell.contact#live.DC/tracked",
  parentPop = "T/tracked", uIDs = uIDs
)

time.interval <- cciaObj$cciaObjects(uIDs = uIDs)[[1]]$omeXMLTimelapseInfo()$interval

dfToPlot <- tracksInfo %>%
  left_join(unique(popDTs[, c(
    "uID", "live.cell.track.clusters.movement", "track_id")])) %>%
  left_join(
    {popDTs %>%
      left_join(
        DCs[, c("uID", "track_id", "label")],
        by = c("uID", `live.cell.contact_id#live.DC/tracked` = "label")) %>%
      dplyr::rename(c(
        "track_id_T" = track_id.x,
        "track_id_DC" = track_id.y
      )) %>%
      dplyr::filter(`live.cell.contact#live.DC/tracked` == TRUE) %>%
      group_by(uID, track_id_T, live.cell.track.clusters.movement) %>%
      summarise(unique.contacts = length(unique(track_id_DC)))},
    by = c("uID", track_id = "track_id_T", "live.cell.track.clusters.movement")
  ) %>%
  mutate(time.per.DC = (time.interval * `live.cell.contact#live.DC/tracked.TRUE.n`)/unique.contacts) %>%
  # replace_na(list(unique.contacts = 0)) %>%
  group_by(uID, live.cell.track.clusters.movement) %>%
  summarise(
    mean.contacts = mean(unique.contacts, na.rm = TRUE),
    mean.time.per.DC = mean(time.per.DC, na.rm = TRUE)
    )

write.csv(dfToPlot, file.path(anaDir, "clusters_contacts_DC.csv"))

ggplot(dfToPlot,
       aes(
         # live.cell.track.clusters.movement, mean.contacts
         live.cell.track.clusters.movement, mean.time.per.DC
         )) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    # position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    width = 0.3, alpha = 0.6) +
  # geom_violin(scale = "width") +
  # stat_summary(fun=mean, geom="point", size=3, shape=18, color="Magenta") +
  ylab("DC contacts (#)") + xlab("") +
  # ylim(1, 3) +
  scale_fill_brewer(name = NULL, palette = "Set3")
```

```{r fig_psuedotime, fig.height=3, fig.width=5}
# show proportion of freq of populations in clusters
# plotColors <- c("#707070", "#ffb804")

ggplot(
  dfToPlot %>%
    # group_by(type, clusters) %>%
    group_by(type, behaviour) %>%
    summarise(n = n()) %>%
    mutate(
      freq = n/sum(n),
      ),
  # aes(x = 1, y = freq, fill = clusters)) +
  aes(x = 1, y = freq, fill = behaviour)) +
  scale_fill_brewer(name = NULL, palette = "Set1") +
  theme_classic() +
  # geom_bar(stat = "identity", width = 1) +
  geom_col() +
  coord_polar("y", start = 0) +
  facet_wrap(.~type, ncol = 2) +
  xlim(0, 1.5) +
  theme(
    axis.text = element_text(size = 15),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    legend.justification = "right",
    legend.position = "bottom",
    # legend.position = "none",
    axis.line = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    strip.background = element_blank(),
    strip.text.x = element_blank()
  )

ggsave(file.path(anaDir, "pop_clusters_freq.tiff"), width = 3, height = 2)
```
