---
title: "Behaviour GCAMP"
output: html_document
date: '2022-08-15'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Show transition states of live cell imaging

```{r}
Sys.setenv(KMP_DUPLICATE_LIB_OK = "TRUE")
devtools::load_all("../")
cciaUse("~/cecelia/dev")

library(ggplot2)
library(tidyverse)
```

```{r}
# set test variables
pID <- "3gzzkZ"
versionID <- 1
projectsDir <- "/Volumes/Analysis_SSD/Dominik/cecelia/projects/"
hpcDir <- "/data/scratch/projects/punim1124/cecelia/USERS/schienstockd/"
```

```{r}
# anaDir <- "/Volumes/USER_data/Dominik/Experiments/3P/Tcells_across"
anaDir <- "/Volumes/Lab-Mueller/Dominik Schienstock/Notebook/Experiments/DS_N060-3P-naive/ANALYSIS/plots"
```

```{r}
# HPC config
HPC_CONF <-  list(
  hpc = list(
    conf = list(
      email = "schienstockd@student.unimelb.edu.au",
      emailOnBegin = FALSE,
      emailOnEnd = FALSE,
      emailOnFail = TRUE,
      numNodes = 1,
      numTasks = 1,
      numCPUperTask = 1,
      numGPUperTask = 1,
      memory = 50,
      walltime = "00-02:00:00",
      projectPartitions = "gpu-a100",
      projectID = "punim1031",
      projectQos = "",
      useGPU = TRUE
    )
  ),
  utils = list(
    ssh = list(
      username = "schienstockd",
      address = "spartan.hpc.unimelb.edu.au",
      keyfile = "/Users/Dominik/.ssh/spartan_rsa"
    ),
    python = list(
      condaEnv = cciaConf()$python$conda$source$env,
      condaDir = cciaConf()$python$conda$dir
    )
  )
)
```

```{r}
# a <- readRDS("/Volumes/USER_data/Dominik/CECELIA_BACKUP/3gzzkZ/ANALYSIS/1/KnSDpd/ccid.rds")
# a$CciaObjectUIDs <- c(
#   a$CciaObjectUIDs, c("fizPPH", "5phIYn", "DpdalG", "Zvd2Z8", "4jX370", "N5bASi", "mpTdNG", "vIm42v")
# )
# 
# names(a$CciaObjectUIDs) <- a$CciaObjectUIDs
# 
# saveRDS(a, "/Volumes/USER_data/Dominik/CECELIA_BACKUP/3gzzkZ/ANALYSIS/1/KnSDpd/ccid.rds")
```

```{r}
# HMM
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "qI6XzC", versionID = versionID, initReactivity = FALSE # Tcells
)

cciaObj$imFilepath()
```


```{r}
# HMM
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "KnSDpd", versionID = versionID, initReactivity = FALSE # Tcells
)

# get experimental info
exp.info <- as.data.table(cciaObj$summary(withSelf = FALSE, fields = c("Attr")))
uIDs <- exp.info[Include == "Y"]$uID

# run task
funParams <- list(
  popType = "live",
  pops = c("gBT/tracked", "gDT/tracked", "default/tracked", "gBT-uGFP/tracked"),
  modelMeasurements = c("live.cell.speed", "live.cell.angle"),
  # scaleMeasurements = c("live.cell.speed", "live.cell.angle"),
  colName = "movement",
  appendStates = list(),
  skipTimesteps = 0,
  subtrackOverlap = TRUE,
  noiseFilterMeasurements = 5,
  postFiltering = 0,
  postIterations = 0,
  numStates = 3,
  uIDs = uIDs
)

# run task
task <- cciaObj$runTask(
  funName = "behaviourAnalysis.hmmStates",
  funParams = funParams,
  env = "local",
  runInplace = TRUE,
  taskID = 1
)
```

```{r}
# get HMM transitions
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "KnSDpd", versionID = versionID, initReactivity = FALSE # Tissues
)

# get experimental info
exp.info <- as.data.table(cciaObj$summary(withSelf = FALSE, fields = c("Attr")))
uIDs <- exp.info[Include == "Y"]$uID

# run task
funParams <- list(
  popType = "live",
  pops = c("gBT/tracked", "gDT/tracked", "default/tracked", "gBT-uGFP/tracked"),
  colName = "movement",
  hmmStates = c("movement"),
  includeStart = FALSE,
  includeSelfTransitions = TRUE,
  uIDs = uIDs
)

# run task
task <- cciaObj$runTask(
  funName = "behaviourAnalysis.hmmTransitions",
  funParams = funParams,
  env = "local",
  runInplace = TRUE,
  taskID = 1
)
```

```{r}
# cluster tracks based on transitions
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "KnSDpd", versionID = versionID, initReactivity = FALSE # Tissues
)

# get experimental info
exp.info <- as.data.table(cciaObj$summary(withSelf = FALSE, fields = c("Attr")))
uIDs <- exp.info[Include == "Y"]$uID

# run task
funParams <- list(
  popType = "live",
  popsToCluster = c("gBT/tracked", "gDT/tracked", "default/tracked", "gBT-uGFP/tracked"),
  valueName = "tracks.clusters.tcells.hmm_transitions_movement",
  clusterColName = "hmm_transitions_movement",
  resolution = 0.20,
  percentile = 99.5,
  trackMeasures = c(
    "speed",
    "duration",
    "trackLength",
    "meanTurningAngle",
    "displacement",
    "straightness",
    "displacementRatio",
    "outreachRatio",
    "asphericity",
    "overallAngle"
  ),
  objectMeasures = c(
    # HMM states
    "live.cell.hmm.state.movement",
    "live.cell.hmm.transitions.movement"
    ),
  nMeasures = c(
    ),
  sumMeasures = c(
    ),
  calcMeasures = list(
  ),
  addPops = c(
    ),
  calcLabelProps = TRUE,
  # usePaga = FALSE,
  usePaga = TRUE,
  pagaThreshold = 0.1,
  minTracklength = 6,
  uIDs = uIDs
)

# run task
task <- cciaObj$runTask(
  funName = "behaviourAnalysis.clusterTracks",
  funParams = funParams,
  env = "local",
  runInplace = TRUE,
  taskID = 1
)
```

```{r}
# get normal tracking parameters and compare
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "KnSDpd", versionID = versionID, initReactivity = FALSE # Tissues
)

# get experimental info
exp.info <- as.data.table(cciaObj$summary(withSelf = FALSE, fields = c("Attr")))

uIDs <- exp.info[Include == "Y"]$uID
# uIDs <- exp.info[Include == "Y" & Source == "3P"]$uID
# pops <- cciaObj$popPaths(popType = "live", combinePaths = FALSE, uIDs = uIDs)

pops <- list(
  # `2P-iLN-gBT` = "tcells.gBT/tracked",
  # `2P-iLN-P14` = "tcells.P14/tracked",
  # `2P-iLN-OTI` = "tcells.OTI/tracked",
  `2P-iLN-gBT` = "gBT/tracked",
  `2P-iLN-gDT` = "gDT/tracked",
  `3P-iLN-gBT` = "default/tracked",
  `3P-SPLEEN-gBT` = "gBT-uGFP/tracked"
)

popDT <- cciaObj$popDT(popType = "live", pops = pops, includeFiltered = TRUE, uIDs = uIDs)

# get tracks info and check parameters
# tracksInfo <- cciaObj$tracksMeasures(pops = "P14-CTDR/tracked")
tracksInfo <- cciaObj$tracksMeasures(pops = pops, uIDs = uIDs)

# # get clustering
# tcells.sc <- as.data.table(cciaEnv()$LabelPropsUtils(
#   cciaObj$persistentObjectDirectory(),
#   value_name = "tracks.clusters.tcells.hmm_transitions_movement.sc")$label_props_view()$as_df())
```

```{r fig_basics, fig.height=5, fig.width=18}
statsToPlot <- colnames(tracksInfo)
statsToPlot <- statsToPlot[!statsToPlot %in% c("uID", "cell_type", "track_id")]
datToPlot <- tracksInfo %>%
  pivot_longer(cols = statsToPlot, names_to = "measure", values_to = "value")

# plot basics
ggplot(datToPlot %>% left_join(exp.info), aes(interaction(Source, Tissue), value, color = cell_type)) +
# ggplot(datToPlot %>% left_join(exp.info) %>% dplyr::filter(Source == "3P", Tissue == "SPLEEN"),
#        aes(interaction(Source, Tissue), value, color = cell_type)) +
       # aes(uID, value, color = cell_type)) +
  theme_classic() +
  geom_jitter(
    position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    # width = 0.2, alpha = 0.4) +
  geom_boxplot(outlier.alpha = 0.) +
  facet_wrap(.~measure, ncol = 5, scales = "free_y") +
  # coord_flip() +
  xlab("")

ggsave(file.path(anaDir, "track_stats.png"), height = 6, width = 18)
```

```{r fig_hmm_props, fig.height=3, fig.width=3}
# show measurements of clusters to compare
colsToPlot <- rev(c(
  "angle",
  "speed",
  "compactness",
  "extent",
  "oblate",
  "prolate",
  "solidity",
  "sphericity",
  "surface_area",
  "volume"
))

# convert angle to degrees
popDT[, live.cell.angle_deg := pracma::rad2deg(live.cell.angle)]

propsToPlot <- popDT[exp.info, on = "uID"] %>%
  dplyr::rename(
    "speed" = "live.cell.speed",
    "angle" = "live.cell.angle_deg",
    "oblate" = "ellipticity_interm_oblate",
    "prolate" = "ellipticity_interm_prolate"
  ) %>%
  # drop_na(live.cell.hmm.state.hybrid_pop) %>%
  pivot_longer(
    cols = colsToPlot, names_to = "prop", values_to = "value"
    ) %>%
  pivot_longer(
    cols = c(
      "live.cell.hmm.state.movement"
      # "live.cell.hmm.state.shape"
    ), names_to = "hmm_type", values_to = "hmm_value"
    )

propsToPlot$prop <- factor(propsToPlot$prop, levels = colsToPlot)

# show heatmap for HMM
propsSummary <- propsToPlot %>%
  dplyr::filter(!is.na(hmm_value)) %>%
  group_by(hmm_type, hmm_value, prop) %>%
  replace_na(list(value = 0)) %>%
  summarise(mean = mean(value)) %>%
  group_by(hmm_type, prop) %>%
  mutate(freq = (mean - min(mean)) / (max(mean) - min(mean))) %>%
  arrange(-prop)

ggplot(propsSummary %>% dplyr::filter(hmm_value != "Clustering"), aes(as.factor(hmm_value), prop)) +
  theme_classic() +
  geom_tile(aes(fill = freq), colour = "white", size = 0.5) +
  viridis::scale_fill_viridis(
    breaks = c(0, 1),
    labels = c(0, 1)
  ) +
  theme(
    legend.position = "none",
    legend.title = element_blank(),
    legend.text = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    axis.text.x = element_text(size = 12),
    strip.background = element_blank(),
    strip.text.x = element_blank(),
    # axis.text.x = element_text(size = 12, angle = 45, hjust = 1, vjust = 1)
    ) +
  xlab("") + ylab("") +
  facet_grid(.~hmm_type)

ggsave(file.path(anaDir, "HMM_heat.pdf"), width = 2.1, height = 3)
```

```{r fig_hmm_freq, fig.height=2, fig.width=6}
# save frequencies of HMM
datToPlot <- popDT %>%
  drop_na(live.cell.hmm.state.movement) %>%
  group_by(uID, pop, live.cell.hmm.state.movement) %>%
  summarise(n.hmm = n()) %>%
  mutate(freq.hmm = n.hmm/sum(n.hmm) * 100) %>%
  left_join(exp.info)

# plot
ggplot(datToPlot,
       aes(as.factor(live.cell.hmm.state.movement), freq.hmm, fill = pop)) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    # width = 0.3, alpha = 0.6) +
  # stat_summary(fun=mean, geom="point", size=3, shape=18, color="Magenta") +
  ylab("Frequency state") + xlab("") +
  ylim(0, 100) +
  scale_fill_brewer(name = NULL, palette = "Set3") +
  facet_grid(.~interaction(Source, Tissue))

ggsave(file.path(anaDir, "HMM_freq.pdf"), width = 5, height = 2)
```
```{r fig_umap, fig.height=4, fig.width=4}
dfToPlot <- copy(tcells.sc) %>% drop_na(clusters) %>% left_join(exp.info)

clusterMapping <- list(
  Directed = c(1),
  Meandering = c(4,0,3),
  Scanning = c(2)
)

dfToPlot <- .mapClustNames(dfToPlot, clusterMapping, "clusters")

# get mean positions of clusters
meanClusterPos <- dfToPlot %>%
  # group_by(clusters) %>%
  group_by(clusters.name) %>%
  summarise(
    UMAP_1 = median(UMAP_1),
    UMAP_2 = median(UMAP_2)
  )
dfToPlot$clusters <- factor(dfToPlot$clusters)

colPal <- randomcoloR::distinctColorPalette(length(unique(dfToPlot$clusters)))

# plot UMAP
ggplot(
  dfToPlot,
  aes(UMAP_1, UMAP_2)
  ) +
  # geom_point(aes(color = clusters)) +
  # geom_point(aes(color = interaction(Source, Tissue))) +
  geom_point(aes(color = clusters.name)) +
  theme_classic() +
  scale_color_brewer(name = NULL, palette = "Set1") +
  # scale_color_manual(values = colPal) +
  theme(
    axis.text = element_text(size = 15),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    legend.justification = "right",
    # legend.position = "bottom"
    legend.position = "none",
    axis.line = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
    ) +
  geom_label(
    data = meanClusterPos,
    # aes(label = clusters),
    aes(label = clusters.name),
    label.size = 0.25,
    color = "black"
    )

ggsave(file.path(anaDir, "umap.png"), width = 2, height = 2)
# ggsave(file.path(anaDir, "umap_wo_labels.png"), width = 2, height = 2)
```

```{r}
# show measurements of clusters to compare
propsToPlot <- copy(tcells.sc)

propsToPlot <- .mapClustNames(propsToPlot, clusterMapping, "clusters")

# propsToPlot <- propsToPlot %>%
#   dplyr::rename(
#     "Movement HMM 1" = "live.cell.hmm.state.movement.1",
#     "Movement HMM 2" = "live.cell.hmm.state.movement.2",
#     "Movement HMM 3" = "live.cell.hmm.state.movement.3",
#     "Movement HMM 4" = "live.cell.hmm.state.movement.4",
#   )

colsToPlot <- colnames(propsToPlot)[!colnames(propsToPlot) %in% c(
  "pop", "uID", "track_id", "clusters", "clusters.name", "clusters.id", "UMAP_1", "UMAP_2"
  )]

propsToPlot <- propsToPlot %>%
  pivot_longer(
    cols = colsToPlot, names_to = "prop", values_to = "value"
    )

propsToPlot$prop <- factor(propsToPlot$prop, levels = sort(colsToPlot, decreasing = TRUE))

# propsList <- c(
#   'Movement HMM 1',
#   'Movement HMM 2',
#   'Movement HMM 3',
#   'Movement HMM 4',
#   'asphericity',
#   'displacement',
#   'displacementRatio',
#   'duration',
#   'meanTurningAngle',
#   'outreachRatio',
#   'overallAngle',
#   'speed',
#   'straightness',
#   'trackLength'
# )

# show heatmap for clusters
propsSummary <- propsToPlot %>%
  dplyr::filter(
    # clusters.name != "NONE",
    # prop %in% propsList
    ) %>%
  # group_by(clusters, prop) %>%
  group_by(clusters.name, prop) %>%
  summarise(mean = mean(value, rm.na = TRUE)) %>%
  group_by(prop) %>%
  mutate(freq = (mean - min(mean)) / (max(mean) - min(mean))) %>%
  arrange(-prop)
```
```{r fig_clusters_heat, fig.height=8, fig.width=6}
# propsSummary$prop <- factor(
#   propsSummary$prop, levels = rev(propsList))
# propsSummary$clusters.name <- factor(
#   propsSummary$clusters.name, levels = c(
#     "Directed", "Meandering", "Scanning", "Clustering"
#   ))

# # sort states
# propsSummary[!propsSummary$clusters %in% clusterOrder[clusterOrder != 1],]$clusters <- NA
# # propsSummary$clusters <- factor(propsSummary$clusters, levels = clusterOrder)
# propsSummary$clusters <- case_match(
#   as.character(propsSummary$clusters),
#   c("3") ~ "1",
#   c("6") ~ "2",
#   c("0") ~ "3",
#   c("7") ~ "4",
#   c("2") ~ "5",
#   c("5") ~ "6",
#   c("4") ~ "7",
# )

# ggplot(propsSummary, aes(as.factor(clusters.name), prop)) +
# ggplot(propsSummary, aes(as.factor(clusters), prop)) +
ggplot(propsSummary %>%
         # dplyr::filter(!str_detect(prop, "live.cell")) %>%
         # drop_na(clusters), aes(clusters, prop)) +
         drop_na(clusters.name), aes(clusters.name, prop)) +
  theme_classic() +
  geom_tile(aes(fill = freq), colour = "white", size = 0.5) +
  viridis::scale_fill_viridis(
    breaks = c(0, 1),
    labels = c(0, 1)
  ) +
  theme(
    legend.position = "none",
    legend.key.size = unit(8, "mm"),
    legend.title = element_blank(),
    legend.text = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    # axis.text.x = element_text(size = 12),
    axis.text.x = element_text(size = 12, angle = 45, hjust = 1, vjust = 1),
    strip.background = element_blank(),
    strip.text.x = element_blank()
    ) +
  xlab("") + ylab("")

ggsave(file.path(anaDir, "clusters_heat.pdf"), width = 2.7, height = 3.5)
# ggsave(file.path(anaDir, "clusters_heat.pdf"), width = 5, height = 14)
```
```{r fig_clusters_freq, fig.height=4, fig.width=6}
# save frequencies of track clusters
summaryDF <- copy(tcells.sc)

summaryDF <- .mapClustNames(summaryDF, clusterMapping, "clusters")

# show frequency of clusters
# summaryDF <- summaryDF[, .(n.clusters = .N), by = .(uID, pop, clusters)] %>%
summaryDF <- summaryDF[, .(n.clusters = .N), by = .(uID, pop, clusters.name)] %>%
  droplevels() %>%
  group_by(uID, pop) %>%
  mutate(freq.clusters = n.clusters/sum(n.clusters) * 100) %>%
  ungroup() %>%
  # complete(uID, pop, clusters, fill = list(freq.clusters = 0)) %>%
  # complete(uID, pop, clusters.name, fill = list(freq.clusters = 0)) %>%
  left_join(exp.info)

# ggplot(summaryDF, aes(clusters, freq.clusters, color = interaction(Source, Tissue))) +
ggplot(summaryDF, aes(clusters.name, freq.clusters, color = interaction(Source, Tissue))) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
  scale_color_brewer(name = "Treatment", palette = "Set1") +
  ylim(0, 100) + xlab("") + ylab("Behaviour (%)")

ggsave(file.path(anaDir, "clusters_freq.pdf"), width = 4, height = 2.5)
```
