---
title: "Behaviour GCAMP"
output: html_document
date: '2022-08-15'
---

```{r setup, include=FALSE}
renv::load("~/R-workspace/cecelia/")
knitr::opts_chunk$set(echo = TRUE)
```

## Show transition states of live cell imaging

```{r}
devtools::load_all("../")
cciaUse("~/cecelia/dev")

library(ggplot2)
library(tidyverse)
```

```{r}
# set test variables
pID <- "8BR53W"
versionID <- 1
projectsDir <- "/Volumes/Analysis_SSD/Dominik/cecelia/projects/"
hpcDir <- "/data/scratch/projects/punim1124/cecelia/USERS/schienstockd/"
```

```{r}
# anaDir <- "/Volumes/USER_data/Dominik/Experiments/DS_N052/ANALYSIS/IMAGE/CECELIA"
anaDir <- "/Volumes/USER_data/Dominik/Experiments/DS_N052/ANALYSIS/IMAGE/CECELIA/transitions"
```

```{r}
# HPC config
HPC_CONF <-  list(
  hpc = list(
    conf = list(
      email = "schienstockd@student.unimelb.edu.au",
      emailOnBegin = FALSE,
      emailOnEnd = FALSE,
      emailOnFail = TRUE,
      numNodes = 1,
      numTasks = 1,
      numCPUperTask = 1,
      numGPUperTask = 1,
      memory = 50,
      walltime = "00-02:00:00",
      projectPartitions = "gpu-a100",
      projectID = "punim1031",
      projectQos = "",
      useGPU = TRUE
    )
  ),
  utils = list(
    ssh = list(
      username = "schienstockd",
      address = "spartan.hpc.unimelb.edu.au",
      keyfile = "/Users/Dominik/.ssh/spartan_rsa"
    ),
    python = list(
      condaEnv = cciaConf()$python$conda$source$env,
      condaDir = cciaConf()$python$conda$dir
    )
  )
)
```

```{r}
# HMM
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "YJRfCW", versionID = versionID, initReactivity = FALSE # H2Kb
)

uIDs <- names(cciaObj$cciaObjects())
uIDs <- uIDs[!uIDs %in% "1wZMND"]

# run task
funParams <- list(
  popType = "live",
  pops = c("gBT/tracked", "OTI/tracked"),
  modelMeasurements = c("live.cell.speed", "live.cell.angle"),
  scaleMeasurements = c("live.cell.speed", "live.cell.angle"),
  colName = "movement",
  appendStates = list(live.cell.is.clust = TRUE),
  skipTimesteps = 0,
  subtrackOverlap = TRUE,
  noiseFilterMeasurements = 5,
  postFiltering = 2,
  postIterations = 2,
  numStates = 3,
  uIDs = uIDs
)

# run task
task <- cciaObj$runTask(
  funName = "behaviourAnalysis.hmmStates",
  funParams = funParams,
  env = "local",
  runInplace = TRUE,
  taskID = 1
)
```

```{r}
# get HMM transitions
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "YJRfCW", versionID = versionID, initReactivity = FALSE # H2Kb
)

uIDs <- names(cciaObj$cciaObjects())
uIDs <- uIDs[!uIDs %in% "1wZMND"]

# run task
funParams <- list(
  popType = "live",
  pops = c("gBT/tracked", "OTI/tracked"),
  colName = "movement",
  hmmStates = c("movement"),
  includeStart = FALSE,
  includeSelfTransitions = TRUE,
  uIDs = uIDs
)

# run task
task <- cciaObj$runTask(
  funName = "behaviourAnalysis.hmmTransitions",
  funParams = funParams,
  env = "local",
  runInplace = TRUE,
  taskID = 1
)
```

```{r}
# cluster tracks based on transitions
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "YJRfCW", versionID = versionID, initReactivity = FALSE # H2Kb
)

uIDs <- names(cciaObj$cciaObjects())
uIDs <- uIDs[!uIDs %in% "1wZMND"]

# run task
funParams <- list(
  popType = "live",
  popsToCluster = c("gBT/tracked", "OTI/tracked"),
  valueName = "tracks.clusters.tcells.hmm_transitions_movement",
  clusterColName = "hmm_transitions_movement",
  # valueName = "tracks.clusters.tcells.hmm_movement",
  # clusterColName = "hmm_movement",
  resolution = 0.20,
  percentile = 99.5,
  trackMeasures = c(
    "speed",
    "duration",
    "trackLength",
    "meanTurningAngle",
    "displacement",
    "straightness",
    "displacementRatio",
    "outreachRatio",
    "asphericity",
    "overallAngle"
  ),
  objectMeasures = c(
    # "extent",
    # "solidity",
    # "integral_mean_curvature",
    # "ellipticity_oblate",
    # "ellipticity_prolate",
    # "ellipticity_interm_oblate",
    # "ellipticity_interm_prolate",
    # "sphericity",
    # HMM states
    "live.cell.hmm.state.movement",
    "live.cell.hmm.transitions.movement"
    ),
  nMeasures = c(
    ),
  sumMeasures = c(
    ),
  calcMeasures = list(
  ),
  addPops = c(
    ),
  calcLabelProps = TRUE,
  # usePaga = FALSE,
  usePaga = TRUE,
  pagaThreshold = 0.1,
  minTracklength = 6,
  uIDs = uIDs
)

# run task
task <- cciaObj$runTask(
  funName = "behaviourAnalysis.clusterTracks",
  funParams = funParams,
  env = "local",
  runInplace = TRUE,
  taskID = 1
)
```

```{r}
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "YJRfCW", versionID = versionID, initReactivity = FALSE # H2Kb
)

uIDs <- names(cciaObj$cciaObjects())
uIDs <- uIDs[!uIDs %in% "1wZMND"]

# get experimental info
exp.info <- cciaObj$summary(
  withSelf = FALSE, fields = c("Attr", "oriFilepath")
)

data.table::fwrite(exp.info, file.path(anaDir, "exp_info.csv"))

# get clustering
tcells.sc <- as.data.table(cciaEnv()$LabelPropsUtils(
  cciaObj$persistentObjectDirectory(),
  value_name = "tracks.clusters.tcells.hmm_transitions_movement.sc")$label_props_view()$as_df())
  # value_name = "tracks.clusters.tcells.hmm_movement.sc")$label_props_view()$as_df())

# get popDTs for set
popDTs <- cciaObj$popDT(
  popType = "live", pops = c(
    "OTI/tracked",
    "gBT/tracked"
    ),
  includeFiltered = TRUE,
  flushCache = TRUE,
  uIDs = uIDs)
```

```{r fig_hmm_props, fig.height=3, fig.width=3}
# show measurements of clusters to compare
colsToPlot <- rev(c(
  "angle",
  "speed",
  "compactness",
  "extent",
  "oblate",
  "prolate",
  "solidity",
  "sphericity",
  "surface_area",
  "volume"
))

# convert angle to degrees
popDTs[, live.cell.angle_deg := pracma::rad2deg(live.cell.angle)]

propsToPlot <- popDTs[exp.info, on = "uID"] %>%
  dplyr::rename(
    "speed" = "live.cell.speed",
    "angle" = "live.cell.angle_deg",
    "oblate" = "ellipticity_interm_oblate",
    "prolate" = "ellipticity_interm_prolate"
  ) %>%
  # drop_na(live.cell.hmm.state.hybrid_pop) %>%
  pivot_longer(
    cols = colsToPlot, names_to = "prop", values_to = "value"
    ) %>%
  pivot_longer(
    cols = c(
      "live.cell.hmm.state.movement"
    ), names_to = "hmm_type", values_to = "hmm_value"
    )

propsToPlot$prop <- factor(propsToPlot$prop, levels = colsToPlot)

# show heatmap for HMM
propsSummary <- propsToPlot %>%
  dplyr::filter(!is.na(hmm_value)) %>%
  group_by(hmm_type, hmm_value, prop) %>%
  replace_na(list(value = 0)) %>%
  summarise(mean = mean(value)) %>%
  group_by(hmm_type, prop) %>%
  mutate(freq = (mean - min(mean)) / (max(mean) - min(mean))) %>%
  arrange(-prop)

ggplot(propsSummary, aes(as.factor(hmm_value), prop)) +
  theme_classic() +
  geom_tile(aes(fill = freq), colour = "white", size = 0.5) +
  viridis::scale_fill_viridis(
    breaks = c(0, 1),
    labels = c(0, 1)
  ) +
  theme(
    legend.position = "none",
    legend.title = element_blank(),
    legend.text = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    axis.text.x = element_text(size = 12),
    strip.background = element_blank(),
    strip.text.x = element_blank(),
    # axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)
    ) +
  xlab("") + ylab("") +
  facet_grid(.~hmm_type)

ggsave(file.path(anaDir, "HMM_heat.pdf"), width = 2.3, height = 3)
```

```{r fig_umap, fig.height=8, fig.width=8}
dfToPlot <- copy(tcells.sc) %>% drop_na(clusters) %>% left_join(exp.info)

clusterMapping <- list(
  Directed = c(2),
  Meandering = c(0,1,3,5),
  Scanning = c(4)
  # Aggregating = c()
)

dfToPlot <- .mapClustNames(dfToPlot, clusterMapping, "clusters")

# get mean positions of clusters
meanClusterPos <- dfToPlot %>%
  group_by(clusters) %>%
  # group_by(clusters.name) %>%
  summarise(
    UMAP_1 = mean(UMAP_1),
    UMAP_2 = mean(UMAP_2)
  )
dfToPlot$clusters <- factor(dfToPlot$clusters)

colPal <- randomcoloR::distinctColorPalette(length(unique(dfToPlot$clusters)))

# plot UMAP
ggplot(
  dfToPlot,
  aes(UMAP_1, UMAP_2)
  ) +
  # geom_point(aes(color = clusters)) +
  geom_point(aes(color = clusters.name)) +
  theme_classic() +
  scale_color_brewer(name = NULL, palette = "Set1") +
  # scale_color_manual(values = colPal) +
  theme(
    axis.text = element_text(size = 15),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    legend.justification = "right",
    # legend.position = "bottom"
    legend.position = "none",
    axis.line = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
    ) 
  # geom_label(
  #   data = meanClusterPos,
  #   aes(label = clusters),
  #   # aes(label = clusters.name),
  #   label.size = 0.25,
  #   color = "black"
  #   )

# ggsave(file.path(anaDir, "umap.tiff"), width = 2, height = 2)
ggsave(file.path(anaDir, "umap_wo_labels.tiff"), width = 2, height = 2)
```

```{r fig_umap_props, fig.height=4, fig.width=4}
datToPlot <- copy(tcells.sc) %>%
  drop_na(clusters) %>%
  left_join(exp.info)

# plot UMAP
ggplot(datToPlot, aes(UMAP_1, UMAP_2)) +
  theme_classic() +
  geom_point(aes(color = speed), size = 1, alpha = 1) +
  # geom_point(aes(color = meanTurningAngle), size = 1, alpha = 1) +
  viridis::scale_color_viridis() +
  theme(
    axis.text = element_text(size = 15),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    legend.justification = "right",
    # legend.position = "bottom"
    legend.position = "none",
    axis.line = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
    )

ggsave(file.path(anaDir, paste0("umap_Velocity.tiff")), width = 2, height = 2)
# ggsave(file.path(anaDir, paste0("umap_Angle.tiff")), width = 2, height = 2)
```

```{r fig_umap, fig.height=4, fig.width=4}
plot.p1 <- function(df.all, df.subset) {
  plot.colours <- .flowColours(df.subset$UMAP_1, df.subset$UMAP_2, colramp = viridisLite::inferno)
  
  ggplot(df.all, aes(UMAP_1, UMAP_2)) +
    theme_classic() +
    geom_point(color = "black", size = 1) +
    geom_point(data = df.subset, color = plot.colours, size = 1, alpha = 1) +
    theme(
      axis.text = element_text(size = 15),
      axis.text.x = element_blank(),
      axis.ticks.x = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank(),
      legend.justification = "right",
      # legend.position = "bottom"
      legend.position = "none",
      axis.line = element_blank(),
      axis.title.x = element_blank(),
      axis.title.y = element_blank()
      )
}

datToPlot <- copy(tcells.sc) %>%
  drop_na(clusters) %>%
  left_join(exp.info)

# plot UMAP
plot.p1(datToPlot, datToPlot %>% dplyr::filter(pop != "gBT/tracked", Genotype == "B6"))
ggsave(file.path(anaDir, paste0("umap_B6_OTI.tiff")), width = 2, height = 2)

plot.p1(datToPlot, datToPlot %>% dplyr::filter(pop == "gBT/tracked", Genotype == "B6"))
ggsave(file.path(anaDir, paste0("umap_B6_gBT.tiff")), width = 2, height = 2)

plot.p1(datToPlot, datToPlot %>% dplyr::filter(pop != "gBT/tracked", Genotype != "B6"))
ggsave(file.path(anaDir, paste0("umap_H2Kb_OTI.tiff")), width = 2, height = 2)

plot.p1(datToPlot, datToPlot %>% dplyr::filter(pop == "gBT/tracked", Genotype != "B6"))
ggsave(file.path(anaDir, paste0("umap_H2Kb_gBT.tiff")), width = 2, height = 2)
```

```{r fig_umap, fig.height=4, fig.width=4}
# can you show the progression of behaviour clusters from infected to uninfected?
clusterOrder <- c(5,4,2,0,1,3)
clusterColours <- c("grey", viridisLite::viridis(length(clusterOrder) - 1))

dfToPlot <- as.data.table(copy(tcells.sc) %>% drop_na(clusters) %>% left_join(exp.info))
dfToPlot <- dfToPlot[clusters %in% clusterOrder]
dfToPlot[, clusters := factor(clusters, levels = clusterOrder)]

# show progression on UMAP
ggplot(
  dfToPlot,
  aes(UMAP_1, UMAP_2)
  ) +
  geom_point(aes(color = clusters)) +
  theme_classic() +
  scale_color_manual(values = clusterColours) +
  theme(
    axis.text = element_text(size = 15),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    legend.justification = "right",
    # legend.position = "bottom"
    legend.position = "none",
    axis.line = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
    )

ggsave(file.path(anaDir, paste0("umap_Progression.tiff")), width = 2, height = 2)
```

```{r}
# show measurements of clusters to compare
propsToPlot <- copy(tcells.sc)

propsToPlot <- .mapClustNames(propsToPlot, clusterMapping, "clusters")

# propsToPlot <- propsToPlot %>%
#   dplyr::rename(
#     "Movement HMM 1" = "live.cell.hmm.state.movement.1",
#     "Movement HMM 2" = "live.cell.hmm.state.movement.2",
#     "Movement HMM 3" = "live.cell.hmm.state.movement.3",
#     "Movement HMM 4" = "live.cell.hmm.state.movement.4",
#   )

colsToPlot <- colnames(propsToPlot)[!colnames(propsToPlot) %in% c(
  "pop", "uID", "track_id", "clusters", "clusters.name", "clusters.id", "UMAP_1", "UMAP_2"
  )]

propsToPlot <- propsToPlot %>%
  pivot_longer(
    cols = colsToPlot, names_to = "prop", values_to = "value"
    )

propsToPlot$prop <- factor(propsToPlot$prop, levels = sort(colsToPlot, decreasing = TRUE))

# propsList <- c(
#   'Movement HMM 1',
#   'Movement HMM 2',
#   'Movement HMM 3',
#   'Movement HMM 4',
#   'asphericity',
#   'displacement',
#   'displacementRatio',
#   'duration',
#   'meanTurningAngle',
#   'outreachRatio',
#   'overallAngle',
#   'speed',
#   'straightness',
#   'trackLength'
# )

# show heatmap for clusters
propsSummary <- propsToPlot %>%
  dplyr::filter(
    # clusters.name != "NONE",
    # prop %in% propsList
    ) %>%
  # group_by(clusters, prop) %>%
  group_by(clusters.name, prop) %>%
  summarise(mean = mean(value, rm.na = TRUE)) %>%
  group_by(prop) %>%
  mutate(freq = (mean - min(mean)) / (max(mean) - min(mean))) %>%
  arrange(-prop)
```

```{r fig_clusters_heat, fig.height=8, fig.width=6}
# propsSummary$prop <- factor(
#   propsSummary$prop, levels = rev(propsList))
# propsSummary$clusters.name <- factor(
#   propsSummary$clusters.name, levels = c(
#     "Directed", "Meandering", "Scanning", "Clustering"
#   ))

# # sort states
# propsSummary[!propsSummary$clusters %in% clusterOrder[clusterOrder != 1],]$clusters <- NA
# # propsSummary$clusters <- factor(propsSummary$clusters, levels = clusterOrder)
# propsSummary$clusters <- case_match(
#   as.character(propsSummary$clusters),
#   c("3") ~ "1",
#   c("6") ~ "2",
#   c("0") ~ "3",
#   c("7") ~ "4",
#   c("2") ~ "5",
#   c("5") ~ "6",
#   c("4") ~ "7",
# )

# ggplot(propsSummary, aes(as.factor(clusters.name), prop)) +
# ggplot(propsSummary, aes(as.factor(clusters), prop)) +
ggplot(propsSummary %>%
         dplyr::filter(!str_detect(prop, "live.cell")) %>%
         # drop_na(clusters), aes(clusters, prop)) +
         drop_na(clusters.name), aes(clusters.name, prop)) +
  theme_classic() +
  geom_tile(aes(fill = freq), colour = "white", size = 0.5) +
  viridis::scale_fill_viridis(
    breaks = c(0, 1),
    labels = c(0, 1)
  ) +
  theme(
    legend.position = "none",
    legend.key.size = unit(8, "mm"),
    legend.title = element_blank(),
    legend.text = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    # axis.text.x = element_text(size = 12),
    axis.text.x = element_text(size = 12, angle = 45, hjust = 1, vjust = 1),
    strip.background = element_blank(),
    strip.text.x = element_blank()
    ) +
  xlab("") + ylab("")

ggsave(file.path(anaDir, "clusters_heat.pdf"), width = 2.7, height = 3.5)
# ggsave(file.path(anaDir, "clusters_heat.pdf"), width = 5, height = 14)
```

```{r fig_clusters_heat, fig.height=2, fig.width=6}
# get frequencies of HMM for each cluster
# and plot as bar graphs
datToPlot <- copy(popDTs)

datToPlot <- .mapClustNames(datToPlot, clusterMapping, "live.cell.track.clusters.hmm_transitions_movement") %>%
  # mutate(live.cell.track.clusters.hmm_transitions_movement = as.numeric(as.character(
  #   live.cell.track.clusters.hmm_transitions_movement))) %>%
  # drop_na(live.cell.track.clusters.hmm_transitions_movement) %>%
  drop_na(live.cell.hmm.state.movement) %>%
  # group_by(live.cell.track.clusters.hmm_transitions_movement, live.cell.hmm.state.movement) %>%
  group_by(clusters.name, live.cell.hmm.state.movement) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n) * 1) %>%
  ungroup() %>%
  # complete(live.cell.track.clusters.hmm_transitions_movement, live.cell.hmm.state.movement, fill = list(freq = 0))
  complete(clusters.name, live.cell.hmm.state.movement, fill = list(freq = 0))

data.table::fwrite(datToPlot, file = file.path(anaDir, "freq_hmm.csv"))

# ggplot(datToPlot, aes(as.factor(live.cell.track.clusters.hmm_transitions_movement), freq,
ggplot(datToPlot, aes(clusters.name, freq,
                      fill = as.factor(live.cell.hmm.state.movement))) +
  theme_classic() +
  # scale_fill_brewer(palette = "Accent") +
  scale_fill_manual(values = wesanderson::wes_palette(name = "Darjeeling2")) +
  theme_classic() +
  geom_bar(stat = "identity", width = 1, color = "black", size = 0.4) +
  theme(
    # legend.position = "none",
    legend.position = "right",
    legend.key.size = unit(6, "mm"),
    legend.title = element_blank(),
    legend.text = element_text(size = 16),
    axis.title.y = element_text(size = 16),
    axis.title.x = element_text(size = 16),
    axis.text.y = element_text(size = 16),
    axis.text.x = element_text(size = 16),
    # axis.text.x = element_text(size = 12, angle = 45, hjust = 1, vjust = 1),
    strip.background = element_blank(),
    # strip.text.x = element_blank()
    strip.text.x = element_text(size = 16)
    ) +
  scale_y_continuous(breaks = c(0, 0.5, 1)) +
  # scale_fill_discrete(name = "HMM State") +
  # xlab("Clusters") + ylab("HMM proportion") +
  xlab("") + ylab("HMM proportion") +
  coord_flip()

ggsave(file.path(anaDir, "clusters_hmm_heat.pdf"), width = 3.8, height = 1.5)
```

```{r fig_clusters_heat, fig.height=3, fig.width=8}
# get frequencies of HMM for each cluster
# and plot as bar graphs
datToPlot <- popDTs %>%
  mutate(
    live.cell.track.clusters.hmm_transitions_movement = as.numeric(as.character(
      live.cell.track.clusters.hmm_transitions_movement)),
    live.cell.hmm.transitions.movement = as.character(
      live.cell.hmm.transitions.movement)
    ) %>%
  drop_na(live.cell.track.clusters.hmm_transitions_movement) %>%
  dplyr::filter(live.cell.hmm.transitions.movement != "NA") %>%
  # group_by(live.cell.track.clusters.hmm_transitions_movement, from, to) %>%
  # dplyr::filter(!live.cell.hmm.transitions.movement %in% paste0(seq(4), "_", seq(4))) %>%
  group_by(live.cell.track.clusters.hmm_transitions_movement, live.cell.hmm.transitions.movement) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n) * 1) %>%
  separate_wider_delim(
    live.cell.hmm.transitions.movement, delim = "_", names = c("from", "to"))
  # ungroup() %>%
  # complete(live.cell.track.clusters.hmm_transitions_movement, from, to, fill = list(freq = 0))

ggplot(datToPlot, aes(as.factor(from), as.factor(to), size = freq * 2, fill = freq)) +
  theme_classic() +
  # scale_fill_brewer(palette = "Accent") +
  # scale_y_continuous(breaks = c(0, 0.5, 1)) +
  geom_vline(xintercept = as.factor(1:4), color = "#d3d3d3") +
  geom_hline(yintercept = as.factor(1:4), color = "#d3d3d3") +
  geom_point(pch = 21, color = "black") +
  # viridis::scale_fill_viridis() +
  scale_fill_gradient2(
    midpoint = 0.5, low="blue", mid="white", high="red", space ="Lab") +
  theme(
    legend.position = "none",
    # legend.position = "right",
    legend.key.size = unit(6, "mm"),
    legend.title = element_blank(),
    legend.text = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    axis.text.x = element_text(size = 12),
    # axis.text.x = element_text(size = 12, angle = 45, hjust = 1, vjust = 1),
    strip.background = element_blank(),
    # strip.text.x = element_blank()
    strip.text.x = element_text(size = 12)
    ) +
  # scale_fill_discrete(name = "HMM State") +
  xlab("From state") + ylab("To state") +
  facet_wrap(.~live.cell.track.clusters.hmm_transitions_movement, nrow = 2)

ggsave(file.path(anaDir, "clusters_transitions_heat.pdf"), width = 4, height = 3)
```

```{r}
# get frequencies of HMM for each cluster
# and plot as bar graphs
datToPlot <- popDTs %>%
  mutate(live.cell.track.clusters.hmm_movement = as.numeric(as.character(
    live.cell.track.clusters.hmm_movement))) %>%
  dplyr::filter(!live.cell.hmm.state.movement %in% c(5)) %>%
  drop_na(live.cell.track.clusters.hmm_movement) %>%
  drop_na(live.cell.hmm.state.movement) %>%
  group_by(live.cell.track.clusters.hmm_movement, live.cell.hmm.state.movement) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n) * 100) %>%
  ungroup() %>%
  complete(live.cell.track.clusters.hmm_movement, live.cell.hmm.state.movement, fill = list(freq = 0))

datToPlot$clusters <- case_match(
  as.character(datToPlot$live.cell.track.clusters.hmm_movement),
  c("4") ~ "1",
  c("2") ~ "2",
  c("0") ~ "3",
  c("1") ~ "4",
  c("3") ~ "5",
)

data.table::fwrite(datToPlot %>% 
            drop_na(clusters) %>%
            arrange(clusters),
          file = file.path(anaDir, "freq_hmm.csv"))
```

```{r fig_total_transitions, fig.height=1, fig.width=5}
library(ggplot2)
library(ggraph)

freqThr <- 0.00

pList <- list()

stateOrder <- list(
  "D" = "1",
  "M" = "3",
  "S" = "2",
  "C" = "4"
)

summaryDF <- popDTs %>%
  left_join(exp.info)

summaryDF$cell_type <- str_extract(summaryDF$pop, "(?<=\\.)[:alnum:]+(?=/)")
summaryDF$stain <- str_extract(
  summaryDF$staining, sprintf("%s-[:alnum:]+", summaryDF$cell_type)
  )
summaryDF$stain[is.na(summaryDF$stain)] <- "gBT-CTV"

summaryDF$clusters.name <- "NONE"


# for (x in unique(summaryDF$live.cell.track.clusters.hmm_movement)) {
for (x in unique(summaryDF$live.cell.track.clusters.hmm_transitions_movement)) {
# for (x in unique(summaryDF$live.cell.track.clusters.hmm_transitions_movement_shape)) {
# for (x in unique(summaryDF$clusters.name)) {
  # plot heatmap of transitions
  DF <- summaryDF %>%
    # dplyr::filter(live.cell.track.clusters.hmm_movement == x) %>%
    dplyr::filter(live.cell.track.clusters.hmm_transitions_movement == x) %>%
    # dplyr::filter(live.cell.track.clusters.hmm_transitions_movement_shape == x) %>%
    # dplyr::filter(clusters.name == x) %>%
    group_by(live.cell.hmm.transitions.movement) %>%
    summarise(n = n()) %>%
    separate(live.cell.hmm.transitions.movement,
             into = c("from", "to"),
             sep = "_", convert = TRUE) %>%
    mutate(across(c(from, to), as.character)) %>%
    replace_na(list(from = "0"))
  
  # edges for non-self transitions
  edges <- DF %>%
    dplyr::filter(from != to) %>%
    mutate(freq = n/sum(n)) %>%
    ungroup() %>%
    complete(from, to, fill = list(freq = 0)) %>%
    # drop_na() %>%
    # dplyr::filter(freq > freqThr) %>%
    mutate(non.self = (freq - min(freq)) / (max(freq) - min(freq))) %>%
    arrange(freq)
  
  # get number of self transitions
  nodes <- DF %>%
    dplyr::filter(from == to) %>%
    mutate(freq = n/sum(n)) %>%
    complete(from = unlist(stateOrder), fill = list(freq = 0)) %>%
    replace_na(list(to = "0")) %>%
    select(from, freq) %>%
    dplyr::rename(node = from) %>%
    add_row(node = "0", freq = 0) %>%
    mutate(nodeName = node) %>%
    dplyr::filter(node %in% unique(c(edges$from, edges$to))) %>%
    mutate(self = (freq - min(freq)) / (max(freq) - min(freq)))
  
  # add names for nodes
  for (i in names(stateOrder)) {
    nodes[nodes$nodeName == stateOrder[[i]], ]$nodeName <- i
  }
  
  # add state order
  counter <- 0
  nodes$order <- 0
  for (y in stateOrder) {
    nodes[nodes$node == y,]$order <- counter

    counter <- counter + 1
  }
  
  # https://www.hydrogenwaterusa.com/visualizing-large-directed-networks-with-ggraph-in-r/
  g <- igraph::graph_from_data_frame(d = edges,
                                     vertices = nodes %>% arrange(order),
                                     directed = TRUE)
  
  # pList[[x]] <- ggraph(g, layout = "auto") +
  # pList[[x]] <- ggraph(g, layout = "igraph", algorithm = "circle") +
  # pList[[x]] <- ggraph(g, layout = "linear") +
  ggraph(g, layout = "igraph", algorithm = "grid") +
  # ggraph(g, layout = "matrix") +
  # ggraph(g, layout = "auto") +
  # ggraph(g, layout = "linear") +
    # ggtitle(sprintf("%s", x)) +
    geom_edge_fan2(aes(width = non.self, color = non.self),
                   arrow = arrow(length = unit(3, 'mm'), type = "closed"),
                   end_cap = circle(5, 'mm')) +
    scale_edge_width(range = c(1, 2)) +
    scale_edge_color_gradient2(
      # low = "#D1D1D1",
      low = "#dadada",
      high = "black",
      mid = "#616161",
      midpoint = .5
    ) +
    geom_node_label(aes(label = nodeName, fill = self),
                    color = "white", repel = FALSE, size = 5,
                    label.padding = unit(0.1, "lines")) +
    scale_fill_gradient2(
      # low = "blue",
      low = "#009fe3",
      mid = "black",
      # high = "red",
      high = "#e71d73",
      midpoint = .5
    ) +
    theme_graph(
      plot_margin = margin(0,0,0,0),
      border = TRUE,
      background = NA
    ) +
    theme(
      legend.position = "none",
      plot.title = element_text(size = 6, family = "Arial"),
      plot.margin = unit(c(3,3,3,3), 'mm'), 
    )

  ggsave(file = file.path(anaDir, "networks", paste0("network_", x, ".pdf")),
         width = 2.2, height = 2.2, dpi = 400, bg = "transparent")
}

# ggpubr::ggarrange(plotlist = pList, nrow = 1)

# https://stackoverflow.com/a/17075381
# ggsave(file = file.path(anaDir, "total_networks.tiff"),
# ggsave(file = file.path(anaDir, "total_networks_GCAMP.tiff"),
  # width = 7, height = 2)
  # width = 20, height = 3.5)
  # width = 25, height = 2)
```

```{r fig_clusters_freq, fig.height=4, fig.width=15}
# save frequencies of track clusters
summaryDF <- copy(tcells.sc)

summaryDF <- .mapClustNames(summaryDF, clusterMapping, "clusters")

# show frequency of clusters
# summaryDF <- summaryDF[, .(n.clusters = .N), by = .(uID, pop, clusters)] %>%
summaryDF <- summaryDF[, .(n.clusters = .N), by = .(uID, pop, clusters.name)] %>%
# summaryDF <- summaryDF[clusters != , .(n.clusters = .N), by = .(uID, pop, clusters)] %>%
# summaryDF <- summaryDF[, .(n.clusters = .N), by = .(uID, pop, clusters.name)] %>%
  droplevels() %>%
  group_by(uID, pop) %>%
  mutate(freq.clusters = n.clusters/sum(n.clusters) * 100) %>%
  ungroup() %>%
  # complete(uID, pop, clusters, fill = list(freq.clusters = 0)) %>%
  complete(uID, pop, clusters.name, fill = list(freq.clusters = 0)) %>%
  left_join(exp.info)

# ggplot(summaryDF, aes(clusters, freq.clusters, color = interaction(Genotype))) +
ggplot(summaryDF, aes(clusters.name, freq.clusters, color = interaction(Genotype))) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
  scale_color_brewer(name = "Treatment", palette = "Set1") +
  facet_grid(.~pop)

# ggsave(file.path(anaDir, "clusters_freq.pdf"), width = 10, height = 3)

summaryDF$Genotype.ID <- 0
summaryDF[summaryDF$Genotype != "B6",]$Genotype.ID <- 1

summaryDF$pop.ID <- 0
summaryDF[summaryDF$pop != "gBT/tracked",]$pop.ID <- 1

summaryDF$cell.id <- 0
summaryDF[summaryDF$clusters.name == "Meandering",]$cell.id <- 1
summaryDF[summaryDF$clusters.name == "Scanning",]$cell.id <- 2

# data.table::fwrite(summaryDF %>% drop_na(clusters) %>%
data.table::fwrite(summaryDF %>% drop_na(clusters.name) %>%
            dplyr::filter(Genotype.ID == 0),
          file = file.path(anaDir, "freq_clusters_B6.csv"))
          # file = file.path(anaDir, "freq_clusters_B6_wo_clusters.csv"))
# data.table::fwrite(summaryDF %>% drop_na(clusters) %>%
data.table::fwrite(summaryDF %>% drop_na(clusters.name) %>%
            dplyr::filter(Genotype.ID == 1),
          file = file.path(anaDir, "freq_clusters_H2Kb.csv"))
          # file = file.path(anaDir, "freq_clusters_H2Kb_wo_clusters.csv"))
```

```{r fig_hmm_props, fig.height=3, fig.width=3}
# show measurements of clusters to compare
colsToPlot <- rev(c(
  "angle",
  "speed",
  "compactness",
  "extent",
  "oblate",
  "prolate",
  "solidity",
  "sphericity",
  "surface_area",
  "volume"
))

# convert angle to degrees
popDTs[, live.cell.angle_deg := pracma::rad2deg(live.cell.angle)]

propsToPlot <- popDTs[exp.info, on = "uID"] %>%
  dplyr::rename(
    "speed" = "live.cell.speed",
    "angle" = "live.cell.angle_deg",
    "oblate" = "ellipticity_interm_oblate",
    "prolate" = "ellipticity_interm_prolate"
  ) %>%
  # drop_na(live.cell.hmm.state.hybrid_pop) %>%
  pivot_longer(
    cols = colsToPlot, names_to = "prop", values_to = "value"
    ) %>%
  pivot_longer(
    cols = c(
      "live.cell.hmm.state.movement"
      # "live.cell.hmm.state.shape"
    ), names_to = "hmm_type", values_to = "hmm_value"
    )

propsToPlot$prop <- factor(propsToPlot$prop, levels = colsToPlot)

# show heatmap for HMM
propsSummary <- propsToPlot %>%
  dplyr::filter(!is.na(hmm_value)) %>%
  group_by(hmm_type, hmm_value, prop) %>%
  replace_na(list(value = 0)) %>%
  summarise(mean = mean(value)) %>%
  group_by(hmm_type, prop) %>%
  mutate(freq = (mean - min(mean)) / (max(mean) - min(mean))) %>%
  arrange(-prop)

propsSummary$hmm_value <- as.character(propsSummary$hmm_value)
propsSummary[propsSummary$hmm_value == "2", ]$hmm_value <- "Arrested"
propsSummary[propsSummary$hmm_value == "1", ]$hmm_value <- "Directed"
propsSummary[propsSummary$hmm_value == "4", ]$hmm_value <- "Scanning"
propsSummary[propsSummary$hmm_value == "3", ]$hmm_value <- "Meandering"
propsSummary[propsSummary$hmm_value == "5", ]$hmm_value <- "Clustering"
propsSummary$hmm_value <- factor(propsSummary$hmm_value, levels = c(
  "Directed", "Meandering", "Scanning", "Arrested", "Clustering"
))

ggplot(propsSummary %>% dplyr::filter(hmm_value != "Clustering"), aes(as.factor(hmm_value), prop)) +
  theme_classic() +
  geom_tile(aes(fill = freq), colour = "white", size = 0.5) +
  viridis::scale_fill_viridis(
    breaks = c(0, 1),
    labels = c(0, 1)
  ) +
  theme(
    legend.position = "none",
    legend.title = element_blank(),
    legend.text = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    # axis.text.x = element_text(size = 12),
    strip.background = element_blank(),
    strip.text.x = element_blank(),
    axis.text.x = element_text(size = 12, angle = 45, hjust = 1, vjust = 1)
    ) +
  xlab("") + ylab("") +
  facet_grid(.~hmm_type)

ggsave(file.path(anaDir, "HMM_heat.pdf"), width = 2.3, height = 3)
```

```{r fig_hmm_freq, fig.height=2, fig.width=3}
# save frequencies of HMM
datToPlot <- popDTs %>%
  drop_na(live.cell.hmm.state.movement) %>%
  group_by(uID, pop, live.cell.hmm.state.movement) %>%
  summarise(n.hmm = n()) %>%
  mutate(freq.hmm = n.hmm/sum(n.hmm) * 100) %>%
  left_join(exp.info)

# plot
ggplot(datToPlot,
       aes(
         as.factor(live.cell.hmm.state.movement), freq.hmm,
         fill = pop
         )) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    # width = 0.3, alpha = 0.6) +
  # stat_summary(fun=mean, geom="point", size=3, shape=18, color="Magenta") +
  ylab("Frequency state") + xlab("") +
  ylim(0, 100) +
  scale_fill_brewer(name = NULL, palette = "Set3") +
  facet_grid(.~Genotype)

ggsave(file.path(anaDir, "HMM_freq.pdf"), width = 5, height = 2)

datToPlot$Genotype.ID <- 1
datToPlot[datToPlot$Genotype == "H2-Kb", ]$Genotype.ID <- 2

data.table::fwrite(datToPlot, file.path(anaDir, "HMM_freq.csv"))
```
