---
title: "Behaviour GCAMP"
output: html_document
date: '2022-08-15'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Show transition states of live cell imaging

```{r}
Sys.setenv(KMP_DUPLICATE_LIB_OK = "TRUE")
devtools::load_all("../")
cciaUse("~/cecelia/dev")

library(ggplot2)
library(tidyverse)
```

```{r}
# set test variables
pID <- "8BR53W"
versionID <- 1
projectsDir <- "/Volumes/USER_data/Dominik/CECELIA_BACKUP/"
hpcDir <- "/data/scratch/projects/punim1124/cecelia/USER_data/schienstockd/"
```

```{r}
anaDir <- "/Volumes/USER_data/Dominik/Experiments/JL-ANALYSIS/RESULTS/XCR1-Venus/all_types_re"
```

```{r}
# load Cecelia tracking measures
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "pPlT5i", versionID = versionID, initReactivity = FALSE # XCR1-venus
)

a <- cciaObj$imPopMap("live", includeFiltered = TRUE)
```

### Comparison to IMARIS

```{r}
# load Cecelia tracking measures
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "ikPuIK", versionID = versionID, initReactivity = FALSE # XCR1-venus
)

pops <- c("tcells.gBT", "tcells.gDT", "dcs.all")

tracksMeasures <- cciaObj$tracksMeasures(pops)
```

```{r}
# load Imaris tracking measures
# get cell types
imsDir <- "/Volumes/USER_data/Dominik/Experiments/JL-ANALYSIS/RESULTS/XCR1-Venus/all_types_re/COMPARE/M3-2b 53-5h XCR1-venus TRITC gDT-CTV gBT-CTDR 175-225/"
imsTypes <- c("gBT", "gDT", "TRITC", "XCR1")

imsMeasures <- lapply(imsTypes, function(x) {
  read.csv(file.path(imsDir, paste0(x, "_Statistics"), paste0(x, "_Track_Speed_Mean_Reference_Frame.csv")), skip = 3)
})
names(imsMeasures) <- c("tcells.gBT", "tcells.gDT", "dcs.all", "dcs.all")

# combine
imsMeasuresDT <- data.table::rbindlist(imsMeasures, idcol = "cell_type")
setnames(imsMeasuresDT, "Track.Speed.Mean.Reference.Frame", "speed")

# adjust Imaris speed which is um/s to um/min
imsMeasuresDT[, speed := speed * 60]
```

```{r fig_ims_v_ccia, fig.height=4, fig.width=4}
# compare
vMeasures <- rbindlist(list(
  Cecelia = tracksMeasures[, c("cell_type", "speed")],
  Imaris = imsMeasuresDT[, c("cell_type", "speed")]),
  idcol = "source")

ggplot(vMeasures, aes(cell_type, speed, color = source)) +
# ggplot(imsMeasuresDT, aes(cell_type, Speed * 100)) +
  theme_classic() +
  geom_jitter(
    position = position_jitterdodge(jitter.width = 0.10),
    # width = 0.2,
    ) +
  geom_boxplot(outlier.alpha = 0) 
  # scale_color_brewer(name = "Treatment", palette = "Set3") 
  # facet_grid(.~pop)

data.table::fwrite(vMeasures, file.path(anaDir, "vMeasures.csv"))
```


### END

```{r}
# HMM
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "CDL3KW", versionID = versionID, initReactivity = FALSE # XCR1-venus
)

cciaObj$omeXMLTimelapseInfo()
```

```{r}
# HMM
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "lMxxOE", versionID = versionID, initReactivity = FALSE # XCR1-venus
)

omexml <- cciaObj$omeXMLTimelapseInfo()
```

```{r}
omexml

# get time delta
valueChildren <- xml2::xml_children(xml2::xml_find_all(
  omexml, cciaObj$omeXMLPath("//Image//Pixels")))

timeDelta <- valueChildren[!is.na(
  stringr::str_match(as.character(valueChildren), "TheZ=\"0\" TheT=\"1\""))]

timeValue <- as.numeric(stringr::str_extract(
  as.character(timeDelta[[1]]), "(?<=DeltaT=\")[0-9]+\\.[0-9]+"))
timeUnit <- stringr::str_extract(
  as.character(timeDelta[[1]]), "(?<=DeltaTUnit=\")[a-z]+")

# convert to time interval
if (timeUnit == "ms")
  timeValue <- timeValue / 1000 / 60
```


```{r}
# HMM
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "lMxxOE", versionID = versionID, initReactivity = FALSE # XCR1-venus
)

cciaObj$setImChannelNames(c("gBT-CTDR", "TRITC", "XCR1-Venus", "gDT-CTV"))
cciaObj$saveState()
```

```{r}
# HMM
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "0Oenks", versionID = versionID, initReactivity = FALSE # XCR1-venus
)

for (x in cciaObj$cciaObjects()) {
  print(paste(x$getUID(), x$oriFilepath()))
}
```


```{r}
# HMM
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "0Oenks", versionID = versionID, initReactivity = FALSE # XCR1-venus
)

# GCAMP
uIDs <- names(cciaObj$cciaObjects())

# run task
funParams <- list(
  popType = "live",
  pops = c("tcells.gBT/tracked", "tcells.gDT/tracked", "dcs.all/tracked"),
  modelMeasurements = c("live.cell.speed", "live.cell.angle"),
  scaleMeasurements = c("live.cell.speed", "live.cell.angle"),
  # modelMeasurements = c(
  #   "surface_area", "volume", "extent", "solidity",
  #   "ellipticity_interm_oblate", "ellipticity_interm_prolate",
  #   "compactness", "sphericity"
  # ),
  colName = "movement",
  # colName = "shape",
  appendStates = list(live.cell.is.clust = TRUE),
  # appendStates = list(),
  # appendStates = list(),
  skipTimesteps = 0,
  subtrackOverlap = TRUE,
  noiseFilterMeasurements = 5,
  postFiltering = 2,
  postIterations = 2,
  numStates = 3, # movement with injection
  # numStates = 4, # movement
  # numStates = 4, # shape
  uIDs = uIDs
)

# run task
task <- cciaObj$runTask(
  funName = "behaviourAnalysis.hmmStates",
  funParams = funParams,
  env = "local",
  runInplace = TRUE,
  taskID = 1
)
```

```{r}
# get HMM transitions
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "0Oenks", versionID = versionID, initReactivity = FALSE # XCR1-venus
)

# GCAMP
uIDs <- names(cciaObj$cciaObjects())

# run task
funParams <- list(
  popType = "live",
  pops = c("tcells.gBT/tracked", "tcells.gDT/tracked", "dcs.all/tracked"),
  colName = "movement",
  hmmStates = c("movement"),
  # colName = "shape",
  # hmmStates = c("shape"),
  includeStart = FALSE,
  includeSelfTransitions = TRUE,
  uIDs = uIDs
)

# run task
task <- cciaObj$runTask(
  funName = "behaviourAnalysis.hmmTransitions",
  funParams = funParams,
  env = "local",
  runInplace = TRUE,
  taskID = 1
)
```

```{r}
# cluster tracks based on transitions
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "0Oenks", versionID = versionID, initReactivity = FALSE # XCR1-venus
)

# GCAMP
uIDs <- names(cciaObj$cciaObjects())

# run task
funParams <- list(
  popType = "live",
  popsToCluster = c("tcells.gBT/tracked", "tcells.gDT/tracked", "dcs.all/tracked"),
  valueName = "tracks.clusters.tcells.hmm_transitions",
  clusterColName = "hmm_transitions",
  # valueName = "tracks.clusters.tcells.hmm_transitions_alt",
  # clusterColName = "hmm_transitions_alt",
  # valueName = "tracks.clusters.tcells.hmm_transitions_hi",
  # clusterColName = "hmm_transitions_hi",
  resolution = 0.30,
  # resolution = 0.25,
  percentile = 99.8,
  trackMeasures = c(
    "speed",
    "duration",
    "trackLength",
    "meanTurningAngle",
    "displacement",
    "straightness",
    "displacementRatio",
    "outreachRatio",
    "asphericity",
    "overallAngle"
  ),
  objectMeasures = c(
    # "surface_area",
    # "volume",
    # "extent",
    # "solidity",
    # "ellipticity_interm_oblate",
    # "ellipticity_interm_prolate",
    # "compactness",
    # "sphericity",
    # HMM states
    "live.cell.hmm.state.movement",
    "live.cell.hmm.state.shape",
    "live.cell.hmm.transitions.movement"
    # "live.cell.hmm.transitions.shape"
    ),
  nMeasures = c(
    ),
  sumMeasures = c(
    ),
  calcMeasures = list(
  ),
  addPops = c(
    ),
  calcLabelProps = TRUE,
  # usePaga = FALSE,
  usePaga = TRUE,
  pagaThreshold = 0.1,
  minTracklength = 6,
  # minTracklength = 50,
  uIDs = uIDs
)

# run task
task <- cciaObj$runTask(
  funName = "behaviourAnalysis.clusterTracks",
  funParams = funParams,
  env = "local",
  runInplace = TRUE,
  taskID = 1
)
```

```{r}
# get populations and show maps
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "0Oenks", versionID = versionID, initReactivity = FALSE
)

exp.info <- as.data.table(cciaObj$summary(withSelf = FALSE, fields = c("Attr")))
uIDs <- exp.info$uID

# show experiments with folder info
for (x in cciaObj$cciaObjects(uIDs = uIDs)) {
  print(paste(x$getUID(), x$oriFilepath()))
}
```


```{r}
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "0Oenks", versionID = versionID, initReactivity = FALSE # XCR1-venus
)

# cciaObj$imAnndataFilepath("clust")
clustPath <- "tracks.clusters.tcells.hmm_transitions.sc.h5ad"
attr(clustPath, "savedIn") <- cciaObj$getUID()
        
for (x in cciaObj$cciaObjects()) {
  x$setImAnndataFilepath(
    clustPath, valueName = "tracks.clusters.tcells.hmm_transitions")
  
  x$saveState()
}
```

```{r}
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "0Oenks", versionID = versionID, initReactivity = FALSE # XCR1-venus
)

# GCAMP
# uIDs <- names(cciaObj$cciaObjects())
uIDs <- names(cciaObj$cciaObjects())[1]

# get experimental info
exp.info <- cciaObj$summary(
  withSelf = FALSE, fields = c("Attr")
)

# get clustering
types.sc <- as.data.table(cciaEnv()$LabelPropsUtils(
  # cciaObj$persistentObjectDirectory(),
  # value_name = "tracks.clusters.types.all.sc")$label_props_view()$as_df())
  cciaObj$persistentObjectDirectory(),
  value_name = "tracks.clusters.tcells.hmm_transitions.sc")$label_props_view()$as_df())
  # value_name = "tracks.clusters.tcells.hmm_transitions_alt.sc")$label_props_view()$as_df())

# # get clustering
# types.tests.sc <- sapply(
#   c("all", "wo_tracks", "wo_hmm", "wo_shape", "wo_movement"), function(x) {
#     as.data.table(cciaEnv()$LabelPropsUtils(
#       cciaObj$persistentObjectDirectory(),
#       value_name = paste0("tracks.clusters.types.", x,".sc"))$label_props_view()$as_df())
#   }
# )

# get popDTs for set
popDTs <- cciaObj$popDT(
  popType = "live", pops = c(
    "tcells.gBT/tracked",
    "tcells.gDT/tracked",
    "dcs.all/tracked"
    ),
  includeFiltered = TRUE,
  flushCache = TRUE,
  uIDs = uIDs)
```

```{r}
paramsToGet <- c(
  "solidity", "live.cell.speed", "volume")

tracksInfo <- rbindlist(list(
  gBT = cciaObj$tracksInfo(paramsToGet, parentPop = "tcells.gBT/tracked", uIDs = uIDs),
  gDT = cciaObj$tracksInfo(paramsToGet, parentPop = "tcells.gDT/tracked", uIDs = uIDs),
  DCs = cciaObj$tracksInfo(paramsToGet, parentPop = "dcs.all/tracked", uIDs = uIDs)
), idcol = "pop")
```


```{r}
# plot speed and percentage of clustering cells
summaryDF <- tracksInfo %>%
  group_by(uID, pop) %>%
  summarise(
    mean.speed = mean(live.cell.speed.mean, na.rm = TRUE),
    mean.solidity = mean(solidity.mean, na.rm = TRUE),
    mean.volume = mean(volume.mean, na.rm = TRUE)
    ) %>%
  left_join(exp.info)

summaryDF$cell_ID <- 0
summaryDF[summaryDF$pop == "gBT",]$cell_ID <- 0
summaryDF[summaryDF$pop == "gDT",]$cell_ID <- 1
summaryDF[summaryDF$pop == "DCs",]$cell_ID <- 2

data.table::fwrite(summaryDF, file = file.path(anaDir, "mean_speed.csv"))
```


```{r fig_hmm_props, fig.height=3, fig.width=3}
# show measurements of clusters to compare
colsToPlot <- rev(c(
  "angle",
  "speed",
  "compactness",
  "extent",
  "oblate",
  "prolate",
  "solidity",
  "sphericity",
  "surface_area",
  "volume"
))

# convert angle to degrees
popDTs[, live.cell.angle_deg := pracma::rad2deg(live.cell.angle)]

propsToPlot <- popDTs[exp.info, on = "uID"] %>%
  dplyr::rename(
    "speed" = "live.cell.speed",
    "angle" = "live.cell.angle_deg",
    "oblate" = "ellipticity_interm_oblate",
    "prolate" = "ellipticity_interm_prolate"
  ) %>%
  # drop_na(live.cell.hmm.state.hybrid_pop) %>%
  pivot_longer(
    cols = colsToPlot, names_to = "prop", values_to = "value"
    ) %>%
  pivot_longer(
    cols = c(
      "live.cell.hmm.state.movement",
      "live.cell.hmm.state.shape"
    ), names_to = "hmm_type", values_to = "hmm_value"
    )

propsToPlot$prop <- factor(propsToPlot$prop, levels = colsToPlot)

# show heatmap for HMM
propsSummary <- propsToPlot %>%
  dplyr::filter(!is.na(hmm_value)) %>%
  group_by(hmm_type, hmm_value, prop) %>%
  replace_na(list(value = 0)) %>%
  summarise(mean = mean(value)) %>%
  group_by(hmm_type, prop) %>%
  mutate(freq = (mean - min(mean)) / (max(mean) - min(mean))) %>%
  arrange(-prop)

ggplot(propsSummary %>% dplyr::filter(hmm_value != "Clustering"), aes(as.factor(hmm_value), prop)) +
  theme_classic() +
  geom_tile(aes(fill = freq), colour = "white", size = 0.5) +
  viridis::scale_fill_viridis(
    breaks = c(0, 1),
    labels = c(0, 1)
  ) +
  theme(
    legend.position = "none",
    legend.title = element_blank(),
    legend.text = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    axis.text.x = element_text(size = 12),
    strip.background = element_blank(),
    strip.text.x = element_blank(),
    # axis.text.x = element_text(size = 12, angle = 45, hjust = 1, vjust = 1)
    ) +
  xlab("") + ylab("") +
  facet_grid(.~hmm_type)

ggsave(file.path(anaDir, "HMM_heat.pdf"), width = 3.5, height = 3)
```

```{r fig_umap, fig.height=4, fig.width=4}
dfToPlot <- copy(types.sc) %>% drop_na(clusters) %>% left_join(exp.info)

clusterMapping <- list(
  Aggregating = c(5),
  Directed = c(2,7),
  `Meandering oblate` = c(1,6),
  `Meandering prolate` = c(4),
  Scanning = c(0,3)
)

dfToPlot <- .mapClustNames(dfToPlot, clusterMapping, "clusters")

# get mean positions of clusters
meanClusterPos <- dfToPlot %>%
  # group_by(clusters) %>%
  group_by(clusters.name) %>%
  summarise(
    UMAP_1 = mean(UMAP_1),
    UMAP_2 = mean(UMAP_2)
  )
dfToPlot$clusters <- factor(dfToPlot$clusters)

# colPal <- randomcoloR::distinctColorPalette(length(unique(dfToPlot$clusters.name)))
# colPal <- randomcoloR::distinctColorPalette(length(unique(dfToPlot$clusters)))
colPal <- c(
  # Scanning = "#E42328",
  # `Meandering prolate` = "#327EBA",
  # `Meandering oblate` = "#974D9E",
  # Directed = "#4CAF48",
  # Clustering = "#ffff00"
  Scanning = "#327EBA",
  `Meandering prolate` = "#1B9E77",
  `Meandering oblate` = "#B3BCC2",
  Directed = "#AA1F5E",
  Aggregating = "#FFFF00"
)

# plot UMAP
ggplot(
  dfToPlot,
  aes(UMAP_1, UMAP_2)
  ) +
  # geom_point(aes(color = clusters)) +
  geom_point(aes(color = clusters.name)) +
  theme_classic() +
  # scale_color_brewer(name = NULL, palette = "Set1") +
  # scale_color_brewer(name = NULL, palette = "Dark2") +
  scale_color_manual(values = colPal) +
  theme(
    axis.text = element_text(size = 15),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    legend.justification = "right",
    # legend.position = "bottom"
    legend.position = "none",
    axis.line = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
    ) +
  geom_label(
    data = meanClusterPos,
    # aes(label = clusters),
    aes(label = clusters.name),
    label.size = 0.25,
    color = "black"
    )

ggsave(file.path(anaDir, "umap.png"), width = 4, height = 4)
# ggsave(file.path(anaDir, "umap_wo_labels.png"), width = 2, height = 2)
# ggsave(file.path(anaDir, "umap_movement_wo_labels.tiff"), width = 2, height = 2)
# ggsave(file.path(anaDir, "umap_hmm_movement_wo_labels.tiff"), width = 2, height = 2)
# ggsave(file.path(anaDir, "umap_hmm_movement_shape_wo_labels.tiff"), width = 2, height = 2)
```


```{r fig_umap_props, fig.height=4, fig.width=4}
datToPlot <- copy(types.sc) %>%
  drop_na(clusters) %>%
  left_join(exp.info) 

channels <- c("speed", "meanTurningAngle",
              paste0("live.cell.hmm.state.movement.", seq(1,4)),
              paste0("live.cell.hmm.state.shape.", seq(1,4)))

for (i in channels) {
  # plot UMAP
  p1 <- ggplot(datToPlot, aes(UMAP_1, UMAP_2)) +
    theme_classic() +
    geom_point(aes(color = get(i)), size = 0.5, alpha = 1) +
    viridis::scale_color_viridis() +
    theme(
      axis.text = element_text(size = 15),
      axis.text.x = element_blank(),
      axis.ticks.x = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank(),
      legend.justification = "right",
      # legend.position = "bottom"
      legend.position = "none",
      axis.line = element_blank(),
      axis.title.x = element_blank(),
      axis.title.y = element_blank()
      )
  
  print(p1)
  ggsave(file.path(anaDir, paste0("umap_", i ,".tiff")), width = 2, height = 2)
}
```

```{r fig_umap, fig.height=4, fig.width=4}
plot.p1 <- function(df.all, df.subsets) {
  p1 <- ggplot(df.all, aes(UMAP_1, UMAP_2)) +
    theme_classic() +
    geom_point(color = "black", size = 1) +
    theme(
      axis.text = element_text(size = 15),
      axis.text.x = element_blank(),
      axis.ticks.x = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank(),
      legend.justification = "right",
      # legend.position = "bottom"
      legend.position = "none",
      axis.line = element_blank(),
      axis.title.x = element_blank(),
      axis.title.y = element_blank()
      )
  
  # add points
  for (i in seq(length(df.subsets))) {
    x <- df.subsets[[i]]$data
    colramp <- df.subsets[[i]]$colramp
    
    p1 <- p1 + geom_point(
      data = x, size = 1, alpha = 1,
      # color = .flowColours(x$UMAP_1, x$UMAP_2, colramp = colramp))
      color = df.subsets[[i]]$colramp)
  }
  
  p1
}

datToPlot <- copy(types.sc) %>%
  drop_na(clusters) %>%
  left_join(exp.info)

# datToPlot <- .mapClustNames(datToPlot, clusterMapping, "clusters")

# plot UMAP
plot.p1(datToPlot, list(
  list(data = datToPlot %>% dplyr::filter(pop == "dcs.all/tracked"),
    colramp = "#B3BCC2"),
  list(data = datToPlot %>% dplyr::filter(pop == "tcells.gBT/tracked"),
    colramp = "#AA1F5E"),
  list(data = datToPlot %>% dplyr::filter(pop == "tcells.gDT/tracked"),
    colramp = "#4682b4")
))
# ggsave(file.path(anaDir, paste0("umap_HSV.png")), width = 2, height = 2)
ggsave(file.path(anaDir, paste0("umap_HSV_big.png")), width = 4, height = 4)
```

```{r fig_psuedotime, fig.height=3, fig.width=5}
# show proportion of freq of populations in clusters
# plotColors <- c("#707070", "#ffb804")

ggplot(
  dfToPlot %>%
    mutate(pop = factor(
      case_match(
        as.character(pop),
        c("tcells.gBT/tracked") ~ "gBT-I",
        c("tcells.gDT/tracked") ~ "gDT-II",
        c("dcs.all/tracked") ~ "Dendritic cells",
      ),levels = c("gBT-I", "gDT-II", "Dendritic cells"))) %>%
    # group_by(pop, clusters) %>%
    group_by(pop, clusters.name) %>%
    summarise(n = n()) %>%
    mutate(freq = n/sum(n),),
  # aes(x = 1, y = freq, fill = clusters)) +
  aes(x = 1, y = freq, fill = clusters.name)) +
  scale_fill_brewer(name = NULL, palette = "Set1") +
  theme_classic() +
  geom_bar(stat = "identity", width = 0.8) +
  # geom_col() +
  # coord_polar("y", start = 0) +
  # facet_wrap(.~pop, nrow = 1, ) +
  # xlim(0, 1.5) +
  theme(
    axis.text = element_text(size = 12),
    legend.key.size = unit(8, "mm"),
    legend.text = element_text(size = 12),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.title.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.title.y = element_blank(),
    legend.position = "bottom",
    # legend.position = "none",
    legend.title = element_blank(),
    axis.line = element_blank(),
    strip.background = element_blank(),
    strip.text.x = element_blank()
  ) + coord_flip() + facet_grid(.~pop) +
  scale_y_continuous(breaks = c(0, 0.5, 1)) +
  guides(fill = guide_legend(nrow = 1))

ggsave(file.path(anaDir, "pop_clusters_freq.tiff"), width = 5, height = 1.2)
```

```{r fig_psuedotime, fig.height=3, fig.width=5}
# show proportion of freq of populations in clusters
plotColors <- c("#AA1F5E", "#4682b4", "#B3BCC2")

dfToPlot$type <- "gBT-I"
dfToPlot[!is.na(str_match(dfToPlot$pop, "^tcells.gDT")[, 1]), type := "gDT-II"]
dfToPlot[!is.na(str_match(dfToPlot$pop, "^dcs")[, 1]), type := "Dendritic cells"]
dfToPlot$type <- factor(dfToPlot$type, levels = c("gBT-I", "gDT-II", "Dendritic cells"))

sumPlot <- dfToPlot %>%
  # group_by(clusters, type) %>%
  group_by(clusters.name, type) %>%
  summarise(n = n()) %>%
  mutate(freq = n/sum(n) * 100)

data.table::fwrite(sumPlot, file = file.path(anaDir, "freq_clusters.csv"))

ggplot(sumPlot,
  # aes(clusters, freq, fill = type)) +
  aes(clusters.name, freq, fill = type)) +
  scale_fill_manual(values = plotColors) +
  theme_classic() +
  geom_bar(stat = "identity", width = 0.9) +
  # geom_bar(stat = "identity", width = 1) +
  # coord_polar("y", start = 0) +
  # xlim(0, 1.8) +
  # facet_wrap(.~clusters, nrow = 1) +
  # facet_grid(clusters.name~.) +
  theme(
    axis.text = element_text(size = 10),
    axis.title = element_text(size = 10),
    # axis.text.x = element_blank(),
    # axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    # legend.position = "bottom",
    legend.position = "none",
    legend.title = element_blank(),
    # axis.line = element_blank(),
    axis.line.y = element_blank(),
    # axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    strip.background = element_blank(),
    strip.text.y = element_blank()
  ) +
  ylab("") +
  # ylab("Cell type (%)") +
  scale_y_continuous(breaks = c(0, 50, 100)) +
  coord_flip()

ggsave(file.path(anaDir, "cluster_pop_freq.tiff"), width = 1, height = 1.5)
```

```{r}
# show measurements of clusters to compare
propsToPlot <- copy(types.sc)

# propsToPlot <- propsToPlot %>%
#   dplyr::rename(
#     "Movement HMM 1" = "live.cell.hmm.state.movement.1",
#     "Movement HMM 2" = "live.cell.hmm.state.movement.2",
#     "Movement HMM 3" = "live.cell.hmm.state.movement.3",
#     "Movement HMM 4" = "live.cell.hmm.state.movement.4",
#   )

colsToPlot <- colnames(propsToPlot)[!colnames(propsToPlot) %in% c(
  "pop", "uID", "track_id", "clusters", "UMAP_1", "UMAP_2"
  )]

propsToPlot <- propsToPlot %>%
  pivot_longer(
    cols = colsToPlot, names_to = "prop", values_to = "value"
    )

propsToPlot$prop <- factor(propsToPlot$prop, levels = sort(colsToPlot, decreasing = TRUE))

# propsToPlot$clusters.name <- "NONE"
# propsToPlot[propsToPlot$clusters %in% c(2,3,6,7), ]$clusters.name <- "Directed"
# propsToPlot[propsToPlot$clusters %in% c(5), ]$clusters.name <- "Meandering"
# propsToPlot[propsToPlot$clusters %in% c(0,4), ]$clusters.name <- "Scanning"
# propsToPlot[propsToPlot$clusters %in% c(1), ]$clusters.name <- "Clustering"

# propsList <- c(
#   'Movement HMM 1',
#   'Movement HMM 2',
#   'Movement HMM 3',
#   'Movement HMM 4',
#   'asphericity',
#   'displacement',
#   'displacementRatio',
#   'duration',
#   'meanTurningAngle',
#   'outreachRatio',
#   'overallAngle',
#   'speed',
#   'straightness',
#   'trackLength'
# )

propsToPlot <- .mapClustNames(propsToPlot, clusterMapping, removeNone = FALSE)

# show heatmap for clusters
propsSummary <- propsToPlot %>%
  dplyr::filter(
    # clusters.name != "NONE",
    # prop %in% propsList
    ) %>%
  # group_by(clusters, prop) %>%
  group_by(clusters.name, prop) %>%
  summarise(mean = mean(value, rm.na = TRUE)) %>%
  group_by(prop) %>%
  # group_by(clusters) %>%
  mutate(freq = (mean - min(mean)) / (max(mean) - min(mean))) %>%
  arrange(-prop)
```


```{r fig_clusters_heat, fig.height=8, fig.width=6}
# propsSummary$prop <- factor(
#   propsSummary$prop, levels = rev(propsList))
# propsSummary$clusters.name <- factor(
#   propsSummary$clusters.name, levels = c(
#     "Directed", "Meandering", "Scanning", "Clustering"
#   ))

# # sort states
# propsSummary[!propsSummary$clusters %in% clusterOrder[clusterOrder != 1],]$clusters <- NA
# # propsSummary$clusters <- factor(propsSummary$clusters, levels = clusterOrder)
# propsSummary$clusters <- case_match(
#   as.character(propsSummary$clusters),
#   c("3") ~ "1",
#   c("6") ~ "2",
#   c("0") ~ "3",
#   c("7") ~ "4",
#   c("2") ~ "5",
#   c("5") ~ "6",
#   c("4") ~ "7",
# )

# ggplot(propsSummary, aes(as.factor(clusters.name), prop)) +
# ggplot(propsSummary, aes(as.factor(clusters), prop)) +
ggplot(propsSummary %>%
         dplyr::filter(!str_detect(prop, "live.cell")) %>%
         # dplyr::filter(!str_detect(prop, "\\.")) %>%
         # drop_na(clusters), aes(clusters, prop)) +
         drop_na(clusters.name), aes(clusters.name, prop)) +
  theme_classic() +
  geom_tile(aes(fill = freq), colour = "white", size = 0.5) +
  # geom_tile(aes(fill = mean), colour = "white", size = 0.5) +
  viridis::scale_fill_viridis(
    breaks = c(0, 1),
    labels = c(0, 1)
  ) +
  theme(
    legend.position = "none",
    legend.key.size = unit(8, "mm"),
    legend.title = element_blank(),
    legend.text = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    # axis.text.x = element_text(size = 12),
    axis.text.x = element_text(size = 12, angle = 45, hjust = 1, vjust = 1),
    strip.background = element_blank(),
    strip.text.x = element_blank()
    ) +
  xlab("") + ylab("")

ggsave(file.path(anaDir, "clusters_heat.pdf"), width = 3, height = 3.5)
# ggsave(file.path(anaDir, "clusters_heat.pdf"), width = 5, height = 6)
```

```{r fig_clusters_heat, fig.height=2, fig.width=6}
# get frequencies of HMM for each cluster
# and plot as bar graphs
datToPlot <- popDTs %>%
  # mutate(live.cell.track.clusters.hmm_transitions_alt = as.numeric(as.character(
  #   live.cell.track.clusters.hmm_transitions_alt))) %>%
  # drop_na(live.cell.track.clusters.hmm_transitions_alt) %>%
  mutate(live.cell.track.clusters.hmm_transitions = as.numeric(as.character(
    live.cell.track.clusters.hmm_transitions))) %>%
  drop_na(live.cell.track.clusters.hmm_transitions) %>%
  drop_na(live.cell.hmm.state.movement) %>%
  drop_na(live.cell.hmm.state.shape) %>%
  pivot_longer(
    cols = c("live.cell.hmm.state.movement", "live.cell.hmm.state.shape"),
    names_to = "hmm_type",
    values_to = "hmm_value"
  ) %>%
  # group_by(live.cell.track.clusters.hmm_transitions_alt, hmm_type, hmm_value) %>%
  group_by(live.cell.track.clusters.hmm_transitions, hmm_type, hmm_value) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n) * 1) %>%
  ungroup() %>%
  # complete(live.cell.track.clusters.hmm_transitions_alt, hmm_type, hmm_value, fill = list(freq = 0))
  complete(live.cell.track.clusters.hmm_transitions, hmm_type, hmm_value, fill = list(freq = 0))

data.table::fwrite(datToPlot, file = file.path(anaDir, "freq_hmm.csv"))

# ggplot(datToPlot, aes(as.factor(live.cell.track.clusters.hmm_transitions_alt), freq,
ggplot(datToPlot, aes(as.factor(live.cell.track.clusters.hmm_transitions), freq,
                      fill = as.factor(hmm_value))) +
  theme_classic() +
  # scale_fill_brewer(palette = "Accent") +
  scale_fill_manual(values = wesanderson::wes_palette(name = "Darjeeling2")) +
  theme_classic() +
  geom_bar(stat = "identity", width = 1, color = "black", size = 0.4) +
  theme(
    # legend.position = "none",
    legend.position = "right",
    legend.key.size = unit(6, "mm"),
    legend.title = element_blank(),
    legend.text = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    axis.text.x = element_text(size = 12),
    # axis.text.x = element_text(size = 12, angle = 45, hjust = 1, vjust = 1),
    strip.background = element_blank(),
    strip.text.x = element_blank()
    # strip.text.x = element_text(size = 12)
    ) +
  scale_y_continuous(breaks = c(0, 0.5, 1)) +
  # scale_fill_discrete(name = "HMM State") +
  xlab("") + ylab("") +
  facet_grid(.~hmm_type)

ggsave(file.path(anaDir, "clusters_hmm_heat.pdf"), width = 6, height = 1.8)
```

```{r fig_clusters_heat, fig.height=3, fig.width=8}
# get frequencies of HMM for each cluster
# and plot as bar graphs
datToPlot <- popDTs %>%
  mutate(
    live.cell.track.clusters.hmm_transitions_alt = as.numeric(as.character(
      live.cell.track.clusters.hmm_transitions_alt)),
    live.cell.hmm.transitions.movement = as.character(
      live.cell.hmm.transitions.movement),
    live.cell.hmm.transitions.shape = as.character(
      live.cell.hmm.transitions.shape)
    ) %>%
  drop_na(live.cell.track.clusters.hmm_transitions_alt) %>%
  dplyr::filter(
    live.cell.hmm.transitions.movement != "NA",
    live.cell.hmm.transitions.shape != "NA"
    ) %>%
  # group_by(live.cell.track.clusters.hmm_transitions_alt, from, to) %>%
  # dplyr::filter(!live.cell.hmm.transitions.movement %in% paste0(seq(4), "_", seq(4))) %>%
  pivot_longer(
    # cols = c("live.cell.hmm.transitions.movement", "live.cell.hmm.transitions.shape"),
    cols = c("live.cell.hmm.transitions.movement"),
    names_to = "hmm_type",
    values_to = "hmm_value"
  ) %>%
  group_by(live.cell.track.clusters.hmm_transitions_alt, hmm_type, hmm_value) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n) * 1) %>%
  separate_wider_delim(hmm_value, delim = "_", names = c("from", "to"))
  # ungroup() %>%
  # complete(live.cell.track.clusters.hmm_transitions_alt, from, to, fill = list(freq = 0))

ggplot(datToPlot, aes(as.factor(from), as.factor(to), size = freq * 2, fill = freq)) +
  theme_classic() +
  # scale_fill_brewer(palette = "Accent") +
  # scale_y_continuous(breaks = c(0, 0.5, 1)) +
  geom_vline(xintercept = as.factor(1:4), color = "#d3d3d3") +
  geom_hline(yintercept = as.factor(1:4), color = "#d3d3d3") +
  geom_point(pch = 21, color = "black") +
  # viridis::scale_fill_viridis() +
  scale_fill_gradient2(
    midpoint = 0.5, low="blue", mid="white", high="red", space ="Lab") +
  theme(
    legend.position = "none",
    # legend.position = "right",
    legend.key.size = unit(6, "mm"),
    legend.title = element_blank(),
    legend.text = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    axis.text.x = element_text(size = 12),
    # axis.text.x = element_text(size = 12, angle = 45, hjust = 1, vjust = 1),
    strip.background = element_blank(),
    strip.text.x = element_blank()
    # strip.text.x = element_text(size = 12)
    ) +
  # scale_fill_discrete(name = "HMM State") +
  xlab("From state") + ylab("To state") +
  facet_wrap(~live.cell.track.clusters.hmm_transitions_alt, nrow = 2)

ggsave(file.path(anaDir, "clusters_transitions_heat.pdf"), width = 8, height = 4)
```

```{r fig_umap_tests, fig.height=3, fig.width=3}
for (i in names(types.tests.sc)) {
  dfToPlot <- copy(types.tests.sc[[i]]) %>% left_join(exp.info)
  
  dfToPlot$type <- "T cells"
  dfToPlot[!is.na(str_match(dfToPlot$pop, "^dcs")[, 1]), type := "DCs"]

  # plot UMAP
  ggplot(
    dfToPlot,
    aes(UMAP_1, UMAP_2)
    ) +
    theme_classic() +
    geom_point(data = dfToPlot[type == "DCs"], color = "#B3BCC2", size = 4) +
    geom_point(data = dfToPlot[type == "T cells"], color = "#AA1F5E", size = 4) +
    theme(
      axis.text = element_text(size = 15),
      axis.text.x = element_blank(),
      axis.ticks.x = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank(),
      legend.justification = "right",
      # legend.position = "bottom"
      legend.position = "none",
      axis.line = element_blank(),
      axis.title.x = element_blank(),
      axis.title.y = element_blank()
      )
  
  ggsave(file.path(anaDir, paste0("umap_", i, ".tiff")), width = 5, height = 5)
}
```

```{r}
# show measurements of clusters to compare
propsToPlot <- copy(types.sc)

propsToPlot <- propsToPlot %>%
  dplyr::rename(
    "oblate (mean)" = "ellipticity_interm_oblate.mean",
    "oblate (sd)" = "ellipticity_interm_oblate.sd",
    "prolate (mean)" = "ellipticity_interm_prolate.mean",
    "prolate (sd)" = "ellipticity_interm_prolate.sd",
    "extent (mean)" = "extent.mean",
    "extent (sd)" = "extent.sd",
    "solidity (mean)" = "solidity.mean",
    "solidity (sd)" = "solidity.sd",
    "sphericity (mean)" = "sphericity.mean",
    "sphericity (sd)" = "sphericity.sd",
    "surface_area (mean)" = "surface_area.mean",
    "surface_area (sd)" = "surface_area.sd",
    "volume (mean)" = "volume.mean",
    "volume (sd)" = "volume.sd",
    "compactness (mean)" = "compactness.mean",
    "compactness (sd)" = "compactness.sd",
    "Movement HMM 1" = "live.cell.hmm.state.movement.1",
    "Movement HMM 2" = "live.cell.hmm.state.movement.2",
    "Movement HMM 3" = "live.cell.hmm.state.movement.3",
    "Movement HMM 4" = "live.cell.hmm.state.movement.4",
    "Shape HMM 1" = "live.cell.hmm.state.shape.1",
    "Shape HMM 2" = "live.cell.hmm.state.shape.2",
    "Shape HMM 3" = "live.cell.hmm.state.shape.3",
    "Shape HMM 4" = "live.cell.hmm.state.shape.4"
  )

colsToPlot <- colnames(propsToPlot)[!colnames(propsToPlot) %in% c(
  "pop", "uID", "track_id", "clusters", "UMAP_1", "UMAP_2"
  )]

propsToPlot <- propsToPlot %>%
  pivot_longer(
    cols = colsToPlot, names_to = "prop", values_to = "value"
    )

propsToPlot$prop <- factor(propsToPlot$prop, levels = sort(colsToPlot, decreasing = TRUE))

propsToPlot$clusters.name <- "NONE"
propsToPlot[propsToPlot$clusters == 0, ]$clusters.name <- "Meandering"
propsToPlot[propsToPlot$clusters == 1, ]$clusters.name <- "Scanning"
propsToPlot[propsToPlot$clusters == 2, ]$clusters.name <- "Directed"

# show heatmap for clusters
propsSummary <- propsToPlot %>%
  # dplyr::filter(!is.na(live.cell.hmm.state.movement)) %>%
  # group_by(live.cell.hmm.state.movement, prop) %>%
  group_by(clusters, prop) %>%
  # group_by(clusters.name, prop) %>%
  summarise(mean = mean(value, rm.na = TRUE)) %>%
  group_by(prop) %>%
  mutate(freq = (mean - min(mean)) / (max(mean) - min(mean))) %>%
  arrange(-prop)
```


```{r fig_clusters_heat, fig.height=3, fig.width=5}
propsSummary$prop <- factor(propsSummary$prop, levels = rev(c(
  'Movement HMM 1',
  'Movement HMM 2',
  'Movement HMM 3',
  'Movement HMM 4',
  'Shape HMM 1',
  'Shape HMM 2',
  'Shape HMM 3',
  'Shape HMM 4',
  'asphericity',
  'displacement',
  'displacementRatio',
  'duration',
  'meanTurningAngle',
  'outreachRatio',
  'overallAngle',
  'speed',
  'straightness',
  'trackLength',
  'compactness (mean)',
  'extent (mean)',
  'oblate (mean)',
  'prolate (mean)',
  'solidity (mean)',
  'sphericity (mean)',
  'surface_area (mean)',
  'volume (mean)',
  'compactness (sd)',
  'extent (sd)',
  'oblate (sd)',
  'prolate (sd)',
  'solidity (sd)',
  'sphericity (sd)',
  'surface_area (sd)',
  'volume (sd)'
)))

# add group
propsSummary$group <- "Movement"
propsSummary[!is.na(str_extract(propsSummary$prop, "\\(sd|mean\\)")),]$group <- "Shape"

# ggplot(propsSummary, aes(prop, as.factor(clusters))) +
ggplot(propsSummary, aes(as.factor(clusters), prop)) +
  theme_classic() +
  geom_tile(aes(fill = freq), colour = "white", size = 0.5) +
  viridis::scale_fill_viridis(
    breaks = c(0, 1),
    labels = c(0, 1)
  ) +
  theme(
    # legend.position = "none",
    legend.title = element_blank(),
    legend.text = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    axis.text.x = element_text(size = 12),
    # axis.text.x = element_text(size = 12, angle = 45, hjust = 1, vjust = 1),
    strip.background = element_blank(),
    strip.text.x = element_blank()
    ) +
  xlab("") + ylab("") + facet_wrap(~group, ncol = 2, scales = "free")

ggsave(file.path(anaDir, "clusters_heat.pdf"), width = 8, height = 6)
```
