---
title: "Behaviour GCAMP"
output: html_document
date: '2022-08-15'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Show transition states of live cell imaging

```{r}
Sys.setenv(KMP_DUPLICATE_LIB_OK = "TRUE")
devtools::load_all("../")
cciaUse("~/cecelia/dev")

library(ggplot2)
library(tidyverse)
```

```{r}
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

.flowPopParent("P14", getRoot = FALSE) 
```


```{r}
# set test variables
pID <- "Co3HDh"
versionID <- 1
anaDir <- "~/Downloads"
```

```{r}
# set test datasets
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "lWinrY", versionID = versionID, initReactivity = FALSE # Tcells
)

cciaObj$setImLabelPropsFilepath("T.h5ad", "T")
# cciaObj$setImPopMap()

a <- cciaObj$imPopMap("live", includeFiltered = TRUE)
b <- a$hwn2dV
b$parent <- "T"
b$path <- "T/tracked"
b$valueName <- "T"
a$P2k4WJ <- b
cciaObj$setImPopMap("live", a)
cciaObj$saveState()
```


```{r}
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "lWinrY", versionID = versionID, initReactivity = FALSE # Tcells
)

pops <- unname(unlist(cciaObj$popPaths(
  popType = "live", filteredOnly = TRUE, filterMeasures = c("track_id"))))

# popDT <- cciaObj$popDT("live", pops = c(popsTracked[[3]]), includeFiltered = TRUE)
popDT <- cciaObj$popDT("live", pops = c(pops), includeFiltered = TRUE)
# popRoot <- cciaObj$popDT("live", pops = c("OTI", "OTI/tracked"), includeFiltered = TRUE)
# popRoot <- cciaObj$popDT("live", pops = c("P14", "P14/tracked"), includeFiltered = TRUE)
# popRoot <- cciaObj$popDT("live", pops = c("gBT", "gBT/tracked"), includeFiltered = TRUE)

g <- cciaObj$tracksGraph(
  completeDT = TRUE,
  replaceNA = TRUE,
  pop = pops[[1]],
  extraAttr = c("label")
)

# tracks.OTI <- cciaObj$tracks(pops[[1]])
# tracks.P14 <- cciaObj$tracks(pops[[2]])
# tracks.gBT <- cciaObj$tracks(pops[[3]])
tracks.T <- cciaObj$tracks(pops[[4]])
```


```{r fig_tracks_points, fig.height=3, fig.width=10}
# plot out tracks
ggplot(popDT, aes(centroid_x, centroid_y, group = track_id,
                  colour = pracma::rad2deg(live.cell.angle))) +
  theme_classic() +
  geom_path() +
  facet_grid(.~pop) +
  viridis::scale_colour_viridis(option = "inferno", name = "Angle (째)") 

ggsave(file.path(anaDir, "pop_tracks.png"), width = 9, height = 3)
```


```{r}
# for each track - can you get the median speed and angle?
# then see which points are total outliers
tracks.info <- cciaObj$tracksInfo(
  c("live.cell.speed", "live.cell.angle"),
  # parentPop = popsTracked[[1]]
  # parentPop = popsTracked[[2]]
  # parentPop = popsTracked[[3]]
  parentPop = pops[[4]]
)
```

```{r}
# get tracks measurements for each population
tracksInfo <- cciaObj$tracksMeasures(pops)
tracksInfo
```

```{r}
colnames(tracksInfo)
```


```{r fig_tracks_measures, fig.height=3, fig.width=10}
colsToPivot <- colnames(tracksInfo)
colsToPivot <- colsToPivot[!colsToPivot %in% c("cell_type", "track_id")]

datToPlot <- tracksInfo %>%
  pivot_longer(cols = colsToPivot,
               names_to = "measure", values_to = "value")

ggplot(datToPlot, aes(cell_type, value, color = cell_type)) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(position = position_jitterdodge(jitter.width = 0.10)) +
  facet_wrap(.~measure, scales = "free", nrow = 2) +
  theme(
    legend.position = "none",
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)
    ) +
  scale_color_brewer(palette = "Set1") +
  coord_flip() + xlab("") + ylab("")

ggsave(file.path(anaDir, "tracks_measures.png"), width = 11, height = 4)
```

```{r}
# can you save the difference between two track id lists?
# this would be a way of creating a history for track editing
trackEdits <- list(
  c(1,2,3,56,2,35,7,2,35,1),
  c(1,3,3,56,4,35,NA,2,35,2),
  c(1,3,3,56,4,35,NA,2,35,2), # start back here
  c(3,4,5,56,4,35,NA,NA,NA,2),
  c(3,4,3,56,4,35,NA,NA,NA,2)
)
curTracks <- c(1,2,3,5,3,34,7,2,35,1)
editHistory <- list()

# get difference between track IDs for history
track.diffs <- function(a, b) {
  # get differences between lists
  # TODO doesn't work for NA; probably would need to time which solution is better
  # https://stackoverflow.com/a/78724307
  # `%!=na%` <- function(e1, e2) (e1 != e2 | (is.na(e1) & !is.na(e2)) | (is.na(e2) & !is.na(e1))) & !(is.na(e1) & is.na(e2))
  # listDiff <- a != b
  # listDiff <- a %!=na% b
  list.diff <- paste(a) != paste(b)
  # https://stackoverflow.com/a/61248968
  # list.diff <- !((a == b) | (is.na(a) & is.na(b)))
  
  # a = previous values, b = current values, i = index
  list(a = a[list.diff], b = b[list.diff], i = which(list.diff))
}

# roll back changes
track.edits.rollback <- function(x, edit.history, i) {
  # get changes in reverse order
  track.changes <- edit.history[length(edit.history):i]
  
  # apply changes
  for (y in track.changes) {
    for (j in seq(length(y$i))) {
      x[y$i[j]] <- y$a[j]
    }
  }
  
  x
}

# create history of edits
for (i in seq(length(trackEdits))) {
  x <- trackEdits[[i]]
  # editHistory[[i]] <- track.diffs(curTracks, x)
  editHistory <- append(editHistory, setNames(list(track.diffs(curTracks, x)), i))
  curTracks <- x
}

# then roll back to a certain state and go from there
curTracks <- track.edits.rollback(curTracks, editHistory, 3)

# check that the tracks are the same
all(paste(curTracks) == paste(trackEdits[[3]]))

# create DF
# as.data.table(editHistory)
as.data.table(list(desc = names(editHistory)))
```


```{r}
# Can you calculate the cumulative change of direction
# depending on user input. Then, package this as a module
# get tracks for every population
valueNames <- sapply(pops, .flowPopParent, USE.NAMES = FALSE)
names(valueNames) <- valueNames

# get tracks for populations
tracks <- lapply(valueNames, function(x) cciaObj$tracks(x))
tracks
```

```{r}
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# get cumulative change of direction for each track
sumLength <- 8

popDT[
  tracks.measure.fun(
    tracks, celltrackR::overallAngle, "live.cell.sumChange",
    steps.subtracks = sumLength, idcol = "value_name")
  on = .(value_name, track_id, cell_id),
  live.cell.sumChange := .(live.cell.sumChange)
]
```

```{r fig_tracks_points, fig.height=3, fig.width=3}
# plot out and compare
# track_to_show <- 22
track_to_show <- 43

# https://stackoverflow.com/a/21538521
myPalette <- colorRampPalette(rev(RColorBrewer::brewer.pal(11, "Spectral")))
sc <- scale_colour_gradientn(colours = myPalette(100), limits=c(1, 180), name = "Angle (째)")

ggplot(popDT[value_name == "P14" & track_id == track_to_show],
       aes(centroid_x, centroid_y, group = track_id,
           colour = pracma::rad2deg(live.cell.sumChange))) +
  theme_classic() +
  geom_path() +
  # facet_grid(.~pop) +
  # scale_color_brewer(palette = "spectral", name = "Sum (째)") +
  sc +
  ggtitle("Cumulative change") +
  coord_fixed() +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.line = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
  ) 
ggsave(file.path(anaDir, "pop_track_sumChange.png"), width = 3, height = 3)

ggplot(popDT[value_name == "P14" & track_id == track_to_show],
       aes(centroid_x, centroid_y, group = track_id,
           colour = pracma::rad2deg(live.cell.angle))) +
  theme_classic() +
  geom_path() +
  # facet_grid(.~pop) +
  # scale_color_brewer(palette = "spectral", name = "Angle (째)") +
  sc + 
  ggtitle("Angle") +
  coord_fixed() +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.line = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
  ) 
ggsave(file.path(anaDir, "pop_track_angle.png"), width = 3, height = 3)
```

```{r}
# test this from a module
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "lWinrY", versionID = versionID, initReactivity = FALSE # Tcells
)

# run task
funParams <- list(
  popType = "live",
  pops = c("OTI/tracked", "P14/tracked", "gBT/tracked"),
  sumLength = 8
)

# run task
task <- cciaObj$runTask(
  funName = "behaviourAnalysis.cumulativeChange",
  funParams = funParams,
  env = "local",
  runInplace = TRUE,
  taskID = 1
)
```
```{r}
library(plotly)

# plot out tracks
plot_ly(source = "trackTraces") %>%
  add_trace(
    data = popDT[value_name == "T"],
    x = ~centroid_x, y = ~centroid_y, split = ~track_id,
    type = "scatter", mode = "lines+markers", showlegend = FALSE) %>%
  layout(
    xaxis = list(scaleanchor = "y", scaleratio = 1),
    yaxis = list(autorange = "reversed"),
    xlim = c(0, max(popDT$centroid_x)),
    ylim = c(0, max(popDT$centroid_y))
    ) %>%
  toWebGL()
```


```{r fig_points_qc, fig.height=8, fig.width=8}
speed.thresh <- 9
angle.thresh <- 1
# popDT[, id := ""]
# popDT[live.cell.speed.dev >= speed.thresh | live.cell.angle.dev >= angle.thresh, id := track_id]
tracks.info[, id := ""]
tracks.info[live.cell.speed.sd >= speed.thresh | live.cell.angle.sd >= angle.thresh, id := track_id]

# ggplot(popDT, aes(live.cell.speed.dev, live.cell.angle.dev)) +
ggplot(tracks.info, aes(live.cell.speed.sd, live.cell.angle.sd)) +
  theme_classic() +
  geom_point() +
  geom_text(aes(label = id), color = "red", hjust = -0.1) +
  geom_vline(xintercept = speed.thresh, col = "blue", lty = 2) +
  geom_hline(yintercept = angle.thresh, col = "blue", lty = 2)
```

```{r fig_tracks_points, fig.height=8, fig.width=18}
# can you plot the pairs
# or could you even zoom into them with napari?
# you would just need XY and then set the coordinates with a buffer

# track.pairs <- popDT[!is.na(id),]$id
# track.pairs <- popDT[id != "",]$id
track.pairs <- tracks.info[id != "",]$id
track.pairs <- unlist(table(track.pairs))
track.pairs <- sort(track.pairs, decreasing = TRUE)

xRes <- cciaObj$omeXMLPixelRes()$x

par.m <- 6
par.n <- ceiling(length(track.pairs)/par.m)

par(mfrow=c(par.n, par.m))

for (i in names(track.pairs)) {
  # x <- popDT[track_id == i & id != ""]
  
  # plot(tracks.OTI[i], main = paste(i, track.pairs[[i]], sep = "-"))
  # plot(tracks.P14[i], main = paste(i, track.pairs[[i]], sep = "-"))
  plot(tracks.gBT[i], main = paste(i, track.pairs[[i]], sep = "-"))
  # points(x$centroid_x * xRes, x$centroid_y * xRes, cex = 2, pch = 6, col ="red") 
}

# to highlight in napari
paste(names(track.pairs), collapse = ",")
```

```{r fig_tracks_qc, fig.height=8, fig.width=8}
library(celltrackR)

# just as a test, can you blow up the data to see how long that takes?
# https://ingewortel.github.io/celltrackR/vignettes-out/QC.html
# then check how long plotting takes with plotly v ggplot
# tracks.gBT.sim <- copy(tracks.gBT)
tracks.gBT.sim <- celltrackR::as.tracks(list())

# shift tracks so that you get a larger field
# get max for adding tracks
centroid.max <- colMax(popDT[pop == "gBT/tracked", c("centroid_x", "centroid_y")])
tracks.rows.n <- 6
tracks.total <- tracks.rows.n * 9

# for (i in seq(8)) {
for (i in seq(tracks.total)) {
  row.idx <- floor((i - 1)/tracks.rows.n) + 1
  col.idx <- i %% tracks.rows.n + 1

  x.shift <- row.idx * centroid.max[[1]]
  y.shift <- col.idx * centroid.max[[2]]
  
  tracks.gBT.dup <- copy(tracks.gBT)

  # Add some noise to coordinates
  for (i in names(tracks.gBT)) {
    # tracks.gBT.dup[[i]][,"x"] <- tracks.gBT.dup[[i]][,"x"] + rnorm(nrow(tracks.gBT.dup[[i]]), sd = 0.5)
    # tracks.gBT.dup[[i]][,"y"] <- tracks.gBT.dup[[i]][,"y"] + rnorm(nrow(tracks.gBT.dup[[i]]), sd = 0.5)
    tracks.gBT.dup[[i]][,"x"] <- tracks.gBT[[i]][,"x"] + x.shift
    tracks.gBT.dup[[i]][,"y"] <- tracks.gBT[[i]][,"y"] + y.shift
    tracks.gBT.dup[[i]][,"z"] <- tracks.gBT[[i]][,"z"] + rnorm(nrow(tracks.gBT[[i]]), sd = 0.5)
  }

  # Wrap the track in a tracks object and add it to the TCell data with
  # a unique id number
  if (length(tracks.gBT.sim) > 0) {
    max.id <- max(as.numeric(names(tracks.gBT.sim)))
    new.ids <- seq(max.id + 1, max.id + length(tracks.gBT.dup))
    names(tracks.gBT.dup) <- as.character(new.ids)
    tracks.gBT.sim <- c(tracks.gBT.sim, tracks.gBT.dup)
  } else {
    tracks.gBT.sim <- tracks.gBT.dup
  }

  print(length(tracks.gBT.sim))
}
```


```{r}
plot(tracks.gBT.sim)
```


```{r fig_tracks_qc, fig.height=8, fig.width=8}
# df <- analyzeCellPairs(tracks.OTI)
# df <- analyzeCellPairs(tracks.P14)
# df <- analyzeCellPairs(tracks.gBT)
# TODO this takes a long time .. even with search radius
# because search radius doesn't do anything pre-distance
# it's just a filter after ALL distances have been measures
# df <- analyzeCellPairs(tracks.gBT.sim, searchRadius = 20)

# could you.. pre-filter tracks somehow or do the pairs analysis by tiles?
# the tiles wouldn't have to be overlapping.. ?
```

```{r}
# get dimensions of tracks
# tracks.gBT.sim.dt <- as.data.table(tracks.gBT.sim)
# tracks.gBT.sim.max <- colMax(tracks.gBT.sim.dt[, c("x", "y")])
tracks.T.dt <- as.data.table(tracks.T)
tracks.T.max <- colMax(tracks.T.dt[, c("x", "y")])

# can you translate that into R?
# block.size <- 512
block.size <- 128
# x.max <- tracks.gBT.sim.max[["x"]]
# y.max <- tracks.gBT.sim.max[["y"]]
x.max <- tracks.T.max[["x"]]
y.max <- tracks.T.max[["y"]]

tiles.m <- ceiling(y.max/block.size)
tiles.n <- ceiling(x.max/block.size)
# M <- floor(y.max/tiles.m)
# N <- floor(x.max/tiles.n)
M <- y.max/tiles.m
N <- x.max/tiles.n

block.list <- list()

for (x in seq(0, x.max, M)) {
  for (y in seq(0, y.max, N)) {
    block.list <- append(block.list, list(list(x1 = x, x2 = x + M, y1 = y, y2 = y + N)))
  }
}

# block.dt <- do.call(rbind, block.list)
```

```{r}
library(celltrackR)

# then go through all tracks that are touching these blocks
pairs.results <- list()

for (block.coords in block.list) {
  x.ids <- unique(
    # tracks.gBT.sim.dt[x >= block.coords$x1 & x <= block.coords$x2 &
    tracks.T.dt[x >= block.coords$x1 & x <= block.coords$x2 &
                  y >= block.coords$y1 & y <= block.coords$y2,]$id)
  
  print(block.coords)
  
  pairs.results <- append(
    # pairs.results, list(analyzeCellPairs(tracks.gBT.sim[names(tracks.gBT.sim) %in% x.ids])))
    pairs.results, list(analyzeCellPairs(tracks.T[names(tracks.T) %in% x.ids])))
}

# TODO is unique required?
# pairs.DT <- unique(rbindlist(pairs.results))
pairs.DT <- rbindlist(pairs.results)
```


```{r fig_tracks_qc, fig.height=8, fig.width=8}
# these thresholds should be dynamic and set by the user to delete tracks
# not sure you need a sort of gating here
# label cellpairs that have both angle and distance below threshold
df <- copy(pairs.DT)

angle.thresh <- 90 # in degrees
dist.thresh <- 10 # this should be the expected cell radius
df$id <- paste0( df$cell1,"-",df$cell2 )
df$id[ !(df$angle < angle.thresh & df$dist < dist.thresh) ] <- "" 
# df[is.na(df$dist), ]$dist <- 0

# Plot; zoom in on the region with small angles and distances
ggplot( df, aes( x = dist, y = angle ) ) +
  geom_point( color = "gray40" ) +
  geom_text( aes( label = id ), color = "red", hjust = -0.1 ) +
  labs( x = "distance between cell pairs",
        y = "angle between cell pairs" ) +
  # coord_cartesian( xlim=c(0,400), ylim=c(0,180) ) +
  coord_cartesian( xlim=c(0,20), ylim=c(0,180) ) +
  geom_hline( yintercept = angle.thresh, col = "blue",lty=2 ) +
  geom_vline( xintercept = dist.thresh, col = "blue", lty=2) +
  theme_classic()
```

```{r fig_tracks_traces, fig.height=5, fig.width=5}
# plot tracks in plotly
# there is no standard way to do this
library(dplyr)
library(plotly)

nonDF <- df[df$id != "" & !is.na(df$dist),]
tracks.A <- unique(nonDF$cell1)
tracks.B <- unique(nonDF$cell2)
popTracks <- as.data.table(popDT[track_id %in% c(tracks.A, tracks.B), ])
popTracks[, track.side := "0"]
popTracks[track_id %in% tracks.B, track.side := "1"]

# df %>% distinct(id) %>%
#   `[<-`(,c(2,4),NA) %>%
#   rbind(df) %>%
#   arrange (id)

plot_ly(popTracks) %>%
  add_trace(data = popTracks[track.side == "0", ],
            x = ~centroid_x, y = ~centroid_y, split = ~track_id,
            type = "scatter", mode = "lines+markers", showlegend = FALSE,
            line = list(color = "black")) %>%
  add_trace(data = popTracks[track.side == "1", ],
            x = ~centroid_x, y = ~centroid_y, split = ~track_id,
            type = "scatter", mode = "lines+markers", showlegend = FALSE,
            line = list(color = "red")) %>%
  layout(xaxis = list(scaleanchor = "y", scaleratio = 1))
```


```{r fig_tracks_pairs, fig.height=8, fig.width=10}
# can you plot the pairs
# or could you even zoom into them with napari?
# you would just need XY and then set the coordinates with a buffer

track.pairs <- df[!is.na(df$dist),]$id
track.pairs <- unique(track.pairs[track.pairs != ""])
track.pairs <- stringr::str_split(track.pairs, "-")

track.border <- list(
  title = "",
  zeroline = FALSE,
  showline = TRUE,
  showticklabels = FALSE,
  showgrid = FALSE
)

plots <- lapply(track.pairs, function(x) {
  plot_ly(popDT[track_id %in% x], x = ~centroid_x, y = ~centroid_y,
        split = ~track_id, type = "scatter", mode = "lines+markers",
        colors = c("black", "red"), color = ~track_id) %>% hide_guides() %>%
    layout(xaxis = track.border, yaxis = track.border)
})

subplot(plots, nrows = 4)
```


```{r fig_tracks_pairs, fig.height=8, fig.width=10}
par.m <- 4
par.n <- ceiling(length(track.pairs)/par.m)

par(mfrow=c(par.n, par.m))

for (x in track.pairs) {
  # plot(tracks.OTI[c(x[[1]], x[[2]])], main = paste(x, collapse = "-"))
  # plot(tracks.P14[c(x[[1]], x[[2]])], main = paste(x, collapse = "-"))
  plot(tracks.gBT[c(x[[1]], x[[2]])], main = paste(x, collapse = "-"))
}

# to highlight in napari
paste(unique(unlist(track.pairs)), collapse = ",")
```


```{r}
# ok, once you selected tracks - how do you change them?
# these functions should work on the popDT for now
# not sure whether I need to do anything else for that
# popDT.local <- copy(popDT)
popDT.local <- copy(popRoot)

# ok go through and correct, check on image and then make an interface for it

## Functions
# delete track
tracks.rm <- function(popDT, trackID) {
  # should work in place
  popDT[track_id == trackID, track_id := NA]
}

# join tracks
tracks.join <- function(popDT, trackID.A, trackID.B) {
  # get last point of first track
  t.a <- popDT[track_id == trackID.A]$centroid_t
  t.b <- popDT[track_id == trackID.B]$centroid_t
  # t.a.last <- t.a[length(t.a)] 
  
  # get first element of B that is not in A
  t.intersect <- intersect(t.a, t.b)
  t.b.unique <- t.b[!t.b %in% t.intersect]
  
  # now merge track points in place
  popDT[track_id == trackID.B & centroid_t %in% t.b.unique, track_id := trackID.A]
}

# save modified tracks file
# TODO this is really only for viewing in napari
tracks.save.mod <- function(popDT, valueName, ext.mod = "-mod") {
  # get labels
  labels <- cciaObj$labelProps(valueName = valueName)
  
  if (length(labels) > 0) {
    labels.path <- labels$adata_filepath()
    
    labels.new.base <- stringr::str_replace(basename(labels.path), ".h5ad", paste0(ext.mod, ".h5ad"))
    labels.new.path <- file.path(dirname(labels.path), labels.new.base)
    
    # add to labels
    labels$add_obs(as.list(popDT[, .(track_id)]))
    
    # save
    labels$save(filename = labels.new.path)
    labels$close()
  }
}

# get track position
tracks.pos <- function(popDT, tracksIDs, pixRes = 1) {
  # get coordinates for tracks to centre camera
  centroid.cols <- c("centroid_t", "centroid_y", "centroid_x")
  
  # https://stackoverflow.com/a/43834005
  tracks.centroids <- unlist(
    popDT[track_id %in% tracksIDs,
          sapply(.SD, function(x) list(median = round(median(x)))),
          .SDcols = centroid.cols])
  
  # set resolution for coordinates
  tracks.centroids[2:length(tracks.centroids)] <- tracks.centroids[2:length(tracks.centroids)] * pixRes
  
  names(tracks.centroids) <- centroid.cols
  tracks.centroids
}
```

```{r}
x <- c(113)

tracks.pos(popDT.local, x, cciaObj$omeXMLPixelRes()$x)
```


```{r}
popDT.local <- copy(popRoot)

# join tracks
# this is done by default on the last point of the first track, and
# then the first point of the second track that is not in the same frame
# TODO this might vary as you encounter other scenarios
x <- c(88, 111)

tracks.join(popDT.local, x[[1]], x[[2]])
tracks.rm(popDT.local, x[[2]])
tracks.save.mod(popDT.local, "OTI")
```

```{r}
x <- c(77, 113)

tracks.join(popDT.local, x[[1]], x[[2]])
tracks.rm(popDT.local, x[[2]])
tracks.save.mod(popDT.local, "OTI")
```


```{r}
# split track at point
```



```{r fig_tracks_traces, fig.height=25, fig.width=25}
trackIDs <- unique(popDT$track_id)
colPal <- randomcoloR::distinctColorPalette(length(trackIDs))
# names(colPal) <- trackIDs

plot_ly(
    # popDT,
    popDT %>% group_by(track_id),
    x = ~centroid_x,
    y = ~centroid_y,
    ids = NULL,
    type = "scatter",
    # mode = "lines+markers",
    mode = "lines",
    source = "trackTraces",
    color = ~track_id,
    colors = colPal,
    line = list(width = 5)
    # marker = list(size = 10)
    ) 
    # add_trace(
    #   alpha = 1,
    #   color = I("red"),
    #   type = "scatter",
    #   mode = "markers",
    #   frame = ~centroid_t,
    #   line = list(width = 0),
    #   marker = list(size = 10),
    #   ids = ~label) %>%
    # plotly::hide_colorbar()
```

```{r fig_tracks_tree, fig.height=25, fig.width=25}
library(ggplot2)
library(ggraph)
library(igraph)

# plot out graph
set.seed(1984)
L <- layout_as_tree(g)

# add time
# L[,2] <- get.vertex.attribute(g, "centroid_t")

L.DT <- as.data.table(L)
colnames(L.DT) <- c("L1", "L2")
L.DT[, label := get.vertex.attribute(g, "label")]

# plot.igraph(g, layout = L, vertex.size = 1)

popDT[L.DT, on = c("label")] %>%
  group_by(track_id) %>%
  plot_ly(
    x = ~L1,
    y = ~centroid_t,
    type = "scatter",
    mode = "lines+markers",
    line = list(color="#000000", width = 1),
    text = get.vertex.attribute(g, "name"),
    hoverinfo = "text",
    size = I(42),
    # color = as.character(vertex_attr(G, 'color')),
    # colors = c('orange', 'skyblue'),
    showlegend = FALSE
  ) %>%
  add_markers(
    x = ~L1,
    y = ~centroid_t,
    type = "scatter",
    mode = "lines+markers",
    line = list(color="", width = 1),
    text = get.vertex.attribute(g, "name"),
    hoverinfo = "text",
    size = I(42),
    # color = as.character(vertex_attr(G, 'color')),
    # colors = c('orange', 'skyblue'),
    showlegend = FALSE
  )
```

```{r}
library(plotly)

cPopDT <- copy(popDT[value_name == "OTI" & !is.na(live.cell.speed) & !is.na(live.cell.angle)])

popKey <- highlight_key(cPopDT, ~track_id)

p1 <- plot_ly(cPopDT, y = ~centroid_y, x = ~centroid_x) %>%
  add_markers(alpha = 0.1, color = I("black")) %>%
  add_markers(
    data = popKey,
    frame = ~centroid_t,
    ids = ~track_id,
    color = I("red")
  )

p2 <- plot_ly(cPopDT, x = ~live.cell.speed, y = ~live.cell.angle, size = ~volume) %>%
  add_markers(color = I("black"), alpha = 0.1) %>%
  add_markers(
    data = popKey,
    frame = ~centroid_t,
    ids = ~track_id,
    color = I("red")
  )

subplot(p1, p2, nrows = 1, widths = c(0.5, 0.5), titleX = TRUE, titleY = TRUE, shareX = FALSE, shareY = FALSE) %>%
  hide_legend() %>%
  animation_opts(30, redraw = FALSE) %>%
  # layout(hovermode = "y", margin = list(l = 100)) %>%
  highlight(
    "plotly_selected", 
    color = "blue", 
    opacityDim = 1, 
    hoverinfo = "none"
  )
```


```{r}
library(htmlwidgets)
library(plotly)

plot_ly(mtcars, x = ~wt, y = ~mpg) %>%
  onRender("
    function(el) { 
      el.on('plotly_hover', function(d) { 
        console.log('Hover: ', d); 
      });
      el.on('plotly_click', function(d) { 
        console.log('Click: ', d);
      });
      el.on('plotly_selected', function(d) { 
        console.log('Select: ', d); 
      });
    }
  ")
```


```{r}
# colPal <- randomcoloR::distinctColorPalette(length(unique(popDT$track_id)))

plot_ly(popDT, x = ~centroid_x, y = ~(-centroid_y)) %>%
  add_markers(color = ~track_id, frame = ~centroid_t, ids = ~track_id) %>%
  hide_legend() %>%
  animation_opts(frame = 30, transition = 0, redraw = FALSE)
```

