---
title: "Behaviour GCAMP"
output: html_document
date: '2022-08-15'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Show transition states of live cell imaging

```{r}
Sys.setenv(KMP_DUPLICATE_LIB_OK = "TRUE")
devtools::load_all("../")
cciaUse("~/cecelia/dev")

library(ggplot2)
library(tidyverse)
```

```{r}
# set test variables
pID <- "uh0h3c"
versionID <- 1
projectsDir <- "/Volumes/USER_data/Dominik/CECELIA_BACKUP/"
hpcDir <- "/data/scratch/projects/punim1124/cecelia/USERS/schienstockd/"
```

```{r}
anaDir <- "/Volumes/USER_data/Dominik/Experiments/Mengliang/CECELIA"
# anaDir <- "/Users/Dominik/Dropbox/_Dominik-Scott share/Meetings/Progress/Mengliang"
```

```{r}
# devtools::load_all("../")
# cciaUse("~/cecelia/dev", initConda = FALSE)
# 
# # init ccia object
# cciaObj <- initCciaObject(
#   pID = pID, uID = "4i3bxX", versionID = versionID, initReactivity = FALSE
# )
# 
# # run task
# funParams <- list(
#   valueName = "default", 
#   imChannels = c("one"),
#   timeDelta = 1,
#   createNewChannels = TRUE
# )
# 
# task <- cciaObj$runTask(
#   funName = "cleanupImages.timeDeltaCorrect",
#   funParams = funParams,
#   env = "local",
#   runInplace = TRUE,
#   taskID = 1
# )
```

```{r}
# show numbers of cells per area
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  # pID = pID, uID = "ZVUrjF", versionID = versionID, initReactivity = FALSE
  pID = pID, uID = "WzCWD0", versionID = versionID, initReactivity = FALSE
)

exp.info <- as.data.table(cciaObj$summary(withSelf = FALSE, fields = c("Attr")))

# get branching
labels <- lapply(cciaObj$cciaObjects(), function(x) {
  y <- x$labelProps(valueName = "fibres.branch")
  uns <- y$values_uns()
  y$close()
  
  uns
})

# merge summary
exp.info <- exp.info[rbindlist(lapply(labels, function(x) x$ilee_summary), idcol = "uID"), on = c("uID")]

# load tracks
tracks.table <- as.data.table(read.csv(
  # "/Volumes/USER_data/Dominik/Experiments/Mengliang/DATA/20231107/Nerve anisotropy and cell track/Cell tracking.csv"))
  "/Volumes/USER_data/Dominik/Experiments/Mengliang/DATA/20240307/MW_videos/Cell_track.csv"))

# get branching
# branchDT <- cciaObj$popDT(popType = "branch")

# clean up Region
# tracks.table[Region != "whorl", Region := "inf"]

# match uIDs
tracks.table[exp.info, on = c("ID" = "Patient", "Region"), uID := uID]

# copy group to exp info
# exp.info[unique(tracks.table[, c("uID", "Group")]), on = c("uID"), Group := Group]

# add cell_ids
tracks.table <- as.data.table(tracks.table %>%
  group_by(across(all_of(c("uID", "Track")))) %>%
  dplyr::mutate(cell_id = 1:n()))
setnames(tracks.table, "Track", "track_id")
```

```{r}
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  # pID = pID, uID = "ZVUrjF", versionID = versionID, initReactivity = FALSE
  pID = pID, uID = "WzCWD0", versionID = versionID, initReactivity = FALSE
)

valueName <- "IJ.manual"

# how can you import tracks from ImageJ .. ?
# build label properties from individual tracks
for (x in cciaObj$cciaObjects()) {
  y <- tracks.table[uID == x$getUID()]
  # z <- cbind(seq(nrow(y)), y[, c("track_id", "Slice", "Y", "X", "pixel.value.fiji.")])
  z <- cbind(seq(nrow(y)), y[, c("track_id", "Slice", "Y", "X", "TI")])
  colnames(z) <- c("label", "track_id", "centroid_t", "centroid_y", "centroid_x", "mean_intensity_0")
  
  # save props
  labelsView <- cciaEnv()$LabelPropsUtils(
    x$persistentObjectDirectory(),
    taskDirFiles("labelProps", valueName))$label_props(
      z, save = TRUE, obs_cols = c("label", "track_id"))
  
  # add to labels
  x$setImLabelPropsFilepath(paste0(valueName, ".h5ad"), valueName)
  x$saveState()
}
```

```{r}
# # get HMM transitions
# devtools::load_all("../")
# cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)
# 
# # init ccia object
# cciaObj <- initCciaObject(
#   # pID = pID, uID = "ZVUrjF", versionID = versionID, initReactivity = FALSE
#   pID = pID, uID = "WzCWD0", versionID = versionID, initReactivity = FALSE
# )
# 
# # run task
# funParams <- list(
#   valueName = "IJ.manual",
#   pops = c("IJ.manual")
# )
# 
# # run task
# task <- cciaObj$runTasks(
# # task <- cciaObj$cciaObjects()[[1]]$runTask(
#   funName = "segment.binariseTracks",
#   funParams = funParams,
#   env = "local",
#   runInplace = TRUE,
#   taskID = 1,
#   uIDs = names(cciaObj$cciaObjects()),
#   mc.cores = 3
# )
```

```{r}
# # get HMM transitions
# devtools::load_all("../")
# cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)
# 
# # init ccia object
# cciaObj <- initCciaObject(
#   # pID = pID, uID = "ZVUrjF", versionID = versionID, initReactivity = FALSE
#   pID = pID, uID = "WzCWD0", versionID = versionID, initReactivity = FALSE
# )
# 
# # run task
# funParams <- list(
#   valueName = "IJ.manual.tracks",
#   preDilationSize = 0,
#   postDilationSize = 2,
#   flattenBranching = FALSE,
#   useBorders = FALSE,
#   calcExtended = TRUE,
#   calcFlattened = FALSE,
#   anisoRadius = 40,
#   saveMeshes = FALSE
# )
# 
# # run task
# task <- cciaObj$runTasks(
#   funName = "segment.createBranching",
#   funParams = funParams,
#   env = "local",
#   runInplace = TRUE,
#   taskID = 1,
#   uIDs = names(cciaObj$cciaObjects()),
#   mc.cores = 4
# )
```

```{r}
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  # pID = pID, uID = "ZVUrjF", versionID = versionID, initReactivity = FALSE # SHG 3P
  pID = pID, uID = "WzCWD0", versionID = versionID, initReactivity = FALSE # SHG 3P
)

exp.info <- as.data.table(cciaObj$summary(withSelf = FALSE, fields = c("Attr")))

# get vector information to plot anisotropy
# unsLabels <- c("fibres", "IJ.manual.tracks")
unsLabels <- c("fibres")
uns <- list()

for (i in unsLabels) {
  uns[[i]] <- list()

  for (x in cciaObj$cciaObjects()) {
    labels <- x$labelProps(valueName = paste0(i, ".branch"))

    if (!is.null(labels)) {
      uns[[i]][[x$getUID()]] <- labels$values_uns()
      labels$close()
    }
  }
}

# merge summary
exp.info <- exp.info[rbindlist(lapply(uns$fibres, function(x) x$ilee_summary), idcol = "uID"), on = c("uID")]

# get branching
branchDT <- cciaObj$popDT(popType = "branch")

pops <- list(
  `IJ.manual` = "IJ.manual"
)

# get tracks to align with SHG
popDT <- cciaObj$popDT(popType = "live", pops = pops, includeFiltered = TRUE)

# get tracks info and check parameters
tracksInfo <- cciaObj$tracksMeasures(pops = pops, uIDs = unique(popDT$uID))

# check where the centre of each track is
tracksInfo[
  popDT[, lapply(.SD[, c("centroid_x", "centroid_y")], mean), by = c("uID", "track_id")],
  on = c("uID", "track_id"),
  `:=` (centroid_x = centroid_x, centroid_y = centroid_y)]
```

```{r}
tracks <- cciaObj$tracks("IJ.manual", uIDs = unique(popDT$uID))

# create data.table with properties
tracks.DT <- tracks.measure.fun(tracks, celltrackR::speed,
                                "live.cell.speed", steps.subtracks = 1,
                                idcol = "uID")

# add further measurements
tracks.DT[
  tracks.measure.fun(
    tracks, celltrackR::overallAngle, "live.cell.angle",
    steps.subtracks = 2, idcol = "uID"),
  on = .(uID, track_id, cell_id),
  live.cell.angle := .(live.cell.angle)]

# convert angle to degrees
tracks.DT[, live.cell.angle_deg := pracma::rad2deg(live.cell.angle)]

# add global angle to each track
tracks.DT[, live.cell.angle_deg.csum := cumsum(tidyr::replace_na(live.cell.angle_deg, 0)), by = c("uID", "track_id")]
```

```{r}
# plot quiver
coords <- lapply(uns, function(x) {
  lapply(x, function(y) {
    coords <- data.frame(
      y = as.vector(y$ilee_coor_list[1,,,1]),
      x = as.vector(y$ilee_coor_list[1,,,2])
    )
    u <- as.vector(y$ilee_eigval[1,,,2]) * as.vector(y$ilee_eigvec[1,,,2,1])
    v <- as.vector(y$ilee_eigval[1,,,1]) * as.vector(y$ilee_eigvec[1,,,1,1])
    
    list(coords = coords, u = u, v = v)
  })
})
```

```{r}
# round datapoints
aRad <- 25
tracksInfo[, centroid_y_tile := round(centroid_y/aRad) * aRad]
tracksInfo[, centroid_x_tile := round(centroid_x/aRad) * aRad]
           
# to which anisotropy does the track belong to?
coordMappingsList <- list()

for (x in unique(tracksInfo$uID)) {
  coordMapping <- (tracksInfo[uID == x] %>%
    left_join(coords$fibres[[x]]$coords %>% tibble::rownames_to_column(),
              by = c("centroid_y_tile" = "y", "centroid_x_tile" = "x"))) %>%
    left_join(
      popDT[uID == x] %>%
        group_by(track_id) %>%
        arrange(label) %>%
        filter(row_number() == 1 | row_number() == n()) %>%
        summarise(y = diff(centroid_y), x = diff(centroid_x)), by = c("track_id"))

  matA <- matrix(c(
    coords$fibres[[x]]$u[as.integer(coordMapping$rowname)],
    coords$fibres[[x]]$v[as.integer(coordMapping$rowname)]
  ), ncol = 2)
  
  matB <- matrix(c(
    coordMapping$x,
    coordMapping$y
  ), ncol = 2)
  
  matAngles <- c()
  matAniso <-  c()
  for (i in seq(nrow(matA))) {
    matAngles <- c(matAngles, matlib::angle(as.vector(matA[i, ]), as.vector(matB[i, ]))[1])
    matAniso <- c(matAniso, norm(matA[i, ], type = "2"))
  }
  
  coordMapping$angle <- matAngles
  coordMapping$aniso <- matAniso
  coordMapping <- as.data.table(coordMapping)
  
  # difference cannot be more than 90 DEG
  coordMapping[angle > 90, angle := 180 - angle]
  
  coordMappingsList[[x]] <- copy(coordMapping)
}

coordMappings <- rbindlist(coordMappingsList)
```

```{r}
runSim <- function(y) {
  x <- y$getUID()
  
  sizeX <- y$omeXMLPixels()$SizeX
  sizeY <- y$omeXMLPixels()$SizeY
  mappingsList <- list()
  
  for (bootID in seq(bootIterations)) {
    if (bootID %% 20 == 0)
        message(paste(">", x, bootID))
    
    # vary angle
    curPopsList <- list()
    for (i in popDT[uID == x]$track_id) {
      bootAngle <- runif(n=1, min=0, max=90)
      
      # vary angle
      curPopsList[[i]] <-
        rearrr::rotate_2d(
          popDT[uID == x & track_id == i] %>%
            group_by(track_id) %>%
            arrange(label) %>%
            filter(row_number() == 1 | row_number() == n()),
          degrees = bootAngle,
          origin_fn = rearrr::centroid,
          x_col = "centroid_x",
          y_col = "centroid_y")
    }
    curPops <- rbindlist(curPopsList)
    
    coordMapping_rot <- (tracksInfo[uID == x] %>%
      left_join(coords$fibres[[x]]$coords %>% tibble::rownames_to_column(),
                by = c("centroid_y_tile" = "y", "centroid_x_tile" = "x"))) %>%
      left_join(
        # popDT[uID == x] %>%
        curPops %>%
          group_by(track_id) %>%
          # arrange(label) %>%
          # filter(row_number() == 1 | row_number() == n()) %>%
          summarise(
            y = diff(centroid_y_rotated),
            x = diff(centroid_x_rotated)),
        by = c("track_id"))
    
    # go through all tracks and vary position
    for (i in bootTracksInfo[uID == x]$track_id) {
      bootX <- runif(n=1, min=0, max=sizeX)
      bootY <- runif(n=1, min=0, max=sizeY)
      
      bootTracksInfo[uID == x & track_id == i, centroid_y_tile := round(bootY/aRad) * aRad]
      bootTracksInfo[uID == x & track_id == i, centroid_x_tile := round(bootX/aRad) * aRad]
    }
    
    coordMapping <- (bootTracksInfo[uID == x] %>%
      left_join(coords$fibres[[x]]$coords %>% tibble::rownames_to_column(),
                by = c("centroid_y_tile" = "y", "centroid_x_tile" = "x")))
  
    matA <- matrix(c(
      coords$fibres[[x]]$u[as.integer(coordMapping$rowname)],
      coords$fibres[[x]]$v[as.integer(coordMapping$rowname)]
    ), ncol = 2)
    
    matA_rot <- matrix(c(
      coords$fibres[[x]]$u[as.integer(coordMapping_rot$rowname)],
      coords$fibres[[x]]$v[as.integer(coordMapping_rot$rowname)]
    ), ncol = 2)
    
    # varied angles
    matB_rot <- matrix(c(
      coordMapping_rot$x,
      coordMapping_rot$y
    ), ncol = 2)
    
    matAngles <- c()
    matAniso <-  c()
    for (i in seq(nrow(matA))) {
      matAngles <- c(matAngles, matlib::angle(as.vector(matA_rot[i, ]), as.vector(matB_rot[i, ]))[1])
      matAniso <- c(matAniso, norm(matA[i, ], type = "2"))
    }
    
    coordMapping$angle <- matAngles
    coordMapping$aniso <- matAniso
    coordMapping <- as.data.table(coordMapping)
    
    # difference cannot be more than 90 DEG
    coordMapping[angle > 90, angle := 180 - angle]
    
    coordMapping$uID <- x
    coordMapping$bootID <- bootID
    
    mappingsList[[bootID]] <- coordMapping
  }
  
  mappingsList
}

# now .. can you also shuffle points and angles?
coordMappingsList <- list()
bootIterations <- 1000
bootTracksInfo <- copy(tracksInfo)
uIDs <- unique(bootTracksInfo$uID)

coordMappingsList <- parallel::mclapply(
# coordMappingsList <- lapply(
  cciaObj$cciaObjects(uIDs = uIDs),
  function(x) {
    message(sprintf("[run sim] >> %s", x$getUID()))
    runSim(x)
  }, mc.cores = parallel::detectCores() - 2
  # }
)

coordMappingsBoot <- rbindlist(lapply(coordMappingsList, function(x) rbindlist(x)))
```

```{r}
# now bind observation and simulation
coordMappings$type <- "obs"
coordMappings$bootID <- 0
coordMappingsBoot$type <- "rand"

coordMappingsTotal <- as.data.table(
  rbindlist(list(coordMappings, coordMappingsBoot), use.names = TRUE, fill = TRUE) %>%
    left_join(exp.info[, c("uID", "Region")]))
```

```{r}
sigValue <- 0.05
pValues <- list()

colnames(coordMappingsTotal)

# now .. can you test for significance for each simulation?
# for(xID in unique(coordMappingsTotal$uID)) {
for(xRegion in unique(coordMappingsTotal$Region)) {
  # print(paste(">>", xID))
  print(paste(">>", xRegion))
  
  # count number of significant differences
  xRes <- sapply(seq(bootIterations), function(i) {
    t.test(
      # coordMappingsTotal[uID == xID & bootID == 0]$angle,
      # coordMappingsTotal[uID == xID & bootID == i]$angle,
      coordMappingsTotal[Region == xRegion & bootID == 0]$angle,
      coordMappingsTotal[Region == xRegion & bootID == i]$angle,
      na.action = na.omit
    )$p.value < sigValue
    })
  
  # pValues[[xID]] <- (bootIterations - sum(xRes, na.rm = TRUE))/bootIterations
  pValues[[xRegion]] <- (bootIterations - sum(xRes, na.rm = TRUE))/bootIterations
}

pValues
```


```{r fig_angles, fig.height=8, fig.width=8}
# now plot out
# datToPlot <- coordMappingsTotal %>%
#   group_by(uID, type, bootID) %>%
#   summarise(mean = mean(angle, na.rm = TRUE)) %>%
#   left_join(exp.info)

# ggplot(datToPlot, aes(Region, mean, color = type)) +
ggplot(coordMappings %>% left_join(exp.info) %>% dplyr::filter(aniso > 0), aes(Region, angle)) +
# ggplot(coordMappingsTotal %>% left_join(exp.info) %>% dplyr::filter(aniso > 0), aes(type, angle)) +
  theme_classic() +
  # geom_boxplot(outlier.alpha = 1) +
  geom_violin(scale = "width") +
  geom_jitter(width = 0.2) +
  # geom_jitter(position = position_jitterdodge(jitter.width = 0.20), alpha = 0.1) +
  # stat_summary(fun=mean, geom="point", size=8, shape=18, color="black")
  stat_summary(fun=mean, geom="point", size=8, shape=18, color="red")
  # ylim(0, 100) +
  # facet_grid(.~Region)

ggsave(file.path(anaDir, "track_alignment.png"), height = 3, width = 3)
# ggsave(file.path(anaDir, "track_alignment_boot.png"), height = 3, width = 4)

# save as CSV
write.csv(coordMappings %>% left_join(exp.info), file.path(anaDir, "track_alignment.csv"))
```

```{r fig_angles, fig.height=8, fig.width=8}
datToPlot <- coordMappingsTotal[type == "obs"] %>% left_join(coordMappingsTotal[type == "rand"] %>%
  group_by(uID) %>%
  summarise(mean.angle = mean(angle, na.rm = TRUE))) %>%
  mutate(angle.norm = angle/mean.angle) %>%
  dplyr::filter(aniso > 0)

ggplot(datToPlot %>% left_join(exp.info), aes(Region, angle.norm)) +
  theme_classic() +
  # geom_boxplot(outlier.alpha = 1) +
  geom_violin(scale = "width") +
  geom_jitter(width = 0.2) +
  # geom_jitter(position = position_jitterdodge(jitter.width = 0.20), alpha = 0.1) +
  stat_summary(fun=mean, geom="point", size=4, shape=18, color="red") +
  ylim(0, 8) + geom_hline(yintercept = 1)

# ggsave(file.path(anaDir, "track_alignment.png"), height = 3, width = 3)
ggsave(file.path(anaDir, "track_alignment_boot_norm.png"), height = 4, width = 4)

# save as CSV
write.csv(datToPlot %>% left_join(exp.info), file.path(anaDir, "track_alignment_norm.csv"))
```

```{r fig_aniso, fig.height=8, fig.width=8}
# now plot out
# datToPlot <- coordMappingsTotal %>%
#   group_by(uID, type, bootID) %>%
#   summarise(mean = mean(angle, na.rm = TRUE)) %>%
#   left_join(exp.info)

# ggplot(datToPlot, aes(Region, mean, color = type)) +
ggplot(coordMappings %>% left_join(exp.info) %>% dplyr::filter(aniso > 0), aes(type, aniso)) +
# ggplot(coordMappingsTotal %>% left_join(exp.info) %>% dplyr::filter(aniso > 0), aes(type, aniso)) +
  theme_classic() +
  # geom_boxplot(outlier.alpha = 1) +
  geom_violin(scale = "width") +
  geom_jitter(width = 0.2) +
  # geom_jitter(position = position_jitterdodge(jitter.width = 0.20), alpha = 0.1) +
  # stat_summary(fun=mean, geom="point", size=8, shape=18, color="black") +
  stat_summary(fun=mean, geom="point", size=8, shape=18, color="red") +
  # ylim(0, 100) +
  facet_grid(.~Region)

ggsave(file.path(anaDir, "track_aniso.png"), height = 3, width = 3)
# ggsave(file.path(anaDir, "track_aniso_boot.png"), height = 3, width = 4)
```

```{r fig_aniso, fig.height=8, fig.width=8}
datToPlot <- coordMappingsTotal[type == "obs"] %>% left_join(coordMappingsTotal[type == "rand"] %>%
  group_by(uID) %>%
  summarise(mean.aniso = mean(aniso, na.rm = TRUE))) %>%
  mutate(aniso.norm = aniso/mean.aniso) %>%
  dplyr::filter(aniso > 0)

ggplot(datToPlot %>% left_join(exp.info), aes(Region, aniso.norm)) +
  theme_classic() +
  # geom_boxplot(outlier.alpha = 1) +
  geom_violin(scale = "width") +
  geom_jitter(width = 0.2) +
  # geom_jitter(position = position_jitterdodge(jitter.width = 0.20), alpha = 0.1) +
  stat_summary(fun=mean, geom="point", size=4, shape=18, color="red") +
  ylim(0, 10) + geom_hline(yintercept = 1)

ggsave(file.path(anaDir, "track_aniso_boot_norm.png"), height = 6, width = 4)

# save as CSV
write.csv(datToPlot %>% left_join(exp.info), file.path(anaDir, "track_aniso_norm.csv"))
```

```{r fig_aniso, fig.height=4, fig.width=12}
# plot vessel measurements for each type
vesselMeasures <- colnames(exp.info)[!colnames(exp.info) %in% c("uID", "Patient", "Region")]

write.csv(exp.info, file.path(anaDir, "fibres.csv"))

datToPlot <- exp.info %>%
  pivot_longer(cols = vesselMeasures,
               names_to = "measure", values_to = "value")

ggplot(datToPlot, aes(Region, value)) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(width = 0.2) +
  # geom_jitter(position = position_jitterdodge(jitter.width = 0.10)) +
  facet_wrap(.~measure, scales = "free", nrow = 2) +
  theme(legend.position = "bottom") +
  scale_color_brewer(palette = "Set1")
  # scale_color_manual(values = c("#327EBA", "#AA1F5E"))

ggsave(file.path(anaDir, "fibres.pdf"), height = 4, width = 12)
```

```{r fig_flows, fig.height=10, fig.width=10}
for (x in cciaObj$cciaObjects()) {
  p1 <- ggplot(popDT[uID == x$getUID()]) + 
    # scale_color_brewer(palette = "Set1") +
    theme_classic() +
    plotThemeDark() +
    coord_fixed() +
    xlim(0, x$omeXMLPixels()$SizeX) +
    ylim(x$omeXMLPixels()$SizeY, 0) +
    theme(
      axis.text.x = element_blank(),
      axis.ticks.x = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank(),
      axis.line = element_blank(),
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      legend.position = "none"
    ) 
  
  xCoords <- coords$IJ.manual.tracks[[x$getUID()]]
  yCoords <- coords$fibres[[x$getUID()]]
  
  # if (all(c(!is.null(xCoords), !is.null(yCoords))))
  if (all(c(!is.null(yCoords))))
    p1 <- p1 + 
      # geom_path(aes(centroid_x, centroid_y, group = track_id, colour = as.factor(track_id)),
      geom_path(aes(centroid_x, centroid_y, group = track_id),
        # color = "#AA1F5E", linewidth = 1, alpha = 1) +
        color = "white", linewidth = 1, alpha = 1) +
        # linewidth = 2, alpha = 1) +
      geom_segment(
        data = branchDT[uID == x$getUID() & pop == "fibres.branch"],
        aes(x = `coord-src-1`, y = `coord-src-0`,
            xend = `coord-dst-1`, yend = `coord-dst-0`),
        # color = "#ebd441", linewidth = 1, alpha = 1) +
        color = "#AA1F5E", linewidth = 1, alpha = 1) +
      ggquiver::geom_quiver(
        data = yCoords$coords, aes(x = x, y = y, u = -yCoords$u, v = yCoords$v), color = "#4682b4") 
      # ggquiver::geom_quiver(
      #   data = xCoords$coords, aes(x = x, y = y, u = -xCoords$u, v = xCoords$v), color = "white")
  
  y <- exp.info[uID == x$getUID()]
  
  ggsave(file.path(anaDir, "flows", paste0(y$Patient, "-", y$Region, "-", x$getUID(), ".pdf")), plot = p1, height = 8, width = 8)
}

# ggsave(file.path(anaDir, "flows", paste0("flow-tracks-", cciaObj$getUID(), ".pdf")), height = 8, width = 8)
```

```{r}
# get angles relative to T cells and structures
tracks.i <- "IJ.manual.tracks"
vecDiffs <- list()

for (i in names(coords)[names(coords) != tracks.i]) {
  vecDiffs[[i]] <- list()
  x <- coords[[i]]
    
  for (j in names(x)) {
    if (!is.null(coords[[tracks.i]][[j]]) > 0) {
      for (k in seq(length(x[[j]]$u))) {
        matA <- matrix(c(coords[[tracks.i]][[j]]$u[[k]], coords[[tracks.i]][[j]]$v[[k]]), nrow = 2)
        matB <- matrix(c(x[[j]]$u[[k]], x[[j]]$v[[k]]), nrow = 2)
        vecDiffs[[i]][[j]] <- c(vecDiffs[[i]][[j]], 180 - matlib::angle(as.vector(matA), as.vector(matB)))
      }
    }
  }
}
```

```{r}
# plot correlation between fibres and tracks
# https://stackoverflow.com/a/39923381
structNames <- names(coords)[names(coords) != tracks.i]

# go through images
for (x in cciaObj$cciaObjects(uIDs = names(vecDiffs$fibres))) {
  i <- x$getUID()
  
  diffsDT <- as.data.table(cbind(coords$fibres[[i]]$coords, vecDiffs$fibres[[i]]))
  diffsDT[is.na(diffsDT), ] <- 0 
  setnames(diffsDT, "vecDiffs$fibres[[i]]", "fibres")
  diffsDT[, max := colnames(.SD)[max.col(.SD, ties.method = "first")], .SDcols = structNames]
  diffsDT[fibres == 0, max := NA]
  
  p1 <- ggplot(diffsDT, aes(x, y)) +
    theme_classic() +
    plotThemeDark() +
    coord_fixed() +
    xlim(-10, x$omeXMLPixels()$SizeX + 10) +
    ylim(x$omeXMLPixels()$SizeY + 10, -10) +
    theme(
      axis.text.x = element_blank(),
      axis.ticks.x = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank(),
      axis.line = element_blank(),
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      legend.position = "none"
    )
  
  for (j in structNames) {
     p2 <- p1 + geom_tile(aes(fill = get(j)), colour = "black", size = 0.5) +
      # viridis::scale_fill_viridis(
      #   breaks = c(0, 180), labels = c(0, 180), na.value = "black") +
      scale_fill_gradient2(low="blue", high="red", mid = "white", midpoint = 90) +
      ggquiver::geom_quiver(
        data = coords$IJ.manual.tracks[[i]]$coords, aes(
          x = x, y = y, u = -coords$IJ.manual.tracks[[i]]$u, v = coords$IJ.manual.tracks[[i]]$v),
        color = "white", size = 1)
    
    ggsave(file.path(anaDir, "angle-diff", paste0("angle-", j, "-", x$getUID(), ".pdf")),
         height = 10, width = 10, plot = p2)
  }
}
```


```{r}
# create data.table with properties
tracks.table[
  tracks.measure.fun(
    tracks, celltrackR::speed, "cell_speed",
    steps.subtracks = 1, idcol = "uID"),
  on = .(uID, track_id, cell_id),
  cell_speed := .(cell_speed)]

tracks.table[
  tracks.measure.fun(
    tracks, celltrackR::overallAngle, "cell_angle",
    steps.subtracks = 2, idcol = "uID"),
  on = .(uID, track_id, cell_id),
  # cell_angle := .(pracma::rad2deg(cell_angle))]
  cell_angle := .(cell_angle)]
```

```{r}
# get average direction and velocity for cells
gridWindow <- 40
shiftCols <- c("X", "Y")
shiftColsNames <- paste("lag", shiftCols, sep = ".")

# https://stackoverflow.com/a/24747155
euc.dist <- function(x1, x2) sqrt(sum((x1 - x2) ^ 2))

# get average vector fields
tracks.table[, centroid_region := as.numeric(NA)]

# get mean orientation
# https://stackoverflow.com/a/26292059
tracks.table[, (shiftColsNames) := shift(.SD), by = .(uID, track_id), .SDcols = shiftCols]
tracks.table[, `:=` (
  delta_X = X - lag.X,
  delta_Y = Y - lag.Y
  )] 

# get distances
tracks.table[, centroid_dist := euc.dist(c(X, Y), c(lag.X, lag.Y)), 
             by = 1:nrow(tracks.table)]

for (x in cciaObj$cciaObjects()) {
  i <- x$getUID()
  
  tracksSpots <- expand.grid(
    seq(0, x$omeXMLPixels()$SizeX, gridWindow),
    seq(0, x$omeXMLPixels()$SizeY, gridWindow)
  )
  colnames(tracksSpots) <- c("X", "Y")
  
  # get closest spots
  tracks.table[uID == i, centroid_region := dbscan::kNN(
    as.matrix(tracksSpots), k = 1, query = as.matrix(tracks.table[uID == i, c("X", "Y")]))$id]
}
```

```{r}
# get average direction of cell
tracks.summary <- as.data.table(tracks.table %>%
  group_by(uID, track_id) %>%
  summarise(
    # mean_x = mean(X, na.rm = TRUE),
    # mean_y = mean(Y, na.rm = TRUE),
    start_x = head(X, n = 1),
    start_y = head(Y, n = 1),
    mean_angle = sum(cell_angle, na.rm = TRUE),
    # mean_angle = mean(cell_angle, na.rm = TRUE),
    # mean_speed = mean(cell_speed, na.rm = TRUE),
    displacement = euc.dist(
      c(head(X, n = 1), head(Y, n = 1)), c(tail(X, n = 1), tail(Y, n = 1)))
  ))

# get direction vectors
# tracks.summary[, c("start_x", "start_y") := as.list(
#   dagR::anglePoint(c(mean_x, mean_y), mean_angle, (displacement/2))), by = 1:nrow(tracks.summary)]
tracks.summary[, c("end_x", "end_y") := as.list(
  # dagR::anglePoint(c(mean_x, mean_y), mean_angle, (displacement/2))), by = 1:nrow(tracks.summary)]
  dagR::anglePoint(c(start_x, start_y), mean_angle, (displacement/2))), by = 1:nrow(tracks.summary)]

# get u and v
tracks.summary[, `:=` (u = start_x - end_x, v = start_y - end_y)]
```


```{r fig_track_aniso, fig.height=6, fig.width=14}
# plot quiver for each sample
# for (i in names(labels)) {
for (i in c("2TIPuT")) {
  local({
    local_i <- i
    x <- labels[[local_i]]
    
    # get coords
    coords <- data.frame(
      y = as.vector(x$ilee_coor_list[1,,,1]),
      x = as.vector(x$ilee_coor_list[1,,,2])
    )
    u <- as.vector(x$ilee_eigval[1,,,2]) * as.vector(x$ilee_eigvec[1,,,2,1])
    v <- as.vector(x$ilee_eigval[1,,,1]) * as.vector(x$ilee_eigvec[1,,,1,1])
    
    # get tracks grid
    # tracksGrid <- tracks.table[uID == local_i] %>%
    #   group_by(centroid_region) %>%
    #   summarise(
    #     x = median(X, na.rm = TRUE),
    #     y = median(Y, na.rm = TRUE),
    #     velocity = median(centroid_dist, na.rm = TRUE),
    #     u = log(velocity) * median(delta_X, na.rm = TRUE),
    #     v = log(velocity) * median(delta_Y, na.rm = TRUE),
    #     # u = median(delta_X, na.rm = TRUE),
    #     # v = median(delta_Y, na.rm = TRUE),
    #   )
    
    p1 <- ggplot(branchDT[uID == local_i]) + 
      ggquiver::geom_quiver(
        data = coords, aes(x = x, y = y, u = -u, v = v), color = "white") +
      # scale_color_brewer(palette = "Set1") +
      theme_classic() +
      plotThemeDark() +
      coord_fixed() +
      xlim(0, cciaObj$cciaObjectByUID(local_i)[[1]]$omeXMLPixels()$SizeX) +
      ylim(cciaObj$cciaObjectByUID(local_i)[[1]]$omeXMLPixels()$SizeY, 0) +
      theme(
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.line = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.position = "none"
      ) +
      geom_segment(aes(
        x = `coord-src-1`, y = `coord-src-0`,
        xend = `coord-dst-1`, yend = `coord-dst-0`),
        # color = as.factor(`branch-type`)),
        color = "#4682b4") +
      # ggquiver::geom_quiver(
      #   data = tracksGrid, aes(x = x, y = y, u = -u, v = v),
      #   color = "yellow", linewidth = 0.5)
      ggquiver::geom_quiver(
        # data = tracks.summary[uID == local_i], aes(x = mean_x, y = mean_y, u = -u, v = v),
        data = tracks.summary[uID == local_i], aes(x = start_x, y = start_y, u = u, v = v),
        color = "yellow", linewidth = 0.5)
      # geom_path(
      #   data = tracks.table[uID == i], aes(X, Y, group = track_id),
      #   color = "#ebd441")
    
    fileID <- paste(as.list(exp.info[uID == local_i, c("Patient", "Type")]), collapse = "-")
    fileID <- paste0(fileID, "-", local_i)
    
    ggsave(file.path(anaDir, "samples", paste0(fileID, "_orientation.pdf")), height = 5, width = 5)
    # ggsave(file.path(anaDir, "samples", paste0(fileID, "_tracks.pdf")), height = 5, width = 5)
  })
}
```

```{r fig_tracks, fig.height=6, fig.width=14}
# then plot track measurements for inf and whorl
datToPlot <- tracksMeasures %>%
  # pivot_longer(cols = c(measures, "mean.aniso.box"),
  pivot_longer(cols = measures,
               names_to = "measure", values_to = "value") %>%
  left_join(exp.info)

write.csv(tracksMeasures %>%
            left_join(exp.info[, c("uID", "Patient", "Type", "Group")]),
          file.path(anaDir, "tracks_summary.csv"))

ggplot(datToPlot, aes(Type, value, color = Group)) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  # geom_jitter(width = 0.2) +
  geom_jitter(position = position_jitterdodge(jitter.width = 0.10)) +
  facet_wrap(.~measure, scales = "free", nrow = 2) +
  theme(legend.position = "bottom") +
  scale_color_brewer(palette = "Set1")

ggsave(file.path(anaDir, "tracks_summary.pdf"), height = 4, width = 14)
```


```{r fig_track_aniso, fig.height=5, fig.width=24}
# plot all combinations of measurements with anisotropy
datToPlot <- tracksMeasures %>%
  # pivot_longer(cols = c(measures, "mean.aniso.box"),
  pivot_longer(cols = measures,
               names_to = "measure", values_to = "value") %>%
  left_join(exp.info)

# ggplot(datToPlot, aes(mean.aniso.box, value, color = uID)) +
# ggplot(datToPlot, aes(weighted.aniso.box, value, color = Type)) +
# ggplot(datToPlot, aes(mean.aniso.box, value)) +
ggplot(datToPlot, aes(weighted.aniso.box, value)) +
  theme_classic() +
  # geom_point(shape = 1, stroke = 1, alpha = 0.5) +
  geom_point() +
  geom_smooth(method = "lm") +
  facet_wrap(.~measure, ncol = 10, scales = "free_y") +
  # facet_wrap(Type~measure, ncol = 10, scales = "free_y") +
  xlab("Close to anisotropy with % of") +
  # scale_color_brewer(palette = "Set1") +
  scale_color_manual(values = c("#327EBA", "#AA1F5E")) +
  expand_limits(x = 0, y = 0) +
  # xlim(0, 50) +
  theme(
    legend.title = element_blank(),
    legend.position = "bottom",
    legend.justification = "left"
  ) 

ggsave(file.path(anaDir, "track_aniso.pdf"), height = 4, width = 32)
```

