---
title: "Behaviour GCAMP"
output: html_document
date: '2022-08-15'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Show transition states of live cell imaging

```{r}
devtools::load_all("../")
cciaUse("~/cecelia/dev")

library(ggplot2)
library(tidyverse)
```

```{r}
# set test variables
pID <- "8BR53W"
versionID <- 1
# projectsDir <- "/Volumes/Analysis_SSD/Dominik/cecelia/projects/"
projectsDir <- "/Volumes/USER_data/Dominik/CECELIA_BACKUP/"
hpcDir <- "/data/scratch/projects/punim1124/cecelia/USERS/schienstockd/"
```

```{r}
# anaDir <- "/Volumes/USER_data/Dominik/Experiments/DS_N030/ANALYSIS/IMAGE/clustering/skip3/"
anaDir <- "/Volumes/USER_data/Dominik/Experiments/DS_N030/ANALYSIS/IMAGE/clustering/transitions/"
```

```{r}
# GCAMP detection
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "BeddcR", versionID = versionID, initReactivity = FALSE #  GCAMP
  # pID = pID, uID = "n8W6bT", versionID = versionID, initReactivity = FALSE #  GCAMP
  # pID = pID, uID = "tseI8L", versionID = versionID, initReactivity = FALSE #  GCAMP
  # pID = pID, uID = "RH7IVY", versionID = versionID, initReactivity = FALSE #  GCAMP
)

# get experimental info
exp.info <- as.data.table(cciaObj$summary(
  withSelf = FALSE, fields = c("Attr")
))

# GCAMP
uIDs <- exp.info[Focus == "non-clustering" & Cells == "gBT_TRITC" & Include == "Y"]$uID
# uIDs <- exp.info[Focus == "non-clustering" & Cells == "gBT_OTI"]$uID

for (x in cciaObj$cciaObjects(uIDs = uIDs)) {
  x$setImChannelNames(c("AF", "TRITC", "GCAMP", "gBT-CTV"))
  x$saveState()
}
```

```{r}
# GCAMP detection
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  # pID = pID, uID = "BeddcR", versionID = versionID, initReactivity = FALSE #  GCAMP
  pID = pID, uID = "n8W6bT", versionID = versionID, initReactivity = FALSE #  GCAMP
)

# # get experimental info
# exp.info <- as.data.table(cciaObj$summary(
#   withSelf = FALSE, fields = c("Attr")
# ))
# 
# # GCAMP
# uIDs <- exp.info[Focus == "non-clustering" & Cells == "gBT_TRITC" & Include == "Y"]$uID
# 
# for (x in cciaObj$cciaObjects(uIDs = uIDs)) {
#   x$setImChannelNames(c("AF", "TRITC", "GCAMP", "gBT-CTV"))
#   x$saveState()
# }

colnames(cciaObj$popDT("live", pops = "tcells.gBT/tracked", includeFiltered = TRUE))
```

```{r}
# GCAMP detection
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "BeddcR", versionID = versionID, initReactivity = FALSE #  GCAMP
  # pID = pID, uID = "n8W6bT", versionID = versionID, initReactivity = FALSE #  GCAMP
  # pID = pID, uID = "tseI8L", versionID = versionID, initReactivity = FALSE #  GCAMP
  # pID = pID, uID = "RH7IVY", versionID = versionID, initReactivity = FALSE #  GCAMP
)

# get experimental info
exp.info <- as.data.table(cciaObj$summary(
  withSelf = FALSE, fields = c("Attr")
))

# GCAMP
uIDs <- exp.info[Focus == "non-clustering" & Cells == "gBT_TRITC" & Include == "Y"]$uID
# uIDs <- exp.info[Focus == "non-clustering" & Cells == "gBT_OTI" & Include == "Y"]$uID

# upload local files
funParams <- list(
  popType = "live",
  pops = c(
    "tcells.gBT/tracked"
    # "tcells.OTI/tracked"
    ),
  signalName = "GCAMP",
  channelSignal = "GCAMP",
  # channelDivision = "TRITC",
  channelDivision = "Sliding GCAMP",
  # channelDivision = "gBT-CTDR",
  # channelDivision = "OTI-CTV",
  normOrder = 5,
  peakThreshold = 1.5,
  minPeaks = 2,
  # sumContactWith = c("dcs.TRITC/tracked"),
  sumContactWith = c(""),
  # channelSubtract = "TRITC",
  channelSubtract = "",
  # channelSubtract = "AF",
  channelSubtractPercentile = 95
)

cciaObj$runTasks(
# cciaObj$runTask(
  funName = "signalAnalysis.findSignalPeaks",
  funParams = funParams,
  uIDs = uIDs,
  runInplace = TRUE,
  mc.cores = 3
)
```

```{r}
# HMM
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "BeddcR", versionID = versionID, initReactivity = FALSE #  GCAMP
)

# get experimental info
exp.info <- as.data.table(cciaObj$summary(
  withSelf = FALSE, fields = c("Attr")
))

# GCAMP
uIDs <- exp.info[Focus == "non-clustering" & Cells == "gBT_TRITC" & Include == "Y"]$uID
# uIDs <- exp.info[Focus == "non-clustering"]$uID

# run task
funParams <- list(
  popType = "live",
  # pops = c("tcells.gBT/tracked", "tcells.OTI/tracked"),
  pops = c("tcells.gBT/tracked"),
  # modelMeasurements = c("GCAMP"),
  # modelMeasurements = c("live.cell.peak.norm.GCAMP", "live.cell.peak.ratio.GCAMP"),
  # modelMeasurements = c("live.cell.peak.ratio.GCAMP"),
  modelMeasurements = c("live.cell.peak.norm.GCAMP"),
  colName = "gcamp",
  appendStates = list(),
  skipTimesteps = 0,
  subtrackOverlap = TRUE,
  # noiseFilterMeasurements = 5,
  noiseFilterMeasurements = 0,
  postFiltering = 0,
  postIterations = 0,
  numStates = 2,
  uIDs = uIDs
)

# run task
task <- cciaObj$runTask(
  funName = "behaviourAnalysis.hmmStates",
  funParams = funParams,
  env = "local",
  runInplace = TRUE,
  taskID = 1
)
```

```{r}
# HMM
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "BeddcR", versionID = versionID, initReactivity = FALSE #  GCAMP
)

# get experimental info
exp.info <- as.data.table(cciaObj$summary(
  withSelf = FALSE, fields = c("Attr")
))

# GCAMP
uIDs <- exp.info[Focus == "non-clustering" & Cells == "gBT_TRITC" & Include == "Y"]$uID
# uIDs <- exp.info[Focus == "non-clustering"]$uID

# run task
funParams <- list(
  popType = "live",
  # pops = c("tcells.gBT/tracked", "tcells.OTI/tracked"),
  pops = c("tcells.gBT/tracked"),
  modelMeasurements = c("live.cell.speed", "live.cell.angle"),
  # scaleMeasurements = c("live.cell.speed", "live.cell.angle"),
  scaleMeasurements = c(),
  # modelMeasurements = c(
  #   "surface_area", "volume", "extent", "solidity",
  #   "ellipticity_interm_oblate", "ellipticity_interm_prolate",
  #   "compactness", "sphericity"
  # ),
  colName = "movement",
  # colName = "shape",
  # appendStates = list(live.cell.is.clust = TRUE),
  appendStates = list(),
  skipTimesteps = 2,
  # skipTimesteps = 0,
  subtrackOverlap = TRUE,
  noiseFilterMeasurements = 5,
  postFiltering = 2,
  postIterations = 2,
  # postFiltering = 0,
  # postIterations = 0,
  numStates = 3, # movement with injection
  # numStates = 3, # shape
  uIDs = uIDs
)

# run task
task <- cciaObj$runTask(
  funName = "behaviourAnalysis.hmmStates",
  funParams = funParams,
  env = "local",
  runInplace = TRUE,
  taskID = 1
)
```

```{r}
# get HMM transitions
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "BeddcR", versionID = versionID, initReactivity = FALSE #  GCAMP
)

# get experimental info
exp.info <- as.data.table(cciaObj$summary(
  withSelf = FALSE, fields = c("Attr")
))

# GCAMP
uIDs <- exp.info[Focus == "non-clustering" & Cells == "gBT_TRITC" & Include == "Y"]$uID
# uIDs <- exp.info[Focus == "non-clustering"]$uID

# run task
funParams <- list(
  popType = "live",
  # pops = c("tcells.gBT/tracked", "tcells.OTI/tracked"),
  pops = c("tcells.gBT/tracked"),
  # colName = "movement",
  # hmmStates = c("movement"),
  colName = "gcamp",
  hmmStates = c("gcamp"),
  # colName = "shape",
  # hmmStates = c("shape"),
  includeStart = FALSE,
  includeSelfTransitions = TRUE,
  uIDs = uIDs
)

# run task
task <- cciaObj$runTask(
  funName = "behaviourAnalysis.hmmTransitions",
  funParams = funParams,
  env = "local",
  runInplace = TRUE,
  taskID = 1
)
```

```{r}
# cluster tracks based on transitions
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "BeddcR", versionID = versionID, initReactivity = FALSE #  GCAMP
)

# get experimental info
exp.info <- as.data.table(cciaObj$summary(
  withSelf = FALSE, fields = c("Attr")
))

# GCAMP
uIDs <- exp.info[Focus == "non-clustering" & Cells == "gBT_TRITC" & Include == "Y"]$uID
# uIDs <- exp.info[Focus == "non-clustering"]$uID

# run task
funParams <- list(
  popType = "live",
  # popsToCluster = c("tcells.gBT/tracked", "tcells.OTI/tracked"),
  popsToCluster = c("tcells.gBT/tracked"),
  valueName = "tracks.clusters.tcells.hmm_transitions_movement",
  clusterColName = "hmm_transitions_movement",
  # valueName = "tracks.clusters.tcells.hmm_transitions_movement_all",
  # clusterColName = "hmm_transitions_movement_all",
  # valueName = "tracks.clusters.tcells.hmm_movement",
  # clusterColName = "hmm_movement",
  # resolution = 0.4,
  # percentile = 99.5,
  resolution = 0.3,
  percentile = 99.9,
  trackMeasures = c(
    "speed",
    "duration",
    "trackLength",
    "meanTurningAngle",
    "displacement",
    "straightness",
    "displacementRatio",
    "outreachRatio",
    "asphericity",
    "overallAngle"
  ),
  objectMeasures = c(
    # "extent",
    # "solidity",
    # "integral_mean_curvature",
    # "ellipticity_oblate",
    # "ellipticity_prolate",
    # "ellipticity_interm_oblate",
    # "ellipticity_interm_prolate",
    # "sphericity",
    # HMM states
    "live.cell.hmm.state.gcamp",
    # "live.cell.hmm.transitions.gcamp",
    "live.cell.hmm.state.movement",
    "live.cell.hmm.transitions.movement"
    # "live.cell.hmm.state.shape",
    # "live.cell.peak.ratio.GCAMP",
    # "live.cell.hmm.transitions.shape"
    ),
  diffMeasures = list("live.cell.hmm.state.gcamp"),
  nMeasures = c(),
  sumMeasures = c(),
  calcMeasures = list(),
  addPops = c(),
  calcLabelProps = TRUE,
  # usePaga = FALSE,
  usePaga = TRUE,
  pagaThreshold = 0.1,
  # minTracklength = 6,
  minTracklength = 6,
  # minTracklength = 50,
  uIDs = uIDs
)

# run task
task <- cciaObj$runTask(
  funName = "behaviourAnalysis.clusterTracks",
  funParams = funParams,
  env = "local",
  runInplace = TRUE,
  taskID = 1
)
```

```{r}
# cluster tracks based on transitions
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "BeddcR", versionID = versionID, initReactivity = FALSE #  GCAMP
)

# get experimental info
exp.info <- as.data.table(cciaObj$summary(
  withSelf = FALSE, fields = c("Attr")
))

# GCAMP
uIDs <- exp.info[Focus == "non-clustering" & Cells == "gBT_TRITC"]$uID
# uIDs <- exp.info[Focus == "non-clustering"]$uID

# run task
funParams <- list(
  popType = "live",
  valueName = "tracks.clusters.tcells.hmm_transitions_movement",
  # valueName = "tracks.clusters.tcells.hmm_movement",
  initRoot = "5"
)

# run task
task <- cciaObj$runTask(
  funName = "behaviourAnalysis.createPseudotime",
  funParams = funParams,
  env = "local",
  runInplace = TRUE,
  taskID = 1
)
```

```{r}
# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "BeddcR", versionID = versionID, initReactivity = FALSE #  GCAMP
)

# get experimental info
exp.info <- as.data.table(cciaObj$summary(
  withSelf = FALSE, fields = c("Attr")
))

# GCAMP
uIDs <- exp.info[Focus == "non-clustering" & Cells == "gBT_TRITC" & Include == "Y"]$uID
# uIDs <- exp.info[Focus == "non-clustering"]$uID

# get clustering
tcells.sc <- as.data.table(cciaEnv()$LabelPropsUtils(
  cciaObj$persistentObjectDirectory(),
  # value_name = "tracks.clusters.tcells.skip3.sc")$label_props_view()$as_df())
  value_name = "tracks.clusters.tcells.hmm_transitions_movement.sc")$label_props_view()$as_df())
  # value_name = "tracks.clusters.tcells.hmm_movement.sc")$label_props_view()$as_df())

# get popDTs for set
popDTs <- cciaObj$popDT(
  popType = "live", pops = c(
    "tcells.gBT/tracked"
    # "tcells.OTI/tracked"
    ),
  includeFiltered = TRUE,
  flushCache = TRUE,
  uIDs = uIDs)
```

```{r fig_GCAMP_hmm, fig.height=3, fig.width=10}
ggplot(
  popDTs[uID == "n8W6bT" & track_id == 156, ],
  aes(x = (centroid_t))) +
  geom_line(aes(y = live.cell.peak.norm.GCAMP), colour = "black") +
  # geom_line(aes(y = live.cell.peak.norm.GCAMP * 100), colour = "#03B8FF") +
  # geom_line(aes(y = live.cell.peak.ratio.GCAMP * 40), colour = "magenta") +
  scale_y_continuous(
    name = "Speed (um)",
    sec.axis = sec_axis(~ . / 100, name = "GCAMP/CTV")) +
  theme_classic() +
  xlab("Time (min)") +
  # ylim(0, 3) +
  theme(strip.text.y = element_text(size = 6))
```


```{r}
# tracks.info.gBT <- cciaObj$tracksInfo(
#   c("live.cell.hmm.state.gcamp"),
#   parentPop = "tcells.gBT/tracked",
#   uIDs = uIDs, replaceNA = FALSE
# )
```

```{r fig_psuedotime, fig.height=3, fig.width=5}
datToPlot <- tcells.sc %>%
  left_join(tracks.info.gBT) %>%
  left_join(exp.info) 
  # dplyr::filter(clusters == 3)

datToPlot$peaks <- "Background"
datToPlot[datToPlot$live.cell.hmm.state.gcamp.2.n > 0, ]$peaks <- "1"
datToPlot[datToPlot$live.cell.hmm.state.gcamp.2.n > 1, ]$peaks <- ">= 2"
datToPlot[datToPlot$live.cell.hmm.state.gcamp.2.n > 2, ]$peaks <- ">= 3"

ggplot(
  datToPlot %>%
    group_by(Treatment, DTx, peaks) %>%
    summarise(n = n()) %>%
    mutate(freq = n/sum(n)),
  aes(x = 1, y = freq, fill = as.factor(peaks))) +
  scale_fill_brewer(name = NULL, palette = "Set1") +
  theme_classic() +
  # geom_bar(stat = "identity", width = 1) +
  geom_col() +
  coord_polar("y", start = 0) +
  facet_wrap(.~interaction(Treatment, DTx), nrow = 1) +
  xlim(0, 1.5) +
  theme(
    axis.text = element_text(size = 15),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    legend.position = "bottom",
    # legend.position = "none",
    legend.title = element_blank(),
    axis.line = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    strip.background = element_blank(),
    # strip.text.x = element_blank()
  )

# ggsave(file.path(anaDir, "GCAMP_peaks.png"), width = 3, height = 2)
```

```{r}
# how many movies and mice per treatment?
# exp.info %>% group_by(Treatment, DTx, Date) %>%
exp.info %>% group_by(Treatment, DTx) %>%
  summarise(movies = n()) %>%
  group_by(interaction(Treatment, DTx)) %>%
  summarise(
    mice = n(),
    sum_movies = sum(movies)
    ) 
  # mutate(movies_per_mouse = sum_movies/mice)
```

```{r fig_hmm_props, fig.height=3, fig.width=3}
# show measurements of clusters to compare
colsToPlot <- rev(c(
  "angle",
  "speed",
  "compactness",
  "extent",
  "oblate",
  "prolate",
  "solidity",
  "sphericity",
  "surface_area",
  "volume"
))

# convert angle to degrees
popDTs[, live.cell.angle_deg := pracma::rad2deg(live.cell.angle)]

propsToPlot <- popDTs[exp.info, on = "uID"] %>%
  dplyr::rename(
    "speed" = "live.cell.speed",
    "angle" = "live.cell.angle_deg",
    "oblate" = "ellipticity_interm_oblate",
    "prolate" = "ellipticity_interm_prolate"
  ) %>%
  # drop_na(live.cell.hmm.state.hybrid_pop) %>%
  pivot_longer(
    cols = colsToPlot, names_to = "prop", values_to = "value"
    ) %>%
  pivot_longer(
    cols = c(
      "live.cell.hmm.state.movement"
      # "live.cell.hmm.state.shape"
    ), names_to = "hmm_type", values_to = "hmm_value"
    )

propsToPlot$prop <- factor(propsToPlot$prop, levels = colsToPlot)

# show heatmap for HMM
propsSummary <- propsToPlot %>%
  dplyr::filter(!is.na(hmm_value)) %>%
  group_by(hmm_type, hmm_value, prop) %>%
  replace_na(list(value = 0)) %>%
  summarise(mean = mean(value)) %>%
  group_by(hmm_type, prop) %>%
  mutate(freq = (mean - min(mean)) / (max(mean) - min(mean))) %>%
  arrange(-prop)

# propsSummary$hmm_value <- factor(dplyr::case_match(
#   as.character(propsSummary$hmm_value),
#   c("5") ~ "Clustering",
#   c("1") ~ "Arrested",
#   c("3") ~ "Scanning",
#   c("4") ~ "Meandering",
#   c("2") ~ "Directed"
# ), levels = c("Directed", "Meandering", "Scanning", "Arrested", "Clustering"))

# ggplot(propsSummary %>% dplyr::filter(hmm_value != "Clustering"), aes(hmm_value, prop)) +
ggplot(propsSummary, aes(hmm_value, prop)) +
  theme_classic() +
  geom_tile(aes(fill = freq), colour = "white", size = 0.5) +
  viridis::scale_fill_viridis(
    breaks = c(0, 1),
    labels = c(0, 1)
  ) +
  theme(
    legend.position = "none",
    legend.title = element_blank(),
    legend.text = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    axis.text.x = element_text(size = 12),
    strip.background = element_blank(),
    strip.text.x = element_blank(),
    # axis.text.x = element_text(size = 12, angle = 45, hjust = 1, vjust = 1)
    ) +
  xlab("") + ylab("") +
  facet_grid(.~hmm_type)

ggsave(file.path(anaDir, "HMM_heat.pdf"), width = 2.5, height = 3)
```

```{r fig_umap, fig.height=2, fig.width=2}
dfToPlot <- copy(tcells.sc) %>% drop_na(clusters) %>% left_join(exp.info)
# dfToPlot <- copy(tcells.sc.info) %>% drop_na(clusters) %>% left_join(exp.info)

clusterMapping <- list(
  Directed = c(3,2),
  Meandering = c(0,4,5,6,7),
  Scanning = c(1)
  # Others = c(6,5,0,1)
)

# dfToPlot <- .mapClustNames(dfToPlot, clusterMapping, "clusters")

# get mean positions of clusters
meanClusterPos <- dfToPlot %>%
  group_by(clusters) %>%
  # group_by(clusters.name) %>%
  summarise(
    UMAP_1 = mean(UMAP_1),
    UMAP_2 = mean(UMAP_2)
  )
dfToPlot$clusters <- factor(dfToPlot$clusters)

colPal <- randomcoloR::distinctColorPalette(length(unique(dfToPlot$clusters)))

# plot UMAP
ggplot(
  dfToPlot,
  aes(UMAP_1, UMAP_2)
  ) +
  geom_point(aes(color = clusters)) +
  # geom_point(aes(color = clusters.name)) +
  theme_classic() +
  scale_color_brewer(name = NULL, palette = "Set1") +
  # scale_color_manual(values = colPal) +
  theme(
    axis.text = element_text(size = 15),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    legend.justification = "right",
    # legend.position = "bottom"
    legend.position = "none",
    axis.line = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
    ) +
  geom_label(
    data = meanClusterPos,
    aes(label = clusters),
    # aes(label = clusters.name),
    label.size = 0.25,
    color = "black"
    )

ggsave(file.path(anaDir, "umap.png"), width = 2, height = 2)
# ggsave(file.path(anaDir, "umap_wo_label.tiff"), width = 2, height = 2)
```

```{r fig_umap_props, fig.height=4, fig.width=4}
datToPlot <- copy(tcells.sc) %>%
  drop_na(clusters) %>%
  left_join(exp.info)

# plot UMAP
ggplot(datToPlot, aes(UMAP_1, UMAP_2)) +
  theme_classic() +
  geom_point(aes(color = speed), size = 1, alpha = 1) +
  # geom_point(aes(color = meanTurningAngle), size = 1, alpha = 1) +
  viridis::scale_color_viridis() +
  theme(
    axis.text = element_text(size = 15),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    legend.justification = "right",
    # legend.position = "bottom"
    legend.position = "none",
    axis.line = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
    )

ggsave(file.path(anaDir, paste0("umap_Velocity.tiff")), width = 2, height = 2)
# ggsave(file.path(anaDir, paste0("umap_Angle.tiff")), width = 2, height = 2)
```

```{r fig_umap, fig.height=2, fig.width=2}
dfToPlot <- as.data.table(copy(tcells.sc) %>% drop_na(clusters) %>% left_join(exp.info))

# show progression on UMAP
ggplot(
  dfToPlot,
  aes(UMAP_1, UMAP_2)
  ) +
  geom_point(aes(color = dpt_pseudotime)) +
  theme_classic() +
  viridis::scale_color_viridis() +
  theme(
    axis.text = element_text(size = 15),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    legend.justification = "right",
    # legend.position = "bottom"
    legend.position = "none",
    axis.line = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
    )

ggsave(file.path(anaDir, paste0("umap_Pseudotime.tiff")), width = 2, height = 2)
```

```{r fig_umap, fig.height=4, fig.width=4}
# can you show the progression of behaviour clusters from infected to uninfected?
clusterOrder <- c(6,4,1,5,2,0,3)
clusterColours <- c("grey", viridisLite::viridis(length(clusterOrder) - 1))

dfToPlot <- as.data.table(copy(tcells.sc) %>% drop_na(clusters) %>% left_join(exp.info))
dfToPlot <- dfToPlot[clusters %in% clusterOrder]
dfToPlot[, clusters := factor(clusters, levels = clusterOrder)]

# show progression on UMAP
ggplot(
  dfToPlot,
  aes(UMAP_1, UMAP_2)
  ) +
  geom_point(aes(color = clusters)) +
  theme_classic() +
  scale_color_manual(values = clusterColours) +
  theme(
    axis.text = element_text(size = 15),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    legend.justification = "right",
    # legend.position = "bottom"
    legend.position = "none",
    axis.line = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
    )

ggsave(file.path(anaDir, paste0("umap_Progression.tiff")), width = 2, height = 2)
```

```{r fig_umap, fig.height=2, fig.width=2}
plot.p1 <- function(df.all, df.subset) {
  plot.colours <- .flowColours(df.subset$UMAP_1, df.subset$UMAP_2, colramp = viridisLite::inferno)
  
  ggplot(df.all, aes(UMAP_1, UMAP_2)) +
    theme_classic() +
    geom_point(color = "black", size = 1) +
    geom_point(data = df.subset, color = plot.colours, size = 1, alpha = 1) +
    theme(
      axis.text = element_text(size = 15),
      axis.text.x = element_blank(),
      axis.ticks.x = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank(),
      legend.justification = "right",
      # legend.position = "bottom"
      legend.position = "none",
      axis.line = element_blank(),
      axis.title.x = element_blank(),
      axis.title.y = element_blank()
      )
}

datToPlot <- copy(tcells.sc) %>%
  drop_na(clusters) %>%
  left_join(exp.info)

# plot UMAP
plot.p1(datToPlot, datToPlot %>% dplyr::filter(Treatment != "HSV"))
# ggsave(file.path(anaDir, paste0("umap_Uninf.tiff")), width = 2, height = 2)

plot.p1(datToPlot, datToPlot %>% dplyr::filter(Treatment == "HSV" & DTx == "PBS"))
# ggsave(file.path(anaDir, paste0("umap_HSV_PBS.tiff")), width = 2, height = 2)

plot.p1(datToPlot, datToPlot %>% dplyr::filter(Treatment == "HSV" & DTx != "PBS"))
# ggsave(file.path(anaDir, paste0("umap_HSV_DTx.tiff")), width = 2, height = 2)
```


```{r fig_umap, fig.height=2, fig.width=2}
# # devtools::load_all("../")
# cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)
# 
# # init ccia object
# cciaObj <- initCciaObject(
#   pID = pID, uID = "BeddcR", versionID = versionID, initReactivity = FALSE #  GCAMP
# )
# 
# # GCAMP
# tracksInfo <- cciaObj$tracksInfo(
#   "live.cell.hmm.state.gcamp", parentPop = "tcells.gBT/tracked", uIDs = uIDs, replaceNA = TRUE)

dfToPlot <- copy(tcells.sc) %>% drop_na(clusters) %>%
  left_join(tracksInfo, by = c("uID", "track_id"))
dfToPlot$gcamp.track <- FALSE
dfToPlot[dfToPlot$live.cell.hmm.state.gcamp.2.n >= 3, ]$gcamp.track <- TRUE
# dfToPlot[dfToPlot$live.cell.hmm.state.gcamp.2 > 0.1, ]$gcamp.track <- TRUE
# dfToPlot[dfToPlot$live.cell.hmm.state.gcamp.2.diff < 100, ]$gcamp.track <- TRUE
# dfToPlot[dfToPlot$live.cell.hmm.state.gcamp.2.diff < 100 & 
#            dfToPlot$live.cell.hmm.state.gcamp.2 > 0.1, ]$gcamp.track <- TRUE

datToPlot <- dfToPlot %>% left_join(exp.info)

# plot UMAP
curDatToPlot <- datToPlot[datToPlot$gcamp.track == TRUE,]
# plotCols <- .flowColours(curDatToPlot$UMAP_1, curDatToPlot$UMAP_2, colramp = viridisLite::mako)
plotCols <- .flowColours(curDatToPlot$UMAP_1, curDatToPlot$UMAP_2, colramp = viridisLite::inferno)

# plot UMAP
ggplot(
  datToPlot,
  aes(UMAP_1, UMAP_2)
  ) +
  theme_classic() +
  geom_point(data = datToPlot, color = "black", size = 1) +
  geom_point(data = curDatToPlot, color = plotCols, size = 1, alpha = 1) +
  theme(
    axis.text = element_text(size = 15),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    legend.justification = "right",
    # legend.position = "bottom",
    legend.position = "none",
    axis.line = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
    )

ggsave(file.path(anaDir, paste0("umap_GCAMP.png")), width = 2, height = 2)
```

```{r}
library(ggplot2)
library(hexbin)

dat <- data.frame(x = rnorm(10000), y = rnorm(10000))

ggplot(dat, aes(x = x, y = y)) +
  geom_hex() + coord_fixed() +
  scale_fill_gradientn(colours = viridisLite::inferno(256))

ggsave(file.path(anaDir, paste0("GCAMP_scale.png")), height = 4, width = 4)
```


```{r fig_GCAMP_freq, fig.height=3, fig.width=4}
# in total - what is the frequency of GCAMP+?
datToPlot <- dfToPlot %>%
  group_by(uID, gcamp.track) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n) * 100) %>%
  ungroup() %>%
  complete(uID, gcamp.track, fill = list(freq = 0)) %>%
  dplyr::filter(gcamp.track == TRUE) %>%
  left_join(exp.info)

ggplot(datToPlot,
       aes(interaction(Treatment, DTx), freq, color = interaction(Treatment, DTx))) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    # width = 2, alpha = 1.0) +
  scale_color_brewer(name = "Treatment", palette = "Set1") +
  coord_flip()

# datToPlot$Treatment.DTx <- 0
# datToPlot[datToPlot$Treatment == "PBS" & datToPlot$DTx == "PBS",]$Treatment.DTx <- 0
# datToPlot[datToPlot$Treatment == "HSV" & datToPlot$DTx == "PBS",]$Treatment.DTx <- 1
# datToPlot[datToPlot$Treatment == "HSV" & datToPlot$DTx == "DTx",]$Treatment.DTx <- 2
# 
# ggsave(file.path(anaDir, paste0("GCAMP_freq.png")), width = 3, height = 2)
# write.csv(datToPlot, file = file.path(anaDir, "freq_gcamp.csv"))
```

```{r}
# show measurements of clusters to compare
propsToPlot <- copy(tcells.sc)

# propsToPlot <- .mapClustNames(propsToPlot, clusterMapping, "clusters")

# propsToPlot <- propsToPlot %>%
#   dplyr::rename(
#     "Movement HMM 1" = "live.cell.hmm.state.movement.1",
#     "Movement HMM 2" = "live.cell.hmm.state.movement.2",
#     "Movement HMM 3" = "live.cell.hmm.state.movement.3",
#     "Movement HMM 4" = "live.cell.hmm.state.movement.4",
#   )

colsToPlot <- colnames(propsToPlot)[!colnames(propsToPlot) %in% c(
  "pop", "uID", "track_id", "clusters", "clusters.name", "clusters.id", "UMAP_1", "UMAP_2"
  )]

propsToPlot <- propsToPlot %>%
  pivot_longer(
    cols = colsToPlot, names_to = "prop", values_to = "value"
    )

propsToPlot$prop <- factor(propsToPlot$prop, levels = sort(colsToPlot, decreasing = TRUE))

# propsList <- c(
#   'Movement HMM 1',
#   'Movement HMM 2',
#   'Movement HMM 3',
#   'Movement HMM 4',
#   'asphericity',
#   'displacement',
#   'displacementRatio',
#   'duration',
#   'meanTurningAngle',
#   'outreachRatio',
#   'overallAngle',
#   'speed',
#   'straightness',
#   'trackLength'
# )

# show heatmap for clusters
propsSummary <- propsToPlot %>%
  dplyr::filter(
    # clusters.name != "NONE",
    # prop %in% propsList
    ) %>%
  group_by(clusters, prop) %>%
  # group_by(clusters.name, prop) %>%
  summarise(mean = mean(value, rm.na = TRUE)) %>%
  group_by(prop) %>%
  mutate(freq = (mean - min(mean)) / (max(mean) - min(mean))) %>%
  arrange(-prop)
```

```{r fig_clusters_heat, fig.height=8, fig.width=6}
# propsSummary$prop <- factor(
#   propsSummary$prop, levels = rev(propsList))
# propsSummary$clusters.name <- factor(
#   propsSummary$clusters.name, levels = c(
#     "Directed", "Meandering", "Scanning", "Clustering"
#   ))

# # sort states
# propsSummary[!propsSummary$clusters %in% clusterOrder[clusterOrder != 6],]$clusters <- NA
# # propsSummary$clusters <- factor(propsSummary$clusters, levels = clusterOrder)
# propsSummary$clusters <- case_match(
#   as.character(propsSummary$clusters),
#   c("4") ~ "1",
#   c("2") ~ "2",
#   c("1") ~ "3",
#   c("5") ~ "4",
#   c("0") ~ "5",
#   c("3") ~ "6",
# )

# ggplot(propsSummary, aes(as.factor(clusters.name), prop)) +
# ggplot(propsSummary, aes(as.factor(clusters), prop)) +
ggplot(propsSummary %>%
         # dplyr::filter(!str_detect(prop, "live.cell")) %>%
         drop_na(clusters), aes(clusters, prop)) +
         # drop_na(clusters.name), aes(clusters.name, prop)) +
  theme_classic() +
  geom_tile(aes(fill = freq), colour = "white", size = 0.5) +
  viridis::scale_fill_viridis(
    breaks = c(0, 1),
    labels = c(0, 1)
  ) +
  theme(
    legend.position = "none",
    legend.key.size = unit(8, "mm"),
    legend.title = element_blank(),
    legend.text = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    # axis.text.x = element_text(size = 12),
    axis.text.x = element_text(size = 12, angle = 45, hjust = 1, vjust = 1),
    strip.background = element_blank(),
    strip.text.x = element_blank()
    ) +
  xlab("") + ylab("")

ggsave(file.path(anaDir, "clusters_heat.pdf"), width = 4.5, height = 5)
```

```{r fig_clusters_heat, fig.height=4, fig.width=6}
# get frequencies of HMM for each cluster
# and plot as bar graphs
datToPlot <- copy(popDTs)

# datToPlot <- .mapClustNames(datToPlot, clusterMapping, "live.cell.track.clusters.hmm_transitions_movement") %>%
datToPlot <- datToPlot %>%
  # mutate(live.cell.track.clusters.hmm_transitions_movement = as.numeric(as.character(
  #   live.cell.track.clusters.hmm_transitions_movement))) %>%
  # drop_na(live.cell.track.clusters.hmm_transitions_movement) %>%
  drop_na(live.cell.hmm.state.movement) %>%
  group_by(live.cell.track.clusters.hmm_transitions_movement, live.cell.hmm.state.movement) %>%
  # group_by(clusters.name, live.cell.hmm.state.movement) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n) * 1) %>%
  ungroup() %>%
  complete(live.cell.track.clusters.hmm_transitions_movement, live.cell.hmm.state.movement, fill = list(freq = 0))
  # complete(clusters.name, live.cell.hmm.state.movement, fill = list(freq = 0))

# write.csv(datToPlot, file = file.path(anaDir, "freq_hmm.csv"))

ggplot(datToPlot, aes(as.factor(live.cell.track.clusters.hmm_transitions_movement), freq,
# ggplot(datToPlot, aes(clusters.name, freq,
                      fill = as.factor(live.cell.hmm.state.movement))) +
  theme_classic() +
  # scale_fill_brewer(palette = "Accent") +
  scale_fill_manual(values = wesanderson::wes_palette(name = "Darjeeling2")) +
  theme_classic() +
  geom_bar(stat = "identity", width = 1, color = "black", size = 0.4) +
  theme(
    # legend.position = "none",
    legend.position = "right",
    legend.key.size = unit(6, "mm"),
    legend.title = element_blank(),
    legend.text = element_text(size = 16),
    axis.title.y = element_text(size = 16),
    axis.title.x = element_text(size = 16),
    axis.text.y = element_text(size = 16),
    axis.text.x = element_text(size = 16),
    # axis.text.x = element_text(size = 12, angle = 45, hjust = 1, vjust = 1),
    strip.background = element_blank(),
    # strip.text.x = element_blank()
    strip.text.x = element_text(size = 16)
    ) +
  scale_y_continuous(breaks = c(0, 0.5, 1)) +
  # scale_fill_discrete(name = "HMM State") +
  # xlab("Clusters") + ylab("HMM proportion") +
  xlab("") + ylab("HMM proportion") +
  coord_flip()

# ggsave(file.path(anaDir, "clusters_hmm_heat.pdf"), width = 4, height = 2)
```

```{r fig_clusters_heat, fig.height=3, fig.width=8}
# get frequencies of HMM for each cluster
# and plot as bar graphs
datToPlot <- popDTs %>%
  mutate(
    live.cell.track.clusters.hmm_transitions_movement = as.numeric(as.character(
      live.cell.track.clusters.hmm_transitions_movement)),
    live.cell.hmm.transitions.movement = as.character(
      live.cell.hmm.transitions.movement)
    ) %>%
  drop_na(live.cell.track.clusters.hmm_transitions_movement) %>%
  dplyr::filter(live.cell.hmm.transitions.movement != "NA") %>%
  # group_by(live.cell.track.clusters.hmm_transitions_movement, from, to) %>%
  # dplyr::filter(!live.cell.hmm.transitions.movement %in% paste0(seq(4), "_", seq(4))) %>%
  group_by(live.cell.track.clusters.hmm_transitions_movement, live.cell.hmm.transitions.movement) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n) * 1) %>%
  separate_wider_delim(
    live.cell.hmm.transitions.movement, delim = "_", names = c("from", "to"))
  # ungroup() %>%
  # complete(live.cell.track.clusters.hmm_transitions_movement, from, to, fill = list(freq = 0))

ggplot(datToPlot, aes(as.factor(from), as.factor(to), size = freq * 2, fill = freq)) +
  theme_classic() +
  # scale_fill_brewer(palette = "Accent") +
  # scale_y_continuous(breaks = c(0, 0.5, 1)) +
  geom_vline(xintercept = as.factor(1:5), color = "#d3d3d3") +
  geom_hline(yintercept = as.factor(1:5), color = "#d3d3d3") +
  geom_point(pch = 21, color = "black") +
  # viridis::scale_fill_viridis() +
  scale_fill_gradient2(
    midpoint = 0.5, low="blue", mid="white", high="red", space ="Lab") +
  theme(
    legend.position = "none",
    # legend.position = "right",
    legend.key.size = unit(6, "mm"),
    legend.title = element_blank(),
    legend.text = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    axis.text.x = element_text(size = 12),
    # axis.text.x = element_text(size = 12, angle = 45, hjust = 1, vjust = 1),
    strip.background = element_blank(),
    # strip.text.x = element_blank()
    strip.text.x = element_text(size = 12)
    ) +
  # scale_fill_discrete(name = "HMM State") +
  xlab("From state") + ylab("To state") +
  facet_wrap(.~live.cell.track.clusters.hmm_transitions_movement, nrow = 2)

ggsave(file.path(anaDir, "clusters_transitions_heat.pdf"), width = 4, height = 3)
```

```{r fig_hmm_over_clusters, fig.height=4, fig.width=4}
# get frequencies of HMM for each cluster
# and plot as bar graphs
datToPlot <- popDTs %>%
  mutate(live.cell.track.clusters.hmm_movement = as.numeric(as.character(
    live.cell.track.clusters.hmm_movement))) %>%
  dplyr::filter(!live.cell.track.clusters.hmm_movement %in% c(6)) %>%
  dplyr::filter(!live.cell.hmm.state.movement %in% c(5)) %>%
  drop_na(live.cell.track.clusters.hmm_movement) %>%
  drop_na(live.cell.hmm.state.movement) %>%
  group_by(live.cell.track.clusters.hmm_movement, live.cell.hmm.state.movement) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n) * 100) %>%
  ungroup() %>%
  complete(live.cell.track.clusters.hmm_movement, live.cell.hmm.state.movement, fill = list(freq = 0))

write.csv(datToPlot, file = file.path(anaDir, "freq_hmm.csv"))
```

```{r fig_total_transitions, fig.height=1, fig.width=5}
library(ggplot2)
library(ggraph)

freqThr <- 0.001

pList <- list()

stateOrder <- list(
  "D" = "2",
  "P" = "4",
  "M" = "3",
  "S" = "1",
  "C" = "5"
)

summaryDF <- popDTs %>%
  left_join(exp.info)

summaryDF$cell_type <- str_extract(summaryDF$pop, "(?<=\\.)[:alnum:]+(?=/)")
summaryDF$stain <- str_extract(
  summaryDF$staining, sprintf("%s-[:alnum:]+", summaryDF$cell_type)
  )
summaryDF$stain[is.na(summaryDF$stain)] <- "gBT-CTV"
summaryDF$Treatment_DTx <- interaction(summaryDF$Treatment, summaryDF$DTx)

summaryDF <- .mapClustNames(summaryDF, clusterMapping, "live.cell.track.clusters.hmm_transitions_movement")

# for (x in unique(summaryDF$live.cell.track.clusters.hmm_transitions_movement)) {
for (x in unique(summaryDF$live.cell.track.clusters.hmm_movement)) {
# for (x in unique(summaryDF$clusters.name)) {
# for (x in unique(summaryDF$Treatment_DTx)) {
  # plot heatmap of transitions
  DF <- summaryDF %>%
    # dplyr::filter(live.cell.track.clusters.hmm_transitions_movement == x) %>%
    dplyr::filter(live.cell.track.clusters.hmm_movement == x) %>%
    # dplyr::filter(clusters.name == x) %>%
    # dplyr::filter(Treatment_DTx == x, live.cell.track.clusters.hmm_transitions_movement == 3) %>%
    group_by(live.cell.hmm.transitions.movement) %>%
    summarise(n = n()) %>%
    separate(live.cell.hmm.transitions.movement,
             into = c("from", "to"),
             sep = "_", convert = TRUE) %>%
    mutate(across(c(from, to), as.character)) %>%
    replace_na(list(from = "0"))
  
  # edges for non-self transitions
  edges <- DF %>%
    dplyr::filter(from != to) %>%
    mutate(freq = n/sum(n)) %>%
    complete(from, to, fill = list(freq = 0)) %>%
    drop_na() %>%
    dplyr::filter(freq > freqThr) %>%
    mutate(non.self = (freq - min(freq)) / (max(freq) - min(freq))) %>%
    arrange(freq)
  
  # get number of self transitions
  nodes <- DF %>%
    dplyr::filter(from == to) %>%
    mutate(freq = n/sum(n)) %>%
    complete(from = unlist(stateOrder), fill = list(freq = 0)) %>%
    replace_na(list(to = "0")) %>%
    select(from, freq) %>%
    dplyr::rename(node = from) %>%
    add_row(node = "0", freq = 0) %>%
    mutate(nodeName = node) %>%
    dplyr::filter(node %in% unique(c(edges$from, edges$to))) %>%
    mutate(self = (freq - min(freq)) / (max(freq) - min(freq)))
  
  # add names for nodes
  for (i in names(stateOrder)) {
    nodes[nodes$nodeName == stateOrder[[i]], ]$nodeName <- i
  }
  
  # add state order
  counter <- 0
  nodes$order <- 0
  for (y in stateOrder) {
    nodes[nodes$node == y,]$order <- counter

    counter <- counter + 1
  }
  
  # https://www.hydrogenwaterusa.com/visualizing-large-directed-networks-with-ggraph-in-r/
  g <- igraph::graph_from_data_frame(d = edges,
                                     vertices = nodes %>% arrange(order),
                                     directed = TRUE)
  
  # pList[[x]] <- ggraph(g, layout = "auto") +
  # pList[[x]] <- ggraph(g, layout = "igraph", algorithm = "circle") +
  # pList[[x]] <- ggraph(g, layout = "linear") +
  # ggraph(g, layout = "igraph", algorithm = "circle") +
  # ggraph(g, layout = "auto") +
  ggraph(g, layout = "linear") +
    # ggtitle(sprintf("%s", x)) +
    geom_edge_fan2(aes(width = non.self, color = non.self),
                   arrow = arrow(length = unit(5, 'mm'), type = "closed"),
                   end_cap = circle(3, 'mm')) +
    scale_edge_width(range = c(1, 2)) +
    scale_edge_color_gradient2(
      # low = "#D1D1D1",
      low = "#dadada",
      high = "black",
      mid = "#616161",
      midpoint = .5
    ) +
    geom_node_label(aes(label = nodeName, fill = self),
                    color = "white", repel = FALSE, size=5,
                    label.padding = unit(0.25, "lines")) +
    scale_fill_gradient2(
      # low = "blue",
      low = "#009fe3",
      mid = "black",
      # high = "red",
      high = "#e71d73",
      midpoint = .5
    ) +
    theme_graph(
      plot_margin = margin(0, 0, 0, 0)
    ) +
    theme(
      legend.position = "none",
      plot.title = element_text(size = 6, family = "Arial")
    )

  ggsave(file = file.path(anaDir, "networks", paste0("network_", x, ".pdf")),
         width = 3, height = 1, dpi = 400)
}

# ggpubr::ggarrange(plotlist = pList, nrow = 1)

# https://stackoverflow.com/a/17075381
# ggsave(file = file.path(anaDir, "total_networks.tiff"),
# ggsave(file = file.path(anaDir, "total_networks_GCAMP.tiff"),
  # width = 7, height = 2)
  # width = 20, height = 3.5)
  # width = 25, height = 2)
```

```{r fig_clusters_freq, fig.height=4, fig.width=10}
# save frequencies of track clusters
summaryDF <- copy(tcells.sc)

# summaryDF <- .mapClustNames(summaryDF, clusterMapping)

# show frequency of clusters - exclude clusters
summaryDF <- summaryDF[, .(n.clusters = .N), by = .(uID, pop, clusters)] %>%
# summaryDF <- summaryDF[clusters != 5, .(n.clusters = .N), by = .(uID, pop, clusters)] %>%
# summaryDF <- summaryDF[, .(n.clusters = .N), by = .(uID, pop, clusters.name)] %>%
  droplevels() %>%
  group_by(uID, pop) %>%
  mutate(freq.clusters = n.clusters/sum(n.clusters) * 100) %>%
  ungroup() %>%
  complete(uID, pop, clusters, fill = list(freq.clusters = 0)) %>%
  # complete(uID, pop, clusters.name, fill = list(freq.clusters = 0)) %>%
  left_join(exp.info)

# ggplot(summaryDF, aes(clusters, freq.clusters, color = interaction(Treatment, DTx))) +
# ggplot(summaryDF %>% dplyr::filter(pop == "tcells.gBT/tracked"),
ggplot(summaryDF, aes(clusters, freq.clusters, color = interaction(Treatment, DTx))) +
# ggplot(summaryDF, aes(clusters.name, freq.clusters, color = interaction(Treatment, DTx))) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
  scale_color_brewer(name = "Treatment", palette = "Set1") +
  facet_grid(.~pop)

# ggsave(file.path(anaDir, "clusters_freq.png"), width = 5, height = 3)
# ggsave(file.path(anaDir, "clusters_freq_wo_clusters.pdf"), width = 8, height = 3)

# summaryDF$Treatment.DTx <- 0
# summaryDF[summaryDF$Treatment == "PBS" & summaryDF$DTx == "PBS",]$Treatment.DTx <- 0
# summaryDF[summaryDF$Treatment == "HSV" & summaryDF$DTx == "PBS",]$Treatment.DTx <- 1
# summaryDF[summaryDF$Treatment == "HSV" & summaryDF$DTx == "DTx",]$Treatment.DTx <- 2

write.csv(summaryDF, file = file.path(anaDir, "freq_clusters.csv"))
# write.csv(summaryDF, file = file.path(anaDir, "freq_clusters_wo_clusters.csv"))
```

```{r}
# what is the difference between background and higher GCAMP clusters?
datToPlot <- as.data.table(
  tracksInfo %>% left_join(tcells.sc[, c("uID", "track_id", "clusters")]))

# get cols to plot
colsToPlot <- colnames(datToPlot)

ggplot(datToPlot[clusters %in% c(0, 2)], aes())
```

```{r}
t.test(
  summaryDF %>% dplyr::filter(clusters == 7, Treatment.DTx == 1) %>% dplyr::select(freq.clusters),
  summaryDF %>% dplyr::filter(clusters == 7, Treatment.DTx == 0) %>% dplyr::select(freq.clusters)
)
```

```{r fig_clusters_heat, fig.height=3, fig.width=3}
# get frequencies of HMM for each cluster
# and plot as bar graphs
datToPlot <- popDTs %>%
  mutate(live.cell.track.clusters.hmm_transitions_movement = as.numeric(as.character(
    live.cell.track.clusters.hmm_transitions_movement))) %>%
  drop_na(live.cell.track.clusters.hmm_transitions_movement) %>%
  dplyr::filter(live.cell.track.clusters.hmm_transitions_movement != 7) %>%
  left_join(exp.info) %>%
  group_by(Treatment, DTx, live.cell.track.clusters.hmm_transitions_movement) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n) * 1)

ggplot(datToPlot, aes(interaction(Treatment, DTx), freq,
                      fill = as.factor(live.cell.track.clusters.hmm_transitions_movement))) +
  theme_classic() +
  scale_fill_brewer(palette = "Accent") +
  # scale_fill_manual(values = wesanderson::wes_palette(name = "Darjeeling2")) +
  theme_classic() +
  geom_bar(stat = "identity", width = 1, color = "black", size = 0.4) +
  theme(
    # legend.position = "none",
    legend.position = "right",
    legend.key.size = unit(6, "mm"),
    legend.title = element_blank(),
    legend.text = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    # axis.text.x = element_text(size = 12),
    axis.text.x = element_text(size = 12, angle = 45, hjust = 1, vjust = 1),
    strip.background = element_blank(),
    # strip.text.x = element_blank()
    strip.text.x = element_text(size = 12)
    ) +
  scale_y_continuous(breaks = c(0, 0.5, 1)) +
  # scale_fill_discrete(name = "HMM State") +
  xlab("") + ylab("") 

# ggsave(file.path(anaDir, "clusters_hmm_heat.pdf"), width = 3, height = 1.5)
```

```{r}
# show measurements of clusters to compare
colsToPlot <- rev(c(
  "GCAMP (ratio)",
  "GCAMP (norm)",
  "angle",
  "speed",
  "compactness",
  "extent",
  "oblate",
  "prolate",
  "solidity",
  "sphericity",
  "surface_area",
  "volume"
))

# convert angle to degrees
popDTs[, live.cell.angle_deg := pracma::rad2deg(live.cell.angle)]

propsToPlot <- popDTs[exp.info, on = "uID"] %>%
  dplyr::rename(
    "GCAMP (ratio)" = "live.cell.peak.ratio.GCAMP",
    "GCAMP (norm)" = "live.cell.peak.norm.GCAMP",
    "speed" = "live.cell.speed",
    "angle" = "live.cell.angle_deg",
    "oblate" = "ellipticity_interm_oblate",
    "prolate" = "ellipticity_interm_prolate"
  ) %>%
  # drop_na(live.cell.hmm.state.hybrid_pop) %>%
  pivot_longer(
    cols = colsToPlot, names_to = "prop", values_to = "value"
    ) %>%
  pivot_longer(
    cols = c(
      "live.cell.hmm.state.gcamp"
    ), names_to = "hmm_type", values_to = "hmm_value"
    ) %>%
  dplyr::filter(!is.na(hmm_value))

propsToPlot$prop <- factor(propsToPlot$prop, levels = colsToPlot)

# rename
propsToPlot$hmm_name <- "High"
propsToPlot[propsToPlot$hmm_value == 1,]$hmm_name <- "Low"
propsToPlot[propsToPlot$hmm_value == 2,]$hmm_name <- "Negative"
```


```{r fig_hmm_props, fig.height=3, fig.width=3}
# show heatmap for HMM
propsSummary <- propsToPlot %>%
  # group_by(hmm_type, hmm_name, prop) %>%
  group_by(hmm_type, hmm_value, prop) %>%
  replace_na(list(value = 0)) %>%
  summarise(mean = mean(value)) %>%
  group_by(hmm_type, prop) %>%
  mutate(freq = (mean - min(mean)) / (max(mean) - min(mean))) %>%
  arrange(-prop)

# ggplot(propsSummary, aes(as.factor(hmm_name), prop)) +
ggplot(propsSummary, aes(as.factor(hmm_value), prop)) +
  theme_classic() +
  geom_tile(aes(fill = freq), colour = "white", size = 0.5) +
  viridis::scale_fill_viridis(
    breaks = c(0, 1),
    labels = c(0, 1)
  ) +
  theme(
    legend.position = "none",
    legend.title = element_blank(),
    legend.text = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    axis.text.x = element_text(size = 12),
    # axis.text.x = element_text(size = 12, angle = 45, hjust = 1, vjust = 1),
    strip.background = element_blank(),
    strip.text.x = element_blank(),
    ) +
  xlab("") + ylab("") +
  facet_grid(.~hmm_type)

ggsave(file.path(anaDir, "HMM_GCAMP_heat.pdf"), width = 2.3, height = 3)
```

```{r fig_GCAMP_trace, fig.height=2, fig.width=2}
# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "2b5uDC", versionID = versionID, initReactivity = FALSE
)

popDT <- cciaObj$popDT(
  "live", pops = c("tcells.gBT/tracked"),
  includeFiltered = TRUE)

# convert angle to degrees
popDT[, live.cell.angle_deg := pracma::rad2deg(live.cell.angle)]
popDT[, live.cell.hmm.state.gcamp.ordered := 0]
popDT[live.cell.hmm.state.gcamp == 2, live.cell.hmm.state.gcamp.ordered := 0]
popDT[live.cell.hmm.state.gcamp == 1, live.cell.hmm.state.gcamp.ordered := 1]
popDT[live.cell.hmm.state.gcamp == 3, live.cell.hmm.state.gcamp.ordered := 2]

colsToPlot <- list(
  "GCAMP HMM" = "live.cell.hmm.state.gcamp.ordered",
  "GCAMP/CTV" = "live.cell.peak.ratio.GCAMP",
  "Speed (um/min)" = "live.cell.speed",
  "Sphericity" = "sphericity"
)

trackToPlot <- popDT[track_id == 37, ] %>%
  pivot_longer(
    cols = unname(unlist(colsToPlot)), names_to = "measure", values_to = "value"
  ) %>%
  mutate(measure = factor(measure, levels = unname(unlist(colsToPlot))))

ggplot(
  trackToPlot,
  aes(x = (centroid_t * cciaObj$omeXMLTimelapseInfo()$interval))) +
  geom_line(aes(y = value), colour = "black") +
  theme_classic() +
  xlab("Time (min)") + ylab("") +
  theme(
    strip.background = element_blank(),
    strip.text.x = element_blank(),
    axis.text.y = element_text(size = 11),
    axis.text.x = element_text(size = 11),
    ) +
  facet_wrap(measure~., scales = "free_y", ncol = 1)
  
ggsave(file.path(anaDir, "2b5uDC_track-37.pdf"), width = 3, height = 3)
```

```{r fig_hmm_state_in_clusters, fig.height=1, fig.width=4}
# plot scanning v migrating cells for treatments
stainingCombinations <- stack(sapply(
  cciaObj$cciaObjects(uIDs = uIDs),
  function(x) paste(x$imChannelNames(), collapse = ",")
))
setnames(stainingCombinations, "values", "staining")
setnames(stainingCombinations, "ind", "uID")

# get track clusters for tracks with at least >= x GCAMP+
summaryDF <- popDTs %>%
# popDTs %>%
  # group_by(uID, pop, live.cell.hmm.state.gcamp, live.cell.track.clusters.skip3) %>%
  group_by(uID, pop, live.cell.hmm.state.gcamp, live.cell.track.clusters.hmm_transitions_movement) %>%
  summarise(n.clust = n()) %>%
  mutate(freq.clust = n.clust/sum(n.clust) * 100) %>%
  ungroup() %>%
  complete(
    # uID, pop, live.cell.hmm.state.gcamp, live.cell.track.clusters.skip3,
    uID, pop, live.cell.hmm.state.gcamp, live.cell.track.clusters.hmm_transitions_movement,
    fill = list(freq.clust = 0)
    ) %>%
  dplyr::filter(
    # !live.cell.track.clusters.skip3 %in% c("NA", NA),
    !live.cell.track.clusters.hmm_transitions_movement %in% c("NA", NA),
    live.cell.hmm.state.gcamp == 3
    # live.cell.track.clusters.skip3 != 3
    ) %>%
  left_join(exp.info) %>%
  left_join(stainingCombinations)

summaryDF$cell_type <- str_extract(summaryDF$pop, "(?<=\\.)[:alnum:]+(?=/)")
summaryDF$stain <- str_extract(
  summaryDF$staining, sprintf("%s-[:alnum:]+", summaryDF$cell_type)
  )
# drop NA stain
summaryDF <- summaryDF %>% drop_na(stain)

# summaryDF$stain[is.na(summaryDF$stain)] <- "gBT-CTV"

# summaryDF[summaryDF$Treatment == "Uninfected",]$DTx <- ""
summaryDF[summaryDF$Treatment == "Uninfected",]$Treatment <- "PBS"

summaryDF$Treatment.DTx <- 0
summaryDF[summaryDF$Treatment == "PBS" & summaryDF$DTx == "PBS",]$Treatment.DTx <- 0
summaryDF[summaryDF$Treatment == "HSV" & summaryDF$DTx == "PBS",]$Treatment.DTx <- 1
summaryDF[summaryDF$Treatment == "HSV" & summaryDF$DTx == "DTx",]$Treatment.DTx <- 2

summaryDF$Stain.ID <- 0
summaryDF[summaryDF$stain == "OTI-CTV",]$Stain.ID <- 2
summaryDF[summaryDF$stain == "gBT-CTDR",]$Stain.ID <- 1

# plot
ggplot(summaryDF,
       aes(
         interaction(Treatment, DTx, stain), freq.clust,
         # fill = as.factor(live.cell.track.clusters.skip3)
         fill = as.factor(live.cell.track.clusters.hmm_transitions_movement)
         )) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    # width = 0.3, alpha = 0.6) +
  # stat_summary(fun=mean, geom="point", size=3, shape=18, color="Magenta") +
  ylab("Frequency GCAMP+") + xlab("") +
  # ylim(0, 1) +
  scale_fill_brewer(name = NULL, palette = "Set3")

ggsave(file.path(anaDir, "clusters_GCAMP_freq.pdf"), width = 12, height = 3)

# write.csv(summaryDF %>%
#             dplyr::filter(live.cell.track.clusters.skip3 == 0),
#           file.path(anaDir, "gcamp_behaviour_Mea.csv"))
# write.csv(summaryDF %>%
#             dplyr::filter(live.cell.track.clusters.skip3 == 1),
#           file.path(anaDir, "gcamp_behaviour_Dir.csv"))
# write.csv(summaryDF %>%
#             dplyr::filter(live.cell.track.clusters.skip3 == 2),
#           file.path(anaDir, "gcamp_behaviour_Sca.csv"))
# write.csv(summaryDF %>%
#             dplyr::filter(Treatment.DTx == 0),
#           file.path(anaDir, "gcamp_behaviour_Uninf.csv"))
# write.csv(summaryDF %>%
#             dplyr::filter(Treatment.DTx == 1),
#           file.path(anaDir, "gcamp_behaviour_PBS.csv"))
# write.csv(summaryDF %>%
#             dplyr::filter(Treatment.DTx == 2),
#           file.path(anaDir, "gcamp_behaviour_DTx.csv"))
```

```{r fig_hmm_state_in_clusters, fig.height=1, fig.width=4}
# plot plot GCAMP for behaviour
stainingCombinations <- stack(sapply(
  cciaObj$cciaObjects(uIDs = uIDs),
  function(x) paste(x$imChannelNames(), collapse = ",")
))
setnames(stainingCombinations, "values", "staining")
setnames(stainingCombinations, "ind", "uID")

# get track clusters for tracks with at least >= x GCAMP+
summaryDF <- popDTs %>%
# popDTs %>%
  group_by(uID, pop, live.cell.track.clusters.skip3, live.cell.hmm.state.gcamp) %>%
  summarise(n.clust = n()) %>%
  mutate(freq.clust = n.clust/sum(n.clust) * 100) %>%
  ungroup() %>%
  complete(
    uID, pop, live.cell.track.clusters.skip3, live.cell.hmm.state.gcamp,
    fill = list(freq.clust = 0)
    ) %>%
  dplyr::filter(
    !live.cell.track.clusters.skip3 %in% c("NA", NA),
    live.cell.hmm.state.gcamp == 3,
    live.cell.track.clusters.skip3 != 3
    ) %>%
  left_join(exp.info) %>%
  left_join(stainingCombinations)

summaryDF$cell_type <- str_extract(summaryDF$pop, "(?<=\\.)[:alnum:]+(?=/)")
summaryDF$stain <- str_extract(
  summaryDF$staining, sprintf("%s-[:alnum:]+", summaryDF$cell_type)
  )
# drop NA stain
summaryDF <- summaryDF %>% drop_na(stain)

# summaryDF$stain[is.na(summaryDF$stain)] <- "gBT-CTV"

# summaryDF[summaryDF$Treatment == "Uninfected",]$DTx <- ""
summaryDF[summaryDF$Treatment == "Uninfected",]$Treatment <- "PBS"

summaryDF$Treatment.DTx <- 0
summaryDF[summaryDF$Treatment == "PBS" & summaryDF$DTx == "PBS",]$Treatment.DTx <- 0
summaryDF[summaryDF$Treatment == "HSV" & summaryDF$DTx == "PBS",]$Treatment.DTx <- 1
summaryDF[summaryDF$Treatment == "HSV" & summaryDF$DTx == "DTx",]$Treatment.DTx <- 2

summaryDF$Stain.ID <- 0
summaryDF[summaryDF$stain == "OTI-CTV",]$Stain.ID <- 2
summaryDF[summaryDF$stain == "gBT-CTDR",]$Stain.ID <- 1

# plot
ggplot(summaryDF,
       aes(
         interaction(Treatment, DTx, stain), freq.clust,
         fill = as.factor(live.cell.track.clusters.skip3)
         )) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    # width = 0.3, alpha = 0.6) +
  # stat_summary(fun=mean, geom="point", size=3, shape=18, color="Magenta") +
  ylab("Frequency GCAMP+") + xlab("") +
  # ylim(0, 1) +
  scale_fill_brewer(name = NULL, palette = "Set3")

# write.csv(summaryDF %>%
#             dplyr::filter(live.cell.track.clusters.skip3 == 0),
#           file.path(anaDir, "Mea_gcamp.csv"))
# write.csv(summaryDF %>%
#             dplyr::filter(live.cell.track.clusters.skip3 == 1),
#           file.path(anaDir, "Dir_gcamp.csv"))
# write.csv(summaryDF %>%
#             dplyr::filter(live.cell.track.clusters.skip3 == 2),
#           file.path(anaDir, "Sca_gcamp.csv"))
```

```{r fig_flashing_freq, fig.height=1, fig.width=4}
# can you show the time between GCAMP peaks?
# for each track, get time for first/last GCAMP peak
# then count peaks within that range
stainingCombinations <- stack(sapply(
  cciaObj$cciaObjects(uIDs = uIDs),
  function(x) paste(x$imChannelNames(), collapse = ",")
))
setnames(stainingCombinations, "values", "staining")
setnames(stainingCombinations, "ind", "uID")

summaryDF <- popDTs %>%
  dplyr::filter(live.cell.hmm.state.gcamp == 3) %>%
  group_by(uID, pop, live.cell.track.clusters.skip3, track_id) %>%
  summarise(
    n = n(),
    first = min(centroid_t),
    last = max(centroid_t),
    median.diff = median(diff(centroid_t), na.rm = TRUE),
    mean.diff = mean(diff(centroid_t), na.rm = TRUE)
  ) %>%
  mutate(
    time = last - first,
    freq = n / time
    ) %>%
  mutate_all(function(x) ifelse(is.infinite(x), NA, x)) %>%
  dplyr::filter(
    !live.cell.track.clusters.skip3 %in% c("NA", NA),
    # live.cell.hmm.state.gcamp == 3,
    live.cell.track.clusters.skip3 != 3
    ) %>%
  left_join(exp.info) %>%
  left_join(stainingCombinations)

summaryDF$cell_type <- str_extract(summaryDF$pop, "(?<=\\.)[:alnum:]+(?=/)")
summaryDF$stain <- str_extract(
  summaryDF$staining, sprintf("%s-[:alnum:]+", summaryDF$cell_type)
  )
# drop NA stain
# summaryDF <- summaryDF %>% drop_na(stain)

# summaryDF$stain[is.na(summaryDF$stain)] <- "gBT-CTV"

# summaryDF[summaryDF$Treatment == "Uninfected",]$DTx <- ""
summaryDF[summaryDF$Treatment == "Uninfected",]$Treatment <- "PBS"

summaryDF$Treatment.DTx <- 0
summaryDF[summaryDF$Treatment == "PBS" & summaryDF$DTx == "PBS",]$Treatment.DTx <- 0
summaryDF[summaryDF$Treatment == "HSV" & summaryDF$DTx == "PBS",]$Treatment.DTx <- 1
summaryDF[summaryDF$Treatment == "HSV" & summaryDF$DTx == "DTx",]$Treatment.DTx <- 2

summaryDF$Stain.ID <- 0
summaryDF[summaryDF$stain == "OTI-CTV",]$Stain.ID <- 2
summaryDF[summaryDF$stain == "gBT-CTDR",]$Stain.ID <- 1

# plot
ggplot(summaryDF,
       aes(
         # interaction(Treatment, DTx, stain), freq,
         # interaction(Treatment, DTx, stain), median.diff,
         # interaction(Treatment, DTx, stain), n,
         interaction(Treatment, DTx, stain), time,
         fill = as.factor(live.cell.track.clusters.skip3)
         )) +
  theme_classic() +
  # geom_boxplot(outlier.alpha = 0) +
  geom_violin(scale = "width") +
  geom_jitter(
    position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    # width = 0.3, alpha = 0.6) +
  # stat_summary(fun=mean, geom="point", size=3, shape=18, color="Magenta") +
  ylab("Frequency GCAMP+") + xlab("") +
  # ylim(0, 100) +
  scale_fill_brewer(name = NULL, palette = "Set3")
```
