---
title: "Behaviour GCAMP"
output: html_document
date: '2022-08-15'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Show transition states of live cell imaging

```{r}
Sys.setenv(KMP_DUPLICATE_LIB_OK = "TRUE")
devtools::load_all("../")
cciaUse("~/cecelia/dev")

library(ggplot2)
library(tidyverse)
```

```{r}
# set test variables
pID <- "8BR53W"
versionID <- 1
projectsDir <- "/Volumes/USER_data/Dominik/CECELIA_BACKUP/"
hpcDir <- "/data/scratch/projects/punim1124/cecelia/USERS/schienstockd/"
```

```{r}
# HPC config
HPC_CONF <-  list(
  hpc = list(
    conf = list(
      email = "schienstockd@student.unimelb.edu.au",
      emailOnBegin = FALSE,
      emailOnEnd = FALSE,
      emailOnFail = TRUE,
      numNodes = 1,
      numTasks = 1,
      numCPUperTask = 1,
      numGPUperTask = 1,
      memory = 50,
      walltime = "00-06:00:00",
      projectPartitions = "physical",
      # projectPartitions = "gpu-a100",
      projectID = "punim1124",
      # projectID = "punim1031",
      useGPU = FALSE
      # useGPU = TRUE
    )
  ),
  utils = list(
    ssh = list(
      username = "schienstockd",
      address = "spartan.hpc.unimelb.edu.au",
      keyfile = "/Users/Dominik/.ssh/spartan_rsa"
    ),
    python = list(
      condaEnv = cciaConf()$python$conda$source$env
    )
  )
)
```

```{r}
anaDir <- "/Volumes/USER_data/Dominik/Experiments/JL-ANALYSIS/PUBRe/clusterTracks/movement"
```

```{r}
# rename
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

anaDir <- "/Volumes/USER_data/Dominik/Experiments/JL-ANALYSIS/PUBRe/clusterTracks/movement"

# init ccia object
cciaObj <- initCciaObject(
  pID = "8BR53W", uID = "rXctjl", versionID = 1, initReactivity = FALSE
)

# get experimental info
exp.info <- as.data.table(cciaObj$summary(
  withSelf = FALSE, fields = c("Attr")
))

uIDs <- exp.info[Cells == "gDT_gBT" & Include == "Y"]$uID

splitTracks <- list(
  live.cell.track.clusters.hmm_transitions_movement = list(
    track.clustering = list(values = list(1), colour = "#ffff00"),
    track.scanning = list(values = list(0), colour = "#327EBA"),
    track.meandering = list(values = list(2,3), colour = "#AA1F5E"),
    track.others = list(values = list(4,5,6), colour = "#B3BCC2")
    )
  )

channelsToShow <- list(
  "gBT-dsRed" = "gray",
  "gDT-uGFP" = "cyan"
  )
popsToShow <- c("gBT", "gDT")
fileAttrs <- c("Treatment", "dpi")

x <- cciaObj$cciaObjects(uIDs = uIDs)[[1]]
popsAdded <- c()

# add populations to popMap
for (pop in paste0(popsToShow, "/tracked")) {
  popType <- "live"
  parentPops <- c(pop)
  pops <- list()
  
  # create pops from cluster information
  # pops <- mapply(function(x, i) {
  for (j in names(splitTracks)) {
    y <- splitTracks[[j]]
    
    pops <- append(pops, mapply(function(z, k) {
    # mapply(function(y, j) {
      list(
        filterMeasure = j,
        filterValues = z[["values"]],
        filterFun = "eq",
        colour = z[["colour"]]
        # isTrack = TRUE
      )
    }, y, names(y), SIMPLIFY = FALSE))
  }
  
  # add pops
  popsToAdd <- levels(interaction(parentPops, names(pops), sep = "/"))
  popsAdded <- c(popsAdded, popsToAdd)
    
  # remove populations
  x$delPopsByPath(popType, pops = popsToAdd, includeFiltered = TRUE)
  
  # add populations
  x$addFilteredPops(popType, parentPops, pops, valueName = pop)
}

x$popPaths("live", includeFiltered = TRUE)

# save to disk
x$savePops(popType, pops = popsAdded, purge = TRUE, includeFiltered = TRUE)
```

```{r}
# rename
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "rXctjl", versionID = versionID, initReactivity = FALSE # PUB Re
  # pID = pID, uID = "7FUptF", versionID = versionID, initReactivity = FALSE 
  # pID = pID, uID = "qwlRcf", versionID = versionID, initReactivity = FALSE 
)

# go through and correct paths
for (x in cciaObj$cciaObjects()) {
  for (i in x$valueNames("imLabelPropsFilepath")) {
      # if (!any(is.na(stringr::str_match(x$imLabelPropsFilepath(valueName = i), "\\.zarr")))) {
      if (!any(is.na(stringr::str_match(x$imLabelPropsFilepath(valueName = i), "SPACEHOLDER")))) {
        print(paste(x$getUID(), "-", i))

        x$setImLabelPropsFilepath(paste0(i, ".h5ad"), valueName = i, setDefault = FALSE)
        x$setImLabelsFilepath(paste0(i, ".zarr"), valueName = i, setDefault = FALSE)

        x$saveState()
      }
  }
}
```

```{r}
# reloadSources()
# 
# # upload local files
# funVars <- list(
#    # valueName = "tcells.gBT",
#    # valueName = "tcells.P14",
#    valueName = "tcells.OTI",
#    # valueName = "dcs.TRITC",
#    maxSearchRadius = 20,
#    maxLost = 3,
#    accuracy = 0.8,
#    probToAssign = 0.8,
#    noiseInital = 300,
#    noiseProcessing = 100,
#    noiseMeasurements = 100,
#    distThresh = 10,
#    timeThresh = 5,
#    segmentationMissRate = 0.1,
#    lambdaLink = 5,
#    lambdaTime = 5,
#    lambdaDist = 5,
#    thetaTime = 5,
#    thetaDist = 5,
#    minTimepoints = 5,
#    minDisplacement = 10,
#    maxMeanTurningAngle = 0,
#    filters = list(
#      a = list(
#        # measure = c("gBT.CTDR"),
#        measure = c("OTI.CTV"),
#        values = c("20"),
#        fun = c("gt")
#      ),
#      b = list(
#        measure = c("surface_to_volume"),
#        values = c("1.2"),
#        fun = c("lte")
#      )
#      # b = list(
#      #   measure = c("TRITC"),
#      #   # values = c("20"),
#      #   values = c("50"),
#      #   fun = c("gt")
#      # )
#    ),
#    calcTrackingStats = TRUE
# )
# 
# # init ccia object
# cciaObj <- initCciaObject(
#    file.path(
#      projectsDir, pID, "ANALYSIS", versionID, "BeddcR" # GCAMP set
#      # projectsDir, pID, "ANALYSIS", versionID, "ZXcUMO" # DTx
#    ),
#    initReactivity = FALSE
# )
# 
# uIDs <- names(cciaObj$cciaObjects())
# uIDs <- uIDs[!uIDs %in% c(
#    "eSfB5I", "O3IRaQ", "a60Xzu",
#    "aLtS86", # does not work
#    # no TRITC cells
#    "5rIRkE", "HLCoCr", "34Ow8s",
#    "jAndy6", "RH7IVY"
# )]
# # uIDs <- uIDs[!uIDs %in% c(
# #   "1SVENE"
# # )]
# # uIDs <- uIDs[1:which(uIDs == "X2Thus")]
# # uIDs <- uIDs[which(uIDs == "eqGfqA"):length(uIDs)]
# uIDs <- c("63XQHh")
# 
# cciaObj$runTasks(
# # cciaObj$runTask(
#    funName = "tracking.bayesianTracking",
#    funVars = funVars,
#    uIDs = uIDs,
#    runInplace = TRUE
# )
```


```{r}
# HMM
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "rXctjl", versionID = versionID, initReactivity = FALSE
)

# get experimental info
exp.info <- as.data.table(cciaObj$summary(
  withSelf = FALSE, fields = c("Attr")
))

uIDs <- exp.info[Cells == "gDT_gBT" & Include == "Y"]$uID

# run task
funParams <- list(
  popType = "live",
  pops = c("gBT/tracked", "gDT/tracked"),
  # modelMeasurements = c("live.cell.speed", "live.cell.angle"),
  # colName = "movement",
  modelMeasurements = c(
    "surface_area", "volume", "extent", "solidity",
    "ellipticity_interm_oblate", "ellipticity_interm_prolate",
    "compactness", "sphericity"
  ),
  colName = "shape",
  # appendStates = list(live.cell.is.clust = TRUE),
  appendStates = list(),
  skipTimesteps = 0,
  subtrackOverlap = TRUE,
  noiseFilterMeasurements = 5,
  postFiltering = 2,
  postIterations = 2,
  numStates = 3,
  uIDs = uIDs
)

# run task
task <- cciaObj$runTask(
  funName = "behaviourAnalysis.hmmStates",
  funParams = funParams,
  env = "local",
  runInplace = TRUE,
  taskID = 1
)
```

```{r}
# get HMM transitions
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "rXctjl", versionID = versionID, initReactivity = FALSE
)

# get experimental info
exp.info <- as.data.table(cciaObj$summary(
  withSelf = FALSE, fields = c("Attr")
))

uIDs <- exp.info[Cells == "gDT_gBT" & Include == "Y"]$uID

# run task
funParams <- list(
  popType = "live",
  pops = c("gBT/tracked", "gDT/tracked"),
  # colName = "movement",
  # hmmStates = c("movement"),
  colName = "shape",
  hmmStates = c("shape"),
  includeStart = FALSE,
  includeSelfTransitions = TRUE,
  uIDs = uIDs
)

# run task
task <- cciaObj$runTask(
  funName = "behaviourAnalysis.hmmTransitions",
  funParams = funParams,
  env = "local",
  runInplace = TRUE,
  taskID = 1
)
```

```{r}
# cluster tracks based on transitions
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "rXctjl", versionID = versionID, initReactivity = FALSE
)

# get experimental info
exp.info <- as.data.table(cciaObj$summary(
  withSelf = FALSE, fields = c("Attr")
))

uIDs <- exp.info[Cells == "gDT_gBT" & Include == "Y"]$uID

# run task
funParams <- list(
  popType = "live",
  popsToCluster = c("gBT/tracked", "gDT/tracked"),
  # valueName = "tracks.clusters.tcells.hmm_transitions_movement",
  # clusterColName = "hmm_transitions_movement",
  valueName = "tracks.clusters.tcells.movement",
  clusterColName = "movement",
  # valueName = "tracks.clusters.tcells.hmm_transitions_movement_shape",
  # clusterColName = "hmm_transitions_movement_shape",
  # valueName = "tracks.clusters.tcells.hmm_movement",
  # clusterColName = "hmm_movement",
  resolution = 0.2,
  percentile = 99.5,
  trackMeasures = c(
    "speed",
    "duration",
    "trackLength",
    "meanTurningAngle",
    "displacement",
    "straightness",
    "displacementRatio",
    "outreachRatio",
    "asphericity",
    "overallAngle"
  ),
  objectMeasures = c(
    # "extent",
    # "solidity",
    # "integral_mean_curvature",
    # "ellipticity_oblate",
    # "ellipticity_prolate",
    # "ellipticity_interm_oblate",
    # "ellipticity_interm_prolate",
    # "sphericity",
    # HMM states
    # "live.cell.hmm.state.movement",
    # "live.cell.hmm.transitions.movement"
    # "live.cell.hmm.state.shape",
    # "live.cell.hmm.transitions.shape"
    ),
  nMeasures = c(
    ),
  sumMeasures = c(
    ),
  calcMeasures = list(
  ),
  addPops = c(
    ),
  calcLabelProps = TRUE,
  usePaga = FALSE,
  minTracklength = 6,
  # minTracklength = 50,
  uIDs = uIDs
)

# run task
task <- cciaObj$runTask(
  funName = "behaviourAnalysis.clusterTracks",
  funParams = funParams,
  env = "local",
  runInplace = TRUE,
  taskID = 1
)
```

```{r}
library(cecelia)
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "rXctjl", versionID = versionID, initReactivity = FALSE
)

# get experimental info
exp.info <- as.data.table(cciaObj$summary(
  withSelf = FALSE, fields = c("Attr")
))

uIDs <- exp.info[Cells == "gDT_gBT" & Include == "Y"]$uID

# get clustering
tcells.sc <- as.data.table(cciaEnv()$LabelPropsUtils(
  cciaObj$persistentObjectDirectory(),
  # value_name = "tracks.clusters.tcells.movement.sc")$label_props_view()$as_df())
  # value_name = "tracks.clusters.tcells.hmm_movement.sc")$label_props_view()$as_df())
  value_name = "tracks.clusters.tcells.hmm_transitions_movement.sc")$label_props_view()$as_df())

# get popDTs for set
popDTs <- cciaObj$popDT(
  popType = "live", pops = c(
    "gBT/tracked",
    "gDT/tracked"
    ),
  includeFiltered = TRUE,
  flushCache = TRUE,
  uIDs = uIDs)
```

```{r}
# extract percentage of clustering cells
summaryDF <- popDTs %>%
  group_by(uID, pop, live.cell.is.clust) %>%
  summarise(n = n()) %>%
  mutate(freq = n/sum(n) * 100) %>%
  dplyr::filter(live.cell.is.clust == FALSE) %>%
  mutate(freq = 100 - freq) %>%
  left_join(exp.info)

write.csv(summaryDF, file = file.path(anaDir, "freq_clust.csv"))
```

```{r fig_umap, fig.height=4, fig.width=4}
dfToPlot <- copy(tcells.sc) %>% drop_na(clusters) %>% left_join(exp.info)

# get mean positions of clusters
meanClusterPos <- dfToPlot %>%
  group_by(clusters) %>%
  summarise(
    UMAP_1 = mean(UMAP_1),
    UMAP_2 = mean(UMAP_2)
  )
dfToPlot$clusters <- factor(dfToPlot$clusters)

colPal <- randomcoloR::distinctColorPalette(length(unique(dfToPlot$clusters)))

# plot UMAP
ggplot(
  dfToPlot,
  aes(UMAP_1, UMAP_2)
  ) +
  geom_point(aes(color = clusters)) +
  theme_classic() +
  scale_color_manual(values = colPal) +
  theme(
    axis.text = element_text(size = 15),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    legend.position = "none",
    axis.line = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
    ) +
  geom_label(
    data = meanClusterPos,
    aes(label = clusters),
    label.size = 0.25,
    color = "black"
    )

# ggsave(file.path(anaDir, "umap_movement.tiff"), width = 2, height = 2)
# ggsave(file.path(anaDir, "umap_hmm_movement.tiff"), width = 2, height = 2)
ggsave(file.path(anaDir, "umap_hmm_transitions_movement.tiff"), width = 2, height = 2)
```

```{r}
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "rXctjl", versionID = versionID, initReactivity = FALSE # DTx
)

# get experimental info
exp.info <- as.data.table(cciaObj$summary(
  withSelf = FALSE, fields = c("Attr")
))

uIDs <- exp.info[Cells == "gDT_gBT" & Include == "Y"]$uID

# get clustering
tcells.sc <- as.data.table(cciaEnv()$LabelPropsUtils(
  cciaObj$persistentObjectDirectory(),
  value_name = "tracks.clusters.tcells.hmm_transitions_movement.sc")$label_props_view()$as_df())
  # value_name = "tracks.clusters.tcells.hmm_transitions_movement_shape.sc")$label_props_view()$as_df())
  # value_name = "tracks.clusters.tcells.hmm_movement.sc")$label_props_view()$as_df())

# get popDTs for set
popDTs <- cciaObj$popDT(
  popType = "live", pops = c(
    "gBT/tracked",
    "gDT/tracked"
    ),
  includeFiltered = TRUE,
  flushCache = TRUE,
  uIDs = uIDs)
```

```{r}
# how many movies and mice per treatment?
exp.info %>% group_by(Treatment, DTx, Date) %>%
# exp.info %>% group_by(Treatment, DTx) %>%
  summarise(movies = n()) %>%
  group_by(interaction(Treatment, DTx)) %>%
  summarise(
    mice = n(),
    sum_movies = sum(movies)
    ) %>%
  mutate(movies_per_mouse = sum_movies/mice)
```

```{r fig_speed, fig.height=3, fig.width=3}
# plot speed and percentage of clustering cells
summaryDF <- popDTs %>%
  group_by(uID, pop, live.cell.is.clust) %>%
  summarise(n = n()) %>%
  mutate(freq = n/sum(n) * 100) %>%
  dplyr::filter(live.cell.is.clust == FALSE) %>%
  mutate(freq = 100 - freq) %>%
  left_join(exp.info)

summaryDF$Treatment.dpi <- 0
summaryDF[summaryDF$Treatment != "HSV",]$Treatment.dpi <- 0
summaryDF[summaryDF$Treatment == "HSV" & summaryDF$dpi == "1",]$Treatment.dpi <- 1
summaryDF[summaryDF$Treatment == "HSV" & summaryDF$dpi == "2",]$Treatment.dpi <- 2

summaryDF$cell_ID <- 0
summaryDF[summaryDF$pop == "gBT/tracked",]$cell_ID <- 0
summaryDF[summaryDF$pop == "gDT/tracked",]$cell_ID <- 1

write.csv(summaryDF, file = file.path(anaDir, "freq_clust.csv"))
```

```{r}
tracksInfo <- rbindlist(list(
  gBT = cciaObj$tracksInfo("live.cell.speed", parentPop = "gBT/tracked", uIDs = uIDs),
  gDT = cciaObj$tracksInfo("live.cell.speed", parentPop = "gDT/tracked", uIDs = uIDs)
), idcol = "pop")
```


```{r}
# plot speed and percentage of clustering cells
summaryDF <- tracksInfo %>%
  group_by(uID, pop) %>%
  summarise(mean.speed = mean(live.cell.speed.mean, na.rm = TRUE)) %>%
  left_join(exp.info)

summaryDF$Treatment.dpi <- 0
summaryDF[summaryDF$Treatment != "HSV",]$Treatment.dpi <- 0
summaryDF[summaryDF$Treatment == "HSV" & summaryDF$dpi == "1",]$Treatment.dpi <- 1
summaryDF[summaryDF$Treatment == "HSV" & summaryDF$dpi == "2",]$Treatment.dpi <- 2

summaryDF$cell_ID <- 0
summaryDF[summaryDF$pop == "gBT/tracked",]$cell_ID <- 0
summaryDF[summaryDF$pop == "gDT/tracked",]$cell_ID <- 1

write.csv(summaryDF, file = file.path(anaDir, "mean_speed.csv"))
```


```{r fig_hmm_props, fig.height=3, fig.width=3}
# show measurements of clusters to compare
colsToPlot <- rev(c(
  "angle",
  "speed",
  "compactness",
  "extent",
  "oblate",
  "prolate",
  "solidity",
  "sphericity",
  "surface_area",
  "volume"
))

# convert angle to degrees
popDTs[, live.cell.angle_deg := pracma::rad2deg(live.cell.angle)]

propsToPlot <- popDTs[exp.info, on = "uID"] %>%
  dplyr::rename(
    "speed" = "live.cell.speed",
    "angle" = "live.cell.angle_deg",
    "oblate" = "ellipticity_interm_oblate",
    "prolate" = "ellipticity_interm_prolate"
  ) %>%
  # drop_na(live.cell.hmm.state.hybrid_pop) %>%
  pivot_longer(
    cols = colsToPlot, names_to = "prop", values_to = "value"
    ) %>%
  pivot_longer(
    cols = c(
      "live.cell.hmm.state.movement"
      # "live.cell.hmm.state.shape"
    ), names_to = "hmm_type", values_to = "hmm_value"
    )

propsToPlot$prop <- factor(propsToPlot$prop, levels = colsToPlot)

# show heatmap for HMM
propsSummary <- propsToPlot %>%
  dplyr::filter(!is.na(hmm_value)) %>%
  group_by(hmm_type, hmm_value, prop) %>%
  replace_na(list(value = 0)) %>%
  summarise(mean = mean(value)) %>%
  group_by(hmm_type, prop) %>%
  mutate(freq = (mean - min(mean)) / (max(mean) - min(mean))) %>%
  arrange(-prop)

ggplot(propsSummary %>% dplyr::filter(hmm_value != "Clustering"), aes(as.factor(hmm_value), prop)) +
  theme_classic() +
  geom_tile(aes(fill = freq), colour = "white", size = 0.5) +
  viridis::scale_fill_viridis(
    breaks = c(0, 1),
    labels = c(0, 1)
  ) +
  theme(
    legend.position = "none",
    legend.title = element_blank(),
    legend.text = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    axis.text.x = element_text(size = 12),
    strip.background = element_blank(),
    strip.text.x = element_blank(),
    # axis.text.x = element_text(size = 12, angle = 45, hjust = 1, vjust = 1)
    ) +
  xlab("") + ylab("") +
  facet_grid(.~hmm_type)

ggsave(file.path(anaDir, "HMM_heat.pdf"), width = 2.3, height = 3)
# ggsave(file.path(anaDir, "HMM_heat_shape.pdf"), width = 2.3, height = 3)
```

```{r}
clusterMapping <- list(
  # Clustering = c(1),
  # Directed = c(2,6),
  # Meandering = c(3,4),
  # Scanning = c(0,5)
  Clustering = c(1),
  Scanning = c(0,5),
  Meandering = c(2,6),
  Others = c(4,3)
)
```


```{r fig_umap, fig.height=8, fig.width=8}
dfToPlot <- copy(tcells.sc) %>% drop_na(clusters) %>% left_join(exp.info)

dfToPlot <- .mapClustNames(dfToPlot, clusterMapping, "clusters")

# get mean positions of clusters
meanClusterPos <- dfToPlot %>%
  group_by(clusters) %>%
  # group_by(clusters.name) %>%
  summarise(
    UMAP_1 = mean(UMAP_1),
    UMAP_2 = mean(UMAP_2)
  )
dfToPlot$clusters <- factor(dfToPlot$clusters)

# colPal <- randomcoloR::distinctColorPalette(length(unique(dfToPlot$clusters)))
colPal <- c(
  Clustering = "#ffff00",
  Scanning = "#327EBA",
  Meandering = "#AA1F5E",
  Others = "#B3BCC2"
)

# plot UMAP
ggplot(
  dfToPlot,
  aes(UMAP_1, UMAP_2)
  ) +
  # geom_point(aes(color = clusters)) +
  geom_point(aes(color = clusters.name)) +
  theme_classic() +
  # scale_color_brewer(name = NULL, palette = "Set1") +
  scale_color_manual(values = colPal) +
  theme(
    axis.text = element_text(size = 15),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    legend.justification = "right",
    # legend.position = "bottom"
    legend.position = "none",
    axis.line = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
    ) 
  # geom_label(
  #   data = meanClusterPos,
  #   aes(label = clusters),
  #   # aes(label = clusters.name),
  #   label.size = 0.25,
  #   color = "black"
  #   )

# # ggsave(file.path(anaDir, "umap.tiff"), width = 2, height = 2)
ggsave(file.path(anaDir, "umap_wo_labels.tiff"), width = 2, height = 2)
# ggsave(file.path(anaDir, "umap_shape.tiff"), width = 2, height = 2)
# ggsave(file.path(anaDir, "umap_shape_wo_labels.tiff"), width = 2, height = 2)
```

```{r fig_umap_props, fig.height=4, fig.width=4}
datToPlot <- copy(tcells.sc) %>%
  drop_na(clusters) %>%
  left_join(exp.info)

# plot UMAP
ggplot(datToPlot, aes(UMAP_1, UMAP_2)) +
  theme_classic() +
  # geom_point(aes(color = speed), size = 1, alpha = 1) +
  geom_point(aes(color = meanTurningAngle), size = 1, alpha = 1) +
  viridis::scale_color_viridis() +
  theme(
    axis.text = element_text(size = 15),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    legend.justification = "right",
    # legend.position = "bottom"
    legend.position = "none",
    axis.line = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
    )

# ggsave(file.path(anaDir, paste0("umap_Velocity.tiff")), width = 2, height = 2)
ggsave(file.path(anaDir, paste0("umap_Angle.tiff")), width = 2, height = 2)
```

```{r fig_umap, fig.height=4, fig.width=4}
plot.p1 <- function(df.all, df.subsets) {
  p1 <- ggplot(df.all, aes(UMAP_1, UMAP_2)) +
    theme_classic() +
    geom_point(color = "black", size = 1) +
    theme(
      axis.text = element_text(size = 15),
      axis.text.x = element_blank(),
      axis.ticks.x = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank(),
      legend.justification = "right",
      # legend.position = "bottom"
      legend.position = "none",
      axis.line = element_blank(),
      axis.title.x = element_blank(),
      axis.title.y = element_blank()
      )
  
  # add points
  for (i in seq(length(df.subsets))) {
    x <- df.subsets[[i]]$data
    colramp <- df.subsets[[i]]$colramp
    
    p1 <- p1 + geom_point(
      data = x, size = 1, alpha = 1,
      # color = .flowColours(x$UMAP_1, x$UMAP_2, colramp = colramp))
      color = df.subsets[[i]]$colramp)
  }
  
  p1
}

datToPlot <- copy(tcells.sc) %>%
  drop_na(clusters) %>%
  left_join(exp.info)

# plot UMAP
plot.p1(datToPlot, list(
    list(data = datToPlot %>% dplyr::filter(pop == "gDT/tracked", Treatment != "HSV"),
       # colramp = viridisLite::mako),
       colramp = "#4682b4"),
  list(data = datToPlot %>% dplyr::filter(pop == "gBT/tracked", Treatment != "HSV"),
       # colramp = viridisLite::inferno)
       colramp = "#AA1F5E")
))
ggsave(file.path(anaDir, paste0("umap_Uninf.tiff")), width = 2, height = 2)
plot.p1(datToPlot, list(
    list(data = datToPlot %>% dplyr::filter(pop == "gDT/tracked", Treatment == "HSV" & dpi == "1"),
       # colramp = viridisLite::mako),
       colramp = "#4682b4"),
  list(data = datToPlot %>% dplyr::filter(pop == "gBT/tracked", Treatment == "HSV" & dpi == "1"),
       # colramp = viridisLite::inferno)
       colramp = "#AA1F5E")
))
ggsave(file.path(anaDir, paste0("umap_HSV_1.tiff")), width = 2, height = 2)
plot.p1(datToPlot, list(
    list(data = datToPlot %>% dplyr::filter(pop == "gDT/tracked", Treatment == "HSV" & dpi == "2"),
       # colramp = viridisLite::mako),
       colramp = "#4682b4"),
  list(data = datToPlot %>% dplyr::filter(pop == "gBT/tracked", Treatment == "HSV" & dpi == "2"),
       # colramp = viridisLite::inferno)
       colramp = "#AA1F5E")
))
ggsave(file.path(anaDir, paste0("umap_HSV_2.tiff")), width = 2, height = 2)
```

```{r}
# show measurements of clusters to compare
propsToPlot <- copy(tcells.sc)

# propsToPlot <- propsToPlot %>%
#   dplyr::rename(
#     "Movement HMM 1" = "live.cell.hmm.state.movement.1",
#     "Movement HMM 2" = "live.cell.hmm.state.movement.2",
#     "Movement HMM 3" = "live.cell.hmm.state.movement.3",
#     "Movement HMM 4" = "live.cell.hmm.state.movement.4",
#   )

colsToPlot <- colnames(propsToPlot)[!colnames(propsToPlot) %in% c(
  "pop", "uID", "track_id", "clusters", "UMAP_1", "UMAP_2"
  )]

propsToPlot <- propsToPlot %>%
  pivot_longer(
    cols = colsToPlot, names_to = "prop", values_to = "value"
    )

propsToPlot$prop <- factor(propsToPlot$prop, levels = sort(colsToPlot, decreasing = TRUE))

# propsToPlot <- .mapClustNames(propsToPlot, clusterMapping, "clusters")

# propsList <- c(
#   'Movement HMM 1',
#   'Movement HMM 2',
#   'Movement HMM 3',
#   'Movement HMM 4',
#   'asphericity',
#   'displacement',
#   'displacementRatio',
#   'duration',
#   'meanTurningAngle',
#   'outreachRatio',
#   'overallAngle',
#   'speed',
#   'straightness',
#   'trackLength'
# )

# show heatmap for clusters
propsSummary <- propsToPlot %>%
  dplyr::filter(
    # clusters.name != "NONE",
    # prop %in% propsList
    ) %>%
  group_by(clusters, prop) %>%
  # group_by(clusters.name, prop) %>%
  summarise(mean = mean(value, rm.na = TRUE)) %>%
  group_by(prop) %>%
  mutate(freq = (mean - min(mean)) / (max(mean) - min(mean))) %>%
  arrange(-prop)
```

```{r fig_clusters_heat, fig.height=8, fig.width=6}
# propsSummary$prop <- factor(
#   propsSummary$prop, levels = rev(propsList))
# propsSummary$clusters.name <- factor(
#   propsSummary$clusters.name, levels = c(
#     "Directed", "Meandering", "Scanning", "Clustering"
#   ))

# # sort states
# propsSummary[!propsSummary$clusters %in% clusterOrder[clusterOrder != 1],]$clusters <- NA
# # propsSummary$clusters <- factor(propsSummary$clusters, levels = clusterOrder)
# propsSummary$clusters <- case_match(
#   as.character(propsSummary$clusters),
#   c("3") ~ "1",
#   c("6") ~ "2",
#   c("0") ~ "3",
#   c("7") ~ "4",
#   c("2") ~ "5",
#   c("5") ~ "6",
#   c("4") ~ "7",
# )

# ggplot(propsSummary, aes(as.factor(clusters.name), prop)) +
# ggplot(propsSummary, aes(as.factor(clusters), prop)) +
ggplot(propsSummary %>%
         dplyr::filter(!str_detect(prop, "live.cell")) %>%
         drop_na(clusters), aes(clusters, prop)) +
         # drop_na(clusters.name), aes(clusters.name, prop)) +
  theme_classic() +
  geom_tile(aes(fill = freq), colour = "white", size = 0.5) +
  viridis::scale_fill_viridis(
    breaks = c(0, 1),
    labels = c(0, 1)
  ) +
  theme(
    legend.position = "none",
    legend.key.size = unit(8, "mm"),
    legend.title = element_blank(),
    legend.text = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    # axis.text.x = element_text(size = 12),
    axis.text.x = element_text(size = 12, angle = 45, hjust = 1, vjust = 1),
    strip.background = element_blank(),
    strip.text.x = element_blank()
    ) +
  xlab("") + ylab("")

ggsave(file.path(anaDir, "clusters_heat.pdf"), width = 3, height = 2.5)
# ggsave(file.path(anaDir, "pops_heat.pdf"), width = 2.7, height = 3)
# ggsave(file.path(anaDir, "clusters_heat.pdf"), width = 5, height = 14)
```

```{r fig_clusters_heat, fig.height=2, fig.width=6}
# get frequencies of HMM for each cluster
# and plot as bar graphs
datToPlot <- popDTs %>%
  mutate(live.cell.track.clusters.hmm_transitions_movement = as.numeric(as.character(
    live.cell.track.clusters.hmm_transitions_movement))) %>%
  drop_na(live.cell.track.clusters.hmm_transitions_movement) %>%
  drop_na(live.cell.hmm.state.movement) %>%
  group_by(live.cell.track.clusters.hmm_transitions_movement, live.cell.hmm.state.movement) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n) * 1) %>%
  ungroup() %>%
  complete(live.cell.track.clusters.hmm_transitions_movement, live.cell.hmm.state.movement, fill = list(freq = 0))

write.csv(datToPlot, file = file.path(anaDir, "freq_hmm.csv"))

ggplot(datToPlot, aes(as.factor(live.cell.track.clusters.hmm_transitions_movement), freq,
                      fill = as.factor(live.cell.hmm.state.movement))) +
  theme_classic() +
  # scale_fill_brewer(palette = "Accent") +
  scale_fill_manual(values = wesanderson::wes_palette(name = "Darjeeling2")) +
  theme_classic() +
  geom_bar(stat = "identity", width = 1, color = "black", size = 0.4) +
  theme(
    # legend.position = "none",
    legend.position = "right",
    legend.key.size = unit(6, "mm"),
    legend.title = element_blank(),
    legend.text = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    axis.text.x = element_text(size = 12),
    # axis.text.x = element_text(size = 12, angle = 45, hjust = 1, vjust = 1),
    strip.background = element_blank(),
    # strip.text.x = element_blank()
    strip.text.x = element_text(size = 12)
    ) +
  scale_y_continuous(breaks = c(0, 0.5, 1)) +
  # scale_fill_discrete(name = "HMM State") +
  xlab("") + ylab("") 

ggsave(file.path(anaDir, "clusters_hmm_heat.pdf"), width = 3, height = 1.5)
```

```{r fig_clusters_heat, fig.height=3, fig.width=8}
# get frequencies of HMM for each cluster
# and plot as bar graphs
datToPlot <- popDTs %>%
  mutate(
    live.cell.track.clusters.hmm_transitions_movement = as.numeric(as.character(
      live.cell.track.clusters.hmm_transitions_movement)),
    live.cell.hmm.transitions.movement = as.character(
      live.cell.hmm.transitions.movement)
    ) %>%
  drop_na(live.cell.track.clusters.hmm_transitions_movement) %>%
  dplyr::filter(live.cell.hmm.transitions.movement != "NA") %>%
  # group_by(live.cell.track.clusters.hmm_transitions_movement, from, to) %>%
  # dplyr::filter(!live.cell.hmm.transitions.movement %in% paste0(seq(4), "_", seq(4))) %>%
  group_by(live.cell.track.clusters.hmm_transitions_movement, live.cell.hmm.transitions.movement) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n) * 1) %>%
  separate_wider_delim(
    live.cell.hmm.transitions.movement, delim = "_", names = c("from", "to"))
  # ungroup() %>%
  # complete(live.cell.track.clusters.hmm_transitions_movement, from, to, fill = list(freq = 0))

ggplot(datToPlot, aes(as.factor(from), as.factor(to), size = freq * 2, fill = freq)) +
  theme_classic() +
  # scale_fill_brewer(palette = "Accent") +
  # scale_y_continuous(breaks = c(0, 0.5, 1)) +
  geom_vline(xintercept = as.factor(1:4), color = "#d3d3d3") +
  geom_hline(yintercept = as.factor(1:4), color = "#d3d3d3") +
  geom_point(pch = 21, color = "black") +
  # viridis::scale_fill_viridis() +
  scale_fill_gradient2(
    midpoint = 0.5, low="blue", mid="white", high="red", space ="Lab") +
  theme(
    legend.position = "none",
    # legend.position = "right",
    legend.key.size = unit(6, "mm"),
    legend.title = element_blank(),
    legend.text = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    axis.text.x = element_text(size = 12),
    # axis.text.x = element_text(size = 12, angle = 45, hjust = 1, vjust = 1),
    strip.background = element_blank(),
    # strip.text.x = element_blank()
    strip.text.x = element_text(size = 12)
    ) +
  # scale_fill_discrete(name = "HMM State") +
  xlab("From state") + ylab("To state") +
  facet_wrap(.~live.cell.track.clusters.hmm_transitions_movement, nrow = 2)

ggsave(file.path(anaDir, "clusters_transitions_heat.pdf"), width = 4, height = 3)
```

```{r fig_clusters_freq, fig.height=4, fig.width=15}
# save frequencies of track clusters
summaryDF <- copy(tcells.sc)

summaryDF <- .mapClustNames(summaryDF, clusterMapping, "clusters")

# show frequency of clusters
# summaryDF <- summaryDF[, .(n.clusters = .N), by = .(uID, pop, clusters)] %>%
summaryDF <- summaryDF[, .(n.clusters = .N), by = .(uID, pop, clusters.name)] %>%
  droplevels() %>%
  group_by(uID, pop) %>%
  mutate(freq.clusters = n.clusters/sum(n.clusters) * 100) %>%
  ungroup() %>%
  # complete(uID, pop, clusters, fill = list(freq.clusters = 0)) %>%
  complete(uID, pop, clusters.name, fill = list(freq.clusters = 0)) %>%
  left_join(exp.info)

# ggplot(summaryDF, aes(clusters, freq.clusters, color = interaction(Treatment, dpi))) +
ggplot(summaryDF, aes(clusters.name, freq.clusters, color = interaction(Treatment, dpi))) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
  scale_color_brewer(name = "Treatment", palette = "Set1") +
  facet_grid(.~pop)

ggsave(file.path(anaDir, "clusters_freq.pdf"), width = 10, height = 3)

summaryDF$Treatment.dpi <- 0
summaryDF[summaryDF$Treatment != "HSV",]$Treatment.dpi <- 0
summaryDF[summaryDF$Treatment == "HSV" & summaryDF$dpi == "1",]$Treatment.dpi <- 1
summaryDF[summaryDF$Treatment == "HSV" & summaryDF$dpi == "2",]$Treatment.dpi <- 2

summaryDF$cell_ID <- 0
summaryDF[summaryDF$pop == "gBT/tracked",]$cell_ID <- 0
summaryDF[summaryDF$pop == "gDT/tracked",]$cell_ID <- 1

summaryDF$clusters.id <- as.numeric(summaryDF$clusters.name)

write.csv(summaryDF[summaryDF$cell_ID == 0,],
          file = file.path(anaDir, "freq_clusters_gBT.csv"))
write.csv(summaryDF[summaryDF$cell_ID == 1,],
          file = file.path(anaDir, "freq_clusters_gDT.csv"))
```

```{r fig_gDT_behaviour, fig.height=4, fig.width=6}
# with which cell types are these clusters in contact?
popDTs[popDTs[pop == "tcells.gBT/tracked", c("uID", "label", "track_id")],
       on = c("uID", "live.cell.contact_id#live.tcells.gBT/tracked" = "label"),
       contact.track := i.track_id]

popDTs[tcells.sc[pop == "tcells.gBT/tracked", c("uID", "track_id", "clusters")],
       on = c("uID", "contact.track" = "track_id"),
       contact.clusters := i.clusters]
```


```{r fig_gDT_behaviour, fig.height=3, fig.width=12}
clusterContacts <- popDTs %>%
  left_join(tcells.sc)

clusterContacts$contact.cell.cluster <- FALSE
clusterContacts[clusterContacts$contact.clusters == 3, ]$contact.cell.cluster <- TRUE

# get percentage of track in contact with clusters
freqClustContact <- clusterContacts %>%
  group_by(uID, pop, track_id, contact.cell.cluster) %>%
  summarise(n = n()) %>%
  mutate(freq.non.contact.cell.cluster = n/sum(n) * 100) %>%
  dplyr::filter(contact.cell.cluster == FALSE)

clusterContacts <- copy(tcells.sc)

clusterContacts$clusters.name <- "NONE"
propsToPlot[propsToPlot$clusters %in% c(2,3,7,8), ]$clusters.name <- "Directed"
propsToPlot[propsToPlot$clusters %in% c(4), ]$clusters.name <- "Meandering"
propsToPlot[propsToPlot$clusters %in% c(0,5,6), ]$clusters.name <- "Scanning"
propsToPlot[propsToPlot$clusters %in% c(1), ]$clusters.name <- "Clustering"

clusterContacts <- clusterContacts %>%
  dplyr::filter(clusters.name != "NONE", pop == "tcells.gDT/tracked") %>%
  left_join(freqClustContact)

clusterContacts$contact.cell.cluster <- FALSE
clusterContacts[clusterContacts$freq.non.contact.cell.cluster < 100, ]$contact.cell.cluster <- TRUE

clusterContacts <- clusterContacts %>%
  # group_by(uID, pop, clusters, contact.clusters) %>%
  group_by(uID, pop, contact.cell.cluster, clusters) %>%
  summarise(n = n()) %>%
  mutate(freq = n/sum(n) * 100) %>%
  ungroup() %>%
  complete(
    uID, contact.cell.cluster, clusters,
    fill = list(freq = 0)) %>%
  left_join(exp.info)

ggplot(clusterContacts, 
       # aes(as.factor(clusters), freq.contact.clusters,
       aes(as.factor(clusters), freq, color = interaction(Treatment, DTx))) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
  ylab("Behaviour (%)") + xlab("gDT cluster") + ylim(0, 100) +
  scale_color_brewer(name = NULL, palette = "Set1") +
  facet_grid(.~contact.cell.cluster)

ggsave(file.path(anaDir, "gDT_behaviour_visiting_gBT_cluster.png"), height = 2, width = 12)
```