---
title: "Behaviour GCAMP"
output: html_document
date: '2022-08-15'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Show transition states of live cell imaging

```{r}
devtools::load_all("../")
cciaUse("~/cecelia/dev")

library(ggplot2)
library(tidyverse)
```

```{r}
# set test variables
pID <- "8BR53W"
versionID <- 1
projectsDir <- "/Volumes/Analysis_SSD/Dominik/cecelia/projects/"
hpcDir <- "/data/scratch/projects/punim1124/cecelia/USERS/schienstockd/"
```

```{r}
anaDir <- "/Volumes/USER_data/Dominik/Experiments/SAPNA_SNS_2P/CECELIA"
```

```{r}
# # adjust segmentation names
# devtools::load_all("../")
# cciaUse("~/cecelia/dev", initConda = FALSE)
# 
# # init ccia object
# cciaObj <- initCciaObject(
#   pID = pID, uID = "LUw0Nx", versionID = versionID, initReactivity = FALSE # SNS
# )
# 
# # get experimental info
# exp.info <- cciaObj$summary(
#   withSelf = FALSE, fields = c("Attr")
# )
# 
# uIDs <- exp.info[exp.info$Treatment == "iso",]$uID
# 
# for (x in cciaObj$cciaObjects(uIDs = uIDs)) {
#   x.rds <- readRDS(x$persistentObjectDirectoryFile("ccid.rds"))
# 
#   names(x.rds$CciaMeta$imLabelsFilepath) <- c("T.A", "T.B")
#   x.rds$CciaMeta$imLabelsFilepath$T.A <- "T.A.zarr"
#   x.rds$CciaMeta$imLabelsFilepath$T.B <- "T.B.zarr"
#   try(system(paste(
#     'mv',
#     x$persistentObjectDirectoryFile("labels/tcells.A.zarr"),
#     x$persistentObjectDirectoryFile("labels/T.A.zarr"))))
#   try(system(paste(
#     'mv',
#     x$persistentObjectDirectoryFile("labels/tcells.B.zarr"),
#     x$persistentObjectDirectoryFile("labels/T.B.zarr"))))
# 
#   names(x.rds$CciaMeta$imLabelPropsFilepath) <- c("T.A", "T.B")
#   x.rds$CciaMeta$imLabelPropsFilepath$T.A <- "T.A.h5ad"
#   x.rds$CciaMeta$imLabelPropsFilepath$T.B <- "T.B.h5ad"
#   try(system(paste(
#     'mv',
#     x$persistentObjectDirectoryFile("labelProps/tcells.A.h5ad"),
#     x$persistentObjectDirectoryFile("labelProps/T.A.h5ad"))))
#   try(system(paste(
#     'mv',
#     x$persistentObjectDirectoryFile("labelProps/tcells.B.h5ad"),
#     x$persistentObjectDirectoryFile("labelProps/T.B.h5ad"))))
# 
#   if (length(x.rds$CciaMeta$imPopMap$live) > 1) {
#     x.rds$CciaMeta$imPopMap$live[[1]]$parent <- "T.A"
#     x.rds$CciaMeta$imPopMap$live[[1]]$path <- "T.A/tracked"
#     x.rds$CciaMeta$imPopMap$live[[1]]$valueName <- "T.A"
#     x.rds$CciaMeta$imPopMap$live[[2]]$parent <- "T.B"
#     x.rds$CciaMeta$imPopMap$live[[2]]$path <- "T.B/tracked"
#     x.rds$CciaMeta$imPopMap$live[[2]]$valueName <- "T.B"
# 
#     saveRDS(x.rds, x$persistentObjectDirectoryFile("ccid.rds"))
#   }
# }
```


```{r}
# devtools::load_all("../")
# cciaUse("~/cecelia/dev", initConda = FALSE)
# 
# # init ccia object
# cciaObj <- initCciaObject(
#   pID = pID, uID = "LUw0Nx", versionID = versionID, initReactivity = FALSE # SNS
# )
# 
# # get experimental info
# exp.info <- cciaObj$summary(
#   withSelf = FALSE, fields = c("Attr")
# )
# 
# uIDs <- exp.info[exp.info$Include == "Y" & exp.info$Treatment == "Sal",]$uID
# 
# for (x in cciaObj$cciaObjects(uIDs = uIDs)) {
#   x$savePopMap("live", includeFiltered = TRUE)
# }
```

```{r}
# HMM 
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "oPZZCg", versionID = versionID, initReactivity = FALSE 
)

# cciaObj$setImLabelPropsFilepath("T.A.h5ad", valueName = "T.A", setDefault = FALSE)
# cciaObj$setImLabelsFilepath("T.A.zarr", valueName = "T.A", setDefault = FALSE)
# cciaObj$saveState()
cciaObj$omeXMLTimelapseInfo()
```

```{r}
# HMM 
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "LUw0Nx", versionID = versionID, initReactivity = FALSE 
)

# get experimental info
exp.info <- cciaObj$summary(
  withSelf = FALSE, fields = c("Attr")
)

uIDs <- exp.info[exp.info$Include == "Y" & exp.info$Treatment == "Sal",]$uID

# run task
funParams <- list(
  popType = "live",
  pops = c("T.A/tracked", "T.B/tracked"),
  modelMeasurements = c("live.cell.speed", "live.cell.angle"),
  colName = "movement",
  skipTimesteps = 0,
  subtrackOverlap = TRUE,
  noiseFilterMeasurements = 5,
  postFiltering = 2,
  postIterations = 2,
  numStates = 4,
  uIDs = uIDs
)

# run task
task <- cciaObj$runTask(
  funName = "behaviourAnalysis.hmmStates",
  funParams = funParams,
  env = "local",
  runInplace = TRUE,
  taskID = 1
)
```

```{r}
# get HMM transitions
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "LUw0Nx", versionID = versionID, initReactivity = FALSE 
)

# get experimental info
exp.info <- cciaObj$summary(
  withSelf = FALSE, fields = c("Attr")
)

uIDs <- exp.info[exp.info$Include == "Y" & exp.info$Treatment == "Sal",]$uID

# run task
funParams <- list(
  popType = "live",
  pops = c("T.A/tracked", "T.B/tracked"),
  modelMeasurements = c("live.cell.speed", "live.cell.angle"),
  colName = "movement",
  hmmStates = c("movement"),
  includeStart = FALSE,
  includeSelfTransitions = TRUE,
  uIDs = uIDs
)

# run task
task <- cciaObj$runTask(
  funName = "behaviourAnalysis.hmmTransitions",
  funParams = funParams,
  env = "local",
  runInplace = TRUE,
  taskID = 1
)
```

```{r}
# cluster tracks based on transitions
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "LUw0Nx", versionID = versionID, initReactivity = FALSE 
)

# get experimental info
exp.info <- cciaObj$summary(
  withSelf = FALSE, fields = c("Attr")
)

uIDs <- exp.info[exp.info$Include == "Y" & exp.info$Treatment == "Sal",]$uID

# run task
funParams <- list(
  popType = "live",
  popsToCluster = c("T.A/tracked", "T.B/tracked"),
  # valueName = "tracks.clusters.tcells.hmm_transitions_movement",
  # clusterColName = "hmm_transitions_movement",
  valueName = "tracks.clusters.tcells.hmm_movement",
  clusterColName = "hmm_movement",
  resolution = 0.20,
  percentile = 99.5,
  trackMeasures = c(
    "speed",
    "duration",
    "trackLength",
    "meanTurningAngle",
    "displacement",
    "straightness",
    "displacementRatio",
    "outreachRatio",
    "asphericity",
    "overallAngle"
  ),
  objectMeasures = c(
    # "extent",
    # "solidity",
    # "integral_mean_curvature",
    # "ellipticity_oblate",
    # "ellipticity_prolate",
    # "ellipticity_interm_oblate",
    # "ellipticity_interm_prolate",
    # "sphericity",
    # HMM states
    "live.cell.hmm.state.movement"
    # "live.cell.hmm.transitions.movement"
    ),
  nMeasures = c(
    ),
  sumMeasures = c(
    ),
  calcMeasures = list(
  ),
  addPops = c(
    ),
  calcLabelProps = TRUE,
  # usePaga = FALSE,
  usePaga = TRUE,
  pagaThreshold = 0.1,
  minTracklength = 6,
  # minTracklength = 50,
  uIDs = uIDs
)

# run task
task <- cciaObj$runTask(
  funName = "behaviourAnalysis.clusterTracks",
  funParams = funParams,
  env = "local",
  runInplace = TRUE,
  taskID = 1
)
```

```{r}
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "LUw0Nx", versionID = versionID, initReactivity = FALSE # SNS
)

# get experimental info
exp.info <- cciaObj$summary(
  withSelf = FALSE, fields = c("Attr")
)

uIDs <- exp.info[exp.info$Include == "Y" & exp.info$Treatment == "Sal",]$uID

# get clustering
tcells.sc <- as.data.table(cciaEnv()$LabelPropsUtils(
  cciaObj$persistentObjectDirectory(),
  # value_name = "tracks.clusters.tcells.hmm_transitions_movement.sc")$label_props_view()$as_df())
  value_name = "tracks.clusters.tcells.hmm_movement.sc")$label_props_view()$as_df())

# get popDTs for set
popDTs <- cciaObj$popDT(
  popType = "live", pops = c(
    "T.A/tracked",
    "T.B/tracked"
    ),
  includeFiltered = TRUE,
  flushCache = TRUE,
  uIDs = uIDs)
```

```{r fig_cluster_freq, fig.height=2, fig.width=5}
# can you show the frequencies of behaviour clusters?
# summaryDF <- .mapClustNames(popDTs, clusterMapping, "live.cell.track.clusters.hmm_transitions_movement")

summaryDF <- summaryDF %>% group_by(uID, clusters.name) %>%
  dplyr::filter(clusters.name != "NONE") %>%
  summarise(n = n()) %>%
  mutate(freq = n/sum(n) * 100) %>%
  ungroup() %>%
  complete(uID, clusters.name, fill = list(freq = 0)) %>%
  left_join(exp.info) %>%
  dplyr::filter(Treatment == "Sal")

# plot
# ggplot(summaryDF, aes(live.cell.track.clusters.hmm_transitions_movement, freq,
#          fill = as.factor(live.cell.track.clusters.hmm_transitions_movement))) +
ggplot(summaryDF, aes(clusters.name, freq,
         fill = as.factor(clusters.name))) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    # width = 0.3, alpha = 0.6) +
  # stat_summary(fun=mean, geom="point", size=3, shape=18, color="Magenta") +
  ylab("Freq") + xlab("") +
  # ylim(0, 1) +
  scale_fill_brewer(name = NULL, palette = "Set3")

summaryDF$cluster.ID <- 0
summaryDF[summaryDF$clusters.name == "Arrested", ]$cluster.ID <- 1
summaryDF[summaryDF$clusters.name == "Stopping", ]$cluster.ID <- 2
summaryDF[summaryDF$clusters.name == "Meandering", ]$cluster.ID <- 3
summaryDF[summaryDF$clusters.name == "Directed", ]$cluster.ID <- 4

write.csv(summaryDF %>% arrange(cluster.ID), file.path(anaDir, "clusters_freq.csv"))
```


```{r fig_tracks_hmm, fig.height=8, fig.width=8}
# plot tracks for each and HMM time
datToPlot <- popDTs[uID == "uZv4t8"]
datToPlot <- datToPlot %>%
  left_join(
    datToPlot %>%
      group_by(uID, value_name, track_id) %>%
      summarise(n = n(), min_t = min(centroid_t))
  )

ggplot(datToPlot %>% filter(n > 50, min_t <= 20),
       aes(as.factor(centroid_t), as.factor(track_id))) +
  theme_classic() +
  geom_tile(aes(fill = as.factor(live.cell.hmm.state.movement))) +
  scale_fill_brewer(palette = "Set1")

ggplot(datToPlot %>% filter(n > 50, min_t <= 20),
       aes(as.factor(centroid_t), as.factor(track_id))) +
  theme_classic() +
  geom_tile(aes(fill = as.factor(live.cell.track.clusters.hmm_transitions_movement))) +
  scale_fill_brewer(palette = "Set1")
  # viridis::scale_fill_viridis(
  #   breaks = c(0, 1),
  #   labels = c(0, 1)
  # ) +
  # theme(
  #   # legend.position = "none",
  #   legend.title = element_blank(),
  #   legend.text = element_text(size = 12),
  #   axis.text.y = element_text(size = 12),
  #   axis.text.x = element_text(size = 12),
  #   strip.background = element_blank(),
  #   strip.text.x = element_blank(),
  #   # axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)
  #   ) +
  # xlab("") + ylab("")
```

```{r fig_total_transitions, fig.height=1, fig.width=5}
library(ggplot2)
library(ggraph)

freqThr <- 0.001

pList <- list()

stateOrder <- list(
  "M" = "2",
  "S" = "3",
  "A" = "1"
)

summaryDF <- popDTs %>%
  left_join(exp.info)

summaryDF$cell_type <- str_extract(summaryDF$pop, "(?<=\\.)[:alnum:]+(?=/)")
summaryDF$stain <- str_extract(
  summaryDF$staining, sprintf("%s-[:alnum:]+", summaryDF$cell_type)
  )
summaryDF$stain[is.na(summaryDF$stain)] <- "gBT-CTV"

summaryDF <- .mapClustNames(summaryDF, clusterMapping, "live.cell.track.clusters.hmm_transitions_movement")

# for (x in unique(summaryDF$live.cell.track.clusters.hmm_transitions_movement)) {
for (x in unique(summaryDF$clusters.name)) {
  # plot heatmap of transitions
  DF <- summaryDF %>%
    # dplyr::filter(live.cell.track.clusters.hmm_transitions_movement == x) %>%
    dplyr::filter(clusters.name == x) %>%
    group_by(live.cell.hmm.transitions.movement) %>%
    summarise(n = n()) %>%
    separate(live.cell.hmm.transitions.movement,
             into = c("from", "to"),
             sep = "_", convert = TRUE) %>%
    mutate(across(c(from, to), as.character)) %>%
    replace_na(list(from = "0"))
  
  # edges for non-self transitions
  edges <- DF %>%
    dplyr::filter(from != to) %>%
    mutate(freq = n/sum(n)) %>%
    complete(from, to, fill = list(freq = 0)) %>%
    drop_na() %>%
    dplyr::filter(freq > freqThr) %>%
    mutate(non.self = (freq - min(freq)) / (max(freq) - min(freq))) %>%
    arrange(freq)
  
  # get number of self transitions
  nodes <- DF %>%
    dplyr::filter(from == to) %>%
    mutate(freq = n/sum(n)) %>%
    complete(from = unlist(stateOrder), fill = list(freq = 0)) %>%
    replace_na(list(to = "0")) %>%
    select(from, freq) %>%
    dplyr::rename(node = from) %>%
    add_row(node = "0", freq = 0) %>%
    mutate(nodeName = node) %>%
    dplyr::filter(node %in% unique(c(edges$from, edges$to))) %>%
    mutate(self = (freq - min(freq)) / (max(freq) - min(freq)))
  
  # add names for nodes
  for (i in names(stateOrder)) {
    nodes[nodes$nodeName == stateOrder[[i]], ]$nodeName <- i
  }
  
  # add state order
  counter <- 0
  nodes$order <- 0
  for (y in stateOrder) {
    nodes[nodes$node == y,]$order <- counter

    counter <- counter + 1
  }
  
  # https://www.hydrogenwaterusa.com/visualizing-large-directed-networks-with-ggraph-in-r/
  g <- igraph::graph_from_data_frame(d = edges,
                                     vertices = nodes %>% arrange(order),
                                     directed = TRUE)
  
  # pList[[x]] <- ggraph(g, layout = "auto") +
  # pList[[x]] <- ggraph(g, layout = "igraph", algorithm = "circle") +
  # pList[[x]] <- ggraph(g, layout = "linear") +
  # ggraph(g, layout = "igraph", algorithm = "circle") +
  # ggraph(g, layout = "auto") +
  ggraph(g, layout = "linear") +
    # ggtitle(sprintf("%s", x)) +
    geom_edge_fan2(aes(width = non.self, color = non.self),
                   arrow = arrow(length = unit(5, 'mm'), type = "closed"),
                   end_cap = circle(3, 'mm')) +
    scale_edge_width(range = c(1, 2)) +
    scale_edge_color_gradient2(
      # low = "#D1D1D1",
      low = "#dadada",
      high = "black",
      mid = "#616161",
      midpoint = .5
    ) +
    geom_node_label(aes(label = nodeName, fill = self),
                    color = "white", repel = FALSE, size=5,
                    label.padding = unit(0.25, "lines")) +
    scale_fill_gradient2(
      # low = "blue",
      low = "#009fe3",
      mid = "black",
      # high = "red",
      high = "#e71d73",
      midpoint = .5
    ) +
    theme_graph(
      plot_margin = margin(0, 0, 0, 0)
    ) +
    theme(
      legend.position = "none",
      plot.title = element_text(size = 6, family = "Arial")
    )

  ggsave(file = file.path(anaDir, paste0("network_", x, ".pdf")),
         width = 3, height = 1, dpi = 400)
}

# ggpubr::ggarrange(plotlist = pList, nrow = 1)

# https://stackoverflow.com/a/17075381
# ggsave(file = file.path(anaDir, "total_networks.tiff"),
# ggsave(file = file.path(anaDir, "total_networks_GCAMP.tiff"),
  # width = 7, height = 2)
  # width = 20, height = 3.5)
  # width = 25, height = 2)
```

```{r fig_hmm_props, fig.height=5, fig.width=4}
# show measurements of clusters to compare
colsToPlot <- rev(c(
  "angle",
  "speed",
  "compactness",
  "extent",
  "oblate",
  "prolate",
  "solidity",
  "sphericity",
  "surface_area",
  "volume"
))

# convert angle to degrees
popDTs[, live.cell.angle_deg := pracma::rad2deg(live.cell.angle)]

propsToPlot <- popDTs[exp.info, on = "uID"] %>%
  dplyr::rename(
    "speed" = "live.cell.speed",
    "angle" = "live.cell.angle_deg",
    "oblate" = "ellipticity_interm_oblate",
    "prolate" = "ellipticity_interm_prolate"
  ) %>%
  # drop_na(live.cell.hmm.state.hybrid_pop) %>%
  pivot_longer(
    cols = colsToPlot, names_to = "prop", values_to = "value"
    ) %>%
  pivot_longer(
    cols = c(
      "live.cell.hmm.state.movement"
    ), names_to = "hmm_type", values_to = "hmm_value"
    )

propsToPlot$prop <- factor(propsToPlot$prop, levels = colsToPlot)

# show heatmap for HMM
propsSummary <- propsToPlot %>%
  dplyr::filter(!is.na(hmm_value)) %>%
  group_by(hmm_type, hmm_value, prop) %>%
  replace_na(list(value = 0)) %>%
  summarise(mean = mean(value)) %>%
  group_by(hmm_type, prop) %>%
  mutate(freq = (mean - min(mean)) / (max(mean) - min(mean))) %>%
  arrange(-prop)

ggplot(propsSummary, aes(as.factor(hmm_value), prop)) +
  theme_classic() +
  geom_tile(aes(fill = freq), colour = "white", size = 0.5) +
  viridis::scale_fill_viridis(
    breaks = c(0, 1),
    labels = c(0, 1)
  ) +
  theme(
    # legend.position = "none",
    legend.title = element_blank(),
    legend.text = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    axis.text.x = element_text(size = 12),
    strip.background = element_blank(),
    strip.text.x = element_blank(),
    # axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)
    ) +
  xlab("") + ylab("") +
  facet_grid(.~hmm_type)

ggsave(file.path(anaDir, "HMM_heat.pdf"), width = 3, height = 3)
```

```{r}
clusterMapping <- list(
  Arrested = c(4),
  Stopping = c(2),
  Meandering = c(0,3,5),
  Directed = c(1)
)
```

```{r fig_umap, fig.height=8, fig.width=8}
dfToPlot <- copy(tcells.sc) %>% drop_na(clusters) %>% left_join(exp.info)

# dfToPlot <- .mapClustNames(dfToPlot, clusterMapping, "clusters")

# get mean positions of clusters
meanClusterPos <- dfToPlot %>%
  group_by(clusters) %>%
  # group_by(clusters.name) %>%
  summarise(
    UMAP_1 = mean(UMAP_1),
    UMAP_2 = mean(UMAP_2)
  )
dfToPlot$clusters <- factor(dfToPlot$clusters)

colPal <- randomcoloR::distinctColorPalette(length(unique(dfToPlot$clusters)))

# plot UMAP
ggplot(
  dfToPlot,
  # dfToPlot %>% dplyr::filter(clusters.name != "NONE"),
  aes(UMAP_1, UMAP_2)
  ) +
  geom_point(aes(color = clusters)) +
  # geom_point(aes(color = clusters.name)) +
  theme_classic() +
  scale_color_brewer(name = NULL, palette = "Set1") +
  # scale_color_manual(values = colPal) +
  # scale_color_manual(values = viridisLite::viridis(4)) +
  theme(
    axis.text = element_text(size = 15),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    legend.justification = "right",
    # legend.position = "bottom"
    legend.position = "none",
    axis.line = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
    ) +
  geom_label(
    data = meanClusterPos,
    aes(label = clusters),
    # aes(label = clusters.name),
    label.size = 0.25,
    color = "black"
    )

ggsave(file.path(anaDir, "umap.tiff"), width = 5, height = 5)
# ggsave(file.path(anaDir, "umap_wo_labels.tiff"), width = 2, height = 2)
```

```{r}
# show measurements of clusters to compare
propsToPlot <- copy(tcells.sc)

# propsToPlot <- propsToPlot %>%
#   dplyr::rename(
#     "Movement HMM 1" = "live.cell.hmm.state.movement.1",
#     "Movement HMM 2" = "live.cell.hmm.state.movement.2",
#     "Movement HMM 3" = "live.cell.hmm.state.movement.3",
#     "Movement HMM 4" = "live.cell.hmm.state.movement.4",
#   )

colsToPlot <- colnames(propsToPlot)[!colnames(propsToPlot) %in% c(
  "pop", "uID", "track_id", "clusters", "UMAP_1", "UMAP_2"
  )]

propsToPlot <- propsToPlot %>%
  pivot_longer(
    cols = colsToPlot, names_to = "prop", values_to = "value"
    )

propsToPlot$prop <- factor(propsToPlot$prop, levels = sort(colsToPlot, decreasing = TRUE))

# propsToPlot <- .mapClustNames(propsToPlot, clusterMapping, "clusters")

# propsList <- c(
#   'Movement HMM 1',
#   'Movement HMM 2',
#   'Movement HMM 3',
#   'Movement HMM 4',
#   'asphericity',
#   'displacement',
#   'displacementRatio',
#   'duration',
#   'meanTurningAngle',
#   'outreachRatio',
#   'overallAngle',
#   'speed',
#   'straightness',
#   'trackLength'
# )

# show heatmap for clusters
propsSummary <- propsToPlot %>%
  dplyr::filter(
    # clusters.name != "NONE",
    # prop %in% propsList
    ) %>%
  group_by(clusters, prop) %>%
  # group_by(clusters.name, prop) %>%
  summarise(mean = mean(value, rm.na = TRUE)) %>%
  group_by(prop) %>%
  mutate(freq = (mean - min(mean)) / (max(mean) - min(mean))) %>%
  arrange(-prop)
```

```{r fig_clusters_heat, fig.height=8, fig.width=6}
# propsSummary$prop <- factor(
#   propsSummary$prop, levels = rev(propsList))
# propsSummary$clusters.name <- factor(
#   propsSummary$clusters.name, levels = c(
#     "Directed", "Meandering", "Scanning", "Clustering"
#   ))

# ggplot(propsSummary, aes(as.factor(clusters.name), prop)) +
ggplot(propsSummary, aes(as.factor(clusters), prop)) +
  theme_classic() +
  geom_tile(aes(fill = freq), colour = "white", size = 0.5) +
  viridis::scale_fill_viridis(
    breaks = c(0, 1),
    labels = c(0, 1)
  ) +
  theme(
    # legend.position = "none",
    legend.key.size = unit(8, "mm"),
    legend.title = element_blank(),
    legend.text = element_text(size = 14),
    axis.text.y = element_text(size = 14),
    # axis.text.x = element_text(size = 12),
    axis.text.x = element_text(size = 14, angle = 45, hjust = 1, vjust = 1),
    strip.background = element_blank(),
    strip.text.x = element_blank()
    ) +
  xlab("") + ylab("")

ggsave(file.path(anaDir, "clusters_heat.pdf"), width = 6, height = 8)
```

```{r fig_speed_time, fig.height = 10, fig.width = 14}
# get frequencies of clusters at time points
speedTime <- popDTs %>%
  dplyr::filter(
    # uID %in% c("O5H6Yx", "uyHGX5", "wTL5w8"),
    # uID %in% c("O5H6Yx", "wTL5w8"),
    live.cell.track.clusters.hmm_movement != "4"
    ) %>%
  group_by(uID, centroid_t) %>%
  summarise(mean.speed = mean(live.cell.speed, na.rm = TRUE)) %>%
  left_join(exp.info)

speedTimeClusters <- popDTs %>%
  dplyr::filter(
    # uID %in% c("O5H6Yx", "uyHGX5", "wTL5w8"),
    # uID %in% c("O5H6Yx", "wTL5w8"),
    live.cell.track.clusters.hmm_movement != "4",
    # live.cell.track.clusters.hmm_movement %in% c("0", "1")
    ) %>%
  group_by(uID, centroid_t) %>%
  group_by(uID, live.cell.track.clusters.hmm_movement, centroid_t) %>%
  summarise(mean.speed = mean(live.cell.speed, na.rm = TRUE)) %>%
  left_join(exp.info)

speedTimeClusters$clusters.name <- "NONE"
speedTimeClusters[speedTimeClusters$live.cell.track.clusters.hmm_movement %in% c(1), ]$clusters.name <- "Directed"
speedTimeClusters[speedTimeClusters$live.cell.track.clusters.hmm_movement %in% c(0,3,5), ]$clusters.name <- "Meandering"
speedTimeClusters[speedTimeClusters$live.cell.track.clusters.hmm_movement %in% c(2), ]$clusters.name <- "Stopping"
speedTimeClusters[speedTimeClusters$live.cell.track.clusters.hmm_movement %in% c(4), ]$clusters.name <- "Arrested"

time.interval <- cciaObj$cciaObjects(uIDs = uIDs)[[1]]$omeXMLTimelapseInfo()$interval

# remove the few unaffected
# speedTimeClusters[
#   speedTimeClusters$live.cell.track.clusters.hmm_movement == 2 &
#     speedTimeClusters$uID == "O5H6Yx", ]$mean.speed <- NA

colPal <- randomcoloR::distinctColorPalette(
  length(unique(speedTimeClusters$live.cell.track.clusters.hmm_movement))
)

speedTimeClusters$uID_Treat <- paste(speedTimeClusters$uID, speedTimeClusters$Treatment)
speedTime$uID_Treat <- paste(speedTime$uID, speedTime$Treatment)

ggplot(speedTimeClusters %>%
         drop_na(mean.speed) %>%
         dplyr::filter(clusters.name != "NONE", !is.na(clusters.name)) %>%
         mutate(uID = as.factor(uID)),
       aes((centroid_t * time.interval), mean.speed,
           color = as.factor(live.cell.track.clusters.hmm_movement),
           fill = as.factor(live.cell.track.clusters.hmm_movement)
           # color = as.factor(clusters.name),
           # fill = as.factor(clusters.name)
           )) +
  theme_classic() +
  # scale_color_manual(values = c("#31688E", "#35B779", "#FDE725", "black")) +
  # scale_fill_manual(values = c("#31688E", "#35B779", "#FDE725", "black")) +
  # scale_color_manual(values = colPal) +
  # scale_fill_manual(values = colPal) +
  scale_color_brewer(palette = "Set1") +
  scale_fill_brewer(palette = "Set1") +
  # stat_smooth(data = speedTime, span = 0.4, color = "#ff048e", fill = "#ff048e") +
  stat_smooth(data = speedTime, span = 0.4, color = "black", fill = "black") +
  stat_smooth(span = 0.4) +
  theme(
    legend.title = element_blank(),
    # legend.position = "None",
    strip.background = element_blank(),
    # strip.text.x = element_blank()
    ) +
  xlab("Time (min)") + ylab("Velocity (μm/min)") +
  # ylim(0, 15) +
  # facet_wrap(.~uID, scales = "free_x")
  facet_wrap(.~uID_Treat, scales = "free_x", nrow = 1)
  # expand_limits(y = 0)

# ggsave(file.path(anaDir, "speed_time_combined.png"), height = 2, width = 12)
# ggsave(file.path(anaDir, "speed_time.png"), height = 8, width = 3)
# ggsave(file.path(anaDir, "speed_time_clusters.png"), height = 8, width = 8)
ggsave(file.path(anaDir, "speed_time_clusters_treat.png"), height = 2, width = 10)
```

```{r fig_states_time, fig.height = 3, fig.width = 4}
# get frequencies of clusters at time points
hmmTime <- popDTs %>%
  dplyr::filter(
    !is.na(live.cell.hmm.state.movement),
    ) %>%
  group_by(
    uID, centroid_t, live.cell.hmm.state.movement
    ) %>%
  summarise(n = n()) %>%
  mutate(
    live.cell.hmm.state.movement = as.factor(live.cell.hmm.state.movement),
    freq = n/sum(n)
    ) %>%
  ungroup() %>%
  complete(uID, centroid_t, live.cell.hmm.state.movement, fill = list(
    freq = 0
  ))

# TODO this is not nice
# set NA for each object after completion with 0
for (x in cciaObj$cciaObjects(uIDs = uIDs)) {
  hmmTime[hmmTime$uID == x$getUID() &
            hmmTime$centroid_t > x$omeXMLPixels()$SizeT, ]$freq = NA
}
```

```{r fig_states_time, fig.height = 1.5, fig.width = 2}
time.interval <- cciaObj$cciaObjects(uIDs = uIDs)[[1]]$omeXMLTimelapseInfo()$interval

for (i in unique(hmmTime$uID)) {
  p1 <- ggplot(hmmTime[hmmTime$uID == i,],
         aes((centroid_t * time.interval), freq,
             color = live.cell.hmm.state.movement,
             fill = live.cell.hmm.state.movement,
             )) +
    stat_smooth(span = 0.2) +
    # geom_line(size = 0.8) +
    theme_classic() +
    # scale_color_brewer(name = NULL, palette = "Set1") +
    # scale_fill_brewer(name = NULL, palette = "Set1") +
    scale_color_manual(values = c("black", "#f28500", "#0080ff")) +
    scale_fill_manual(values = c("black", "#f28500", "#0080ff")) +
    theme(
      legend.title = element_blank(),
      # legend.position = "bottom"
      legend.position = "none"
      ) +
    xlab("Time (min)") + ylab("HMM frequency")
    # ylim(0, 1) +
    # facet_grid(uID~.)
  print(p1)
  
  # ggsave(file.path(anaDir, "hmm_time.png"), height = 4, width = 3)
  ggsave(file.path(anaDir, paste0("hmm_time_", i, ".tiff")), height = 2, width = 3)
}
```

```{r fig_states_time, fig.height = 3, fig.width = 4}
# get steady state HMM proportions
# then normalise frequencies to that
timeSplit <- hmmTime %>%
  arrange(uID, centroid_t) %>%
  dplyr::filter(
    live.cell.hmm.state.movement == 3,
    freq > 0.3
    ) %>%
  group_by(uID, live.cell.hmm.state.movement) %>%
  slice_head(n = 1)

# get average of range
# go through and split off data
baseList <- list()
responseList <- list()
for (i in uIDs) {
  x <- timeSplit[timeSplit$uID == i,]$centroid_t
  baseList[[i]] <- as.data.table(hmmTime[hmmTime$uID == i & hmmTime$centroid_t < x,])
  responseList[[i]] <- as.data.table(hmmTime[hmmTime$uID == i & hmmTime$centroid_t >= x,])
}

baseDT <- rbindlist(baseList) 
responseDT <- rbindlist(responseList) 
baseSummary <- baseDT %>%
  group_by(uID, live.cell.hmm.state.movement) %>%
  summarise(sum.hmm = sum(n, na.rm = TRUE)) %>%
  mutate(
    live.cell.hmm.state.movement = as.factor(live.cell.hmm.state.movement),
    freq.base = sum.hmm/sum(sum.hmm)
    )

# normalise to baseline
# hmmTime <- hmmTime %>%
#   left_join(baseSummary, by = c("uID", "live.cell.hmm.state.movement")) %>%
#   mutate(freq.norm = freq/freq.base * 100)

ggplot(baseSummary, aes(live.cell.hmm.state.movement, freq.base,
                        fill = live.cell.hmm.state.movement)) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(width = 0.2) +
  ylim(0, 0.8) +
  scale_fill_brewer(name = NULL, palette = "Set1") +
  xlab("HMM state")

ggsave(file.path(anaDir, "hmm_baseline.png"), height = 2, width = 2)

write.csv(baseSummary %>% mutate(freq.base = freq.base * 100),
          file.path(anaDir, "hmm_baseline.csv"))
```

```{r fig_states_space, fig.height = 2, fig.width = 2}
# get frequencies of hmm states at time points
hmmSpaceAll <- copy(popDTs) %>%
  dplyr::filter(
    !is.na(live.cell.hmm.state.movement),
    uID == "O5H6Yx"
    )

tInterval <- 10
for (i in seq(ceiling(max(hmmSpaceAll$centroid_t)/tInterval))) {
  p1 <- ggplot(hmmSpaceAll %>%
         dplyr::filter(
           centroid_t >= i * tInterval,
           centroid_t < (i * tInterval) + tInterval
         ), aes(centroid_x, -centroid_y,
                color = as.factor(live.cell.hmm.state.movement))) +
    theme_classic() +
    # plotThemeDark(
    #   fontSize = 8,
    #   legend.justification = "centre"
    #   ) +
    scale_color_manual(values = c("black", "#f28500", "#0080ff")) +
    geom_point(size = 2) +
    coord_fixed() +
    theme(
      axis.text.x = element_blank(),
      axis.ticks.x = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank(),
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      legend.title = element_blank(),
      legend.position = "none",
      axis.line = element_blank(),
      panel.border = element_rect(colour = "black", fill = NA, size = 1)
      )
  print(p1)

  ggsave(file.path(anaDir, "hmm_space", paste0("O5H6Yx", "_", i, ".tiff")),
         height = 2, width = 2)
}
```


```{r fig_states_time, fig.height = 2, fig.width = 6}
ggplot(hmmTime,
       aes((centroid_t * time.interval), freq.norm,
           color = live.cell.hmm.state.movement,
           fill = live.cell.hmm.state.movement,
           )) +
  geom_hline(yintercept = 1) +
  # geom_line(size = 0.8) +
  stat_smooth(span = 0.4) +
  # geom_smooth(size = 0.8) +
  theme_classic() +
  scale_color_brewer(name = NULL, palette = "Set1") +
  scale_fill_brewer(name = NULL, palette = "Set1") +
  theme(
    legend.title = element_blank(),
    legend.position = "bottom"
    ) +
  xlab("Time (min)") + ylab("HMM frequency") +
  # ylim(0, 1) +
  # facet_wrap(live.cell.hmm.state.movement~uID, nrow = 3, scales = "free_y")
  facet_wrap(live.cell.hmm.state.movement~uID, nrow = 3, scales = "free_y")

ggsave(file.path(anaDir, "hmm_time_split.png"), height = 6, width = 8)
```
