---
title: "Run modules"
output: html_document
date: '2022-08-16'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Examples to run functions and modules

```{r}
# set test variables
pID <- "pEdOoZ"
versionID <- 2
projectsDir <- "/Volumes/Analysis_SSD/Dominik/cecelia/projects/"
hpcDir <- "/data/scratch/projects/punim1124/cecelia/USERS/schienstockd/"
```

```{r}
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia")

library(ggplot2)
library(tidyverse)
```

```{r}
# HPC config
HPC_CONF <-  list(
  hpc = list(
    conf = list(
      email = "schienstockd@student.unimelb.edu.au",
      emailOnBegin = FALSE,
      emailOnEnd = FALSE,
      emailOnFail = TRUE,
      numNodes = 1,
      numTasks = 1,
      numCPUperTask = 1,
      numGPUperTask = 1,
      memory = 50,
      walltime = "00-01:00:00",
      projectPartitions = "physical",
      # projectPartitions = "shortgpgpu,gpgpu",
      projectID = "punim1124",
      # projectID = "punim1031",
      useGPU = FALSE
      # useGPU = TRUE
    )
  ),
  utils = list(
    ssh = list(
      username = "schienstockd",
      address = "spartan.hpc.unimelb.edu.au",
      keyfile = "/Users/schiend/.ssh/spartan_rsa"
    ),
    python = list(
      condaEnv = cciaConf()$python$conda$source$env
    )
  )
)
```

```{r}
anaDir <- "/Volumes/USER_data/Dominik/Experiments/DS_N051/ANALYSIS/IMAGE/CECELIA"
```

```{r}
# get distances from lymphs to melano
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "TURHVv", versionID = versionID, initReactivity = FALSE # Set
)

cciaObj$popDT("region", includeFiltered = TRUE)
```

```{r}
# get distances from lymphs to melano
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "ktUu0n", versionID = versionID, initReactivity = FALSE # Set
)

# run task
funParams <- list(
  uIDs = c("TURHVv"),
  popType = c("flow"),
  pops = c("/nonDebris"),
  colName = "default",
  valueName = "default",
  excludeSelfConnections = FALSE,
  useClusters = FALSE,
  expandPops = TRUE,
  numClusters = 3
)

task <- cciaObj$runTask(
  funName = "clustRegions.kmeansClust",
  funParams = funParams,
  env = "local",
  runInplace = TRUE,
  taskID = 1
)
```

```{r}
# get distances from lymphs to melano
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "TURHVv", versionID = versionID, initReactivity = FALSE 
)

# run task
funParams <- list(
  popType = c("flow"),
  popsToCluster = c("/nonDebris/P14"),
  clustDiameter = 30,
  clustMinPts = 3,
  clustBorderPoints = TRUE,
  combinePops = FALSE
)

task <- cciaObj$runTask(
  funName = "spatialAnalysis.cellClusters",
  funParams = funParams,
  env = "local",
  runInplace = TRUE,
  taskID = 1
)
```

```{r}
# get distances from lymphs to melano
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "TURHVv", versionID = versionID, initReactivity = FALSE 
)

cciaObj$popDT("flow", pops = c("/nonDebris/P14/clustered"), includeFiltered = TRUE)
```


```{r}
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = "pEdOoZ", uID = "yBiUZh", versionID = 2, initReactivity = FALSE
)

cciaObj$runTask(
  funName = "gatePopulations.createGatingSet",
  funParams = list(
    compensateZ = TRUE,
    polyDegree = 4,
    applyReversedLog = FALSE,
    transformation = "logicle"
  ),
  runInplace = TRUE
)
```

```{r}
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "TURHVv", versionID = versionID, initReactivity = FALSE # Set
)

# show gating hierarchy
library(ggplot2)

# go through pops and build gating scheme
fgs <- cciaObj$flowGatingSet()

# nudge for populations
nudgeList <- list(
  "/nonDebris" = list(x = 5000, y = 500),
  "/nonDebris/P14" = list(x = 3, y = -1),
  "/nonDebris/nonP14/CD11b" = list(x = 0, y = -3),
  "/nonDebris/nonP14/B220" = list(x = 0, y = -3),
  "/nonDebris/nonP14/others" = list(x = 0, y = 2),
  "/nonDebris/nonP14/others/XCR1" = list(x = 0, y = 1)
)

p1s <- list()

for (x in fgs$popLeaves("root")) {
  local({
    xParent <- .flowPopParent(x, root = "root")
  
    # get gate
    xGate <- fgs$popGate(x)
    xLabel <- names(xGate@parameters)[1]
    yLabel <- names(xGate@parameters)[2]
    
    # get pops
    popDT <- cciaObj$popDT(
      "flow", pops = c("root", xParent), popCols = names(xGate@parameters),
      completeDT = FALSE, uniqueLabels = TRUE)
    
    # get range
    xRange <- range(popDT[, ..xLabel])
    yRange <- range(popDT[, ..yLabel])
    
    # build raster
    rasterContours <- .flowRasterContour(
      popDT[pop == xParent], xLabel, yLabel, xRange = xRange, yRange = yRange)

    # get boundaries
    # rectangle gate?
    if (attr(xGate, "class") == "rectangleGate") {
      # build path
      gateDT <- as.data.table(list(
        x = c(xGate@min[1], xGate@min[1], xGate@max[1], xGate@max[1]),
        y = c(xGate@min[2], xGate@max[2], xGate@max[2], xGate@min[2])
      ))
      setnames(gateDT, "x", xLabel)
      setnames(gateDT, "y", yLabel)
    } else {
      # close path
      gateDT <- as.data.table(xGate@boundaries)
      gateDT <- rbind(gateDT, gateDT[1])
    }
    
    # get gate range
    xRangeGate <- range(gateDT[, ..xLabel])
    yRangeGate <- range(gateDT[, ..yLabel])
    
    # combine with data range
    xRange <- c(min(xRange[[1]], xRangeGate[[1]]),
                max(xRange[[2]], xRangeGate[[2]]))
    yRange <- c(min(yRange[[1]], yRangeGate[[1]]),
                max(yRange[[2]], yRangeGate[[2]]))
    
    # add label
    # nameDT <- as.data.frame(rbind(gateDT %>% colMeans()))
    nameDT <- as.data.frame(list(
      x = mean(gateDT[[xLabel]]),
      y = max(gateDT[[yLabel]])
    ))
    colnames(nameDT) <- c(xLabel, yLabel)
    nameDT$label <- .flowTrimPath(x, pathLevels = 0)
    
    # add percentage
    popStats <- fgs$getPopStats(x, type = "percent")
    nameDT$label <- paste(
      nameDT$label, paste0(
        sprintf("%0.1f", popStats$percent * 100), "%"))
    
    # plot out
    p1 <- ggplot() +
      theme_classic() +
      annotation_raster(
        rasterContours$raster$image,
        xmin = rasterContours$raster$x_range[1],
        xmax = rasterContours$raster$x_range[2],
        ymin = rasterContours$raster$y_range[1],
        ymax = rasterContours$raster$y_range[2]) +
      # xlim(xRange) + ylim(yRange) +
      # https://stackoverflow.com/a/21307010
      xlim(range(pretty(xRange))) +
      ylim(range(pretty(yRange))) +
      xlab(xLabel) + ylab(yLabel) +
      geom_polygon(
        data = rasterContours$contours,
        aes(x = y, y = x, group = as.factor(seq)),
        size = 0.2, color = "black", fill = "white")
    
    # get nudge
    nudgeX <- 0
    nudgeY <- 0
    
    if (x %in% names(nudgeList)) {
      nudgeX <- nudgeList[[x]]$x
      nudgeY <- nudgeList[[x]]$y
    }
    
    p1 <- p1 + geom_polygon(
      data = gateDT,
      aes(
        x = get(xLabel),
        y = get(yLabel)
        ), size = 0.5, color = "black", fill = "#23aeff", alpha = 0.2) +
      geom_label(
        data = nameDT,
        aes(
          label = label,
          x = get(xLabel),
          y = get(yLabel)),
        nudge_x = nudgeX,
        nudge_y = nudgeY,
        size = 4, color = cciaObj$popAttr("flow", "colour", popPath = x)[[1]]
        ) +
      ggtitle(xParent) +
      theme(plot.title = element_text(size = 8))
    
    p1s[[x]] <<- p1
  })
}

ggpubr::ggarrange(plotlist = p1s, nrow = 3, ncol = 3)
ggsave(file.path(anaDir, "gating_contours_indv.pdf"), width = 8, height = 8)
```

```{r}
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "TURHVv", versionID = versionID, initReactivity = FALSE # Set
)

# positions for population labels
labelPos <- list(
  "/nonDebris" = list(x = 5000, y = 500),
  "/nonDebris/nonP14" = list(yFun = min),
  "/nonDebris/nonP14/others" = list(yFun = min),
  "/nonDebris/nonP14/CD11b" = list(yFun = min)
)

plotWidth <- 10
plotHeight <- 2.5
nRow <- 1
nCol <- 4

p1s <- .flowPlotGatedRaster(
  cciaObj, labelPos = labelPos, asContours = FALSE, showPopColours = FALSE)

ggpubr::ggarrange(plotlist = p1s, nrow = nRow, ncol = nCol)
ggsave(file.path(anaDir, "gating_contours_noContour_noColour.pdf"),
       width = plotWidth, height = plotHeight)

p1s <- .flowPlotGatedRaster(
  cciaObj, labelPos = labelPos, asContours = TRUE, showPopColours = FALSE)

ggpubr::ggarrange(plotlist = p1s, nrow = nRow, ncol = nCol)
ggsave(file.path(anaDir, "gating_contours_contours_noColour.pdf"),
       width = plotWidth, height = plotHeight)

p1s <- .flowPlotGatedRaster(
  cciaObj, labelPos = labelPos, asContours = FALSE, showPopColours = TRUE)

ggpubr::ggarrange(plotlist = p1s, nrow = nRow, ncol = nCol)
ggsave(file.path(anaDir, "gating_contours_noContours_colour.pdf"),
       width = plotWidth, height = plotHeight)

p1s <- .flowPlotGatedRaster(
  cciaObj, labelPos = labelPos, asContours = TRUE, showPopColours = TRUE)

ggpubr::ggarrange(plotlist = p1s, nrow = nRow, ncol = nCol)
ggsave(file.path(anaDir, "gating_contours_contours_colour.pdf"),
       width = plotWidth, height = plotHeight)
```


```{r}
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "TURHVv", versionID = versionID, initReactivity = FALSE # Set
)

# show gating hierarchy
library(ggplot2)

# go through pops and build gating scheme
fgs <- cciaObj$flowGatingSet()

p1s <- list()



# positions for population labels
posList <- list(
  "/nonDebris" = list(x = 5000, y = 500),
  "/nonDebris/nonP14" = list(yFun = min),
  "/nonDebris/nonP14/others" = list(yFun = min),
  "/nonDebris/nonP14/CD11b" = list(yFun = min)
)

.flowPlotGatedRaster(cciaObj, )

for (xParent in names(leaves)) {
  local({
    pops <- leaves[[xParent]]
    
    # go through pops and get gates
    popGates <- lapply(pops, fgs$popGate)
    names(popGates) <- pops
    
    # get channels
    popGateChannels <- lapply(popGates, function(x) names(x@parameters))
    
    # get pops
    popDT <- cciaObj$popDT(
      "flow", pops = c("root", xParent), popCols = unique(unlist(popGateChannels)),
      completeDT = FALSE, uniqueLabels = TRUE)
    
    # go through gate combinations
    for (gateChannels in unique(popGateChannels)) {
      xLabel <- gateChannels[[1]]
      yLabel <- gateChannels[[2]]
      
      # get range
      xRange <- range(popDT[, ..xLabel])
      yRange <- range(popDT[, ..yLabel])
      
      # build raster
      rasterContours <- .flowRasterContour(
        popDT[pop == xParent], xLabel, yLabel, xRange = xRange, yRange = yRange)
  
      # get boundaries
      gateDTs <- list()
      
      for (j in names(popGates)) {
        xGate <- popGates[[j]]
        
        # rectangle gate?
        if (attr(xGate, "class") == "rectangleGate") {
          # build path
          gateDTs[[j]] <- as.data.table(list(
            x = c(xGate@min[1], xGate@min[1], xGate@max[1], xGate@max[1]),
            y = c(xGate@min[2], xGate@max[2], xGate@max[2], xGate@min[2])
          ))
          setnames(gateDTs[[j]], "x", xLabel)
          setnames(gateDTs[[j]], "y", yLabel)
        } else {
          # close path
          gateDTs[[j]] <- as.data.table(xGate@boundaries)
          gateDTs[[j]] <- rbind(gateDTs[[1]], gateDTs[[1]][1])
        }
      }
      
      # bind together
      gateDT <- rbindlist(gateDTs, idcol = "pop")
      
      # get gate range
      xRangeGate <- range(gateDT[, ..xLabel])
      yRangeGate <- range(gateDT[, ..yLabel])
      
      # combine with data range
      xRange <- c(min(xRange[[1]], xRangeGate[[1]]),
                  max(xRange[[2]], xRangeGate[[2]]))
      yRange <- c(min(yRange[[1]], yRangeGate[[1]]),
                  max(yRange[[2]], yRangeGate[[2]]))
      
      # add label
      # nameDT <- as.data.frame(rbind(gateDT %>% colMeans()))
      nameDTs <- list()
      for (j in names(popGates)) {
        nameDTs[[j]] <- as.data.frame(list(
          x = mean(gateDT[pop == j, ][[xLabel]]),
          y = max(gateDT[pop == j, ][[yLabel]])
        ))
        
        if (j %in% names(posList)) {
          if ("x" %in% names(posList[[j]]))
            nameDTs[[j]]$x <- posList[[j]]$x
          if ("y" %in% names(posList[[j]]))
            nameDTs[[j]]$y <- posList[[j]]$y
          if ("yFun" %in% names(posList[[j]]))
            nameDTs[[j]]$y <- posList[[j]]$yFun(gateDT[pop == j, ][[yLabel]])
        }
        
        colnames(nameDTs[[j]]) <- c(xLabel, yLabel)
        nameDTs[[j]]$label <- .flowTrimPath(j, pathLevels = 0)
        
        # add percentage
        popStats <- fgs$getPopStats(j, type = "percent")
        nameDTs[[j]]$label <- paste(
          nameDTs[[j]]$label, paste0(
            sprintf("%0.1f", popStats$percent * 100), "%"))
      }
      nameDT <- rbindlist(nameDTs, idcol = "pop")
      
      # plot out
      p1 <- ggplot() +
        theme_classic() +
        annotation_raster(
          rasterContours$raster$image,
          xmin = rasterContours$raster$x_range[1],
          xmax = rasterContours$raster$x_range[2],
          ymin = rasterContours$raster$y_range[1],
          ymax = rasterContours$raster$y_range[2]) +
        # xlim(xRange) + ylim(yRange) +
        # https://stackoverflow.com/a/21307010
        xlim(range(pretty(xRange))) +
        ylim(range(pretty(yRange))) +
        xlab(xLabel) + ylab(yLabel) +
        geom_polygon(
          data = rasterContours$contours,
          aes(x = y, y = x, group = as.factor(seq)),
          size = 0.2, color = "black", fill = "white")
      
      popColors <- sapply(
        pops, function(x) cciaObj$popAttr("flow", "colour", popPath = x)[[1]])
      
      p1 <- p1 + geom_polygon(
        data = gateDT,
        aes(
          x = get(xLabel),
          y = get(yLabel),
          group = pop
          ), size = 0.5, color = "black", fill = "#23aeff", alpha = 0.2) +
        geom_label(
          data = nameDT,
          aes(
            label = label,
            x = get(xLabel),
            y = get(yLabel),
            group = pop,
            color = pop),
          # nudge_x = nudgeX,
          # nudge_y = nudgeY,
          # size = 4, color = cciaObj$popAttr("flow", "colour", popPath = x)[[1]]
          size = 2
          ) +
        scale_color_manual(values = popColors) +
        ggtitle(xParent) +
        theme(
          legend.position = "none",
          plot.title = element_text(size = 8)
          )
      
      p1s[[xParent]] <<- p1
    }
  })
}

ggpubr::ggarrange(plotlist = p1s, nrow = 2, ncol = 2)
ggsave(file.path(anaDir, "gating_contours.pdf"), width = 5, height = 5)
```

```{r}
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "U7LRc9", versionID = versionID, initReactivity = FALSE # Set
)

exp.info <- as.data.table(
  cciaObj$summary(withSelf = FALSE, fields = c("Attr")) %>%
    left_join(read.csv(file.path(anaDir, "sample.info.csv")))
  )

uIDs <- names(cciaObj$cciaObjects())
uIDs <- uIDs[uIDs %in% exp.info[
  exp.info$Include == "Y" & exp.info$Cohort == "ICI", ]$uID]

# get cluster information
popDT <- cciaObj$popDT(
  popType = "clust", includeFiltered = TRUE,
  # pops = c("melano", "endothelial", "lymphs", "macro.mono", "macro.PDL1+"),
  pops = c("debris", "endothelial", "melano", "lymphs", "macro.mono", "macro.PDL1+", "Tc.Ki67+"),
  uIDs = uIDs, completeDT = TRUE, replaceX = TRUE)

unique(popDT$clusters)
```

```{r}
# define populations
clust <- list(
  init = c("debris", "endothelial", "melano", "lymphs", "macro.mono", "macro.PDL1+", "Tc.Ki67+"),
  cd45 = c("lymphs", "macro.mono", "macro.PDL1+", "Tc.Ki67+"),
  macro = c("macro.mono", "macro.PDL1+"),
  lymphs = c("lymphs", "Tc.Ki67+")
)

markers <- list(
  init = c(
    "x191Ir_Ir191", "x193Ir_Ir193", "Histone-H3_Yb176", "CD45_Sm152",
    "CD31_Sm147", "S100_Lu175", "SOX10_Dy164"
  ),
  cd45 = c(
    "x191Ir_Ir191", "x193Ir_Ir193", "Histone-H3_Yb176", "CD45_Sm152",
    "CD20_Dy161", "CD3_Er170", "CD31_Sm147", "CD68_Tb159", "CD14_Nd144" 
  ),
  macro = c(
    "PDL1_Nd150", "cleaved-Caspase3_Yb172", "pERK1-2_Yb171",
    "CD68_Tb159", "CD14_Nd144"
  ),
  lymphs = c(
    "CD45_Sm152", "CD8a_Dy162", "CD4_Gd156", "CD45RA_Er166",
    "CD45RO_Yb173", "Ki67_Nd143", "LAG3_Eu153", "OX40_Eu151", 
    "TIM3_Sm154", "FoxP3_Gd155", "ICOS_Nd148", "GranzymeB_Er167", 
    "CCR7_Gd158", "CD40_Er168", "CD20_Dy161", "CD3_Er170"
  )
)

groupVars <- list(
  init = "pop",
  cd45 = "pop",
  macro = "clusters",
  lymphs = "clusters"
)

combinePops <- list(
  init = list(
    non.melano = c("lymphs", "macro.mono", "macro.PDL1+", "Tc.Ki67+")
  ),
  cd45 = list(
    macro.mono = c("macro.mono", "macro.PDL1+"),
    lymphs = c("lymphs", "Tc.Ki67+")
    ),
  macro = list(),
  lymphs = list()
)

plotSizes <- list(
  init = c(4.5, 4.5),
  cd45 = c(4, 5),
  macro = c(5, 3),
  lymphs = c(7, 6)
)
```

```{r fig_clusters_heat, fig.height=5, fig.width=8}
for (i in names(clust)) {
  popsToShow <- clust[[i]]
  markersToShow <- .flowCorrectChannelNames(markers[[i]])
  groupVar <- groupVars[[i]]
  popsToCombine <- combinePops[[i]]
  plotSize <- plotSizes[[i]]
  
  markersToShowNoDye <- stringr::str_extract(markersToShow, ".*(?=_)")
  
  colsToShow <- c("label", "clusters", "pop", markersToShow)
  colsToShow <- colsToShow[colsToShow %in% colnames(popDT)]
  
  # show heatmap
  popLymphs <- popDT[pop %in% popsToShow, ..colsToShow]
  
  # combine pops
  if (length(popsToCombine) > 0) {
    for (j in names(popsToCombine))
      popLymphs[pop %in% popsToCombine[[j]], pop := j]
  }
  
  markersToPlot <- popLymphs %>%
    pivot_longer(
      cols = all_of(markersToShow), names_to = "marker", values_to = "value"
      )
  markersToPlot$marker <- as.factor(markersToPlot$marker)
  
  # show heatmap for clusters
  markersSummary <- markersToPlot %>%
    drop_na() %>%
    group_by(marker, get(groupVar)) %>%
    summarise(mean = mean(value, rm.na = TRUE)) %>%
    mutate(norm = (mean - min(mean))/(max(mean) - min(mean))) %>%
    replace_na(list(norm = 0)) %>%
    rename_with(~ c(groupVar), all_of(c("get(groupVar)")))
  
  # find order for clusters and markers
  markersMatrix <- markersSummary %>%
    pivot_wider(names_from = marker, values_from = norm, id_cols = groupVar)
  
  hcClusters <- hclust(dist(as.matrix(markersMatrix %>% dplyr::select(-all_of(groupVar)))), "ave")
  hcMarkers <- hclust(dist(t(as.matrix(markersMatrix %>% dplyr::select(-all_of(groupVar))))), "ave")
  
  clustersOrder <- markersMatrix[[groupVar]][hcClusters$order]
  markerOrder <- colnames(markersMatrix)[2:length(colnames(markersMatrix))][hcMarkers$order]
  
  p1 <- ggplot(markersSummary %>%
           mutate(
             # clusters = factor(clusters, levels = clustersOrder),
             # clusters = factor(clusters, levels = sort(as.numeric(levels(clustersOrder)))),
             marker = factor(marker, levels = markerOrder)
           ), aes(get(groupVar), marker)) +
    theme_classic() +
    # geom_tile(aes(fill = mean), colour = "white", size = 0.5) +
    geom_tile(aes(fill = norm), colour = "white", size = 0.5) +
    viridis::scale_fill_viridis(
      breaks = c(0, 1),
      labels = c(0, 1)
    ) +
    theme(
      legend.position = "none",
      legend.title = element_blank(),
      legend.text = element_text(size = 20),
      legend.key.size = unit(10, "mm"),
      axis.text.y = element_text(size = 20),
      # axis.text.x = element_text(size = 20),
      axis.text.x = element_text(size = 20, angle = 45, hjust = 1, vjust = 1),
      strip.background = element_blank(),
      strip.text.x = element_blank()
      ) +
    xlab("") + ylab("")
  plot(p1)
  
  ggsave(file.path(anaDir, paste0("clusters_heat_", i, ".pdf")),
         width = plotSize[[1]], height = plotSize[[2]])
}
```

```{r fig_pops_umap, fig.height=2, fig.width=2}
library(tidyverse)

dfToPlot <- copy(popDT[!clusters %in% c(melanoClusters, endothelialClusters)])

# get mean positions of clusters
meanClusterPos <- dfToPlot %>%
  group_by(clusters) %>%
  summarise(
    UMAP_1 = mean(UMAP_1),
    UMAP_2 = mean(UMAP_2)
  )

clustersPalette <- randomcoloR::distinctColorPalette(
  length(unique(dfToPlot$clusters)))

# plot UMAP with paga connections
ggplot(
  dfToPlot %>%
    mutate(clusters = factor(clusters, levels = clustersOrder)),
  aes(UMAP_1, UMAP_2)
  ) +
  theme_classic() +
  geom_point(aes(color = as.factor(clusters)), size = 0.5) +
  # scale_color_brewer(name = NULL, palette = "Set1") +
  scale_color_manual(values = clustersPalette) +
  theme(
    axis.text = element_text(size = 15),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    legend.justification = "center",
    legend.direction = "horizontal",
    legend.position = "bottom",
    # legend.position = "none",
    legend.title = element_blank(),
    legend.key.size = unit(5, "mm"),
    legend.text = element_text(size = 18),
    axis.line = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
    ) +
  guides(colour = guide_legend(override.aes = list(size = 4))) 
  # geom_label(
  #   data = meanClusterPos,
  #   aes(label = clusters),
  #   label.size = 0.25,
  #   color = "black"
  #   )

ggsave(file.path(anaDir, "cd45_umap.tiff"), width = 5, height = 6.5)
```

```{r fig_pops_freq, fig.height=5, fig.width=8}
# show frequency of populations for treatments
summaryDF <- popDT %>%
  dplyr::filter(
    !clusters %in% c("0", "3")
  ) %>%
  group_by(uID, clusters) %>%
  summarise(n = n()) %>%
  mutate(freq = n/sum(n) * 100) %>%
  ungroup() %>%
  complete(uID, clusters, fill = list(freq = 0)) %>%
  left_join(exp.info)

# plot
ggplot(summaryDF,
       aes(interaction(Cohort, Response), freq, fill = interaction(Cohort, Response))) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    # width = 0.3, alpha = 0.6) +
  # stat_summary(fun=mean, geom="point", size=3, shape=18, color="Magenta") +
  theme(
    axis.text.x = element_text(size = 12, angle = 45, hjust = 1, vjust = 1),
  ) +
  ylab("Population (%)") + xlab("") +
  facet_wrap(.~clusters, ncol = 10, scales = "free_y") +
  scale_fill_brewer(name = NULL, palette = "Set3")

summaryDF$Treatment <- 0
# summaryDF[summaryDF$Cohort == "ICI" & summaryDF$Response == "No",]$Treatment <- 1
summaryDF[summaryDF$Cohort == "ICI" & summaryDF$Response == "Yes",]$Treatment <- 1

# save as csv for plotting in Prism
write.csv(summaryDF, file.path(anaDir, "clusters_freq.csv"))
```

```{r}
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "U7LRc9", versionID = versionID, initReactivity = FALSE # Set
)

exp.info <- as.data.table(
  cciaObj$summary(withSelf = FALSE, fields = c("Attr")) %>%
    left_join(read.csv(file.path(anaDir, "sample.info.csv")))
  )

uIDs <- names(cciaObj$cciaObjects())
uIDs <- uIDs[uIDs %in% exp.info[exp.info$Include == "Y",]$uID]

# get cluster information
spatialDT <- cciaObj$spatialDT(valueName = "default", uIDs = uIDs)

# join pops
# spatialDT[popDT[, c("uID", "label", "pop")],
#           on = c("uID", "to" = "label"),
#           pop.to := pop]
# spatialDT[popDT[, c("uID", "label", "pop")],
#           on = c("uID", "from" = "label"),
#           pop.from := pop]
spatialDT[popDT[, c("uID", "label", "clusters")],
          on = c("uID", "to" = "label"),
          clusters.to := clusters]
spatialDT[popDT[, c("uID", "label", "clusters")],
          on = c("uID", "from" = "label"),
          clusters.from := clusters]

# filter same type associations
spatialDT <- spatialDT[clusters.to == "3", clusters.to := "0"]
spatialDT <- spatialDT[clusters.from == "3", clusters.from := "0"]
spatialDT <- spatialDT[clusters.to != clusters.from]
```


```{r fig_kmeans_clusters, fig.height=1.5, fig.width=12}
# get "i-niches" and determine a given number of defined clusters
freqRegions <- spatialDT %>%
  dplyr::filter(
    # !clusters.from %in% c("0"),
    # !clusters.from %in% c("0")
    # clusters.from %in% c("9")
    # !clusters.to %in% c("9")
  ) %>%
  # group_by(uID, from, clusters.from, clusters.to) %>%
  group_by(uID, clusters.from, clusters.to) %>%
  # group_by(uID, to, clusters.to, clusters.from) %>%
  summarise(n = n()) %>%
  mutate(freq = n/sum(n) * 100) %>%
  drop_na() %>%
  ungroup() %>%
  complete(uID, clusters.from, clusters.to, fill = list(freq = 0)) %>%
  left_join(exp.info)
  # pivot_wider(
  #   id_cols = c(uID, clusters.from),
  #   names_from = clusters.to,
  #   values_from = freq,
  #   values_fill = 0
  # )

# show interactions of individuals
for (i in unique(freqRegions$clusters.from)) {
  x <- freqRegions %>% dplyr::filter(clusters.from == i) 
  
  p1 <- ggplot(x,
               aes(clusters.to, freq, fill = Response)) +
    theme_classic() +
    geom_boxplot(outlier.alpha = 0) +
    geom_jitter(
      position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
      # width = 0.3, alpha = 0.6) +
    # stat_summary(fun=mean, geom="point", size=3, shape=18, color="Magenta") +
    ylab("Population (%)") + xlab("") +
    # ylim(0, 1) +
    scale_fill_brewer(name = NULL, palette = "Set3") +
    ggtitle(i)

  print(p1)
  
  x$Treatment <- 0
  x[x$Cohort == "ICI" & x$Response == "Yes",]$Treatment <- 1
  
  # save as csv for plotting in Prism
  write.csv(x, file.path(anaDir, paste0("interactions_freq", i, ".csv")))
}
```

```{r fig_kmeans_clusters, fig.height=1.5, fig.width=2.5}
# use K-Means to get clusters of regions
normalit <- function(m) (m - min(m))/(max(m)-min(m))

freqRegionsWider <- freqRegions %>%
  # ungroup() %>%
  # mutate(norm = normalit(freq)) %>%
  pivot_wider(
    # id_cols = c(uID, clusters.from),
    id_cols = c(uID, from, clusters.from),
    # id_cols = c(uID, to, clusters.to),
    # id_cols = c(from),
    # id_cols = c(uID),
    names_from = clusters.to,
    # names_from = clusters.from,
    # values_from = norm,
    values_from = freq,
    values_fill = 0
  )

freqRegionsMat <- as.matrix(freqRegionsWider %>%
  ungroup() %>% 
  select(-c(uID, from, clusters.from)))
rownames(freqRegionsMat) <- freqRegionsWider$from
```

```{r fig_kmeans_clusters, fig.height=1.5, fig.width=2.5}
clustToFind <- 3

clusters <- kmeans(
  freqRegionsWider %>%
    ungroup() %>%
    select(-c(uID, clusters.from)),
    # select(-c(uID, clusters.to)),
  clustToFind)
# mcl.model <- mclust::Mclust(freqRegionsMat)
# mcl.model <- mclust::Mclust(freqRegionsMat, clustToFind)

# Plot our results.
# plot(mcl.model, what = "classification", main = "Mclust Classification")

# push back clusters
freqRegionsWider$cluster <- clusters$cluster
# freqRegionsWider$cluster <- mcl.model$classification

popCols <- colnames(freqRegionsWider)[!colnames(freqRegionsWider) %in% c(
  "uID", "from", "to", "n", "cluster", "clusters.from", "clusters.to")]

freqRegionsWiderSummary <- freqRegionsWider %>%
  group_by(cluster) %>%
  summarise(across(all_of(popCols), mean)) %>%
  pivot_longer(
    cols = popCols,
    names_to = "pop",
    values_to = "value"
    ) %>%
  mutate(norm = normalit(value))

ggplot(
  freqRegionsWiderSummary, aes(as.factor(cluster), pop)) +
  geom_tile(aes(fill = norm)) +
  viridis::scale_fill_viridis(discrete=FALSE, limits = c(0, 1)) +
  theme_classic() +
  theme(legend.title=element_blank()) +
  xlab("") + ylab("")
```

```{r fig_region_freq, fig.height=1, fig.width=6}
# show frequency of populations for treatments
summaryDF <- copy(freqRegionsWider) %>%
  group_by(uID, cluster) %>%
  summarise(n = n()) %>%
  mutate(freq = n/sum(n) * 100) %>%
  ungroup() %>%
  complete(uID, cluster, fill = list(freq = 0)) %>%
  left_join(exp.info)

# plot
ggplot(summaryDF,
       aes(as.factor(cluster), freq, fill = interaction(Cohort, Response))) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    # width = 0.3, alpha = 0.6) +
  # stat_summary(fun=mean, geom="point", size=3, shape=18, color="Magenta") +
  ylab("Population (%)") + xlab("") +
  # ylim(0, 1) +
  scale_fill_brewer(name = NULL, palette = "Set3")

summaryDF$Treatment <- 0
summaryDF[summaryDF$Cohort == "ICI" & summaryDF$Response == "Yes",]$Treatment <- 1

# save as csv for plotting in Prism
write.csv(summaryDF, file.path(anaDir, "cluster_regions.csv"))
```

```{r}
# get distances from lymphs to melano
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "U7LRc9", versionID = versionID, initReactivity = FALSE # Set
)

exp.info <- cciaObj$summary(withSelf = FALSE, fields = c("Attr"))

uIDs <- names(cciaObj$cciaObjects())
uIDs <- uIDs[uIDs %in% exp.info[exp.info$Include == "Y",]$uID]

# run task
funParams <- list(
  popsA = c("clust.lymphs"),
  popsB = c("clust.melano"),
  maxContactDist = 5
)

task <- cciaObj$runTasks(
  funName = "spatialAnalysis.cellContactsMeshes",
  funParams = funParams,
  env = "local",
  runInplace = TRUE,
  taskID = 1,
  uIDs = uIDs
)
```

```{r}
# get pops for contact detection
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "U7LRc9", versionID = versionID, initReactivity = FALSE # Set
)

exp.info <- as.data.table(
  cciaObj$summary(withSelf = FALSE, fields = c("Attr")) %>%
    left_join(read.csv(file.path(anaDir, "sample.info.csv")))
  )

uIDs <- names(cciaObj$cciaObjects())
uIDs <- uIDs[uIDs %in% exp.info[exp.info$Include == "Y", ]$uID]

# get cluster information
popDT <- cciaObj$popDT(
  # popType = "clust", pops = c("lymphs"), includeFiltered = TRUE, uIDs = uIDs)
  popType = "clust", pops = c("lymphs", "melano"), includeFiltered = TRUE, uIDs = uIDs)
```


```{r}
# get distance of activated T cells to melano
clusterDist <- popDT %>%
  group_by(uID, clusters) %>%
  summarise(mean.dist = median(`clust.cell.min_distance#clust.melano`)) %>%
  ungroup() %>%
  # complete(uID, clusters, fill = list(mean.dist = 100)) %>%
  left_join(exp.info)
clusterContact <- popDT[,`clust.cell.contact#clust.melano` := `clust.cell.min_distance#clust.melano` <= 1] %>%
  group_by(uID, clusters, `clust.cell.contact#clust.melano`) %>%
  summarise(n = n()) %>%
  mutate(freq.contact = n/sum(n)) %>%
  dplyr::filter(`clust.cell.contact#clust.melano` == TRUE) %>%
  ungroup() %>%
  complete(uID, clusters, fill = list(freq.contact = 0)) %>%
  left_join(exp.info)
```

```{r fig_cluster_dist, fig.height=1.5, fig.width=14}
# plot out
ggplot(clusterDist, aes(clusters, mean.dist,
                        fill = interaction(Cohort, Response))) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    # width = 0.3, alpha = 0.6) +
  ylab("Median distance to melano (um)") + xlab("") +
  scale_fill_brewer(name = NULL, palette = "Set3")

clusterDist$Treatment <- 0
clusterDist[clusterDist$Cohort == "ICI" & clusterDist$Response == "No",]$Treatment <- 1
clusterDist[clusterDist$Cohort == "ICI" & clusterDist$Response == "Yes",]$Treatment <- 2

# save as csv for plotting in Prism
write.csv(clusterDist, file.path(anaDir, "cluster_dist.csv"))
```

```{r fig_cluster_contact, fig.height=1.5, fig.width=14}
# plot out
ggplot(clusterContact, aes(clusters, freq.contact,
                        fill = interaction(Cohort, Response))) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    # width = 0.3, alpha = 0.6) +
  ylab("Contact with melano (%)") + xlab("") +
  scale_fill_brewer(name = NULL, palette = "Set3")
```

