---
title: "Run modules"
output: html_document
date: '2022-08-16'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Examples to run functions and modules

```{r}
# set test variables
pID <- "kicbHw"
versionID <- 1
```

```{r}
anaDir <- "/Volumes/USER_data/Dominik/Experiments/SAPNA_SNS_2P/CECELIA"
```

```{r}
Sys.setenv(KMP_DUPLICATE_LIB_OK = "TRUE")
devtools::load_all("../")
cciaUse("~/cecelia/dev")

library(ggplot2)
library(tidyverse)
```

```{r}
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "SRMXQH", versionID = versionID, initReactivity = FALSE
)

# get clustering
cells.sc <- as.data.table(cciaEnv()$LabelPropsUtils(
  cciaObj$persistentObjectDirectory(), value_name = "tracks.clusters.cells.default.sc")$label_props_view()$as_df())

# get popDTs for set
popDTs <- cciaObj$popDT(
  popType = "live", pops = c("cellA/tracked", "cellB/tracked"),
  includeFiltered = TRUE, flushCache = TRUE)
```

```{r fig_umap, fig.height=3, fig.width=3}
# plot UMAP
ggplot(
  cells.sc,
  aes(UMAP_1, UMAP_2)
  ) +
  geom_point(aes(color = clusters)) +
  theme_classic() +
  scale_color_brewer(name = NULL, palette = "Set1") +
  theme(
    axis.text = element_text(size = 15),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    legend.justification = "center",
    legend.position = "bottom",
    legend.text = element_text(size = 20),
    axis.line = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    ) + guides(colour = guide_legend(override.aes = list(size = 6)))

ggsave(file.path(anaDir, "umap.png"), width = 5, height = 5)
```

```{r fig_clusters_heat, fig.height=3, fig.width=3}
# show heatmap for clusters
propsSummary <- cells.sc %>%
  pivot_longer(
    cols = colnames(cells.sc)[!colnames(cells.sc) %in% c(
      "pop", "uID", "track_id", "clusters", "UMAP_1", "UMAP_2"
      )],
    names_to = "prop", values_to = "value"
    ) %>%
  group_by(clusters, prop) %>%
  summarise(mean = mean(value, rm.na = TRUE)) %>%
  group_by(prop) %>%
  mutate(freq = (mean - min(mean)) / (max(mean) - min(mean)))

ggplot(propsSummary, aes(as.factor(clusters), prop)) +
  theme_classic() +
  geom_tile(aes(fill = freq), colour = "white", size = 0.5) +
  viridis::scale_fill_viridis(
    breaks = c(0, 1),
    labels = c(0, 1)
  ) +
  theme(
    # legend.position = "none",
    legend.key.size = unit(4, "mm"),
    legend.title = element_blank(),
    legend.text = element_text(size = 14),
    axis.text.y = element_text(size = 14),
    axis.text.x = element_text(size = 14),
    strip.background = element_blank(),
    strip.text.x = element_blank()
    ) +
  xlab("") + ylab("")

ggsave(file.path(anaDir, "clusters_heat.png"), width = 4.5, height = 4)
```

```{r fig_states_time, fig.height = 2, fig.width = 2}
# get frequencies of clusters at time points
hmmTime <- popDTs %>%
  dplyr::filter(
    !is.na(live.cell.hmm.state.default),
    live.cell.track.clusters.default != "NA"
    ) %>%
  group_by(uID,
    centroid_t,
    # live.cell.track.clusters.default
    live.cell.hmm.state.default
    ) %>%
  summarise(n = n()) %>%
  mutate(
    # live.cell.track.clusters.default = as.factor(live.cell.track.clusters.default),
    live.cell.hmm.state.default = as.factor(live.cell.hmm.state.default),
    freq = n/sum(n)
    )

time.interval <- cciaObj$cciaObjects()[[1]]$omeXMLTimelapseInfo()$interval

ggplot(hmmTime,
       aes((centroid_t * time.interval), freq,
           # color = live.cell.track.clusters.default,
           # fill = live.cell.track.clusters.default,
           color = live.cell.hmm.state.default,
           fill = live.cell.hmm.state.default,
           )) +
  geom_smooth() +
  theme_classic() +
  scale_color_brewer(name = NULL, palette = "Dark2") +
  scale_fill_brewer(name = NULL, palette = "Dark2") +
  theme(
    legend.title = element_blank(),
    legend.position = "bottom"
    ) +
  xlab("Time (min)") + ylab("HMM frequency") +
  ylim(0, 1) + facet_grid(uID~.)

ggsave(file.path(anaDir, "hmm_time.png"), height = 2.5, width = 3)
```

```{r fig_states_space, fig.height = 2, fig.width = 5}
# get frequencies of hmm states at time points
hmmSpace <- copy(popDTs) %>%
  dplyr::filter(!is.na(live.cell.hmm.state.default))

# get density colours
hmmSpace$density <- ""
for (i in unique(hmmSpace$uID)) {
  for (j in unique(hmmSpace$live.cell.hmm.state.default)) {
    x <- hmmSpace[hmmSpace$uID == i & hmmSpace$live.cell.hmm.state.default == j,]
    
    hmmSpace[hmmSpace$uID == i & hmmSpace$live.cell.hmm.state.default == j,]$density <- .flowColours(
      x$centroid_x, x$centroid_y)
  }
}

ggplot(hmmSpace, aes(centroid_x, centroid_y)) +
  theme_classic() +
  plotThemeDark(
    fontSize = 8,
    legend.justification = "centre"
    ) +
  geom_point(
    color = hmmSpace$density, size = 0.5
    ) +
  scale_color_brewer(name = NULL, palette = "Set3") +
  coord_fixed() +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    legend.title = element_blank(),
    legend.position = 'bottom'
    ) +
  facet_grid(uID~live.cell.hmm.state.default)

ggsave(file.path(anaDir, "hmm_space.png"), height = 2, width = 5)
```
