---
title: "Run modules"
output: html_document
date: '2022-08-16'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Examples to run functions and modules

```{r}
# set test variables
pID <- "Yl5tkH"
versionID <- 1
projectsDir <- "/Volumes/Analysis_SSD/Dominik/cecelia/projects/"
hpcDir <- "/data/scratch/projects/punim1124/cecelia/USERS/schienstockd/"
```

```{r}
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia")
```

```{r}
# calculate compensation matric
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "rcjHiw", versionID = versionID, initReactivity = FALSE
)

cciaObj$runTask(
  funName = "gatePopulations.applyAutospill",
  funParams = list(
    uIDs = names(cciaObj$cciaObjects())
  ),
  runInplace = TRUE,
  taskID = 1
)
```

```{r}
anaDir <- "/Volumes/USER_data/Dominik/Experiments/DS_N033/ANALYSIS/CCIA"
```

```{r}
# visualise compensation
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE)
library(ggplot2)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "rcjHiw", versionID = versionID, initReactivity = FALSE
)

# get channels
channels <- paste0(stringr::str_extract(
  lapply(cciaObj$cciaObjects(), function(x) basename(x$oriFilepath())),
  "(?<=Controls_).*(?= Stained)"), "-A")

p1s <- list()
for (x in channels) {
  p1s[[x]] <- list()
}

# go through compensations and plot out
for (x in cciaObj$cciaObjects()) {
  fgs <- x$flowGatingSet()
  gs <- fgs$getPopObj()
  xPop <- "comp"
  
  # get DTs
  rootDT <- .flowFortifyGs(gs, subset = "root")
  oriDT <- .flowFortifyGs(gs, subset = "comp")
  comDT <- .flowFortifyGs(
    .flowCompensateGs(flowWorkspace::gs_clone(gs), cciaObj$flowAutospillMatrix()),
    subset = "comp")
  
  gsDT <- rbindlist(list(comp = comDT, ori = oriDT), idcol = "type")
  
  # get gate
  xGate <- fgs$popGate(xPop)
  xLabel <- names(xGate@parameters)[1]
  yLabel <- names(xGate@parameters)[2]
    
  # get range
  xRange <- range(rootDT[, ..xLabel])
  yRange <- range(rootDT[, ..yLabel])
    
  # build raster
  r1 <- .flowRasterBuild(rootDT, xLabel, yLabel,
                         colorMode = "white", layout = "cover",
                         color = "black",
                         xRange = xRange, yRange = yRange)
    
  # get boundaries
  # rectangle gate?
  if (attr(xGate, "class") == "rectangleGate") {
    # build path
    gateDT <- as.data.table(list(
      x = c(xGate@min[1], xGate@min[1], xGate@max[1], xGate@max[1]),
      y = c(xGate@min[2], xGate@max[2], xGate@max[2], xGate@min[2])
    ))
    setnames(gateDT, "x", xLabel)
    setnames(gateDT, "y", yLabel)
  } else {
    # close path
    gateDT <- as.data.table(xGate@boundaries)
    gateDT <- rbind(gateDT, gateDT[1])
  }
    
  # go through channels
  channelNames <- colnames(gsDT)[!colnames(gsDT) %in% c(
    'type','.rownames','name','Time','FSC-A','FSC-H','FSC-W','SSC-A','SSC-H','SSC-W'
  )]
  
  channel <- paste0(stringr::str_extract(
    basename(x$oriFilepath()), "(?<=Controls_).*(?= Stained)"), "-A")
  
  # plot gate
  local({
    p1s[[channel]][["gate"]] <<- ggplot() +
      theme_classic() +
      annotation_raster(
        r1$image,
        xmin=r1$x_range[1], xmax=r1$x_range[2],
        ymin=r1$y_range[1], ymax=r1$y_range[2]) +
      xlim(xRange) + ylim(yRange) +
      xlab(xLabel) + ylab(yLabel) +
      geom_polygon(
        data = gateDT,
        aes(
          x = get(xLabel),
          y = get(yLabel)
          ), size = 2, color = "#ff048e", fill = "#ff048e")
  })
  
  for (y in channelNames[channelNames != channel]) {
    local({
      local_channel <- channel
      local_y <- y
      
      # get raster
      r1 <- .flowRasterBuild(
        gsDT, local_channel, local_y,
        colorMode = "white", layout = "cover",
        colorBy = "type", color = c("black", "blue"))
      
      p1s[[channel]][[y]] <<- ggplot() +
        theme_classic() +
        annotation_raster(
          r1$image,
          xmin=r1$x_range[1], xmax=r1$x_range[2],
          ymin=r1$y_range[1], ymax=r1$y_range[2]) +
        xlim(r1$x_range) + ylim(r1$y_range) +
        xlab(local_channel) + ylab(local_y) 
    })
  }
}
```

```{r fig_comp, fig.height=4, fig.width=6}
for (i in names(p1s)) {
  ggpubr::ggarrange(plotlist = p1s[[i]], nrow = 3, ncol = 4)
  ggsave(file.path(anaDir, "comp", paste0(i, ".pdf")), width = 10, height = 6)
}
```


```{r}
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "nNwqEC", versionID = versionID, initReactivity = FALSE
)

paste(cciaObj$imChannelNames(), collapse = "','")

funParams <- list(
  fileAutospillComp = "/Volumes/USER_data/Dominik/Experiments/DS_N033/ANALYSIS/20201121/autospill_spillover.csv",
  applyAutospillComp = TRUE
)

cciaObj$runTask(
  funName = "importFlow.fcsRaw",
  funParams = funParams,
  runInplace = TRUE
)
```


```{r}
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "nNwqEC", versionID = versionID, initReactivity = FALSE
)

cciaObj$runTask(
  funName = "gatePopulations.createGatingSet",
  funParams = list(
    compensateZ = FALSE,
    applyReversedLog = FALSE,
    transformation = "logicle",
    transChannels = c(
      'FITC-A','PE (561)-A','PerCP-Cy5-5-A',
      'APC-A','AF700-A','APC-Cy7-A','V450-A',
      'Qdot 800-A','Qdot 705-A','Qdot 525-A',
      'Qdot 605-A','PE-Cy7-A'
    )
  ),
  runInplace = TRUE
)
```

```{r}
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "nNwqEC", versionID = versionID, initReactivity = FALSE
)

library(ggplot2)

# go through pops and build gating scheme
fgs <- cciaObj$flowGatingSet()

p1s <- list()
for (x in fgs$popPaths()) {
  local({
    xParent <- .flowPopParent(x, root = "root")
  
    # get gate
    xGate <- fgs$popGate(x)
    xLabel <- names(xGate@parameters)[1]
    yLabel <- names(xGate@parameters)[2]
    
    # get pops
    popDT <- cciaObj$popDT(
      "flow", pops = c("root", xParent), cols = names(xGate@parameters),
      completeDT = FALSE, uniqueLabels = TRUE)
    
    # get range
    xRange <- range(popDT[, ..xLabel])
    yRange <- range(popDT[, ..yLabel])
    
    # build raster
    rasterContours <- .flowRasterContour(
      popDT[pop == xParent], xLabel, yLabel, xRange = xRange, yRange = yRange)

    # get boundaries
    # rectangle gate?
    if (attr(xGate, "class") == "rectangleGate") {
      # build path
      gateDT <- as.data.table(list(
        x = c(xGate@min[1], xGate@min[1], xGate@max[1], xGate@max[1]),
        y = c(xGate@min[2], xGate@max[2], xGate@max[2], xGate@min[2])
      ))
      setnames(gateDT, "x", xLabel)
      setnames(gateDT, "y", yLabel)
    } else {
      # close path
      gateDT <- as.data.table(xGate@boundaries)
      gateDT <- rbind(gateDT, gateDT[1])
    }
    
    # add label
    # nameDT <- as.data.frame(rbind(gateDT %>% colMeans()))
    nameDT <- as.data.frame(list(
      x = mean(gateDT[[xLabel]]),
      y = max(gateDT[[yLabel]])
    ))
    colnames(nameDT) <- c(xLabel, yLabel)
    nameDT$label <- .flowTrimPath(x, pathLevels = 0)
    
    # add percentage
    popStats <- fgs$getPopStats(x, type = "percent")
    nameDT$label <- paste(
      nameDT$label, paste0(
        sprintf("%0.3f", popStats$percent), "%"))
    
    # plot out
    p1 <- ggplot() +
      theme_classic() +
      annotation_raster(
        rasterContours$raster$image,
        xmin=rasterContours$raster$x_range[1],
        xmax=rasterContours$raster$x_range[2],
        ymin=rasterContours$raster$y_range[1],
        ymax=rasterContours$raster$y_range[2]) +
      xlim(xRange) + ylim(yRange) +
      xlab(xLabel) + ylab(yLabel) +
      geom_polygon(
        data = rasterContours$contours,
        aes(x = y, y = x, group = as.factor(seq)),
        size = 0.2, color = "black", fill = "white")
    
    p1 <- p1 + geom_polygon(
      data = gateDT,
      aes(
        x = get(xLabel),
        y = get(yLabel)
        ), size = 0.5, color = "black", fill = "#23aeff", alpha = 0.2) +
      geom_label(
        data = nameDT,
        aes(
          label = label,
          x = get(xLabel),
          y = get(yLabel)),
        size = 2, color = cciaObj$popAttr("flow", "colour", popPath = x)[[1]]
        )
    
    p1s[[x]] <<- p1
  })
}

ggpubr::ggarrange(plotlist = p1s, nrow = 2, ncol = 3)
ggsave(file.path(anaDir, "gating_contours.pdf"), width = 10, height = 6)
```

```{r}
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "nNwqEC", versionID = versionID, initReactivity = FALSE
)

library(ggplot2)

# go through pops and build gating scheme
fgs <- cciaObj$flowGatingSet()

p1s <- list()
for (x in fgs$popPaths()) {
  local({
    xParent <- .flowPopParent(x, root = "root")
  
    # get gate
    xGate <- fgs$popGate(x)
    xLabel <- names(xGate@parameters)[1]
    yLabel <- names(xGate@parameters)[2]
    xPops <- c("root", xParent, x, fgs$popDirectLeaves(x))
    
    # get pops
    popDT <- cciaObj$popDT(
      "flow", pops = xPops,
      cols = names(xGate@parameters),
      completeDT = FALSE, uniqueLabels = TRUE)
    
    # get range
    xRange <- range(popDT[, ..xLabel])
    yRange <- range(popDT[, ..yLabel])
    
    # get colours
    popColours <- as.list(sapply(
      xPops,
      function(x) cciaObj$popAttr("flow", "colour", popPath = x)[[1]]
    ))
    
    # adjust root colour
    popColours$root <- "black"
    
    popExclude <- ""
    if (!.flowPopIsRoot(xParent)) {
      popExclude <- "root"
      popColours <- popColours[names(popColours) != "root"]
    }
    
    # build raster
    r1 <- .flowRasterBuild(
      popDT[pop != popExclude], xLabel, yLabel,
      colorMode = "white", layout = "cover",
      colorBy = "pop", color = popColours, xRange = xRange, yRange = yRange)
    
    # get boundaries
    # rectangle gate?
    if (attr(xGate, "class") == "rectangleGate") {
      # build path
      gateDT <- as.data.table(list(
        x = c(xGate@min[1], xGate@min[1], xGate@max[1], xGate@max[1]),
        y = c(xGate@min[2], xGate@max[2], xGate@max[2], xGate@min[2])
      ))
      setnames(gateDT, "x", xLabel)
      setnames(gateDT, "y", yLabel)
    } else {
      # close path
      gateDT <- as.data.table(xGate@boundaries)
      gateDT <- rbind(gateDT, gateDT[1])
    }
    
    # add label
    # nameDT <- as.data.frame(rbind(gateDT %>% colMeans()))
    nameDT <- as.data.frame(list(
      x = mean(gateDT[[xLabel]]),
      y = max(gateDT[[yLabel]])
    ))
    colnames(nameDT) <- c(xLabel, yLabel)
    nameDT$label <- .flowTrimPath(x, pathLevels = 0)
    
    # add percentage
    popStats <- fgs$getPopStats(x, type = "percent")
    nameDT$label <- paste(
      nameDT$label, paste0(
        sprintf("%0.3f", popStats$percent), "%"))
    
    p1 <- ggplot() +
      theme_classic() +
      annotation_raster(
        r1$image,
        xmin=r1$x_range[1], xmax=r1$x_range[2],
        ymin=r1$y_range[1], ymax=r1$y_range[2]) +
      xlim(xRange) + ylim(yRange) +
      xlab(xLabel) + ylab(yLabel) 
    
    p1 <- p1 + geom_polygon(
      data = gateDT,
      aes(
        x = get(xLabel),
        y = get(yLabel)
        ), size = 0.5, color = "black", fill = "#23aeff", alpha = 0.0) +
      geom_label(
        data = nameDT,
        aes(
          label = label,
          x = get(xLabel),
          y = get(yLabel)),
        size = 2, color = cciaObj$popAttr("flow", "colour", popPath = x)[[1]]
        )
    
    p1s[[x]] <<- p1
  })
}

ggpubr::ggarrange(plotlist = p1s, nrow = 2, ncol = 3)
ggsave(file.path(anaDir, "gating_overlays.pdf"), width = 10, height = 6)
```

```{r}
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "nNwqEC", versionID = versionID, initReactivity = FALSE
)

library(ggplot2)

# go through pops and build gating scheme
fgs <- cciaObj$flowGatingSet()

p1s <- list()
for (x in fgs$popPaths()) {
  local({
    xParent <- .flowPopParent(x, root = "root")
  
    # get gate
    xGate <- fgs$popGate(x)
    xLabel <- names(xGate@parameters)[1]
    yLabel <- names(xGate@parameters)[2]
    xPops <- c("root", xParent, x, fgs$popDirectLeaves(x))
    
    # get pops
    popDT <- cciaObj$popDT(
      "flow", pops = xPops, cols = names(xGate@parameters),
      completeDT = FALSE, uniqueLabels = TRUE)
    
    # get range
    xRange <- range(popDT[, ..xLabel])
    yRange <- range(popDT[, ..yLabel])
    
    # get colours
    popColours <- as.list(sapply(
      xPops,
      function(x) cciaObj$popAttr("flow", "colour", popPath = x)[[1]]
    ))
    
    # adjust root colour
    popColours$root <- "black"
    
    popExclude <- ""
    if (!.flowPopIsRoot(xParent)) {
      popExclude <- "root"
      popColours <- popColours[names(popColours) != "root"]
    }
    
    # build raster
    rasterContours <- list()
    for (y in xPops[!xPops %in% popExclude]) {
      rasterContours[[y]] <- .flowRasterContour(
        popDT[pop == y], xLabel, yLabel, color = popColours[[y]],
        xRange = xRange, yRange = yRange)
    }

    # get boundaries
    # rectangle gate?
    if (attr(xGate, "class") == "rectangleGate") {
      # build path
      gateDT <- as.data.table(list(
        x = c(xGate@min[1], xGate@min[1], xGate@max[1], xGate@max[1]),
        y = c(xGate@min[2], xGate@max[2], xGate@max[2], xGate@min[2])
      ))
      setnames(gateDT, "x", xLabel)
      setnames(gateDT, "y", yLabel)
    } else {
      # close path
      gateDT <- as.data.table(xGate@boundaries)
      gateDT <- rbind(gateDT, gateDT[1])
    }
    
    # add label
    # nameDT <- as.data.frame(rbind(gateDT %>% colMeans()))
    nameDT <- as.data.frame(list(
      x = mean(gateDT[[xLabel]]),
      y = max(gateDT[[yLabel]])
    ))
    colnames(nameDT) <- c(xLabel, yLabel)
    nameDT$label <- .flowTrimPath(x, pathLevels = 0)
    
    # add percentage
    popStats <- fgs$getPopStats(x, type = "percent")
    nameDT$label <- paste(
      nameDT$label, paste0(
        sprintf("%0.3f", popStats$percent), "%"))
    
    # plot out
    p1 <- ggplot() +
      theme_classic()
    
    # add rasters
    for (j in names(rasterContours)) {
      y <- rasterContours[[j]]
      
      p1 <- p1 + annotation_raster(
        y$raster$image,
        xmin = y$raster$x_range[1],
        xmax = y$raster$x_range[2],
        ymin = y$raster$y_range[1],
        ymax = y$raster$y_range[2]
      ) +
        geom_polygon(
          data = y$contours,
          aes(x = y, y = x, group = as.factor(seq)),
          size = 0.2, color = popColours[[j]], fill = "white"
          )
    }
    
    p1 <- p1 + xlim(xRange) + ylim(yRange) +
      xlab(xLabel) + ylab(yLabel) +
      geom_polygon(
        data = gateDT,
        aes(
          x = get(xLabel),
          y = get(yLabel)
        ), size = 0.5, color = "black", fill = "#23aeff", alpha = 0.0) +
      geom_label(
        data = nameDT,
        aes(
          label = label,
          x = get(xLabel),
          y = get(yLabel)),
        size = 2, color = cciaObj$popAttr("flow", "colour", popPath = x)[[1]]
        )
    
    p1s[[x]] <<- p1
  })
}

ggpubr::ggarrange(plotlist = p1s, nrow = 2, ncol = 3)
ggsave(file.path(anaDir, "gating_contours_overlay.pdf"), width = 10, height = 6)
```

```{r}
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "nNwqEC", versionID = versionID, initReactivity = FALSE
)

library(ggplot2)

# go through pops and build gating scheme
fgs <- cciaObj$flowGatingSet()

p1s <- list()
for (x in fgs$popPaths()) {
  local({
    xParent <- .flowPopParent(x, root = "root")
  
    # get gate
    xGate <- fgs$popGate(x)
    xLabel <- names(xGate@parameters)[1]
    yLabel <- names(xGate@parameters)[2]
    
    # get pops
    popDT <- cciaObj$popDT(
      "flow", pops = c("root", xParent), cols = names(xGate@parameters),
      completeDT = FALSE, uniqueLabels = TRUE)
    
    # get range
    xRange <- range(popDT[, ..xLabel])
    yRange <- range(popDT[, ..yLabel])
    
    # build raster
    r1 <- .flowRasterBuild(popDT[pop == xParent], xLabel, yLabel,
                           colorMode = "white", layout = "cover",
                           xRange = xRange, yRange = yRange)
    
    # get boundaries
    # rectangle gate?
    if (attr(xGate, "class") == "rectangleGate") {
      # build path
      gateDT <- as.data.table(list(
        x = c(xGate@min[1], xGate@min[1], xGate@max[1], xGate@max[1]),
        y = c(xGate@min[2], xGate@max[2], xGate@max[2], xGate@min[2])
      ))
      setnames(gateDT, "x", xLabel)
      setnames(gateDT, "y", yLabel)
    } else {
      # close path
      gateDT <- as.data.table(xGate@boundaries)
      gateDT <- rbind(gateDT, gateDT[1])
    }
    
    # add label
    # nameDT <- as.data.frame(rbind(gateDT %>% colMeans()))
    nameDT <- as.data.frame(list(
      x = mean(gateDT[[xLabel]]),
      y = max(gateDT[[yLabel]])
    ))
    colnames(nameDT) <- c(xLabel, yLabel)
    nameDT$label <- .flowTrimPath(x, pathLevels = 0)
    
    # add percentage
    popStats <- fgs$getPopStats(x, type = "percent")
    nameDT$label <- paste(
      nameDT$label, paste0(
        sprintf("%0.3f", popStats$percent), "%"))
    
    p1 <- ggplot() +
      theme_classic() +
      annotation_raster(
        r1$image,
        xmin=r1$x_range[1], xmax=r1$x_range[2],
        ymin=r1$y_range[1], ymax=r1$y_range[2]) +
      xlim(xRange) + ylim(yRange) +
      xlab(xLabel) + ylab(yLabel) 
    
    p1 <- p1 + geom_polygon(
      data = gateDT,
      aes(
        x = get(xLabel),
        y = get(yLabel)
        ), size = 0.5, color = "black", fill = "#23aeff", alpha = 0.2) +
      geom_label(
        data = nameDT,
        aes(
          label = label,
          x = get(xLabel),
          y = get(yLabel)),
        size = 2, color = cciaObj$popAttr("flow", "colour", popPath = x)[[1]]
        )
    
    p1s[[x]] <<- p1
  })
}

ggpubr::ggarrange(plotlist = p1s, nrow = 2, ncol = 3)
ggsave(file.path(anaDir, "gating.pdf"), width = 10, height = 6)
```

```{r}
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE)

# propagate gating to other objects
# propagateFlowGating in CciaImageSet
fromUID <- "nNwqEC"
toUIDs <- NULL

# get gating set
cciaFrom <- initCciaObject(
  pID = pID, uID = fromUID, versionID = versionID, initReactivity = FALSE
)
cciaTo <- initCciaObject(
  pID = pID, uID = "Oqu9Il", versionID = versionID, initReactivity = FALSE
)

# get gating set
# gsFrom <- cciaFrom$flowGatingSet()
# gsTo <- cciaTo$flowGatingSet()
```

```{r}
# visualise gating
# CytoExploreR 
devtools::install_github("DillonHammill/CytoExploreR")
```

```{r}
library(CytoExploreR)

devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "nNwqEC", versionID = versionID, initReactivity = FALSE
)

# Gating scheme
cyto_plot_gating_scheme(
  cciaObj$flowGatingSet()$getPopObj(),
  back_gate = TRUE, gate_track = TRUE)
```

```{r}
# cluster Va2+
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "etxWEx", versionID = versionID, initReactivity = FALSE
)

imChannels <- cciaObj$cciaObjects()[[1]]$imChannelNames()
clusterChannels <- c(
  'TEAL.FITC','CD71.PE','CD25.APC','CD98.PE.Cy7','CTV'
)

cciaObj$runTask(
  funName = "clustPopulations.leidenClustering",
  funParams = list(
    valueName = "default",
    popsToCluster = c("/Lymph/Singlets/Live/T/Va2+"),
    popType = "flow",
    # savePops = TRUE,
    savePops = FALSE,
    keepPops = FALSE,
    resolution = 0.4,
    normaliseAxis = "channels",
    normaliseToMedian = FALSE,
    maxFraction = 0,
    normalisePercentile = 99.98,
    normalisePercentileBottom = 0,
    normaliseIndividually = FALSE,
    transformation = "log",
    logBase = 0,
    uIDs = names(cciaObj$cciaObjects()),
    clusterChannels = list(
      base = list(
        channels = which(imChannels %in% clusterChannels) - 1
      )
    )
  ),
  runInplace = TRUE
)
```

```{r}
# show treatments on UMAP
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "etxWEx", versionID = versionID, initReactivity = FALSE
)

popDT <- cciaObj$popDT(
  popType = "clust",
  uIDs = names(cciaObj$cciaObjects()),
  includeFiltered = TRUE,
  completeDT = FALSE, replaceNA = TRUE,
  # only focus on clustered values
  filterMeasures = c("clusters")
)

exp.info <- cciaObj$summary(withSelf = FALSE, fields = c("Attr"))
```

```{r fig_pop_freq, fig.height=1, fig.width=1.5}
datToPlot <- copy(popDT) %>% left_join(exp.info) %>%
  group_by(Treatment, uID, pop) %>%
  summarise(n = n()) %>%
  mutate(freq = n/sum(n))

ggplot(
  datToPlot, aes(Treatment, freq, fill = pop)) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    # width = 0.4, alpha = 1.0) +
  scale_fill_brewer(name = NULL, palette = "Set3")

ggsave(file.path(anaDir, "pop_freq.pdf"), width = 3, height = 2)
```


```{r fig_umap, fig.height=3, fig.width=6}
# plot UMAP with paga connections
datToPlot <- copy(popDT) %>% left_join(exp.info)

p1 <- ggplot(
  datToPlot,
  aes(UMAP_1, UMAP_2)) +
  theme_classic() +
  scale_color_brewer(name = NULL, palette = "Set3") +
  geom_point(color = "grey") +
  stat_density_2d(
    contour_var = "ndensity", bins = 12,
    colour = "yellow") +
  facet_grid(.~Treatment)

p1 + plotThemeDark(angle = 0, fontSize = 15) +
  theme(
    axis.text = element_text(size = 15),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    legend.justification = "right",
    # legend.position = "bottom"
    legend.position = "none",
    axis.line = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
    )

ggsave(file.path(anaDir, "umap_treatment.pdf"), width = 6, height = 3)
```


