---
title: "Run modules"
output: html_document
date: '2022-08-16'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Examples to run functions and modules

```{r}
# set test variables
pID <- "RTA7nu"
versionID <- 1
projectsDir <- "/Volumes/USER_data/Dominik/CECELIA_BACKUP/"
```

```{r}
anaDir <- "/Volumes/USER_data/Dominik/Experiments/YA_CCL19/static"
```

```{r}
# Load cluster data
Sys.setenv(KMP_DUPLICATE_LIB_OK = "TRUE")

library(flowCore)
devtools::load_all("../")
cciaUse("~/cecelia/dev")

library(ggplot2)
library(tidyverse)
```

```{r}
      - "#ff0000"
      - "#ff8c00"
      - "#ffd700"
      - "#0000cd"
      - "#00ff00"
      - "#00fa9a"
      - "#4169e1"
      - "#e9967a"
      - "#00ffff"
      - "#00bfff"
      - "#d8bfd8"
      - "#ff00ff"
      - "#f0e68c"
      - "#ff1493"
      - "#ee82ee"
```


```{r}
# add pop map back to images
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "TtEFdZ", versionID = versionID, initReactivity = FALSE
)

for (x in cciaObj$cciaObjects()) {
  x$setImPopMap("flow", list(
    tu0wiW = list(name = "cells", colour = "#d8bfd8", show = TRUE,
                  parent = "root", path = "/cells", valueName = "default",
                  gateID = 1, xChannel = "volume", yChannel = "surface_to_volume"),
    tu0wi1 = list(name = "P14", colour = "#ff1493", show = TRUE,
                  parent = "cells", path = "/cells/P14", valueName = "default",
                  gateID = 1, xChannel = "AF", yChannel = "P14"),
    tu0wi4 = list(name = "O1", colour = "#d8bfd8", show = TRUE,
                  parent = "cells", path = "/cells/O1", valueName = "default",
                  gateID = 2, xChannel = "AF", yChannel = "P14"),
    tu0wi5 = list(name = "XCR1", colour = "#00fa9a", show = TRUE,
                  parent = "O1", path = "/cells/O1/XCR1", valueName = "default",
                  gateID = 1, xChannel = "XCR1.Venus", yChannel = "CD11c.PE"),
    tu0wi0 = list(name = "CD11c", colour = "#ffd700", show = TRUE,
                  parent = "O1", path = "/cells/O1/CD11c", valueName = "default",
                  gateID = 2, xChannel = "XCR1.Venus", yChannel = "CD11c.PE"),
    tu0wi6 = list(name = "O2", colour = "#d8bfd8", show = TRUE,
                  parent = "O1", path = "/cells/O1/O2", valueName = "default",
                  gateID = 3, xChannel = "XCR1.Venus", yChannel = "CD11c.PE"),
    tu0wi7 = list(name = "B220", colour = "#4169e1", show = TRUE,
                  parent = "O2", path = "/cells/O1/O2/B220", valueName = "default",
                  gateID = 1, xChannel = "AF", yChannel = "B220.PB")
  ))
  
  # x$setImGatingSetFilepath("default.gs", "default")
  # x$imGatingSetFilepath()
  # x$saveState()
  
  # run task
  funParams <- list(
    valueName = "LCMV",
    preDilationSize = 0,
    postDilationSize = 2,
    flattenBranching = FALSE,
    useBorders = FALSE,
    calcExtended = FALSE,
    calcFlattened = FALSE,
    anisoRadius = 40,
    saveMeshes = FALSE
  )
  
  # run task
  # task <- cciaObj$runTasks(
  task <- x$runTask(
    funName = "segment.createBranching",
    funParams = funParams,
    env = "local",
    runInplace = FALSE,
    taskID = 1
    # uIDs = names(cciaObj$cciaObjects()),
    # mc.cores = 4
  )
}
```

```{r}
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "CXqh2V", versionID = versionID, initReactivity = FALSE
)

colnames(cciaObj$popDT("flow"))
```



```{r}
# Load cluster data
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "7rIBcg", versionID = versionID, initReactivity = FALSE
)

saveRDS(cciaObj$getCciaMeta()$funParams.segment.cellpose,
        file.path(anaDir, "conf", "cp_params_exp1.rds"))

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "b0iSyj", versionID = versionID, initReactivity = FALSE
)

saveRDS(cciaObj$getCciaMeta()$funParams.segment.cellpose,
        file.path(anaDir, "conf", "cp_params_exp2.rds"))
```

```{r}
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  # pID = pID, uID = "TtEFdZ", versionID = versionID, initReactivity = FALSE, projectsDir = projectsDir
  pID = pID, uID = "7rIBcg", versionID = versionID, initReactivity = FALSE, projectsDir = projectsDir
)

# run task
funParams <- list(
  popsA = c("flow./cells/P14"),
  # popsB = c("flow./cells/O1/XCR1", "flow./cells/O1/CD11c", "branch.LCMV.branch/two"),
  popsB = c("branch.LCMV.branch/two"),
  maxContactDist = 5
)

# uIDs <- names(cciaObj$cciaObjects())

# run task
# task <- cciaObj$runTasks(
task <- cciaObj$runTask(
  funName = "spatialAnalysis.cellContacts",
  funParams = funParams,
  env = "local",
  runInplace = TRUE,
  taskID = 1
  # uIDs = uIDs,
  # mc.cores = 1
)
```


```{r fig_gating, fig.height=3, fig.width=5}
# Load cluster data
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "TtEFdZ", versionID = versionID, initReactivity = FALSE
)

exp.info <- as.data.table(cciaObj$summary(withSelf = FALSE, fields = c("Attr")))

popDT <- cciaObj$popDT(popType = "flow", pops = c("/cells/P14"))
# popDT <- cciaObj$popDT(popType = "flow")
```

```{r fig_gating, fig.height=6, fig.width=6}
# Load cluster data
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "TtEFdZ", versionID = versionID, initReactivity = FALSE
)

for (x in cciaObj$cciaObjects()) {
    # get raster contours
  p1s <- .flowPlotGatedRaster(
    x, popPaths = "root", labelSize = 5, labelBorder = 1, labelAlpha = 0.8,
    xTitleSize = 16, yTitleSize = 16, asContours = TRUE, plotTitleSize = 16)
  
  p1 <- ggpubr::ggarrange(plotlist = p1s, nrow = 2, ncol = 2)
  
  ggsave(file.path(anaDir, "gating", paste0(x$getCciaAttr(attrName = "DTx"), "_", x$getUID(), ".pdf")),
         width = 8, height = 8, plot = p1)
}
```

```{r}
# plot out clustering cells
datToPlot <- popDT %>%
  group_by(uID, flow.cell.is.clust) %>%
  summarise(n = n()) %>%
  mutate(freq = n/sum(n) * 100) %>%
  dplyr::filter(flow.cell.is.clust == TRUE) %>%
  left_join(exp.info)

ggplot(datToPlot, aes(DTx, freq)) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    # position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    width = 0.2, alpha = 1.0) +
  ylim(0, 100)

ggsave(file.path(anaDir, "P14_clustering.pdf"), width = 2, height = 2)
write.csv(datToPlot, file.path(anaDir, "P14_clustering.csv"))
```

```{r}
# plot out composition of cluster ie/ contact with XCR1 and virus
# ie/ for every cluster ID there is a composition
# datToPlot <- popDT[flow.cell.is.clust == TRUE] %>%
datToPlot <- popDT %>%
  rename(
    XCR1 = `flow.cell.contact#flow.__cells/O1/XCR1`,
    CD11c = `flow.cell.contact#flow.__cells/O1/CD11c`,
    LCMV = `flow.cell.contact#branch.LCMV.branch__two`
  ) %>%
  pivot_longer(
    cols = c("XCR1", "CD11c", "LCMV"),
    names_to = "contact_type", values_to = "contact_value") %>%
  # dplyr::filter(contact_value == TRUE) %>%
  group_by(uID, flow.cell.is.clust, contact_type, contact_value) %>%
  summarise(n = n()) %>%
  mutate(freq = n/sum(n) * 100) %>%
  ungroup() %>%
  complete(uID, contact_type, contact_value, fill = list(freq = 0)) %>%
  dplyr::filter(contact_value == TRUE) %>%
  left_join(exp.info)

datToPlot$popState <- "non.clustering"
datToPlot[datToPlot$flow.cell.is.clust == TRUE,]$popState <- "clustering"

ggplot(datToPlot, aes(DTx, freq, color = contact_type)) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    # width = 0.2, alpha = 1.0) +
  ylim(0, 100) +
  scale_color_brewer(palette = "Set2") +
  facet_grid(.~popState)

ggsave(file.path(anaDir, "P14_cluster_interactions.pdf"), width = 5, height = 2)
write.csv(datToPlot, file.path(anaDir, "P14_cluster_interactions.csv"))
```

```{r}
# plot out % of all three cell types together
# ie/ for every cluster ID there is a composition
# datToPlot <- popDT[flow.cell.is.clust == TRUE] %>%
datToPlot <- as.data.table(popDT %>%
  rename(
    XCR1 = `flow.cell.contact#flow.__cells/O1/XCR1`,
    CD11c = `flow.cell.contact#flow.__cells/O1/CD11c`,
    LCMV = `flow.cell.contact#branch.LCMV.branch__two`
  ))

# condition for 
datToPlot[, triplet := FALSE]
datToPlot[, triplet_CD11c := FALSE]
datToPlot[, triplet_XCR1 := FALSE]
datToPlot[(XCR1 == TRUE | CD11c == TRUE) & LCMV == TRUE, triplet := TRUE]
datToPlot[(CD11c == TRUE) & LCMV == TRUE, triplet_CD11c := TRUE]
datToPlot[(XCR1 == TRUE) & LCMV == TRUE, triplet_XCR1 := TRUE]
```


```{r fig_triplet, fig.height=3, fig.width=3}
summaryToPlot <- datToPlot %>%
  group_by(uID, flow.cell.is.clust, triplet) %>%
  summarise(n = n()) %>%
  mutate(freq = n/sum(n) * 100) %>%
  ungroup() %>%
  complete(uID, triplet, fill = list(freq = 0)) %>%
  dplyr::filter(triplet == TRUE) %>%
  left_join(exp.info)

summaryToPlot$popState <- "non.clustering"
summaryToPlot[summaryToPlot$flow.cell.is.clust == TRUE,]$popState <- "clustering"

ggplot(summaryToPlot, aes(DTx, freq, color = popState)) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    # width = 0.2, alpha = 1.0) +
  ylim(0, 100) +
  scale_color_brewer(palette = "Set2")

ggsave(file.path(anaDir, "P14_triplet_interactions.pdf"), width = 3, height = 2)
write.csv(summaryToPlot, file.path(anaDir, "P14_triplet_interactions.csv"))
```

```{r fig_triplet, fig.height=3, fig.width=3}
summaryToPlot <- datToPlot %>%
  group_by(uID, flow.cell.is.clust, triplet_CD11c) %>%
  summarise(n = n()) %>%
  mutate(freq = n/sum(n) * 100) %>%
  ungroup() %>%
  complete(uID, triplet_CD11c, fill = list(freq = 0)) %>%
  dplyr::filter(triplet_CD11c == TRUE) %>%
  left_join(exp.info) %>%
  replace_na(list(flow.cell.is.clust = FALSE))

summaryToPlot$popState <- "non.clustering"
summaryToPlot[summaryToPlot$flow.cell.is.clust == TRUE,]$popState <- "clustering"

ggplot(summaryToPlot, aes(DTx, freq, color = popState)) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    # width = 0.2, alpha = 1.0) +
  ylim(0, 100) +
  scale_color_brewer(palette = "Set2")

ggsave(file.path(anaDir, "P14_triplet_CD11c_interactions.pdf"), width = 3, height = 2)
write.csv(summaryToPlot, file.path(anaDir, "P14_triplet_CD11c_interactions.csv"))
```

```{r fig_triplet, fig.height=3, fig.width=3}
summaryToPlot <- datToPlot %>%
  group_by(uID, flow.cell.is.clust, triplet_XCR1) %>%
  summarise(n = n()) %>%
  mutate(freq = n/sum(n) * 100) %>%
  ungroup() %>%
  complete(uID, triplet_XCR1, fill = list(freq = 0)) %>%
  dplyr::filter(triplet_XCR1 == TRUE) %>%
  left_join(exp.info)

summaryToPlot$popState <- "non.clustering"
summaryToPlot[summaryToPlot$flow.cell.is.clust == TRUE,]$popState <- "clustering"

ggplot(summaryToPlot, aes(DTx, freq, color = popState)) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    # width = 0.2, alpha = 1.0) +
  ylim(0, 100) +
  scale_color_brewer(palette = "Set2")

ggsave(file.path(anaDir, "P14_triplet_XCR1_interactions.pdf"), width = 3, height = 2)
write.csv(summaryToPlot, file.path(anaDir, "P14_triplet_XCR1_interactions.csv"))
```


```{r}
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "TtEFdZ", versionID = versionID, initReactivity = FALSE
)

uIDs <- names(cciaObj$cciaObjects())
# pops <- cciaObj$popPaths(popType = "flow", includeFiltered = FALSE, uIDs = uIDs[1])
pops <- cciaObj$popPaths(popType = "flow", includeFiltered = TRUE, uIDs = uIDs[1])
pops <- pops[is.na(str_match(pops, "/O[0-9]*$"))]
pops <- pops[pops != "/cells"]

# can you show a similar trend with SPIAT?
spe <- cciaObj$spe(popType = "flow", pops = pops, uIDs = uIDs, includeFiltered = TRUE)
```

```{r}
entropies <- list()

gradient_pos <- seq(50, 500, 50) ##radii
spe_pops <- c(
  "/cells/P14/clustered",
  "/cells/P14/non.clustered",
  "/cells/O1/XCR1",
  "/cells/O1/CD11c"
)

for (i in names(spe)) {
  print(paste(">>", i))
  
  x <- spe[[i]]
  
  entropies[[i]] <- as.data.table(SPIAT::entropy_gradient_aggregated(
    x, cell_types_of_interest = spe_pops,
    feature_colname = "Phenotype", radii = gradient_pos)$gradient_df)
}

entropiesDT <- rbindlist(entropies, idcol = "uID")
```

```{r fig_spe_entity, fig.height=10, fig.width=10}
datToPlot <- entropiesDT %>%
  pivot_longer(
    cols = starts_with("Pos_"),
    names_to = "radius",
    names_pattern = ".*_(.*)",
    values_to = "value") %>%
  mutate(radius = as.numeric(radius)) %>%
  left_join(exp.info)

ggplot(datToPlot, aes(radius, value, color = DTx, group = uID)) +
  theme_classic() +
  geom_line() +
  # ylim(0, 1) +
  facet_wrap(Celltype1~Celltype2, ncol = 3, scales = "free_y")
```

```{r fig_spe_colocalisation, fig.height=5, fig.width=8}
# is there anything that you can use to find a difference between PBS/DTx?
spe_pops <- c(
  "/cells/P14/clustered",
  "/cells/P14/non.clustered",
  "/cells/O1/XCR1"
  # "/cells/O1/CD11c"
)

# Average pairwise distance (APD)
# Average minimum distance (AMD)
spiat.amd <- lapply(spe, function(x) {
  # SPIAT::calculate_pairwise_distances_between_celltypes(
  as.data.table(SPIAT::calculate_minimum_distances_between_celltypes(
    spe_object = x, 
    cell_types_of_interest = spe_pops,
    feature_colname = "Phenotype"))
})
spiat.amdDT <- rbindlist(spiat.amd, idcol = "uID")

ggplot(spiat.amdDT %>% left_join(exp.info), aes(Pair, Distance, fill = DTx)) +
  theme_classic() +
  geom_violin(scale = "width") +
  # geom_jitter(
  #   position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
  coord_flip()
    # width = 0.2, alpha = 1.0)
  # ylim(0, 1)
```


```{r fig_spe_colocalisation, fig.height=3, fig.width=3}
# Normalized mixing score (NMS)
spiat.nms <- lapply(spe, function(x) {
  as.data.table(SPIAT::mixing_score_summary(
    spe_object = x, 
    # reference_celltype = "/cells/P14/clustered",
    reference_celltype = "/cells/P14/non.clustered",
    target_celltype = "/cells/O1/XCR1",
    feature_colname = "Phenotype"))
})
spiat.nmsDT <- rbindlist(spiat.nms, idcol = "uID")

ggplot(spiat.nmsDT %>% left_join(exp.info), aes(DTx, Mixing_score)) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    # position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    width = 0.2, alpha = 1.0)

ggplot(spiat.nmsDT %>% left_join(exp.info), aes(DTx, Normalised_mixing_score)) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    # position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    width = 0.2, alpha = 1.0)
```

```{r fig_spe_colocalisation, fig.height=3, fig.width=3}
# Cross-K AUC
spiat.ckauc <- lapply(spe, function(x) {
  SPIAT::AUC_of_cross_function(SPIAT::calculate_cross_functions(
    spe_object = x, 
    method = "Kcross", cell_types_of_interest = c(
      # "/cells/P14/clustered", "/cells/O1/XCR1"),
      "/cells/P14/non.clustered", "/cells/O1/XCR1"),
      # "/cells/P14/non.clustered", "/cells/O1/CD11c"),
    dist = 100,
    feature_colname = "Phenotype"))
})
spiat.ckaucDT <- as.data.frame(unlist(spiat.ckauc)) %>% rownames_to_column()
colnames(spiat.ckaucDT) <- c("uID", "value")

ggplot(spiat.ckaucDT %>% left_join(exp.info), aes(DTx, value)) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    # position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    width = 0.2, alpha = 1.0)
  # ylim(0, 1)
```


```{r fig_spe_colocalisation, fig.height=3, fig.width=3}
# Cross-K intersection (CKI)
spiat.cki <- lapply(spe, function(x) {
  SPIAT::crossing_of_crossK(SPIAT::calculate_cross_functions(
    spe_object = x, 
    method = "Kcross", cell_types_of_interest = c(
      # "/cells/P14/clustered", "/cells/O1/XCR1"),
      "/cells/P14/non.clustered", "/cells/O1/XCR1"),
      # "/cells/P14/non.clustered", "/cells/O1/CD11c"),
    dist = 100,
    feature_colname = "Phenotype"))
})
spiat.ckiDT <- as.data.frame(unlist(spiat.cki)) %>% rownames_to_column()
colnames(spiat.ckiDT) <- c("uID", "value")

ggplot(spiat.ckiDT %>% left_join(exp.info), aes(DTx, value)) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    # position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    width = 0.2, alpha = 1.0)
  # ylim(0, 1)
```


```{r}
# show pops on image
Sys.setenv(KMP_DUPLICATE_LIB_OK = "TRUE")
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = TRUE, initJupyter = TRUE)
# cciaUse("~/cecelia/dev", initConda = FALSE, initJupyter = TRUE)

# start ipython kernel
viewer <- NapariUtils$new()

viewer$initNapari()
```

```{r}
generateScreenshots <- function(
    anaDir, cciaObj, uIDs, channelsToShow, popsToShow, fileAttrs,
    valueName = "default", matchChannels = FALSE, save = TRUE, ...) {
  # go through images and save movies
  for (x in cciaObj$cciaObjects(uIDs = uIDs)) {
    i <- x$getUID()
    viewer$setTaskDir(x$persistentObjectDirectory())
    
    # get channels
    imChannelNames <- x$imChannelNames()
    
    # match channels
    curChannelsToShow <- channelsToShow
    if (matchChannels == TRUE) {
      # TODO this is very crude    
      names(curChannelsToShow) <- sapply(names(channelsToShow), function(y) {
        imChannelNames[!is.na(stringr::str_extract(imChannelNames, y))][[1]]
      })
    }

    # get cmaps
    layersVisible <- imChannelNames %in% names(curChannelsToShow)
    channelColormaps <- rep("gray", length(layersVisible))
    
    for (j in names(curChannelsToShow))
      channelColormaps[[which(imChannelNames == j)]] <- curChannelsToShow[[j]]
    
    # open image
    viewer$openImage(
      x$imFilepath(),
      imChannelNames = imChannelNames,
      show3D = TRUE,
      layersVisible = layersVisible,
      channelColormaps = channelColormaps,
      multiscales = as.integer(2)
    )
    
    # add populations
    popsAdded <- list()
    
    # show on image
    removePrevious <- TRUE
    pointsSize <- max(x$omeXMLPixels()$SizeX, x$omeXMLPixels()$SizeY) * 0.005
    # pointsSize <- max(x$omeXMLPixels()$SizeX, x$omeXMLPixels()$SizeY) * 0.003
    
    # add populations to popMap
    for (popType in names(popsToShow)) {
      popMap <- x$imPopMap(popType, includeFiltered = TRUE)
      curPops <- popsToShow[[popType]]
    
      # get popIDs for paths
      popIDs <- lapply(names(curPops), function(y) x$popIDsByAttr(popType, "path", y, includeFiltered = TRUE))
      names(popIDs) <- names(curPops)
      
      for (pop in names(curPops)) {
        x$editPopColour(popType, popIDs[[pop]], curPops[[pop]], includeFiltered = TRUE)
      }
    
      # save to disk
      x$savePopMap(popType, includeFiltered = TRUE)
      x$savePops(popType, pops = names(popIDs),
                 purge = TRUE, includeFiltered = TRUE)
      
      for (j in names(curPops)) {
        viewer$showPopMapping(popType, valueName = popMap[[popIDs[[j]]]]$valueName,
                              pops = list(j), pointsSize = pointsSize,
                              execInteractive = FALSE, removePrevious = removePrevious)
        removePrevious <- FALSE
      }
    }
    
    # adjust channel intensities
    browser()
  
    # save screenshot
    if (save == TRUE)
      viewer$saveScreenshot(
        file.path(anaDir, paste0(
          paste(sapply(fileAttrs, function(i) x$getCciaAttr(i)), collapse = "_"), "_", i, ".png")),
        ...)
  }
}

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "TtEFdZ", versionID = versionID, initReactivity = FALSE
)

exp.info <- as.data.table(cciaObj$summary(withSelf = FALSE, fields = c("Attr")))
uIDs <- names(cciaObj$cciaObjects())

uIDs <- c("gLtekp", "f7ncxo")

channelsToShow <- list(
  "P14" = "gray",
  "LCMV-594" = "red",
  "CD11c-PE" = "yellow",
  "XCR1-Venus" = "green",
  "B220-PB" = "bop blue"
  )
popsToShow <- list(
  flow = list(
    "/cells/O1/O2/B220" = "#327EBA",
    "/cells/O1/CD11c" = "yellow",
    "/cells/O1/XCR1" = "green",
    "/cells/P14" = "magenta",
    "/cells/P14/clustered" = "white"
  ),
  branch = list(
    "LCMV.branch/two" = "red"
  )
)
fileAttrs <- c("DTx")

generateScreenshots(
  # file.path(anaDir, "images"), cciaObj, uIDs, channelsToShow,
  file.path(anaDir, "populations"), cciaObj, uIDs, channelsToShow,
  # list(), fileAttrs, size = list(1200, 1200), save = TRUE)
  popsToShow, fileAttrs, size = list(1200, 1200), save = FALSE)
```