---
title: "Run modules"
output: html_document
date: '2022-08-16'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Examples to run functions and modules

```{r}
# set test variables
pID <- "wEsnzt"
versionID <- 1
projectsDir <- "/Volumes/Analysis_SSD/Dominik/cecelia/projects/"
hpcDir <- "/data/scratch/projects/punim1124/cecelia/USERS/schienstockd/"
```

```{r}
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia")

library(ggplot2)
library(tidyverse)
```

```{r}
# HPC config
HPC_CONF <-  list(
  hpc = list(
    conf = list(
      email = "schienstockd@student.unimelb.edu.au",
      emailOnBegin = FALSE,
      emailOnEnd = FALSE,
      emailOnFail = TRUE,
      numNodes = 1,
      numTasks = 1,
      numCPUperTask = 1,
      numGPUperTask = 1,
      memory = 50,
      # walltime = "01-00:00:00",
      walltime = "00-04:00:00",
      # walltime = "00-00:20:00",
      projectPartitions = "physical",
      projectID = "punim1124",
      useGPU = FALSE
      # projectPartitions = "gpu-a100",
      # projectID = "punim1031",
      # useGPU = TRUE
    )
  ),
  utils = list(
    ssh = list(
      username = "schienstockd",
      address = "spartan.hpc.unimelb.edu.au",
      keyfile = "/Users/schiend/.ssh/spartan_rsa"
    ),
    python = list(
      condaEnv = cciaConf()$python$conda$source$env
    )
  )
)
```

```{r}
anaDir <- "/Volumes/USER_data/Dominik/Experiments/IBEX/CECELIA"
```

```{r}
# upload 
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "n22foC", versionID = versionID, initReactivity = FALSE 
)

# run cellpose
# run task
funParams <- list(
)

# run task
task <- cciaObj$runTask(
  funName = "hpc.uploadCciaObj",
  funParams = funParams,
  envVars = HPC_CONF,
  hpcDir = paste(hpcDir, pID, "ANALYSIS", sep = "/"),
  env = "local",
  runInplace = TRUE,
  taskID = 1
)
```

```{r}
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "n22foC", versionID = versionID, initReactivity = FALSE # Spleen
)

# run cellpose
# run task
funParams <- list(
  # valueName = "default",
  valueName = "stroma",
  models = list(
    "1" = list(
      "model" = "ccia.fluo",
      # "model" = "cyto2",
      "matchAs" = "none",
      # "matchAs" = "cyto",
      "cellDiameter" = 5,
      # "cellChannels" = list("Vimentin", "CD49a", "SMA", "Fibrinogen"),
      "cellChannels" = list("Vimentin", "CD49a"),
      "nucChannels" = list(),
      # "nucChannels" = list("Hoechst"),
      "normalise" = 98,
      "stitchThreshold" = 0.2,
      # "mergeLabels" = FALSE,
      "mergeLabels" = TRUE,
      "threshold" = 1,
      "relTreshold" = 0,
      "gaussianFilter" = 0,
      "medianFilter" = 0
    )
    # "1" = list(
    #   "model" = "cyto2",
    #   "matchAs" = "cyto",
    #   "cellDiameter" = 10,
    #   "cellChannels" = list("CD31"),
    #   "nucChannels" = list("Hoechst"),
    #   "normalise" = 99,
    #   "stitchThreshold" = 0.2,
    #   "mergeLabels" = FALSE,
    #   "threshold" = 0,
    #   "relTreshold" = 0,
    #   "gaussianFilter" = 0,
    #   "medianFilter" = 0
    # ),
    # "2" = list(
    #   "model" = "cyto2",
    #   "matchAs" = "cyto",
    #   "cellDiameter" = 15,
    #   "cellChannels" = list("CD11c", "HLA-DR", "CD163", "CD68"),
    #   "nucChannels" = list("Hoechst"),
    #   "normalise" = 99,
    #   "stitchThreshold" = 0.2,
    #   "mergeLabels" = FALSE,
    #   "threshold" = 0,
    #   "relTreshold" = 0,
    #   "gaussianFilter" = 0,
    #   "medianFilter" = 0
    # ),
    # "3" = list(
    #   "model" = "cyto2",
    #   "matchAs" = "cyto",
    #   "cellDiameter" = 10,
    #   "cellChannels" = list("CD45", "CD15", "CD138", "CD54"),
    #   "nucChannels" = list("Hoechst"),
    #   "normalise" = 99,
    #   "stitchThreshold" = 0.2,
    #   "mergeLabels" = FALSE,
    #   "threshold" = 0,
    #   "relTreshold" = 0,
    #   "gaussianFilter" = 0,
    #   "medianFilter" = 0
    # ),
    # "4" = list(
    #   "model" = "cyto2",
    #   "matchAs" = "nuc",
    #   "cellDiameter" = 10,
    #   "cellChannels" = list("Hoechst"),
    #   "nucChannels" = list(),
    #   "normalise" = 99,
    #   "stitchThreshold" = 0.2,
    #   "mergeLabels" = FALSE,
    #   "threshold" = 0,
    #   "relTreshold" = 0,
    #   "gaussianFilter" = 0,
    #   "medianFilter" = 0
    # )
  ),
  clearDepth = FALSE,
  clearTouchingBorder = FALSE,
  haloSize = 0,
  blockSize = 2048,
  overlap = 120,
  blockSizeZ = -1,
  overlapZ = -1,
  context = 40,
  # segment = TRUE,
  segment = FALSE,
  updateMeasures = FALSE,
  extendedMeasures = TRUE,
  saveMeshes = FALSE,
  saveMeasures = TRUE,
  labelExpansion = 0,
  labelErosion = 0,
  minCellSize = 50,
  matchThreshold = 0.2,
  removeUnmatched = TRUE
)

# run task
task <- cciaObj$runTask(
  funName = "segment.cellpose",
  funParams = funParams,
  envVars = HPC_CONF,
  hpcDir = paste(hpcDir, pID, "ANALYSIS", sep = "/"),
  env = "hpc",
  # env = "local",
  runInplace = FALSE,
  # runInplace = TRUE,
  taskID = 1
  # taskID = 2
)
```

```{r}
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "n22foC", versionID = versionID, initReactivity = FALSE # Spleen
)

# run task
funParams <- list(
  valueName = "stroma",
  dilationSize = 1
)

# run task
task <- cciaObj$runTask(
  funName = "segment.createBranching",
  funParams = funParams,
  env = "local",
  # runInplace = TRUE,
  runInplace = FALSE,
  taskID = 1
)
```


```{r}
# retrieve 
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "n22foC", versionID = versionID, initReactivity = FALSE 
)

# run cellpose
# run task
funParams <- list(
  valueNames = c("default", "stroma"),
  retrieveMeshesOnly = FALSE
)

# run task
task <- cciaObj$runTask(
  funName = "segment.retrieve",
  funParams = funParams,
  envVars = HPC_CONF,
  hpcDir = paste(hpcDir, pID, "ANALYSIS", sep = "/"),
  env = "local",
  runInplace = TRUE,
  taskID = 1
)
```

```{r}
# get branching of stroma network
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "n22foC", versionID = versionID, initReactivity = FALSE 
)

branchingDT <- as.data.table(cciaObj$labelProps(valueName = "stroma.branch")$as_df())
```

```{r fig_branching, fig.height=5, fig.width=13}
# show branching of stroma network
ggplot(branchingDT, aes(`coord-dst-2`, `coord-dst-1`, color = as.factor(`branch-type`))) +
  theme_classic() +
  geom_point(size = 0.5) +
  coord_fixed() +
  scale_color_brewer(palette = "Set1") +
  plotThemeDark(angle = 0)

ggsave(file.path(anaDir, 'stroma', 'n22foC_branching_type.png'), height = 20, width = 30)
```

```{r}
# show regions of stroma
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "n22foC", versionID = versionID, initReactivity = FALSE 
)

regionDT <- cciaObj$popDT(
  "region", includeFiltered = TRUE, completeDT = TRUE,
  completeValueNames = "stroma.branch", pops = c("root"))

popDT <- cciaObj$popDT(
  "clust", includeFiltered = TRUE, completeDT = TRUE,
  popCols = c("pop", paste0("stroma.branch_type_", seq(0, 3))),
  # pops = unlist(unname(cciaObj$popPaths("clust", includeFiltered = TRUE))),
  pops = unlist(unname(cciaObj$popPaths("clust", includeFiltered = TRUE, includeRoot = TRUE))),
  forceReload = TRUE)
```

```{r fig_branching_regions, fig.height=5, fig.width=8}
# plot out
ggplot(popDT %>% filter(
    pop != "root",
    # centroid_x > 3000, centroid_x <= 7000,
    # centroid_y > 2000, centroid_y <= 6000,
  ), aes(centroid_x, centroid_y, color = as.factor(pop))) +
  theme_classic() +
  plotThemeDark(angle = 0) +
  geom_point(size = 4) +
  coord_fixed() +
  scale_color_brewer(palette = "Set3") +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.line = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    legend.position = "none"
  )

# ggsave(file.path(anaDir, 'stroma', 'n22foC_pops.png'), height = 20, width = 20)
ggsave(file.path(anaDir, 'stroma', 'n22foC_pops_whole.png'), height = 20, width = 35)
```

```{r fig_branching_regions, fig.height=5, fig.width=8}
# plot out
ggplot(regionDT %>% filter(
    # centroid_x > 3000, centroid_x <= 7000,
    # centroid_y > 2000, centroid_y <= 6000,
  ),  aes(centroid_x, centroid_y, color = as.factor(regions))) +
# ggplot(regionDT, aes(centroid_x, centroid_y, color = as.factor(`branch-type`))) +
  theme_classic() +
  plotThemeDark(angle = 0) +
  geom_point(size = 2) +
  coord_fixed() +
  scale_color_brewer(palette = "Set1") +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.line = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    legend.position = "none"
  )

# ggsave(file.path(anaDir, 'stroma', 'n22foC_branching_type.png'), height = 20, width = 30)
# ggsave(file.path(anaDir, 'stroma', 'n22foC_branching_regions.png'), height = 20, width = 20)
ggsave(file.path(anaDir, 'stroma', 'n22foC_branching_regions_whole.png'), height = 20, width = 35)
```

```{r}
# find nearest neighbours
popNN <- dbscan::kNN(
  as.matrix(regionDT[, c('centroid_z', 'centroid_y', 'centroid_x')]),
  k = 1,
  query = as.matrix(popDT[, c('centroid_z', 'centroid_y', 'centroid_x')]))

# filter long distances
regionVals <- regionDT[popNN$id, ]$regions
# regionVals <- regionDT[popNN$id, ]$`branch-type`
regionVals[popNN$dist > 50 * cciaObj$omeXMLPixelRes()$x] <- -1

# assign regions to pops
popDT[, regionsNN := as.factor(regionVals)]
```

```{r fig_pop_branching, fig.height=1, fig.width=2.5}
summaryDT <- popDT %>%
  # drop_na() %>%
  # group_by(pop, regionsNN) %>%
  group_by(clusters, regionsNN) %>%
  summarise(n = n()) %>%
  mutate(freq = n/sum(n) * 100) %>%
  dplyr::filter(regionsNN != "-1")
  
summaryDT$clusters <- recode(
  summaryDT$clusters,
  `0` = 'CD20+ B cell',
  `1` = 'CD8+ T cell',
  `2` = 'CD54+ 1',
  `3` = 'Unspecified',
  `4` = 'CD163+ Macro',
  `5` = 'CD45+1',
  `6` = 'CD4+ T cell',
  `7` = 'CD54+ 2',
  `8` = 'CD45+ 2',
  `9` = 'CD54+ 3',
  `10` = 'CD11c+ Macro',
  `11` = 'CD15+ Macro',
  `12` = 'CD54+ 4',
  `13` = 'CD61+',
  `14` = 'CD31+',
  `15` = 'CD54+ 5',
  `16` = 'Glyco.A+'
)
summaryDT$regionsNN <- recode(
  summaryDT$regionsNN,
  `1` = 'Loose',
  `2` = 'Medium',
  `3` = 'Dense'
)

# ggplot(summaryDT, aes(pop, freq, fill = regionsNN)) +
# ggplot(summaryDT, aes(clusters, freq, fill = regionsNN)) +
ggplot(summaryDT, aes(reorder(clusters, freq), freq, fill = regionsNN)) +
  theme_classic() +
  ylim(0, 100) +
  geom_col() +
  scale_fill_brewer(palette = "Set1") +
  theme(
    # axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
    legend.title = element_blank(),
    legend.position = "bottom",
    legend.justification = "left"
  ) +
  xlab("") + ylab("Stroma region (%)") +
  coord_flip()

ggsave(file.path(anaDir, 'stroma', 'n22foC_branching_regions_clusters.png'), height = 4, width = 4)
```

```{r}
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE)
# init ccia object
cciaObj <- initCciaObject(
  # pID = pID, uID = "BNcZ2j", versionID = versionID, initReactivity = FALSE # LN
  # pID = pID, uID = "SXejeM", versionID = versionID, initReactivity = FALSE # Liver
  # pID = pID, uID = "TyFwVs", versionID = versionID, initReactivity = FALSE # Set
  pID = pID, uID = "n22foC", versionID = versionID, initReactivity = FALSE # Spleen
)
# exp.info <- as.data.table(cciaObj$summary(withSelf = FALSE, fields = c("Attr")))
# uIDs <- c("BNcZ2j")
# get cluster information
popDT <- cciaObj$popDT(
  popType = "clust", includeFiltered = TRUE,
  pops = c("root"),
  # pops = c("T", "B", "macro.dc", "endothelial", "lymphatic", "lymphs"), # LN
  completeDT = TRUE, replaceX = TRUE)
unique(popDT$clusters)
```

```{r}
# define populations
clust <- list(
  init = c("T", "B", "macro.dc", "endothelial", "lymphatic", "lymphs"),
  macro.dc = c("macro.dc"),
  cd45 = c("T", "B"),
  b = c("B"),
  t = c("T")
)
markers <- list(
  init = c("CD11c", "CD45", "CD68", "Lyve-1", "CD31"),
  macro.dc = c(
    "CLEC9a AF488", "DC-SIGN", "HLA-DR", "CXCL13", "CD1c",
    "CD163", "CD68", "CD11c", "IRF4", "CD35", "CD10"),
  cd45 = c("CD4", "CD3", "CD20", "CD8", "CD45"),
  b = c("BCL2", "BCL6", "IgD", "CD21", "CD23"),
  t = c(
    "TCR Va7.2", "CD25", "PD-1", "CD69", "ICOS", "nuc_Ki-67",
    "nuc_FOXP3", "CD44", "CD106", "CD38", "CD4", "CD8", "CD3")
)
groupVars <- list(
  init = "pop",
  macro.dc = "clusters",
  cd45 = "pop",
  b = "clusters",
  t = "clusters"
)
combinePops <- list(
  init = list(
    lymphs = c("T", "B", "lymphs")
    ),
  macro.dc = list(),
  cd45 = list(),
  b = list(),
  t = list()
)
plotSizes <- list(
  init = c(3, 4),
  macro.dc = c(4.5, 4.5),
  cd45 = c(2, 3),
  b = c(3, 3),
  t = c(5, 5)
)
```

```{r fig_clusters_heat, fig.height=5, fig.width=8}
for (i in names(clust)) {
  popsToShow <- clust[[i]]
  markersToShow <- .flowCorrectChannelNames(markers[[i]])
  groupVar <- groupVars[[i]]
  popsToCombine <- combinePops[[i]]
  plotSize <- plotSizes[[i]]
  
  # excludeMarkers <- c(
  # )
  # 
  # markersToShow <- cciaObj$imChannelNames()[!cciaObj$imChannelNames() %in% excludeMarkers]
  # markersToShow <- unname(unlist(.flowCorrectChannelNames(markersToShow)))
  # markersToShow <- markersToShow[markersToShow %in% colnames(popDT)]
  # markersToShow <- c(markersToShow, "nuc_FOXP3", "nuc_Ki.67")
  
  markersToShowNoDye <- stringr::str_extract(markersToShow, ".*(?=_)")
  
  colsToShow <- c("label", "clusters", "pop", markersToShow)
  colsToShow <- colsToShow[colsToShow %in% colnames(popDT)]
  
  # show heatmap
  popLymphs <- popDT[pop %in% popsToShow, ..colsToShow]
  
  # combine pops
  if (length(popsToCombine) > 0) {
    for (j in names(popsToCombine))
      popLymphs[pop %in% popsToCombine[[j]], pop := j]
  }
  
  markersToPlot <- popLymphs %>%
    pivot_longer(
      cols = all_of(markersToShow), names_to = "marker", values_to = "value"
      )
  markersToPlot[markersToPlot$marker == "CLEC9a.AF488", ]$marker <- "CLEC9a"
  markersToPlot$marker <- as.factor(markersToPlot$marker)
  
  # show heatmap for clusters
  markersSummary <- markersToPlot %>%
    drop_na() %>%
    group_by(marker, get(groupVar)) %>%
    summarise(mean = mean(value, rm.na = TRUE)) %>%
    mutate(norm = (mean - min(mean))/(max(mean) - min(mean))) %>%
    replace_na(list(norm = 0)) %>%
    rename_with(~ c(groupVar), all_of(c("get(groupVar)")))
  
  # find order for clusters and markers
  markersMatrix <- markersSummary %>%
    pivot_wider(names_from = marker, values_from = norm, id_cols = groupVar)
  
  hcClusters <- hclust(dist(as.matrix(markersMatrix %>% dplyr::select(-all_of(groupVar)))), "ave")
  hcMarkers <- hclust(dist(t(as.matrix(markersMatrix %>% dplyr::select(-all_of(groupVar))))), "ave")
  
  clustersOrder <- markersMatrix[[groupVar]][hcClusters$order]
  markerOrder <- colnames(markersMatrix)[2:length(colnames(markersMatrix))][hcMarkers$order]
  
  p1 <- ggplot(markersSummary %>%
           mutate(
             # clusters = factor(clusters, levels = clustersOrder),
             # clusters = factor(clusters, levels = sort(as.numeric(levels(clustersOrder)))),
             marker = factor(marker, levels = markerOrder)
           ), aes(get(groupVar), marker)) +
    theme_classic() +
    # geom_tile(aes(fill = mean), colour = "white", size = 0.5) +
    geom_tile(aes(fill = norm), colour = "white", size = 0.5) +
    viridis::scale_fill_viridis(
      breaks = c(0, 1),
      labels = c(0, 1)
    ) +
    theme(
      legend.position = "none",
      legend.title = element_blank(),
      legend.text = element_text(size = 20),
      legend.key.size = unit(10, "mm"),
      axis.text.y = element_text(size = 20),
      # axis.text.x = element_text(size = 20),
      axis.text.x = element_text(size = 20, angle = 45, hjust = 1, vjust = 1),
      strip.background = element_blank(),
      strip.text.x = element_blank()
      ) +
    xlab("") + ylab("")
  plot(p1)
  
  ggsave(file.path(anaDir, paste0("clusters_heat_", i, ".pdf")),
         width = plotSize[[1]], height = plotSize[[2]])
}
```


```{r fig_pops_umap, fig.height=2, fig.width=2}
library(tidyverse)
dfToPlot <- copy(popDT[!clusters %in% c(melanoClusters, endothelialClusters)])
# get mean positions of clusters
meanClusterPos <- dfToPlot %>%
  group_by(clusters) %>%
  summarise(
    UMAP_1 = mean(UMAP_1),
    UMAP_2 = mean(UMAP_2)
  )
clustersPalette <- randomcoloR::distinctColorPalette(
  length(unique(dfToPlot$clusters)))
# plot UMAP with paga connections
ggplot(
  dfToPlot %>%
    mutate(clusters = factor(clusters, levels = clustersOrder)),
  aes(UMAP_1, UMAP_2)
  ) +
  theme_classic() +
  geom_point(aes(color = as.factor(clusters)), size = 0.5) +
  # scale_color_brewer(name = NULL, palette = "Set1") +
  scale_color_manual(values = clustersPalette) +
  theme(
    axis.text = element_text(size = 15),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    legend.justification = "center",
    legend.direction = "horizontal",
    legend.position = "bottom",
    # legend.position = "none",
    legend.title = element_blank(),
    legend.key.size = unit(5, "mm"),
    legend.text = element_text(size = 18),
    axis.line = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
    ) +
  guides(colour = guide_legend(override.aes = list(size = 4))) 
  # geom_label(
  #   data = meanClusterPos,
  #   aes(label = clusters),
  #   label.size = 0.25,
  #   color = "black"
  #   )
ggsave(file.path(anaDir, "cd45_umap.tiff"), width = 5, height = 6.5)
```

```{r fig_pops_freq, fig.height=1, fig.width=3}
# show frequency of populations for treatments
summaryDF <- popDT %>%
  mutate(clusters = as.character(clusters)) %>%
  group_by(clusters) %>%
  summarise(n = n()) %>%
  mutate(freq = n/sum(n) * 100) %>%
  ungroup() %>%
  complete(clusters, fill = list(freq = 0))
  # left_join(exp.info)
summaryDF$clusters <- factor(
  summaryDF$clusters, levels = unique((summaryDF %>% arrange(-freq))$clusters))
# plot
ggplot(summaryDF,
       aes(clusters, freq)) +
  theme_classic() +
  geom_point() +
  theme(
    axis.text.x = element_text(size = 12, angle = 45, hjust = 1, vjust = 1),
  ) +
  ylab("Population (%)") + xlab("") +
  scale_fill_brewer(name = NULL, palette = "Set3")
# save as csv for plotting in Prism
write.csv(summaryDF, file.path(anaDir, "clusters_freq.csv"))
```

```{r}
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE)
# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "BNcZ2j", versionID = versionID, initReactivity = FALSE # LN
)
# get cluster information
spatialDT <- cciaObj$spatialDT(valueName = "default")
# join pops
# spatialDT[popDT[, c("label", "pop")],
#           on = c("to" = "label"),
#           pop.to := pop]
# spatialDT[popDT[, c("label", "pop")],
#           on = c("from" = "label"),
#           pop.from := pop]
spatialDT[popDT[, c("label", "clusters")],
          on = c("to" = "label"),
          clusters.to := clusters]
spatialDT[popDT[, c("label", "clusters")],
          on = c("from" = "label"),
          clusters.from := clusters]
# filter same type associations
spatialDT <- spatialDT[clusters.to != clusters.from]
```


```{r fig_kmeans_clusters, fig.height=1.5, fig.width=12}
# get "i-niches" and determine a given number of defined clusters
freqRegions <- spatialDT %>%
  group_by(clusters.from, clusters.to) %>%
  summarise(n = n()) %>%
  mutate(freq = n/sum(n)) %>%
  drop_na()
  # ungroup() %>%
  # complete(clusters.from, clusters.to, fill = list(freq = 0))
```

```{r fig_interactions_heat, fig.height=5, fig.width=5}
ggplot(freqRegions %>%
         ungroup() %>%
         complete(clusters.from, clusters.to, fill = list(freq = 0)),
       aes(clusters.from, clusters.to)) +
  theme_classic() +
  geom_tile(aes(fill = freq), colour = "white", size = 0.5) +
  viridis::scale_fill_viridis(
    breaks = c(0, 0.5),
    labels = c(0, 0.5)
  ) +
  theme(
    # legend.position = "none",
    legend.title = element_blank(),
    legend.text = element_text(size = 20),
    legend.key.size = unit(10, "mm"),
    axis.text.y = element_text(size = 20),
    # axis.text.x = element_text(size = 20),
    axis.text.x = element_text(size = 20, angle = 45, hjust = 1, vjust = 1),
    strip.background = element_blank(),
    strip.text.x = element_blank()
    ) +
  xlab("") + ylab("")
ggsave(file.path(anaDir, "interactions_heat.pdf"), width = 10, height = 10)
```


```{r fig_kmeans_clusters, fig.height=1.5, fig.width=12}
# show interactions of individuals
for (i in unique(freqRegions$clusters.from)) {
  x <- freqRegions %>% dplyr::filter(clusters.from == i) 
  
  p1 <- ggplot(x,
               aes(clusters.to, freq)) +
    theme_classic() +
    geom_boxplot(outlier.alpha = 0) +
    geom_jitter(
      # position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
      width = 0.3, alpha = 0.6) +
    # stat_summary(fun=mean, geom="point", size=3, shape=18, color="Magenta") +
    ylab("Population (%)") + xlab("") +
    # ylim(0, 1) +
    scale_fill_brewer(name = NULL, palette = "Set3") +
    ggtitle(i)
  print(p1)
  
  # save as csv for plotting in Prism
  write.csv(x, file.path(anaDir, paste0("interactions_freq", i, ".csv")))
}
```

```{r fig_kmeans_clusters, fig.height=1.5, fig.width=2.5}
# use K-Means to get clusters of regions
normalit <- function(m) (m - min(m))/(max(m)-min(m))
freqRegionsWider <- freqRegions %>%
  # ungroup() %>%
  # mutate(norm = normalit(freq)) %>%
  pivot_wider(
    # id_cols = c(clusters.from),
    id_cols = c(from, clusters.from),
    # id_cols = c(to, clusters.to),
    # id_cols = c(from),
    # id_cols = c(uID),
    names_from = clusters.to,
    # names_from = clusters.from,
    # values_from = norm,
    values_from = freq,
    values_fill = 0
  )
freqRegionsMat <- as.matrix(freqRegionsWider %>%
  ungroup() %>% 
  select(-c(from, clusters.from)))
rownames(freqRegionsMat) <- freqRegionsWider$from
```

```{r fig_kmeans_clusters, fig.height=1.5, fig.width=2.5}
clustToFind <- 4
library(mclust)
# clusters <- kmeans(
#   freqRegionsWider %>%
#     ungroup() %>%
#     select(-c(from, clusters.from)),
#     # select(-c(clusters.to)),
#   clustToFind)
# mcl.model <- Mclust(freqRegionsMat)
mcl.model <- Mclust(freqRegionsMat, clustToFind)
# Plot our results.
# plot(mcl.model, what = "classification", main = "Mclust Classification")
# push back clusters
# freqRegionsWider$cluster <- clusters$cluster
freqRegionsWider$cluster <- mcl.model$classification
popCols <- colnames(freqRegionsWider)[!colnames(freqRegionsWider) %in% c(
  "from", "to", "n", "cluster", "clusters.from", "clusters.to")]
freqRegionsWiderSummary <- freqRegionsWider %>%
  group_by(cluster) %>%
  summarise(across(all_of(popCols), mean)) %>%
  pivot_longer(
    cols = popCols,
    names_to = "pop",
    values_to = "value"
    ) %>%
  mutate(norm = normalit(value))
ggplot(
  freqRegionsWiderSummary, aes(as.factor(cluster), pop)) +
  geom_tile(aes(fill = norm)) +
  viridis::scale_fill_viridis(discrete=FALSE, limits = c(0, 1)) +
  theme_classic() +
  theme(legend.title=element_blank()) +
  xlab("") + ylab("")
```
```{r fig_kmeans_clusters_map, fig.height=3, fig.width=4}
# plot out
popDT[as.data.table(freqRegionsWider[, c("from", "cluster")]),
      on = list(label = from), spatial_cluster := cluster]
ggplot(popDT %>% drop_na(),
       aes(centroid_x, -centroid_y, color = as.factor(spatial_cluster))) +
  theme_classic() +
  geom_point() +
  coord_fixed() +
  scale_color_brewer(palette = "Set1") +
  theme(
    # legend.position = "none",
    legend.title = element_blank(),
    axis.text = element_text(size = 15),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
  ) +
  xlab("") + ylab("")
```


```{r fig_region_freq, fig.height=1, fig.width=6}
# show frequency of populations for treatments
summaryDF <- copy(freqRegionsWider) %>%
  group_by(cluster) %>%
  summarise(n = n()) %>%
  mutate(freq = n/sum(n) * 100) %>%
  ungroup() %>%
  complete(cluster, fill = list(freq = 0)) %>%
  left_join(exp.info)
# plot
ggplot(summaryDF,
       aes(as.factor(cluster), freq, fill = interaction(Cohort, Response))) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    # width = 0.3, alpha = 0.6) +
  # stat_summary(fun=mean, geom="point", size=3, shape=18, color="Magenta") +
  ylab("Population (%)") + xlab("") +
  # ylim(0, 1) +
  scale_fill_brewer(name = NULL, palette = "Set3")
summaryDF$Treatment <- 0
summaryDF[summaryDF$Cohort == "ICI" & summaryDF$Response == "Yes",]$Treatment <- 1
# save as csv for plotting in Prism
write.csv(summaryDF, file.path(anaDir, "cluster_regions.csv"))
```

```{r}
# get distances from lymphs to melano
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE)
# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "U7LRc9", versionID = versionID, initReactivity = FALSE # Set
)
exp.info <- cciaObj$summary(withSelf = FALSE, fields = c("Attr"))
uIDs <- names(cciaObj$cciaObjects())
uIDs <- uIDs[uIDs %in% exp.info[exp.info$Include == "Y",]$uID]
# run task
funParams <- list(
  popsA = c("clust.lymphs"),
  popsB = c("clust.melano"),
  maxContactDist = 5
)
task <- cciaObj$runTasks(
  funName = "spatialAnalysis.cellContactsMeshes",
  funParams = funParams,
  env = "local",
  runInplace = TRUE,
  taskID = 1,
  uIDs = uIDs
)
```

```{r}
# get pops for contact detection
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE)
# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "U7LRc9", versionID = versionID, initReactivity = FALSE # Set
)
exp.info <- as.data.table(
  cciaObj$summary(withSelf = FALSE, fields = c("Attr")) %>%
    left_join(read.csv(file.path(anaDir, "sample.info.csv")))
  )
uIDs <- names(cciaObj$cciaObjects())
uIDs <- uIDs[uIDs %in% exp.info[exp.info$Include == "Y", ]$uID]
# get cluster information
popDT <- cciaObj$popDT(
  # popType = "clust", pops = c("lymphs"), includeFiltered = TRUE, uIDs = uIDs)
  popType = "clust", pops = c("lymphs", "melano"), includeFiltered = TRUE, uIDs = uIDs)
```


```{r}
# get distance of activated T cells to melano
clusterDist <- popDT %>%
  group_by(clusters) %>%
  summarise(mean.dist = median(`clust.cell.min_distance#clust.melano`)) %>%
  ungroup() %>%
  # complete(clusters, fill = list(mean.dist = 100)) %>%
  left_join(exp.info)
clusterContact <- popDT[,`clust.cell.contact#clust.melano` := `clust.cell.min_distance#clust.melano` <= 1] %>%
  group_by(clusters, `clust.cell.contact#clust.melano`) %>%
  summarise(n = n()) %>%
  mutate(freq.contact = n/sum(n)) %>%
  dplyr::filter(`clust.cell.contact#clust.melano` == TRUE) %>%
  ungroup() %>%
  complete(clusters, fill = list(freq.contact = 0)) %>%
  left_join(exp.info)
```

```{r fig_cluster_dist, fig.height=1.5, fig.width=14}
# plot out
ggplot(clusterDist, aes(clusters, mean.dist,
                        fill = interaction(Cohort, Response))) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    # width = 0.3, alpha = 0.6) +
  ylab("Median distance to melano (um)") + xlab("") +
  scale_fill_brewer(name = NULL, palette = "Set3")
clusterDist$Treatment <- 0
clusterDist[clusterDist$Cohort == "ICI" & clusterDist$Response == "No",]$Treatment <- 1
clusterDist[clusterDist$Cohort == "ICI" & clusterDist$Response == "Yes",]$Treatment <- 2
# save as csv for plotting in Prism
write.csv(clusterDist, file.path(anaDir, "cluster_dist.csv"))
```

```{r fig_cluster_contact, fig.height=1.5, fig.width=14}
# plot out
ggplot(clusterContact, aes(clusters, freq.contact,
                        fill = interaction(Cohort, Response))) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    # width = 0.3, alpha = 0.6) +
  ylab("Contact with melano (%)") + xlab("") +
  scale_fill_brewer(name = NULL, palette = "Set3")
```