---
title: "Run modules"
output: html_document
date: '2022-08-16'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Examples to run functions and modules

```{r}
# set test variables
pID <- "Bi2995"
# pID <- "rMeKCv"
versionID <- 1
projectsDir <- "/Volumes/Analysis_SSD/Communal/cecelia/projects/"
# projectsDir <- "/Volumes/Analysis_SSD/Dominik/cecelia/projects/"
```

```{r}
anaDir <- "/Volumes/USER_data/Dominik/Experiments/PDAC_Aleynick2023/CECELIA"
```

```{r}
# Load cluster data
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia")

library(ggplot2)
library(tidyverse)
```

```{r}
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "oKjACa", versionID = versionID, initReactivity = FALSE
)

# cciaObj$setImLabelPropsFilepath("default.h5ad", valueName = "default")
# cciaObj$saveState()

cciaObj$runTask(
  funName = "gatePopulations.createGatingSet",
  funParams = list(
    compensateZ = FALSE,
    polyDegree = 0,
    applyReversedLog = FALSE,
    transformation = "logicle",
    transChannels = unlist(cciaObj$imChannelNames())
  ),
  runInplace = TRUE
)
```

```{r}
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "oKjACa", versionID = versionID, initReactivity = FALSE
)

valueName <- "default"
labelSuffixes <- c("nuc", "cyto")

# set combined labels
labelsPath <- paste0(valueName, cciaConf()$files$ext$labels)
attr(labelsPath, "suffixes") <- unlist(labelSuffixes)

cciaObj$setImLabelsFilepath(labelsPath, valueName = valueName)

# set suffixes for channel names
channelNames <- cciaObj$imChannelNames()
attr(channelNames, "types") <- unlist(labelSuffixes)

cciaObj$setImChannelNames(channelNames, valueName = valueName)

cciaObj$valueSuffixes("imLabelsFilepath", valueName = valueName)
cciaObj$saveState()
```

```{r fig_gating, fig.height=3, fig.width=5}
# Load cluster data
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "oKjACa", versionID = versionID, initReactivity = FALSE
)

paste(cciaObj$imChannelNames(), collapse = "', '")

# cciaObj$editPopColour(
#   popType = "flow", colour = "#ff1493",
#   popID = cciaObj$popIDFromPath(cciaObj$imPopMap("flow"), "/gBT+/CD69+"))

# get raster contours
p1s <- .flowPlotGatedRaster(
  cciaObj, popPath = "root", labelSize = 5, asContours = FALSE)
  # cciaObj, popPath = "/nonDebris/Others", labelSize = 3, asContours = TRUE, directLeaves = TRUE)

ggpubr::ggarrange(plotlist = p1s, nrow = 2, ncol = 2)

ggsave(file.path(anaDir, "gating.pdf"), width = 6.5, height = 6.5)
```

```{r}
# get spatial interactions and check CD8 and PDL1
# get populations and show maps
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "oKjACa", versionID = versionID, initReactivity = FALSE
)

pops <- cciaObj$popPaths(popType = "flow", includeFiltered = TRUE)

# exclude 'O' pops
pops <- pops[is.na(str_match(pops, "/O[0-9]*$"))]
# pops <- pops[pops != "/nonDebris"]

# get pops
popDT <- cciaObj$popDT(popType = "flow", pops = pops, includeFiltered = TRUE)

unique(popDT$pop)
```

```{r fig_pops, fig.height=5, fig.width=8}
# plot out
p1 <- ggplot(popDT %>% filter(
    pop %in% c("", "/nonDebris/CD8+/clustered")
  ), aes(centroid_x, centroid_y, color = as.factor(pop))) +
  theme_classic() +
  plotThemeDark(angle = 0) +
  # geom_point(size = 4) +
  geom_point(data = popDT[pop == "/nonDebris"], size = 1, color = "#5B5B5B") +
  geom_point(data = popDT[pop == "/nonDebris/CD8+/non.clustered"], size = 1, color = "#377EB8") +
  geom_point(data = popDT[pop == "/nonDebris/Others/CD68+"], size = 1, color = "#4DAF4A") +
  # geom_point(data = popDT[pop == "/nonDebris/Others/CD68+/PDL1+"], size = 1, color = "#E631BE") +
  geom_point(data = popDT[pop == "/nonDebris/CD8+/clustered"], size = 1, color = "yellow") +
  coord_fixed() +
  scale_color_brewer(palette = "Set3") +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.line = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    legend.position = "none"
  )

ggsave(file.path(anaDir, 'oKjACa_pops_whole.png'), plot = p1, height = 20, width = 20)
```


```{r}
# show with which cells CD8+ are in contact
# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "oKjACa", versionID = versionID, initReactivity = FALSE
)

# get regions
spatialDT <- cciaObj$spatialDT(valueName = "default")

# join pops
spatialDT[popDT[, c("label", "pop")],
          on = c("to" = "label"),
          pop.to := pop]
spatialDT[popDT[, c("label", "pop")],
          on = c("from" = "label"),
          pop.from := pop]

# filter same type associations
spatialDT <- spatialDT[pop.to != pop.from]
spatialDT <- spatialDT[
  !(pop.to == "/nonDebris/CD8+/non.clustered" & pop.from == "/nonDebris/CD8+/clustered")]
spatialDT <- spatialDT[
  !(pop.to == "/nonDebris/CD8+/clustered" & pop.from == "/nonDebris/CD8+/non.clustered")]

unique(spatialDT$pop.from)
```

```{r fig_p14, fig.height=1.5, fig.width=2}
summaryAssociation <- spatialDT %>%
  dplyr::filter(startsWith(pop.from, "/nonDebris/CD8+")) %>%
  group_by(pop.from, pop.to) %>%
  dplyr::summarise(n = n()) %>%
  mutate(freq = n/sum(n) * 100) %>%
  drop_na() %>%
  ungroup() %>%
  complete(pop.from, pop.to, fill = list(freq = 0)) %>%
  dplyr::filter(pop.to != "NONE")

ggplot(data = summaryAssociation,
       aes(
         y = freq,
         x = pop.to)) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  # geom_jitter(position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
  geom_jitter(width = 0.3, alpha = 1.0) +
  # geom_point(alpha = 1.0) +
  theme(
    legend.justification = "center",
    legend.direction = "horizontal",
    legend.position = "bottom",
    legend.title = element_blank(),
    axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1)
  ) +
  # geom_line(aes(group = interaction(uID, pop.to))) +
  xlab("") + ylab("Interaction (%)") +
  # facet_wrap(~pop.to, nrow = 1, scales = "free_y") +
  facet_wrap(~pop.from, nrow = 1) +
  expand_limits(y = 0)

# write.csv(summaryAssociation, file.path(anaDir, "spatial_interactions.csv"))
# write.csv(summaryAssociation, file.path(anaDir, "spatial_interactions_bin.csv"))
```


```{r fig_clusters_heat, fig.height=1, fig.width=2}
summaryClust <- summaryDT %>%
  dplyr::filter(
    pop.from %in% c("clustered", "non.clustered"),
    !pop.to %in% c("clustered", "non.clustered", "Other", "T")
      # "/nonDebris/XCR1", "/nonDebris/O/LCMV"),
    # pop.to %in% c("/nonDebris", "/nonDebris/XCR1", "/nonDebris/O/LCMV")
    # !pop.to %in% c("/nonDebris/O/O1/O2/B")
    ) %>%
  # group_by(uID, pop.from, pop.to) %>%
  group_by(uID, pop.to, pop.from) %>%
  # group_by(pop.from, pop.to) %>%
  dplyr::summarise(n = n()) %>%
  mutate(freq = n/sum(n) * 100) %>%
  drop_na() %>%
  ungroup() %>%
  # complete(uID, pop.from, pop.to, fill = list(freq = 0))
  complete(uID, pop.to, pop.from, fill = list(freq = 0))
  # complete(pop.from, pop.to, fill = list(freq = 0))
  # mutate(pop.group = interaction(uID, pop.to))

ggplot(data = summaryClust %>%
         mutate(
           # pop.to = factor(pop.to, levels = c("XCR1", "LCMV", "Other")),
           # pop.from = factor(pop.from, levels = c("non.clustered", "clustered"))
           ),
       aes(
         # color = as.factor(pop.from),
         y = freq,
         # x = as.factor(pop.to))) +
         # x = pop.from)) +
         x = pop.to)) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  # geom_jitter(position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
  # geom_jitter(width = 0.3, alpha = 1.0) +
  geom_point(alpha = 1.0) +
  theme(
    legend.justification = "center",
    legend.direction = "horizontal",
    legend.position = "bottom",
    legend.title = element_blank(),
    axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1)
  ) +
  # geom_line(aes(group = interaction(uID, pop.to))) +
  xlab("") + ylab("Interaction (%)") +
  # facet_wrap(~pop.to, nrow = 1, scales = "free_y") +
  facet_wrap(~pop.from, nrow = 1) +
  expand_limits(y = 0)

# ggsave(file.path(anaDir, "P14_interactions.pdf"), width = 3, height = 2)
```


