---
title: "Run modules"
output: html_document
date: '2022-08-16'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Examples to run functions and modules

```{r}
Sys.setenv(KMP_DUPLICATE_LIB_OK = "TRUE")
# set test variables
pID <- "az8y8l" # ZOE
# pID <- "Wq59Z0" # JY
versionID <- 1
projectsDir <- "/Volumes/Analysis_SSD/Communal/cecelia/projects/"
# projectsDir <- "/Volumes/USER_data/Dominik/CECELIA_BACKUP/"
```

```{r}
devtools::load_all("../")
cciaUse("~/cecelia/dev")

library(ggplot2)
library(tidyverse)
```

```{r}
anaDir <- "/Volumes/USER_data/Dominik/Experiments/ZOE/tumours"
# anaDir <- "/Volumes/USER_data/Dominik/Experiments/JY/tumours"
```

```{r}
# HMM
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "mmEf5V", versionID = versionID, initReactivity = FALSE, projectsDir = projectsDir
)

testDT <- cciaObj$popDT("clust", includeFiltered = TRUE, flushCache = TRUE)

testDT[label == "35265",]
```

```{r}
# HMM
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "mmEf5V", versionID = versionID, initReactivity = FALSE, projectsDir = projectsDir
)

# run task
funParams <- list(
  popsA = c("clust.MHCII+", "clust.F480+"),
  popsB = c("branch.CD31.branch/two"),
  maxContactDist = 10
)

# run task
task <- cciaObj$runTask(
  funName = "spatialAnalysis.cellContacts",
  funParams = funParams,
  env = "local",
  runInplace = TRUE,
  taskID = 1
)
```

```{r}
# HMM
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  # pID = pID, uID = "Ynvgzy", versionID = versionID, initReactivity = FALSE # Tcells
  # pID = pID, uID = "bQ4XcX", versionID = versionID, initReactivity = FALSE # wrong side
  pID = pID, uID = "mmqrqO", versionID = versionID, initReactivity = FALSE # edge in the middle
)

# uIDs <- names(cciaObj$cciaObjects())
# uIDs <- c("2Lb1kQ")

# run task
funParams <- list(
  popType = "flow",
  popsForEdge = c("/nondebris/included"),
  borderCutoff = 10
)

# run task
# task <- cciaObj$runTasks(
task <- cciaObj$runTask(
  funName = "spatialAnalysis.distLeadingEdge",
  funParams = funParams,
  env = "local",
  runInplace = TRUE,
  taskID = 1
  # uIDs = uIDs
)
```

```{r fig_tumour_border, fig.height=3, fig.width=12}
# show numbers of cells per area
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  # pID = pID, uID = "bQ4XcX", versionID = versionID, initReactivity = FALSE
  pID = pID, uID = "mmqrqO", versionID = versionID, initReactivity = FALSE
)

# can you extract the tumour border as a line?
popDT <- cciaObj$popDT("flow", pops = c("/nondebris/included"))

ggplot(popDT, aes(centroid_x, -centroid_y, color = flow.cell.dist.leading.edge)) +
  geom_point() +
  theme_classic() +
  coord_fixed() +
  viridis::scale_color_viridis()
```


```{r}
# get dimensions and pops
pixelRes <- x$omeXMLPixelRes()

popDT <- x$popDT("clust", pops = popPaths, includeFiltered = TRUE)

centroidCols <- str_match(names(popDT), "^centroid_(x|y|z)$")
centroidCols <- centroidCols[,1][!is.na(centroidCols[,1])]
centroidCols <- c("centroid_y", "centroid_x")

pixelRes <- unlist(pixelRes[str_extract(centroidCols, "(?<=_).*")])

# adjust for units
areaUnit <- "mm"
areaDim <- "area"

areaUnitAdjust <- 1
if (areaUnit == "mm")
  areaUnitAdjust <- 1000

# # get centroid limits
popsLimits <- list(
  min = popDT[, sapply(.SD, min), .SDcols = centroidCols] * pixelRes * (1/areaUnitAdjust),
  max = popDT[, sapply(.SD, max), .SDcols = centroidCols] * pixelRes * (1/areaUnitAdjust)
)
popsLimits$max - popsLimits$min

# get convex hull
# https://stackoverflow.com/a/41190160
# https://stackoverflow.com/a/59940985
ps1 <- popDT[, ..centroidCols] * pixelRes * (1/areaUnitAdjust)
ps1.surf <- geometry::convhulln(ps1, options = "FA")

ps1.surf$area
ps1.surf$vol

# get cells per area
popDT[, .(pop.n = .N, pop.area = (.N/ps1.surf$vol)),
      by = .(pop)] %>% left_join(exp.info)
```


```{r}
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "8lAe4q", versionID = versionID, initReactivity = FALSE
)

cciaObj$imChannelNames()
```

```{r}
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "CeViIH", versionID = versionID, initReactivity = FALSE
)

sapply(
  c("root", "FRC"),
  function(x) {
  y <- cciaObj$popAttr("clust", "colour", popPath = x, includeFiltered = TRUE, selectedOnly = TRUE)
  
  if (length(y) > 0)
    y[[1]]
  else
    "grey"
})
```


```{r}
# rename channels for label props
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "f6YZeo", versionID = versionID, initReactivity = FALSE
)

cciaObj$labelPropsCols()
```


```{r}
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  # pID = pID, uID = "f6YZeo", versionID = versionID, initReactivity = FALSE
  pID = pID, uID = "EgflKz", versionID = versionID, initReactivity = FALSE
)

cciaObj$runTask(
  funName = "gatePopulations.createGatingSet",
  funParams = list(
    compensateZ = FALSE,
    applyReversedLog = FALSE,
    transformation = "biexponential"
  ),
  runInplace = TRUE
)
```

```{r}
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "HV7E1F", versionID = versionID, initReactivity = FALSE
)

exp.info <- as.data.table(cciaObj$summary(withSelf = FALSE, fields = c("Attr")))
uIDs <- exp.info[include == "y" & stain == "YAP"]$uID

# get pops
frcYAP <- cciaObj$popDT(
  popType = "flow", uIDs = uIDs,
  includeFiltered = FALSE, pops = c("/nonDebris/FRC", "/nonDebris/FRC/YAP"))

frcBorder <- cciaObj$popDT(
  popType = "flow", uIDs = uIDs,
  includeFiltered = FALSE, pops = c("/nonDebris/FRC/border"))

frcKi67 <- cciaObj$popDT(
  popType = "flow", uIDs = uIDs,
  includeFiltered = FALSE, pops = c("/nonDebris/FRC", "/nonDebris/FRC/YAP"))

# join border FRC
frcBorder[, border := TRUE]
frcYAP[frcBorder[, c("uID", "label", "border")], on = c("uID", "label"), border := border]
frcYAP[is.na(border), border := FALSE]
```


```{r fig_tumour_border, fig.height=3, fig.width=12}
# plot percentage of YAP+ cells
datSummary <- frcYAP %>%
  # group_by(uID, pop, border) %>%
  group_by(uID, border, pop) %>%
  # group_by(uID, pop) %>%
  summarise(n = n()) %>%
  mutate(freq = n/sum(n) * 100) %>%
  dplyr::filter(pop == "/nonDebris/FRC/YAP") %>%
  left_join(exp.info)

oriFilepaths <- data.frame(
  sapply(cciaObj$cciaObjects(uIDs = uIDs), function(x) x$oriFilepath())) %>%
  rownames_to_column()
colnames(oriFilepaths) <- c("uID", "filepath")
datSummary <- datSummary %>% left_join(oriFilepaths)

ggplot(datSummary, aes(location, freq, color = location)) +
  theme_classic() +
  # geom_violin(outlier.alpha = 0) +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    # width = 0.3, alpha = 1) +
  # stat_summary(fun=mean, geom="point", size=3, shape=18, color="Magenta") +
  ylab("YAP+ (%)") + xlab("") + ylim(0, 100) +
  scale_fill_brewer(name = NULL, palette = "Set3") +
  theme(legend.position = "none") + facet_wrap(.~border)

ggsave(file.path(anaDir, "YAP_positive.png"), width = 2, height = 2)

write.csv(datSummary, file.path(anaDir, "YAP_positive.csv"))
```

```{r}
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "HV7E1F", versionID = versionID, initReactivity = FALSE
)

exp.info <- as.data.table(cciaObj$summary(withSelf = FALSE, fields = c("Attr")))
uIDs <- exp.info[include == "y" & stain == "Ki67"]$uID

# get pops
frcKi67 <- cciaObj$popDT(
  popType = "flow", uIDs = uIDs,
  includeFiltered = FALSE, pops = c("/nonDebris/include", "/nonDebris/include/"))
```



```{r fig_tumour_border, fig.height=3, fig.width=12}
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "HV7E1F", versionID = versionID, initReactivity = FALSE
)

exp.info <- as.data.table(cciaObj$summary(withSelf = FALSE, fields = c("Attr")))
uIDs <- exp.info[include == "y" & stain == "YAP"]$uID

# get pops
popDT <- cciaObj$popDT(
  popType = "flow", uIDs = uIDs,
  includeFiltered = FALSE, pops = c("/nonDebris/FRC", "/nonDebris/FRC/YAP", "/nonDebris/Tumour"))

# get spatial
spatialDT <- cciaObj$spatialDT(valueName = "default")

# join pops
spatialDT[popDT[, c("label", "pop")],
          on = c("to" = "label"),
          pop.to := pop]
spatialDT[popDT[, c("label", "pop")],
          on = c("from" = "label"),
          pop.from := pop]
```

```{r}
# get FRC in vicinity of tumour
vicinityDT <- spatialDT[pop.from == "/nonDebris/FRC" & pop.to == "/nonDebris/Tumour", c("uID", "from")]
vicinityDT[, vicinity := TRUE]

vicinityDT <- vicinityDT[popDT, on = c("uID", "from" = "label")]
vicinityDT[is.na(vicinity), vicinity := FALSE]
```

```{r fig_yap_border, fig.height=3, fig.width=6}
# what is the nuclear yap in border cells - raw and population
# datToPlot <- vicinityDT[pop %in% c("/nonDebris/FRC", "/nonDebris/FRC/YAP")] %>%
datToPlot <- popDT[pop %in% c("/nonDebris/FRC", "/nonDebris/FRC/YAP")] %>%
  left_join(exp.info)

# normalise to median
channels <- cciaObj$cciaObjects()[[1]]$imChannelNames(includeTypes = TRUE, correctChannelNames = TRUE)
for (i in unique(datToPlot$uID)) {
  for (j in channels) {
    datToPlot[uID == i, paste0("norm.", j) := datToPlot[uID == i][[j]]/median(datToPlot[uID == i][[j]])]
    # datToPlot[uID == i, paste0("norm.", j) := datToPlot[uID == i][[j]]/max(datToPlot[uID == i][[j]])]
  }
}

# ggplot(datToPlot, aes(location, norm.nuc_YAP.647, color = location)) +
ggplot(datToPlot, aes(location, nuc_YAP.647, color = location)) +
  theme_classic() +
  # geom_violin(outlier.alpha = 0) +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    # position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    width = 0.3, alpha = 1, size = 0.5) +
  # stat_summary(fun=mean, geom="point", size=3, shape=18, color="Magenta") +
  ylab("Nuclear Yap (Ratio)") + xlab("") +
  # coord_flip()
  # ylim(0, 1) +
  scale_fill_brewer(name = NULL, palette = "Set3") +
  theme(legend.position = "none") + facet_grid(.~uID)

ggsave(file.path(anaDir, "YAP_nucleus.png"), width = 10, height = 2)

# # plot percentage of YAP+ cells
# datSummary <- datToPlot %>%
#   group_by(uID, pop) %>%
#   summarise(n = n()) %>%
#   mutate(freq = n/sum(n) * 100) %>%
#   dplyr::filter(pop == "/nonDebris/FRC/YAP") %>%
#   left_join(exp.info)
# 
# ggplot(datSummary, aes(location, freq, color = location)) +
#   theme_classic() +
#   # geom_violin(outlier.alpha = 0) +
#   geom_boxplot(outlier.alpha = 0) +
#   geom_jitter(
#     # position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
#     width = 0.3, alpha = 1) +
#   # stat_summary(fun=mean, geom="point", size=3, shape=18, color="Magenta") +
#   ylab("YAP+ (%)") + xlab("") + ylim(0, 100) + 
#   scale_fill_brewer(name = NULL, palette = "Set3") +
#   theme(legend.position = "none")
# 
# ggsave(file.path(anaDir, "YAP_positive.png"), width = 2, height = 2)
```

```{r}

```



```{r fig_gating, fig.height=3, fig.width=12}
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "MX220R", versionID = versionID, initReactivity = FALSE
)

# get densities
popDT <- cciaObj$popDT(popType = "clust", uIDs = names(cciaObj$cciaObjects())[1:10],
                       includeFiltered = TRUE, pops = c("MHCII+", "F480+", "MHCII+F480+"))

popDT[, density := .flowColours(.SD$centroid_x, .SD$centroid_y),
      by = c("uID", "pop"), .SDcols = c("centroid_x", "centroid_y")]

popDT[, pop := factor(pop, levels = c("MHCII+", "F480+", "MHCII+F480+"))]

unique(popDT$uID)
```


```{r fig_density, fig.height=10, fig.width=6}
# plot density maps for individual populations
p1s <- list()

portraitMode <- FALSE

for (i in unique(popDT$uID)) {
  local({
    x <- popDT[uID == i]
    
    axisX <- "centroid_x"
    axisY <- "centroid_y"
    
    # can you orientate them in the same direction?
    if (portraitMode == TRUE) {
      if (max(x$centroid_x) > max(x$centroid_y)) {
        axisX <- "centroid_y"
        axisY <- "centroid_x"
      }
    } else {
       if (max(x$centroid_x) < max(x$centroid_y)) {
        axisX <- "centroid_y"
        axisY <- "centroid_x"
      }
    }
    
    # p1s[[i]] <<- ggplot(x, aes(get(axisX), -get(axisY))) +
    p1s[[i]] <<- ggplot(x, aes(get(axisX), get(axisY))) +
      theme_classic() +
      geom_point(colour = x$density) +
      facet_grid(uID~pop) +
      plotThemeDark(angle = 0) +
      coord_fixed() +
      theme(
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.line = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.position = "none"
      ) +
      scale_x_continuous(expand = c(0, 0)) +
      scale_y_continuous(expand = c(0, 0))
  })
}

ggpubr::ggarrange(plotlist = p1s, ncol = 1) +
  theme(plot.background = element_rect(fill = "#222222", color = NA))
```

```{r fig_gating, fig.height=3, fig.width=6}
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "HV7E1F", versionID = versionID, initReactivity = FALSE
)

exp.info <- as.data.table(cciaObj$summary(withSelf = FALSE, fields = c("Attr")))
uIDs <- c("MiM7Tl")

for (x in cciaObj$cciaObjects(uIDs = uIDs)) {
  # get raster contours
  p1s <- .flowPlotGatedRaster(
    x, popPath = "root", labelSize = 2, labelBorder = 0.4,
    xTitleSize = 12, yTitleSize = 12, labelAlpha = 0.8,
    xAxisSize = 0, yAxisSize = 0,
    asContours = TRUE, plotTitleSize = 0,
    # plot_width = 92, plot_height = 92,
    showPopName = TRUE, showGatePopColours = TRUE)
    # cciaObj, popPaths = "/nonDebris", labelSize = 3, asContours = TRUE, directLeaves = FALSE)
  
  p1 <- ggpubr::ggarrange(plotlist = p1s, nrow = 1)
  suppressWarnings(print(p1))
  
  ggsave(file.path(anaDir, paste0(x$getUID(), "_gating.png")),
         width = 5.4, height = 1.8, plot = p1, bg = "white")
}
```

```{r}
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "HV7E1F", versionID = versionID, initReactivity = FALSE
)

exp.info <- as.data.table(cciaObj$summary(withSelf = FALSE, fields = c("Attr")))

popDT <- cciaObj$popDT(popType = "flow", pops = c("/nonDebris"))

# calc ratio
# popDT$ratio <- popDT$nuc_YAP.647/popDT$cyto_YAP.647
# popDT$ratio <- popDT$nuc_YAP.647/popDT$cyto_FRC.TdTomato
popDT$ratio <- popDT$nuc_YAP.647/popDT$nuc_FRC.TdTomato
```

```{r fig_ratio, fig.height=4, fig.width=25}
# can you plot per image and show the numbers?
# popDT$ratio <- popDT$nuc_YAP.647/popDT$nuc_FRC.TdTomato
# popDT$ratio <- popDT$nuc_YAP.647/popDT$cyto_FRC.TdTomato
# popDT$ratio <- popDT$nuc_YAP.647/popDT$cyto_YAP.647
popDT$ratio <- popDT$nuc_FRC.TdTomato/popDT$cyto_YAP.647

x <- popDT %>% dplyr::filter(uID == "79ncGd")

for (i in cciaObj$cciaObjects()[[1]]$imChannelNames(includeTypes = TRUE, correctChannelNames = TRUE)) {
  x[[paste0("norm.", i)]] <- x[[i]]/median(x[[i]])
}

x$ratio <- log(x$norm.nuc_YAP.647/x$norm.YAP.647)

popToPlot <- x %>%
  left_join(exp.info) %>%
  filter(!is.infinite(ratio))

ggplot(popToPlot %>% dplyr::filter(uID == "79ncGd"), aes(as.factor(1), ratio)) +
# ggplot(popToPlot, aes(location, ratio)) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    position = position_jitter(seed = 1),
    # position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    alpha = 1, color = "lightgrey") +
    # alpha = 1, color = "black")
  facet_grid(.~location+uID) +
  geom_text(aes(label = label),
            position = position_jitter(seed = 1), check_overlap = FALSE)
  ggrepel::geom_text_repel(
    data = popToPlot, aes(y = ratio, label = label),
    max.overlaps = 30)

# ggsave(file.path(anaDir, "ratio_nuc_cyto_YAP.png"), height = 2, width = 2)
# ggsave(file.path(anaDir, "ratio_nuc_cyto_YAP_indv.png"), height = 4, width = 20)

# write.csv(popToPlot, file.path(anaDir, "ratio_nuc_cyto_YAP.csv"))
```

```{r}
# show segmented numbers on image
Sys.setenv(KMP_DUPLICATE_LIB_OK = "TRUE")
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = TRUE, initJupyter = TRUE)
# cciaUse("~/cecelia/dev", initConda = FALSE, initJupyter = TRUE)

# start ipython kernel
viewer <- NapariUtils$new()

viewer$initNapari()
```

```{r}
generateScreenshots <- function(
    anaDir, cciaObj, uIDs, channelsToShow, popsToShow, fileAttrs,
    matchChannels = FALSE, ...) {
  # go through images and save movies
  for (x in cciaObj$cciaObjects(uIDs = uIDs)) {
    i <- x$getUID()
    viewer$setTaskDir(x$persistentObjectDirectory())
    
    # get channels
    imChannelNames <- x$imChannelNames()
    
    # match channels
    curChannelsToShow <- channelsToShow
    if (matchChannels == TRUE) {
      # TODO this is very crude    
      names(curChannelsToShow) <- sapply(names(channelsToShow), function(y) {
        imChannelNames[!is.na(stringr::str_extract(imChannelNames, y))][[1]]
      })
    }

    # get cmaps
    layersVisible <- imChannelNames %in% names(curChannelsToShow)
    channelColormaps <- rep("gray", length(layersVisible))
    
    for (j in names(curChannelsToShow))
      channelColormaps[[which(imChannelNames == j)]] <- curChannelsToShow[[j]]
    
    # open image
    viewer$openImage(
      x$imFilepath(),
      imChannelNames = imChannelNames,
      show3D = TRUE,
      layersVisible = layersVisible,
      channelColormaps = channelColormaps
    )
    
    # add tracks
    viewer$showLabelsAll(
      popsToShow,
      # showLabels = TRUE,
      # labelSuffixes = list(default = list("nuc", "cyto")),
      showPoints = TRUE,
      showLabelIds = TRUE
    )
    
    # adjust channel intensities
    browser()
  
    # save screenshot
    viewer$saveScreenshot(
      file.path(anaDir, paste0(
        paste(sapply(fileAttrs, function(i) x$getCciaAttr(i)), collapse = "_"), "_", i, ".png")),
      ...)
  }
}
```

```{r}
# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "HV7E1F", versionID = versionID, initReactivity = FALSE
)

exp.info <- as.data.table(cciaObj$summary(withSelf = FALSE, fields = c("Attr")))
uIDs <- exp.info$uID

channelsToShow <- list(
  "YAP-647" = "magenta",
  "FRC-TdTomato" = "green"
  )
popsToShow <- list("default")
fileAttrs <- c("location", "mouse")

generateScreenshots(
  file.path(anaDir, "shots"), cciaObj, uIDs, channelsToShow,
  popsToShow, fileAttrs, size = list(1200, 1200))
```
