---
title: "Run modules"
output: html_document
date: '2022-08-16'
---

```{r setup, include=FALSE}
renv::load("~/R-workspace/cecelia/")
knitr::opts_chunk$set(echo = TRUE)
```

## Examples to run functions and modules

```{r}
Sys.setenv(KMP_DUPLICATE_LIB_OK = "TRUE")
# set test variables
# pID <- "Bi2995"
# pID <- "rMeKCv"
pID <- "Kr5So2"
versionID <- 1
# projectsDir <- "/Volumes/Analysis_SSD/Communal/cecelia/projects/"
projectsDir <- "/Volumes/USER_data/Dominik/CECELIA_BACKUP/"
```

```{r}
anaDir <- "/Volumes/USER_data/Dominik/Experiments/DS_N051/ANALYSIS/IMAGE/CECELIA"
```

```{r}
library(flowWorkspace)

# Load cluster data
devtools::load_all("../")
cciaUse("~/cecelia/dev")

library(ggplot2)
library(tidyverse)
```

```{r}
# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "fJOCk6", versionID = versionID, initReactivity = FALSE
)

cciaObj$runTask(
  funName = "gatePopulations.createGatingSet",
  funParams = list(
    compensateZ = FALSE,
    applyReversedLog = FALSE,
    transformation = "biexponential",
    valueName = "XCR1"
  ),
  runInplace = TRUE
)
```


```{r}
# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "fJOCk6", versionID = versionID, initReactivity = FALSE
)

a <- cciaObj$popDT("labels", pops = "XCR1.branch")
```


```{r}
# Load cluster data
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "NjumBK", versionID = versionID, initReactivity = FALSE
)

cciaObj$oriFilepath()

# # reset values
# cciaObj$setImLabelsFilepath(
#   spaceholder, valueName = valueName, setDefault = FALSE)
# 
# cciaObj$setImLabelPropsFilepath(
#   "SPACEHOLDER", valueName = valueName, setDefault = FALSE)
# 
# # save object
# cciaObj$saveState()
```

```{r fig_gating, fig.height=3, fig.width=5}
# Load cluster data
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  # pID = pID, uID = "NjumBK", versionID = versionID, initReactivity = FALSE
  pID = pID, uID = "TK5dex", versionID = versionID, initReactivity = FALSE
)

a <- cciaObj$imPopMap("flow", includeFiltered = TRUE)
# cciaObj$setImPopMap("flow", a)
# cciaObj$setImGatingSetFilepath("default.gs")
# cciaObj$saveState()

names(a)
```

```{r}
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "fJOCk6", versionID = versionID, initReactivity = FALSE
)

# cciaObj$setImLabelPropsFilepath("default.h5ad", valueName = "default")
# cciaObj$saveState()

task <- cciaObj$runTask(
  funName = "gatePopulations.createGatingSet",
  funParams = list(
    compensateZ = FALSE,
    polyDegree = 0,
    applyReversedLog = FALSE,
    transformation = "biexponential",
    transChannels = unlist(cciaObj$imChannelNames())
  ),
  runInplace = FALSE
)

task$result()
```

```{r}
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "oKjACa", versionID = versionID, initReactivity = FALSE
)

valueName <- "default"
labelSuffixes <- c("nuc", "cyto")

# set combined labels
labelsPath <- paste0(valueName, cciaConf()$files$ext$labels)
attr(labelsPath, "suffixes") <- unlist(labelSuffixes)

cciaObj$setImLabelsFilepath(labelsPath, valueName = valueName)

# set suffixes for channel names
channelNames <- cciaObj$imChannelNames()
attr(channelNames, "types") <- unlist(labelSuffixes)

cciaObj$setImChannelNames(channelNames, valueName = valueName)

cciaObj$valueSuffixes("imLabelsFilepath", valueName = valueName)
cciaObj$saveState()
```

--- XCR1-venus

```{r fig_gating, fig.height=6, fig.width=6}
# Load cluster data
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "NjumBK", versionID = versionID, initReactivity = FALSE
  # pID = pID, uID = "TK5dex", versionID = versionID, initReactivity = FALSE
)

paste(cciaObj$imChannelNames(), collapse = "', '")

cciaObj$editPopColour(
  popType = "flow", colour = "magenta",
  popID = cciaObj$popIDFromPath(cciaObj$imPopMap("flow"), "/nonDebris/O/LCMV"))
# cciaObj$editPopColour(
#   popType = "flow", colour = "#ff1493",
#   popID = cciaObj$popIDFromPath(cciaObj$imPopMap("flow"), "/gBT+/CD69+"))

# get raster contours
p1s <- .flowPlotGatedRaster(
  cciaObj, popPaths = "root", labelSize = 6, labelBorder = 1.1,
  xTitleSize = 16, yTitleSize = 16,
  asContours = TRUE, plotTitleSize = 20)
  # cciaObj, popPaths = "/nonDebris", labelSize = 3, asContours = TRUE, directLeaves = FALSE)

ggpubr::ggarrange(plotlist = p1s, nrow = 2, ncol = 2)

ggsave(file.path(anaDir, "NjumBK_gating.pdf"), width = 7, height = 7)
# ggsave(file.path(anaDir, "TK5dex_gating.png"), width = 8, height = 8)
```

```{r}
# make regions
# get distances from lymphs to melano
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "TK5dex", versionID = versionID, initReactivity = FALSE 
)

# run task
funParams <- list(
  valueName = "default",
  popType = c("flow"),
  pops = c(
    '/nonDebris', '/nonDebris/XCR1', '/nonDebris/P14', '/nonDebris/O/LCMV',
    '/nonDebris/O/CD11b','/nonDebris/O/O1/CD11c', '/nonDebris/O/O1/CD3',
    '/nonDebris/O/O1/O2/B'),
  neighbourMethod = "delaunay",
  neighbourRadius = 30,
  nRings = 1,
  savePops = TRUE
)

task <- cciaObj$runTask(
  funName = "spatialAnalysis.cellNeighbours",
  funParams = funParams,
  env = "local",
  runInplace = TRUE,
  taskID = 1
)
```

```{r}
# can you generate maps to show XCR1, P14 and LCMV? Then,
# a) Show whether P14 are more associated with XCR1 and P14
# b) Show whether P14 are in T cell, B cell or other area

# ie, showing direct interactions of cells and where these cells are in general
# First generate maps with the actual populations to show distribution 
# for all LCMV images; Also show actual image of P14 in XCR1 area or LCMV associated
# To say that P14 also cluster around LCMV in presence of XCR1
```

```{r}
# get populations and show maps
devtools::load_all("../")
cciaUse("~/cecelia/dev", projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "6QzZsl", versionID = versionID, initReactivity = FALSE
)

# cciaObj$popDT(popType = "labels")

for (x in cciaObj$cciaObjects())
  print(x$imFilepath())
```
```{r}
# get populations and show maps
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "6QzZsl", versionID = versionID, initReactivity = FALSE
)

exp.info <- as.data.table(cciaObj$summary(withSelf = FALSE, fields = c("Attr")))
uIDs <- exp.info[Treatment == "LCMV"]$uID

# show experiments with folder info
for (x in cciaObj$cciaObjects(uIDs = uIDs)) {
  print(paste(x$getUID(), x$oriFilepath()))
}
```


```{r fig_gating, fig.height=3, fig.width=5}
# get populations and show maps
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "6QzZsl", versionID = versionID, initReactivity = FALSE
)

exp.info <- as.data.table(cciaObj$summary(withSelf = FALSE, fields = c("Attr")))

# only get first LCMV samples
# uIDs <- exp.info$uID[1:3]
# uIDs <- exp.info$uID[!exp.info$uID %in% c()]
# uIDs <- exp.info$uID
uIDs <- c("NjumBK")

# pops <- cciaObj$popPaths(popType = "flow", uIDs = uIDs, includeFiltered = FALSE)
pops <- cciaObj$popPaths(popType = "flow", uIDs = uIDs[1], includeFiltered = TRUE)

# exclude 'O' pops
pops <- pops[is.na(str_match(pops, "/O[0-9]*$"))]
# pops <- pops[pops != "/nonDebris"]

# get pops
# popDT <- cciaObj$popDT(popType = "flow", uIDs = uIDs, pops = pops, includeFiltered = FALSE)
popDT <- cciaObj$popDT(popType = "flow", uIDs = uIDs, pops = pops,
                       includeFiltered = TRUE, convertToPhysical = TRUE)

unique(popDT$pop)
```

```{r}
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  # pID = pID, uID = "6QzZsl", versionID = versionID, initReactivity = FALSE
  pID = pID, uID = "NjumBK", versionID = versionID, initReactivity = FALSE
)

pops <- cciaObj$popPaths(popType = "flow", includeFiltered = FALSE)
```

```{r}
# SPIAT test
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "6QzZsl", versionID = versionID, initReactivity = FALSE
  # pID = pID, uID = "NjumBK", versionID = versionID, initReactivity = FALSE
  # pID = pID, uID = "TK5dex", versionID = versionID, initReactivity = FALSE
)

uIDs <- names(cciaObj$cciaObjects())

# get pops
pops <- cciaObj$popPaths(popType = "flow", includeFiltered = FALSE, uIDs = uIDs[1])

# # exclude 'O' pops
pops <- pops[is.na(str_match(pops, "/O[0-9]*$"))]
pops <- pops[is.na(str_match(pops, "/nonDebris$"))]
names(pops) <- pops

# spe <- cciaObj$spe(popType = "flow", pops = pops, uIDs = names(cciaObj$cciaObjects())[2])
spe <- cciaObj$spe(popType = "flow", pops = pops, uIDs = uIDs)
```


```{r fig_spe_map, fig.height=4, fig.width=7}
x <- cciaObj$cciaObjects(uIDs = c("NjumBK"))[[1]]
imPopMap <- x$imPopMap(popType = "flow", includeFiltered = TRUE)
popColours <- sapply(imPopMap, function(x) {x$colour})
names(popColours) <- sapply(imPopMap, function(x) {x$path})

phenotypes <- unique(spe[[1]]$Phenotype)
popColours <- popColours[names(popColours) %in% phenotypes]

# plot populations
SPIAT::plot_cell_categories(spe$NjumBK, pops, popColours, "Phenotype") +
  facet_wrap(.~Phenotype)

ggsave(file.path(anaDir, "SPIAT", paste0(x$getUID(), "_map.png")),
       height = 6, width = 10)
```

```{r}
gradient_pos <- seq(20, 300, 20) # radii

spiat.entropies <- lapply(spe[names(spe) == "NjumBK"], function(x) {
  as.data.table(SPIAT::entropy_gradient_aggregated(
    x, cell_types_of_interest = pops,
    feature_colname = "Phenotype", radii = gradient_pos)$gradient_df)
})

entropiesDT <- rbindlist(spiat.entropies, idcol = "uID")
```

```{r fig_spe_entity, fig.height=3, fig.width=12}
datToPlot <- entropiesDT %>%
  pivot_longer(
    cols = starts_with("Pos_"),
    names_to = "radius",
    names_pattern = ".*_(.*)",
    values_to = "value") %>%
  mutate(radius = as.numeric(radius))

ggplot(datToPlot, aes(radius, value, color = Celltype2, fill = Celltype2, group = Celltype2)) +
  theme_classic() +
  geom_line(size = 1.5) +
  # geom_smooth() +
  facet_grid(uID~Celltype1) +
  scale_color_brewer(palette = "Set1") +
  scale_fill_brewer(palette = "Set1")

ggsave(file.path(anaDir, "SPIAT", "entropy.png"), height = 2.5, width = 12)
```

```{r fig_spe_colocalisation, fig.height=3, fig.width=4}
# Normalized mixing score (NMS)
target_pops <- pops[pops != "/nonDebris/P14"]
spiat.nms <- lapply(target_pops, function(x) {
  nsm <- lapply(spe, function(y) {
    as.data.table(SPIAT::mixing_score_summary(
      spe_object = y, 
      reference_celltype = "/nonDebris/P14",
      target_celltype = x,
      feature_colname = "Phenotype"))
  })
  
  rbindlist(nsm, idcol = "uID")
})
names(spiat.nms) <- target_pops
spiat.nmsDT <- rbindlist(spiat.nms, idcol = "target")

# ggplot(spiat.nmsDT, aes(target, Mixing_score)) +
#   theme_classic() +
#   geom_boxplot(outlier.alpha = 0) +
#   geom_jitter(
#     # position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
#     width = 0.2, alpha = 1.0) +
#   coord_flip()

ggplot(spiat.nmsDT, aes(target, Normalised_mixing_score)) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    # position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    width = 0.2, alpha = 1.0) +
  coord_flip()

ggsave(file.path(anaDir, "SPIAT", "nms.png"), height = 2.5, width = 4)
```

```{r fig_spe_colocalisation, fig.height=3, fig.width=3}
# Cross-K AUC
spiat.auc <- lapply(target_pops, function(x) {
  auc <- lapply(spe, function(y) {
    SPIAT::AUC_of_cross_function(SPIAT::calculate_cross_functions(
      spe_object = y, 
      method = "Kcross", cell_types_of_interest = c("/nonDebris/P14", x),
      dist = 100,
      feature_colname = "Phenotype"))
  })
  
  DT <- as.data.table(as.data.frame(unlist(auc)) %>% rownames_to_column())
  colnames(DT) <- c("uID", "value")
  DT
})
names(spiat.auc) <- target_pops
spiat.aucDT <- rbindlist(spiat.auc, idcol = "target")

ggplot(spiat.aucDT, aes(target, value)) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    # position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    width = 0.2, alpha = 1.0) +
  coord_flip()

ggsave(file.path(anaDir, "SPIAT", "auc.png"), height = 2.5, width = 4)
```

```{r}
# test to show regions of clustered T cells
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "6QzZsl", versionID = versionID, initReactivity = FALSE
)

exp.info <- as.data.table(cciaObj$summary(withSelf = FALSE, fields = c("Attr")))

# only get first LCMV samples
uIDs <- exp.info$uID

# get pops
# pops <- cciaObj$popPaths(popType = "flow", includeFiltered = FALSE, uIDs = uIDs[1])
pops <- cciaObj$popPaths(popType = "flow", includeFiltered = TRUE, uIDs = uIDs[3])

# # exclude 'O' pops
pops <- pops[is.na(str_match(pops, "/O[0-9]*$"))]
pops <- pops[is.na(str_match(pops, "/nonDebris$"))]
windowPops <- c("root")

popDT <- cciaObj$popDT(
  # popType = "flow", uIDs = uIDs, pops = pops, includeFiltered = FALSE)
  popType = "flow", uIDs = uIDs, pops = pops, includeFiltered = TRUE)

# get ppp for all populations
# popPPP <- lapply(pops, function(x) {
#   cciaObj$ppp(
#     popType = "flow", pops = x, uIDs = uIDs, usePhysicalScale = FALSE, windowPops = windowPops)
# })
# names(popPPP) <- pops
```

```{r}
png(filename = file.path(anaDir, "spatstat", "NjumBK_maps.png"), height = 300, width = 1200)

# plot populations out
layout(matrix(1:5, ncol = 5))
plot(popPPP$`/nonDebris/O/B220`$NjumBK, main = "B220")
plot(popPPP$`/nonDebris/O/O1/CD3`$NjumBK, main = "CD3")
plot(popPPP$`/nonDebris/O/LCMV`$NjumBK, main = "LCMV")
plot(popPPP$`/nonDebris/XCR1`$NjumBK, main = "XCR1")
plot(popPPP$`/nonDebris/P14`$NjumBK, main = "P14")

dev.off()
```

```{r}
# test for spatial randomness
ce.results <- list()
for (i in names(popPPP)) {
  message(paste(">> Test CSR for", i))
  # test for randomness
  ce.results[[i]] <- unlist(parallel::mclapply(popPPP[[i]], function(x) {
    spatstat.explore::clarkevans.test(x, method = "MonteCarlo", nsim = 99)$statistic
  }))
}
```

```{r fig_ce.results, fig.height=4, fig.width=4}
cdDF <- as.data.frame(ce.results)
colnames(cdDF) <- stringr::str_extract(colnames(cdDF), "(?<=\\.)[^\\.]*$")
rownames(cdDF) <- stringr::str_extract(rownames(cdDF), ".+(?=\\.R)")

ggplot(cdDF %>% pivot_longer(cols = everything(), names_to = "pop", values_to = "ce"),
       aes(pop, ce)) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(width = 0.2, alpha = 1.0) +
  expand_limits(y = 0) + geom_hline(yintercept = 1)

ggsave(file.path(anaDir, "spatstat", "ce_results.png"), height = 3, width = 3)
```


```{r fig_regions, fig.height=10, fig.width=8}
# plot regions
x <- sapply(popPPP$y0IE8s, function(x) x$window$bdry[[1]]$x)
y <- sapply(popPPP$y0IE8s, function(x) x$window$bdry[[1]]$y)

spatDF <- data.frame(x = unname(unlist(x)), y = unname(unlist(y)))
spatDF$id <- unname(unlist(mapply(function(x, i) rep(i, x), lengths(x), names(popPPP$y0IE8s))))

sum(sapply(popPPP$y0IE8s[names(popPPP$y0IE8s) != 0], function(x) spatstat.geom::area(x)))

ggplot(spatDF, aes(x, -y, colour = id)) + 
  theme_classic() +
  # scale_color_brewer(name = NULL, palette = "Dark2") +
  geom_path() +
  coord_fixed() +
  plotThemeDark() +
  theme(
    axis.text = element_text(size = 15),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.line = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    legend.justification = "center",
    legend.position = "bottom"
  )
```


```{r fig_maps, fig.height=3, fig.width=6}
# show XCR1, LCMV and P14?
# nonDT <- popDT %>% dplyr::filter(uID == "XBAokO")
# there are three dots
# nonDT <- popDT %>% dplyr::filter(uID == "XBAokO", pop != "/nonDebris/O/LCMV")
infDT <- popDT %>% dplyr::filter(uID == "NjumBK")

# ggplot(nonDT,
#        aes(centroid_x, -centroid_y), size = 0.3) +
#   # geom_point(data = nonDT %>% dplyr::filter(pop == "/nonDebris/O/B"), color = "magenta", alpha = 0.05) +
#   geom_point(data = nonDT %>% dplyr::filter(pop == "/nonDebris/O/B220"), color = "orange", alpha = 0.05) +
#   # geom_point(data = nonDT %>% dplyr::filter(pop == "/nonDebris/XCR1"), color = "#2A52BE", alpha = 0.2) +
#   geom_point(data = nonDT %>% dplyr::filter(pop == "/nonDebris/XCR1"), color = "#66A266", alpha = 0.2) +
#   geom_point(data = nonDT %>% dplyr::filter(pop == "/nonDebris/O/LCMV"), color = "red") +
#   geom_point(data = nonDT %>% dplyr::filter(pop == "/nonDebris/P14/non.clustered"), color = "white") +
#   geom_point(data = nonDT %>% dplyr::filter(pop == "/nonDebris/P14/clustered"), color = "#4169e1") +
#   theme_classic() +
#   scale_color_brewer(name = NULL, palette = "Dark2") +
#   coord_fixed() +
#   plotThemeDark() +
#   theme(
#     axis.text = element_text(size = 15),
#     axis.text.x = element_blank(),
#     axis.ticks.x = element_blank(),
#     axis.text.y = element_blank(),
#     axis.ticks.y = element_blank(),
#     axis.line = element_blank(),
#     axis.title.x = element_blank(),
#     axis.title.y = element_blank(),
#     legend.justification = "center",
#     legend.position = "bottom"
#   )
# 
# ggsave(file.path(anaDir, "non_pops.png"), width = 6, height = 6)

p1 <- ggplot(infDT,
       aes(centroid_x, -centroid_y), size = 0.3) +
  # geom_point(data = infDT %>% dplyr::filter(pop == "/nonDebris/O/B220"), color = "orange", alpha = 0.01) +
  # geom_point(data = infDT %>% dplyr::filter(pop == "/nonDebris/XCR1"), color = "#66A266", alpha = 0.2) +
  geom_point(data = infDT %>% dplyr::filter(pop == "/nonDebris/O/B220"), color = "#ED7307") +
  geom_point(data = infDT %>% dplyr::filter(pop == "/nonDebris/XCR1"), color = "#0BB40B") +
  geom_point(data = infDT %>% dplyr::filter(pop == "/nonDebris/O/LCMV"), color = "#CB1699") +
  geom_point(data = infDT %>% dplyr::filter(pop == "/nonDebris/P14/non.clustered"), color = "white") +
  geom_point(data = infDT %>% dplyr::filter(pop == "/nonDebris/P14/clustered"), color = "#4169e1") +
  # geom_line(data = data.frame(centroid_x = c(10, 710),  centroid_y = c(10, 10)), color = "white", size = 1) +
  theme_classic() +
  scale_color_brewer(name = NULL, palette = "Dark2") +
  coord_fixed() +
  plotThemeDark(bgColor = "black") +
  theme(
    axis.text = element_text(size = 15),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.line = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    legend.justification = "center",
    legend.position = "bottom"
  )

# ggsave(file.path(anaDir, "NjumBK_pops.png"), width = 6, height = 6)
# ggsave(file.path(anaDir, "NjumBK_pops_wo.png"), width = 6, height = 6)
ggsave(file.path(anaDir, "NjumBK_pops_small.png"), width = 12, height = 12, plot = p1)
```

```{r fig_maps, fig.height=3, fig.width=6}
# show XCR1, LCMV and P14?
# nonDT <- popDT %>% dplyr::filter(uID == "XBAokO")
# there are three dots
ggplot(popDT.spatial %>%
         dplyr::filter(uID == "NjumBK", startsWith(pop, "/nonDebris/P14")),
       aes(centroid_x, centroid_y), size = 0.3) +
  geom_point(aes(color = pop.to)) +
  theme_classic() +
  scale_color_brewer(name = NULL, palette = "Dark2") +
  coord_fixed() +
  plotThemeDark() +
  theme(
    axis.text = element_text(size = 15),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.line = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    legend.justification = "center",
    legend.position = "bottom"
  ) +
  facet_wrap(.~uID, nrow = 1)

ggsave(file.path(anaDir, "contact_pops.png"), width = 6, height = 6)
```

```{r fig_clusters, fig.height = 1.5, fig.width = 1.5}
# clusters
dataToPlot <- popDT %>%
  dplyr::filter(startsWith(pop, "/nonDebris/P14")) %>%
  group_by(uID, pop) %>%
  summarise(n = n()) %>%
  mutate(freq = (n / sum(n) * 100)) %>%
  dplyr::filter(pop == "/nonDebris/P14/clustered") %>%
  left_join(exp.info)

ggplot(dataToPlot, aes(Treatment, freq)) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    # position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    width = 0.2, alpha = 1.0) +
  ylim(0, 100)
```

```{r}
# show with which cells P14 are in contact
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "6QzZsl", versionID = versionID, initReactivity = FALSE
)

# get regions
spatialDT <- cciaObj$spatialDT(valueName = "default", uIDs = uIDs)
# regionsDT <- cciaObj$popDT(popType = "region", uIDs = uIDs, includeFiltered = TRUE)

# join pops
# regionsDT[popDT[, c("uID", "label", "pop")],
#           on = c("uID", "label"),
#           from.pop := i.pop]
spatialDT[popDT[, c("uID", "label", "pop")],
          on = c("uID", "to" = "label"),
          pop.to := pop]
spatialDT[popDT[, c("uID", "label", "pop")],
          on = c("uID", "from" = "label"),
          pop.from := pop]

# can you add on cells that are not in contact with anything?
table(spatialDT[
  popDT[!popDT$label %in% spatialDT$from, c("uID", "label", "pop")],
  on = c("uID", "from" = "label")
]$pop)

unique(spatialDT$pop.from)
```

```{r}
# can you bootstrap interactions?
spatialDT <- spatialDT[!is.na(pop.to)]

# summaryAssociation <- spatialDT %>%
summaryAssociation <- spatialDT %>%
  # dplyr::filter(startsWith(pop.from, "/nonDebris/P14")) %>%
  group_by(uID, pop.from, pop.to) %>%
  dplyr::summarise(n = n()) %>%
  mutate(freq = n/sum(n) * 100) %>%
  drop_na() %>%
  ungroup() %>%
  complete(uID, pop.from, pop.to, fill = list(freq = 0))

# bootstrap
# numIterations <- 1000
numIterations <- 10
associationSummaries <- list()

for (i in seq(numIterations)) {
  if (i %% 10 == 0)
    print(paste(">>", i))
  
  suppressMessages({
    curSummary <- copy(spatialDT)
    
    curPopDT <- copy(popDT[, c("uID", "label", "pop")])
    curPopDT[, pop := sample(pop, replace = FALSE)]
    
    # randomise pop
    curSummary[curPopDT[, c("uID", "label", "pop")],
               on = c("uID", "to" = "label"),
               pop.to := pop]
    curSummary[popDT[, c("uID", "label", "pop")],
               on = c("uID", "from" = "label"),
               pop.from := pop]
    
    # summarise
    associationSummaries[[i]] <- as.data.table(curSummary %>%
      group_by(uID, pop.from, pop.to) %>%
      dplyr::summarise(n = n()) %>%
      mutate(freq = n/sum(n) * 100) %>%
      drop_na() %>%
      ungroup() %>%
      complete(uID, pop.from, pop.to, fill = list(freq = 0)))
  })
}

# bind together
associationSummaries <- rbindlist(associationSummaries, idcol = "it")
```

```{r}
# take mean and sd for iterations
associationSummaries <- as.data.table(associationSummaries %>%
  pivot_wider(names_from = "it", values_from = "freq") %>%
  replace(is.na(.), 0) %>%
  pivot_longer(cols = -c(uID, pop.from, pop.to, n), names_to = "it", values_to = "freq") %>%
  group_by(uID, pop.from, pop.to) %>%
  summarise(
    mean = mean(freq),
    sd = sd(freq)
  ) %>%
  left_join(summaryAssociation) %>%
  mutate(z.score = (freq - mean) / sd) %>%
  drop_na())

associationSummaries[is.infinite(z.score), z.score := 0]
```

```{r fig_p14, fig.height=4, fig.width=4}
ggplot(associationSummaries %>% left_join(exp.info), aes(Treatment, z.score)) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  # geom_jitter(position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
  geom_jitter(width = 0.3, alpha = 1.0) +
  xlab("") + ylab("Interaction (z score)") +
  facet_grid(pop.to~pop.from) +
  expand_limits(y = 0)
```

```{r}
popDT.spatial <- copy(popDT)

# then join closest contact if present
popDT.spatial[
  spatialDT[
    pop.from %in% c("/nonDebris/P14/clustered", "/nonDebris/P14/non.clustered") &
    !pop.to %in% c("/nonDebris/P14/clustered", "/nonDebris/P14/non.clustered"),
    # [!] this will only select the cells in closest proximity
    .SD[which.min(dist)], by = c("uID", "from")][, c("from", "pop.to")],
  on = c("label" = "from"), pop.to := pop.to
]

popDT.spatial[is.na(pop.to), pop.to := "NONE"]
```

```{r fig_p14, fig.height=4, fig.width=4}
# summaryAssociation <- summaryAssociation %>%
summaryAssociation <- copy(popDT.spatial)
# summaryAssociation[startsWith(pop, "/nonDebris/P14"), pop := "/nonDebris/P14"]

summaryAssociation <- summaryAssociation %>%
  dplyr::filter(startsWith(pop, "/nonDebris/P14")) %>%
  group_by(uID, pop, pop.to) %>%
  dplyr::summarise(n = n()) %>%
  mutate(freq = n/sum(n) * 100) %>%
  drop_na() %>%
  ungroup() %>%
  complete(uID, pop, pop.to, fill = list(freq = 0)) %>%
  left_join(exp.info)

ggplot(data = summaryAssociation %>%
         mutate(
           # pop.to = factor(pop.to, levels = c("XCR1", "LCMV", "Other")),
           # pop.from = factor(pop.from, levels = c("non.clustered", "clustered"))
           ),
       aes(
         # color = as.factor(pop.from),
         y = freq,
         # x = as.factor(pop.to))) +
         # x = pop.from)) +
         x = pop.to,
         color = Treatment)) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
  # geom_jitter(width = 0.3, alpha = 1.0) +
  # geom_point(alpha = 1.0) +
  theme(
    legend.justification = "center",
    legend.direction = "horizontal",
    legend.position = "bottom",
    legend.title = element_blank(),
    axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1)
  ) +
  # geom_line(aes(group = interaction(uID, pop.to))) +
  xlab("") + ylab("Interaction (%)") +
  # facet_wrap(~pop.to, nrow = 1, scales = "free_y") +
  facet_wrap(~pop, nrow = 1) +
  expand_limits(y = 0)

data.table::fwrite(summaryAssociation, file.path(anaDir, "spatial_interactions.csv"))
# data.table::fwrite(summaryAssociation, file.path(anaDir, "spatial_interactions_bin.csv"))
```


```{r fig_clusters_heat, fig.height=1, fig.width=2}
summaryClust <- summaryDT %>%
  dplyr::filter(
    pop.from %in% c("clustered", "non.clustered"),
    !pop.to %in% c("clustered", "non.clustered", "Other", "T")
      # "/nonDebris/XCR1", "/nonDebris/O/LCMV"),
    # pop.to %in% c("/nonDebris", "/nonDebris/XCR1", "/nonDebris/O/LCMV")
    # !pop.to %in% c("/nonDebris/O/O1/O2/B")
    ) %>%
  # group_by(uID, pop.from, pop.to) %>%
  group_by(uID, pop.to, pop.from) %>%
  # group_by(pop.from, pop.to) %>%
  dplyr::summarise(n = n()) %>%
  mutate(freq = n/sum(n) * 100) %>%
  drop_na() %>%
  ungroup() %>%
  # complete(uID, pop.from, pop.to, fill = list(freq = 0))
  complete(uID, pop.to, pop.from, fill = list(freq = 0))
  # complete(pop.from, pop.to, fill = list(freq = 0))
  # mutate(pop.group = interaction(uID, pop.to))

ggplot(data = summaryClust %>%
         mutate(
           # pop.to = factor(pop.to, levels = c("XCR1", "LCMV", "Other")),
           # pop.from = factor(pop.from, levels = c("non.clustered", "clustered"))
           ),
       aes(
         # color = as.factor(pop.from),
         y = freq,
         # x = as.factor(pop.to))) +
         # x = pop.from)) +
         x = pop.to)) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  # geom_jitter(position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
  # geom_jitter(width = 0.3, alpha = 1.0) +
  geom_point(alpha = 1.0) +
  theme(
    legend.justification = "center",
    legend.direction = "horizontal",
    legend.position = "bottom",
    legend.title = element_blank(),
    axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1)
  ) +
  # geom_line(aes(group = interaction(uID, pop.to))) +
  xlab("") + ylab("Interaction (%)") +
  # facet_wrap(~pop.to, nrow = 1, scales = "free_y") +
  facet_wrap(~pop.from, nrow = 1) +
  expand_limits(y = 0)

# ggsave(file.path(anaDir, "P14_interactions.pdf"), width = 3, height = 2)
```


