---
title: "Run modules"
output: html_document
date: '2022-08-16'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Examples to run functions and modules

```{r}
# set test variables
pID <- "wEsnzt"
versionID <- 1
projectsDir <- "/Volumes/Analysis_SSD/Dominik/cecelia/projects/"
hpcDir <- "/data/scratch/projects/punim1124/cecelia/USERS/schienstockd/"
```

```{r}
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia")

library(ggplot2)
library(tidyverse)
```

```{r}
# HPC config
HPC_CONF <-  list(
  hpc = list(
    conf = list(
      email = "schienstockd@student.unimelb.edu.au",
      emailOnBegin = FALSE,
      emailOnEnd = FALSE,
      emailOnFail = TRUE,
      numNodes = 1,
      numTasks = 1,
      numCPUperTask = 1,
      numGPUperTask = 1,
      memory = 50,
      walltime = "00-01:00:00",
      projectPartitions = "physical",
      # projectPartitions = "shortgpgpu,gpgpu",
      projectID = "punim1124",
      # projectID = "punim1031",
      useGPU = FALSE
      # useGPU = TRUE
    )
  ),
  utils = list(
    ssh = list(
      username = "schienstockd",
      address = "spartan.hpc.unimelb.edu.au",
      keyfile = "/Users/schiend/.ssh/spartan_rsa"
    ),
    python = list(
      condaEnv = cciaConf()$python$conda$source$env
    )
  )
)
```

```{r}
# anaDir <- "/Volumes/USER_data/Dominik/Experiments/Moldoveanu2022_IMC/CECELIA"
```

```{r}
# run clustering
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "Jg3ofZ", versionID = versionID, initReactivity = FALSE # Set
)

cciaObj$persistentObjectDirectory(root = TRUE, zero = TRUE)
```

```{r}
# run clustering
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "Jg3ofZ", versionID = versionID, initReactivity = FALSE # Set
)

exp.info <- cciaObj$summary(withSelf = FALSE, fields = c("Attr"))

uIDs <- names(cciaObj$cciaObjects())
uIDs <- uIDs[uIDs %in% exp.info[exp.info$Organ == "Liver",]$uID]

# run task
funParams <- list(
  uIDs = uIDs,
  regChannel = "Hoechst",
  doFftInitialization = FALSE,
  doAffine2d = TRUE,
  doAffine3d = FALSE,
  ignoreSpacing = TRUE,
  sigma = 1.0,
  autoMask = FALSE,
  samplesPerParameter = 5000,
  expand = 0
)

task <- cciaObj$runTask(
  funName = "cleanupImages.registerImages",
  funParams = funParams,
  envVars = HPC_CONF,
  hpcDir = paste(hpcDir, pID, "ANALYSIS", sep = "/"),
  env = "hpc",
  # env = "local",
  runInplace = FALSE,
  # runInplace = TRUE,
  taskID = 1
)
```
