---
title: "Behaviour GCAMP"
output: html_document
date: '2022-08-15'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Show transition states of live cell imaging

```{r}
devtools::load_all("../")
cciaUse("~/cecelia/dev")

library(ggplot2)
library(tidyverse)
```

```{r}
# set test variables
pID <- "8BR53W"
versionID <- 1
projectsDir <- "/Volumes/Analysis_SSD/Dominik/cecelia/projects/"
hpcDir <- "/data/scratch/projects/punim1124/cecelia/USERS/schienstockd/"
```

```{r}
# HPC config
HPC_CONF <-  list(
  hpc = list(
    conf = list(
      email = "schienstockd@student.unimelb.edu.au",
      emailOnBegin = FALSE,
      emailOnEnd = FALSE,
      emailOnFail = TRUE,
      numNodes = 1,
      numTasks = 1,
      numCPUperTask = 1,
      numGPUperTask = 1,
      memory = 50,
      walltime = "00-06:00:00",
      projectPartitions = "physical",
      # projectPartitions = "gpu-a100",
      projectID = "punim1124",
      # projectID = "punim1031",
      useGPU = FALSE
      # useGPU = TRUE
    )
  ),
  utils = list(
    ssh = list(
      username = "schienstockd",
      address = "spartan.hpc.unimelb.edu.au",
      keyfile = "/Users/Dominik/.ssh/spartan_rsa"
    ),
    python = list(
      condaEnv = cciaConf()$python$conda$source$env
    )
  )
)
```

```{r}
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

sshUtil <- SshUtils$new(
  username = HPC_CONF$utils$ssh$username,
  address = HPC_CONF$utils$ssh$address,
  keyfile = HPC_CONF$utils$ssh$keyfile
  )

hpcPath  <- paste(
  cciaConf()$hpc$dirs$base,
  cciaConf()$hpc$dirs$users,
  # include username
  HPC_CONF$utils$ssh$username,
  pID,
  cciaConf()$hpc$dirs$analysis,
  sep = "/"
)

# for (i in c("LGk0Oc", "9g5v0b", "73d2Y7", "i37o6P", "fD6yGF")) {
for (i in c("73d2Y7", "i37o6P", "fD6yGF")) {
  # init ccia object
  cciaObj <- initCciaObject(
    pID = pID, uID = i, versionID = versionID, initReactivity = FALSE # Skin
  )

  for (x in cciaObj$cciaObjects()) {
    print(x$getUID())
  
    # remove '0'
    handleSystem(sshUtil$sshExecute(
      sprintf(
        "rm -fr \"%s\"",
        paste(hpcPath, "0", x$getUID(), sep = "/")
      )
    ), silent = FALSE)
  
    # task directory
    handleSystem(sshUtil$sshExecute(
      sprintf(
        "rm -fr \"%s\"",
        paste(hpcPath, versionID, x$getUID(), sep = "/")
      )
    ), silent = FALSE)
  }
  
  # remove local
  cciaObj$removeCciaObjects(removeZero = TRUE)
  cciaObj$deleteObjectDirectory()
}
```


```{r}
# for (curObj in selectedSet()$cciaObjects()) {
#     globalManagers$projectManager()$deleteHPCpersistentObjectDirectory(
#       curObj()$getUID()
#     )
#   }
#   
#   progress$close()
# }
# 
# # remove set and its child objects
# selectedSet()$removeCciaObjects()
# selectedSet()$deleteObjectDirectory()
# globalManagers$dataManager()$cciaImageCollection()$removeCciaObjectByUID(selectedSet()$getUID())
# 
# removeCciaObjects
```

