---
title: "Run app"
output: html_document
date: '2022-08-17'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Run app

```{r}
library(flowCore)
Sys.setenv(KMP_DUPLICATE_LIB_OK = "TRUE")
# NotImplementedError: The operator 'aten::to_mkldnn' is not currently implemented for the MPS device.
Sys.setenv(PYTORCH_ENABLE_MPS_FALLBACK = "1")

devtools::load_all("../")
# library(cecelia)
# cciaSetup("~/cecelia/dev")
# cciaUse("~/cecelia/dev") 
# cciaCreateApp()
cciaUse("~/cecelia/dev", initJupyter = TRUE)
# cciaUse("~/cecelia/dev", initConda = FALSE, initJupyter = FALSE)
# cciaUse("~/cecelia/dev", initJupyter = FALSE)
# cciaUse("~/cecelia/dev", initConda = FALSE)

cciaRunApp(port = 6853, localPath = FALSE)

# cciaRunApp(port = 6866)
```

```{r}
devtools::load_all("../")
cciaUse("~/cecelia/dev")
```

```{r}
a <- readRDS("/Volumes/USER_data/Dominik/CECELIA_BACKUP/ZOE/4e268db5d87fd405/values.rds")

a$project$ProjectVersionStateID <- "4e268db5d87fd405"
a$project$ProjectName <- "ZOE TEST"
a$project$ProjectUID <- "az8y8l"
a$project$ProjectPath <- "/cecelia/projects/az8y8l"
a$project$ProjectHPCusername <- "zfransos"
a$project$ProjectHPCemail <- "zfransos@student.unimelb.edu.au"
a$project$ProjectHPCprojectCPU <- "cascade"
a$project$ProjectHPCpartitionsGPU <- "gpu-a100,gpu-a100-short"

saveRDS(a, "/Volumes/USER_data/Dominik/CECELIA_BACKUP/ZOE/4e268db5d87fd405/values.rds")
```

```{r}
a <- readRDS("/Volumes/Analysis_SSD/Communal/cecelia/projects/az8y8l/ANALYSIS/1/IIIII0/ccid.rds")
names(sets) <- sets
a$CciaObjectUIDs <- sets

saveRDS(a, "/Volumes/Analysis_SSD/Communal/cecelia/projects/az8y8l/ANALYSIS/1/IIIII0/ccid.rds")
```


```{r}
a <- list.dirs("/Volumes/Analysis_SSD/Communal/cecelia/projects/az8y8l/ANALYSIS/1", recursive = FALSE)
sets <- c()

for (i in a) {
      tryCatch({
        x <- readRDS(file.path(i, "ccid.rds"))
        
        if (x$CciaClass == "CciaImageSet" && "CciaObjectUIDs" %in% names(x)) {
          sets <- c(sets, x$UID)
          
          # if () {
          #   sets <- c(sets, x$UID)
          # }
        }
      },
      error = function(cond) {
      },
      warning = function(cond) {
      },
      finally = {}
    )
}


```



```{r}
# when you are done shutdown kernel
# cciaEnv()$jupyterKernel$quitKernel()
.rs.removeAllObjects(env = .GlobalEnv, includeHidden = TRUE)
.rs.api.restartSession()
```

