---
title: "napari"
output: html_document
date: '2022-08-18'
---

```{r setup, include=FALSE}
renv::load("~/R-workspace/cecelia/")
knitr::opts_chunk$set(echo = TRUE)
```

## Use napari from R

```{r}
Sys.setenv(KMP_DUPLICATE_LIB_OK = "TRUE")
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = TRUE, initJupyter = TRUE)
# cciaUse("~/cecelia/dev", initConda = FALSE, initJupyter = FALSE)
projectsDir <- "/Volumes/USER_data/Dominik/CECELIA_BACKUP/"

# start ipython kernel
viewer <- NapariUtils$new()

viewer$initNapari()
```

```{r}
generateMovies <- function(anaDir, cciaObj, uIDs, channelsToShow, popsToShow, fileAttrs,
                           splitTracks = NULL, splitPops = NULL, matchChannels = FALSE, fps = 10,
                           generateMovie = TRUE, tracksBlending = "additive", pointsSize = 8,
                           showTracks = TRUE, valueName = NULL) {
  # go through images and save movies
  for (x in cciaObj$cciaObjects(uIDs = uIDs)) {
    i <- x$getUID()
    viewer$setTaskDir(x$persistentObjectDirectory())
    
    # get channels
    imChannelNames <- x$imChannelNames()
    
    # match channels
    curChannelsToShow <- channelsToShow
    if (matchChannels == TRUE) {
      # TODO this is very crude    
      names(curChannelsToShow) <- sapply(names(channelsToShow), function(y) {
        imChannelNames[!is.na(stringr::str_extract(imChannelNames, y))][[1]]
      })
    }

    # get cmaps
    layersVisible <- imChannelNames %in% names(curChannelsToShow)
    channelColormaps <- rep("gray", length(layersVisible))

    for (j in names(curChannelsToShow))
      channelColormaps[[which(imChannelNames == j)]] <- curChannelsToShow[[j]]
    
    # get time information
    showTimestamp <- x$omeXMLPixels()$SizeT > 1
      
    if (showTimestamp == TRUE) {
      timeInterval <- x$omeXMLTimelapseInfo()$interval
    } else {
      timeInterval <- 1
    }
    
    # open image
    viewer$openImage(
      x$imFilepath(valueName = valueName),
      imChannelNames = imChannelNames,
      show3D = TRUE,
      layersVisible = layersVisible,
      channelColormaps = channelColormaps,
      showTimestamp = showTimestamp,
      timeInterval = timeInterval
    )
    
    if (length(popsToShow) > 0) {
      # add tracks
      if (showTracks == TRUE) {
        viewer$showLabelsAll(
          popsToShow,
          # showLabels = TRUE,
          showTracks = showTracks,
          splitTracks = splitTracks,
          tracksBlending = tracksBlending
        )
      }
  
      # add populations
      popsAdded <- list()
  
      # add populations to popMap
      for (k in popsToShow) {
        pop <- paste0(k, "/tracked")
        popType <- "live"
        parentPops <- c(pop)
        pops <- list()
  
        # create pops from cluster information
        # pops <- mapply(function(x, i) {
        for (j in names(splitTracks)) {
          y <- splitTracks[[j]]
  
          pops <- append(pops, mapply(function(z, k) {
          # mapply(function(y, j) {
            list(
              filterMeasure = j,
              filterValues = z[["values"]],
              filterFun = "eq",
              colour = z[["colour"]]
              # isTrack = TRUE
            )
          }, y, names(y), SIMPLIFY = FALSE))
        }
        
        # create pops from other measures
        # TODO this is essentially the same as the previous
        for (j in names(splitPops)) {
          y <- splitPops[[j]]
  
          pops <- append(pops, mapply(function(z, k) {
          # mapply(function(y, j) {
            list(
              filterMeasure = j,
              filterValues = z[["values"]],
              filterFun = "eq",
              colour = z[["colour"]]
              # isTrack = TRUE
            )
          }, y, names(y), SIMPLIFY = FALSE))
        }
  
        # add pops
        popsToAdd <- levels(interaction(parentPops, names(pops), sep = "/"))
        popsAdded[[k]] <- popsToAdd
        
        # remove populations
        x$delPopsByPath(popType, pops = popsToAdd, includeFiltered = TRUE)
  
        # add populations
        x$addFilteredPops(popType, parentPops, pops, valueName = k)
      }
  
      # save to disk
      x$savePopMap(popType, includeFiltered = TRUE)
      x$savePops(popType, pops = unname(unlist(popsAdded)),
                 purge = TRUE, includeFiltered = TRUE)
      
      # show on image
      removePrevious <- TRUE
      for (j in names(popsAdded)) {
        viewer$showPopMapping("live", valueName = j, pops = popsAdded[[j]], pointsSize = pointsSize,
                              execInteractive = FALSE, removePrevious = removePrevious)
        removePrevious <- FALSE
      }
    }

    # save animation
    if (generateMovie == TRUE) {
      browser()
      
      viewer$saveTimeAnimation(
        file.path(anaDir, "movies", paste0(
          paste(sapply(fileAttrs, function(i) x$getCciaAttr(i)), collapse = "_"), "_", i, ".mp4")),
        windowSizeX = 1600, windowSizeY = 1200, fps = fps)
    } else {
      browser()
    }
  }
}
```

```{r}
anaDir <- "/Volumes/Lab-Mueller/Dominik Schienstock/Notebook/Experiments/3P_TESTS/Spleen/ANALYSIS"

# init ccia object
cciaObj <- initCciaObject(
  pID = "QZwVFQ", uID = "efgRsn", versionID = "1", initReactivity = FALSE 
)

# get experimental info
exp.info <- as.data.table(cciaObj$summary(
  withSelf = FALSE, fields = c("Attr")
))

# only include OK movies
# uIDs <- names(cciaObj$cciaObjects())
# uIDs <- exp.info[Notes == "OK" & Type == "Live"]$uID
# uIDs <- exp.info[Notes != "OK" & Type == "Live"]$uID
# uIDs <- exp.info[Type == "Live"]$uID
uIDs <- c("nQLvxD")

channelsToShow <- list(
  "one" = "red",
  "two" = "green",
  "three" = "gray",
  "four" = "bop purple"
  )

generateMovies(anaDir, cciaObj, uIDs, channelsToShow, NULL, NULL,
               # splitTracks = splitTracks, fps = 10, valueName = "default")
               splitTracks = splitTracks, fps = 10, valueName = "corrected")
```

```{r}
anaDir <- "/Volumes/MDHS-Research/5300/5260/Lab-Mueller/Dominik Schienstock/Notebook/Experiments/MARIJA_CAR_T/ANALYSIS"

# init ccia object
cciaObj <- initCciaObject(
  pID = "ScCqhf", uID = "PABXLt", versionID = "1", initReactivity = FALSE 
)

# get experimental info
exp.info <- as.data.table(cciaObj$summary(
  withSelf = FALSE, fields = c("Attr")
))

uIDs <- names(cciaObj$cciaObjects())

splitTracks <- list(
  live.cell.track.clusters.movement = list(
    Directed = list(values = list(3,4), colour = "#ff1493"),
    Meandering = list(values = list(2), colour = "#ffd700"),
    Immotile = list(values = list(1), colour = "#00bfff"),
    Imm.Meander = list(values = list(0), colour = "#00fa9a")
    )
  )

channelsToShow <- list(
  "Tcells" = "gray",
  "SHG" = "bop purple"
  )
popsToShow <- list("tcells")
fileAttrs <- c("Day", "Treatment")

generateMovies(anaDir, cciaObj, uIDs, channelsToShow, popsToShow, fileAttrs,
               splitTracks = splitTracks, fps = 20)
```

```{r}
anaDir <- "/Volumes/USER_data/Dominik/Experiments/DS_N058/ANALYSIS/CECELIA"

# init ccia object
cciaObj <- initCciaObject(
  pID = "8BR53W", uID = "6p8l06", versionID = 1, initReactivity = FALSE
)

uIDs <- names(cciaObj$cciaObjects())

channelsToShow <- list(
  "one" = "cyan",
  "two" = "gray",
  "three" = "magenta",
  "four" = "yellow"
  )
fileAttrs <- c("DTx")

generateMovies(anaDir, cciaObj, uIDs, channelsToShow, c(), fileAttrs,
               # generateMovie = TRUE, valueName = NULL)
               generateMovie = TRUE, valueName = "default")
```


```{r}
anaDir <- "/Volumes/USER_data/Dominik/Experiments/FELIX_GARVAN/ANALYSIS/"

# init ccia object
cciaObj <- initCciaObject(
  pID = "Ar69Mq", uID = "qLglaf", versionID = "1", initReactivity = FALSE 
)

# get experimental info
exp.info <- cciaObj$summary(
  withSelf = FALSE, fields = c("Attr")
)

uIDs <- c("6VVbzF")

splitPops <- list(
  # live.cell.hmm.state.movement = list(
  #   meandering = list(values = list(1), colour = "#ebd441"),
  #   directed = list(values = list(2), colour = "#AA1F5E"),
  #   scanning = list(values = list(3), colour = "#4682b4")
  #   )
  # live.cell.hmm.state.shape = list(
  #   oblate = list(values = list(1), colour = "#4682b4"),
  #   prolate = list(values = list(2), colour = "#AA1F5E"),
  #   interm = list(values = list(3), colour = "#ebd441")
  #   )
  live.cell.hmm.state.nuclei = list(
    oblate = list(values = list(1), colour = "#AA1F5E"),
    prolate = list(values = list(2), colour = "#4682b4"),
    interm = list(values = list(3), colour = "#ebd441")
    )
  )

channelsToShow <- list(
  "one" = "gray",
  "two" = "bop blue"
  )
popsToShow <- list("merged")
fileAttrs <- c("")

generateMovies(anaDir, cciaObj, uIDs, channelsToShow, popsToShow, fileAttrs,
               splitPops = splitPops, fps = 30, pointsSize = 20, showTracks = FALSE)
```


```{r}
anaDir <- "/Volumes/USER_data/Dominik/Experiments/SAPNA_TUMOUR_2P/CECELIA"

# init ccia object
cciaObj <- initCciaObject(
  pID = "8BR53W", uID = "LiQDGt", versionID = "1", initReactivity = FALSE 
)

# get experimental info
exp.info <- cciaObj$summary(
  withSelf = FALSE, fields = c("Attr")
)

uIDs <- exp.info[exp.info$Include == "Y" & exp.info$Treatment == "CNO",]$uID
# uIDs <- c("tbh61I")

# splitTracks <- list(
#   live.cell.track.clusters.default = list(
#     meandering = list(values = list(0), colour = "#4CAF48"),
#     arresting = list(values = list(1), colour = "#327EBA"),
#     directed = list(values = list(2), colour = "#E42328")
#     )
#   )

channelsToShow <- list(
  "OTI-CTV" = "yellow",
  "EvansBlue" = "bop blue",
  "SHG" = "gray"
  )
# popsToShow <- list("default")
popsToShow <- list()
fileAttrs <- c("Treatment")

generateMovies(anaDir, cciaObj, uIDs, channelsToShow, popsToShow, fileAttrs,
               # splitTracks = splitTracks, fps = 10)
               fps = 20)
```

```{r}
anaDir <- "/Volumes/USER_data/Dominik/Experiments/SAPNA_TUMOUR_3P/CECELIA"

# init ccia object
cciaObj <- initCciaObject(
  pID = "CV5iNI", uID = "vwzo5g", versionID = "1", initReactivity = FALSE 
)

# get experimental info
exp.info <- cciaObj$summary(
  withSelf = FALSE, fields = c("Attr")
)

# uIDs <- exp.info[exp.info$Include == "Y" & exp.info$Treatment == "Sal",]$uID
uIDs <- c("HYmMxh")

splitTracks <- list(
  live.cell.track.clusters.hmm_transitions_movement = list(
    meandering = list(values = list(0), colour = "#4CAF48"),
    arresting = list(values = list(1), colour = "#327EBA"),
    directed = list(values = list(2), colour = "#E42328")
    )
  )

channelsToShow <- list(
  "OTI-GFP" = "yellow",
  "Sliding EB" = "bop blue",
  "Sliding SHG" = "magenta",
  "Sliding THG" = "gray"
  )
popsToShow <- list("OTI")
fileAttrs <- c("Treatment")

generateMovies(anaDir, cciaObj, uIDs, channelsToShow, popsToShow, fileAttrs,
               splitTracks = splitTracks, fps = 10)
```

```{r}
anaDir <- "/Volumes/USER_data/Dominik/Experiments/JL-ANALYSIS/RESULTS/clusterTracks/movement"

# init ccia object
cciaObj <- initCciaObject(
  pID = "8BR53W", uID = "ZXcUMO", versionID = 1, initReactivity = FALSE
)

# get experimental info
exp.info <- as.data.table(cciaObj$summary(withSelf = FALSE, fields = c("Attr")))

uIDs <- exp.info[Include == "Y"]$uID

# uIDs <- c("iTfSUG") # PBS
# uIDs <- c("m87rLx") # DTx
# uIDs <- c("Yw6sqF") # Uninf

uIDs <- c(
  # "iTfSUG", # PBS
  # "m87rLx", # DTx
  "Yw6sqF" # Uninf
)

splitTracks <- list(
  live.cell.track.clusters.hmm_transitions_movement = list(
    # others = list(values = list(1,3,5,6,7), colour = "#B3BCC2"),
    meandering = list(values = list(1), colour = "#B3BCC2"),
    clustering = list(values = list(3), colour = "#ebd441"),
    scanning = list(values = list(2), colour = "#4682b4"),
    directed = list(values = list(0), colour = "#AA1F5E")
    # arrested = list(values = list(4), colour = "#008000")
    )
  )

channelsToShow <- list(
  "gBT" = "gray",
  "gDT" = "cyan",
  "TRITC" = "red"
  )
# popsToShow <- list("tcells.gBT", "tcells.gDT")
popsToShow <- list("tcells.gBT")
fileAttrs <- list("Treatment", "DTx")

generateMovies(anaDir, cciaObj, uIDs, channelsToShow, popsToShow, fileAttrs, splitTracks = splitTracks, generateMovie = TRUE)
```

```{r}
anaDir <- "/Volumes/USER_data/Dominik/Experiments/DS_N052/ANALYSIS/IMAGE/CECELIA/transitions"

# init ccia object
cciaObj <- initCciaObject(
  pID = "8BR53W", uID = "YJRfCW", versionID = 1, initReactivity = FALSE
)

uIDs <- names(cciaObj$cciaObjects())
uIDs <- uIDs[!uIDs %in% "1wZMND"]
# uIDs <- c("rF9J6a") # B6
uIDs <- c("WOJjrl") # H2KB

splitTracks <- list(
  live.cell.track.clusters.hmm_transitions_movement = list(
    others = list(values = list(0,1,3,4,6), colour = "#B3BCC2"),
    scanning = list(values = list(5), colour = "#4682b4"),
    directed = list(values = list(2), colour = "#AA1F5E")
    )
  )

channelsToShow <- list(
  "gBT-CTV" = "magenta",
  "OTI-uGFP" = "yellow"
  )
popsToShow <- c("gBT", "OTI")
fileAttrs <- c("Genotype")

generateMovies(anaDir, cciaObj, uIDs, channelsToShow, popsToShow, fileAttrs,
               splitTracks = splitTracks, generateMovie = FALSE, tracksBlending = "opaque")
```

```{r}
anaDir <- "/Volumes/USER_data/Dominik/Experiments/SAPNA_SNS_2P/CECELIA"

# init ccia object
cciaObj <- initCciaObject(
  pID = "8BR53W", uID = "LUw0Nx", versionID = "1", initReactivity = FALSE 
)

# get experimental info
exp.info <- cciaObj$summary(
  withSelf = FALSE, fields = c("Attr")
)

uIDs <- exp.info[exp.info$Include == "Y" & exp.info$Treatment == "Sal",]$uID
uIDs <- c("oPZZCg")

splitTracks <- list(
  live.cell.track.clusters.hmm_transitions_movement = list(
    meandering = list(values = list(1,4), colour = "#4CAF48"),
    arresting = list(values = list(2,3,5), colour = "#327EBA"),
    directed = list(values = list(0), colour = "#E42328")
    )
  )

channelsToShow <- list(
  "T-A" = "magenta",
  "T-B" = "yellow",
  "AF" = "gray"
  )
popsToShow <- c("T.A", "T.B")
fileAttrs <- c("Treatment")

generateMovies(anaDir, cciaObj, uIDs, channelsToShow, popsToShow, fileAttrs,
               splitTracks = splitTracks, fps = 20, generateMovie = FALSE)
```

```{r}
anaDir <- "/Volumes/USER_data/Dominik/Experiments/JL-ANALYSIS/PUBRe/clusterTracks/movement"

# init ccia object
cciaObj <- initCciaObject(
  pID = "8BR53W", uID = "rXctjl", versionID = 1, initReactivity = FALSE
)

# get experimental info
exp.info <- as.data.table(cciaObj$summary(
  withSelf = FALSE, fields = c("Attr")
))

# uIDs <- exp.info[Cells == "gDT_gBT" & Include == "Y"]$uID
uIDs <- exp.info[Cells == "gDT_gBT" & Include == "Y" & Treatment == "Naive"]$uID
uIDs <- c("Ws5sVa")
# uIDs <- c("5phIYn")

splitTracks <- list(
  live.cell.track.clusters.hmm_transitions_movement = list(
    track.clustering = list(values = list(1), colour = "#ffff00"),
    track.scanning = list(values = list(0,5), colour = "#327EBA"),
    track.meandering = list(values = list(2,6), colour = "#AA1F5E"),
    track.others = list(values = list(3,4), colour = "#B3BCC2")
    )
  )
# splitTracks <- NULL

channelsToShow <- list(
  "gBT-dsRed" = "gray",
  "gDT-uGFP" = "cyan"
  )
popsToShow <- c("gBT", "gDT")
# popsToShow <- NULL
fileAttrs <- c("Treatment", "dpi")

generateMovies(anaDir, cciaObj, uIDs, channelsToShow, popsToShow, fileAttrs,
               splitTracks = splitTracks, generateMovie = FALSE)
```

```{r}
anaDir <- "/Volumes/USER_data/Dominik/Experiments/Immunemap_expID_49/CECELIA"

# init ccia object
cciaObj <- initCciaObject(
  pID = "8BR53W", uID = "mrMpi5", versionID = 1, initReactivity = FALSE, projectsDir = projectsDir # Immunemap
)

# uIDs <- names(cciaObj$cciaObjects())[[1]]
uIDs <- c("01MS5C")

splitTracks <- list(
  live.cell.track.clusters.hmm_transitions_movement = list(
    zero = list(values = list(3), colour = "#1B9064"),
    one = list(values = list(1,4), colour = "#CE4A09"),
    two = list(values = list(0), colour = "#6259A3"),
    three = list(values = list(2), colour = "#DD0277")
    )
  )

channelsToShow <- list(
  # "CD11c-YFP" = "bop orange",
  # "PROX1" = "bop blue",
  "PROX1" = "white",
  "hCD2-DsRed" = "magenta"
  )
popsToShow <- list("T")
fileAttrs <- list()

generateMovies(anaDir, cciaObj, uIDs, channelsToShow, popsToShow, fileAttrs, splitTracks = splitTracks,
               generateMovie = FALSE)

# viewer$showLabelsAll(showLabels = TRUE, valueNames = list("T", "LV"))
```

```{r}
anaDir <- "/Volumes/USER_data/Dominik/Experiments/DS_N044/ANALYSIS/IMAGE/CECELIA/"

# init ccia object
cciaObj <- initCciaObject(
  pID = "8BR53W", uID = "QJYqa7", versionID = 1, initReactivity = FALSE # Tcells
)

# get experimental info
exp.info <- as.data.table(cciaObj$summary(
  withSelf = FALSE, fields = c("Attr")
))

uIDs <- exp.info[Include == "Y"]$uID

splitTracks <- list(
  live.cell.track.clusters.hmm_transitions_movement = list(
    directed = list(values = list(3), colour = "#AA1F5E"),
    scanning = list(values = list(4), colour = "#327EBA"),
    meandering = list(values = list(0,1,2), colour = "#B3BCC2")
    )
  )

channelsToShow <- list(
  "P14" = "red",
  "gBT" = "gray",
  "OTI" = "cyan"
  )
popsToShow <- c("tcells.P14", "tcells.gBT", "tcells.OTI")
fileAttrs <- c("Treatment")

generateMovies(anaDir, cciaObj, uIDs, channelsToShow, popsToShow, fileAttrs,
               splitTracks = splitTracks, matchChannels = TRUE, fps = 20)
```

```{r}
anaDir <- "/Volumes/USER_data/Dominik/Experiments/JL-ANALYSIS/RESULTS/XCR1-Venus/all_types_re"

# init ccia object
cciaObj <- initCciaObject(
  pID = "8BR53W", uID = "0Oenks", versionID = 1, initReactivity = FALSE # XCR1-venus
)

# GCAMP
# uIDs <- names(cciaObj$cciaObjects())[[8]]
uIDs <- c("ZmxDIj")

splitTracks <- list(
  live.cell.track.clusters.hmm_transitions = list(
    # zero = list(values = list(0), colour = "#E42328"),
    # zero = list(values = list(0), colour = "magenta"),
    # one = list(values = list(1), colour = "#327EBA"),
    # two = list(values = list(2), colour = "#4CAF48"),
    # three = list(values = list(3), colour = "#974D9E"),
    # four = list(values = list(4), colour = "#F47F20"),
    # five = list(values = list(5), colour = "#ffff00")
    Scanning = list(values = list(0,3), colour = "#327EBA"),
    `Meandering prolate` = list(values = list(4), colour = "#1B9E77"),
    `Meandering oblate` = list(values = list(1,6), colour = "#B3BCC2"),
    Directed = list(values = list(2,7), colour = "#AA1F5E"),
    Aggregating = list(values = list(5), colour = "#FFFF00")
    )
  )

channelsToShow <- list(
  "gBT-CTDR" = "gray",
  "gDT-CTV" = "cyan",
  "XCR1-Venus" = "green",
  # "TRITC" = "red"
  "TRITC" = "magenta"
  )
popsToShow <- c("tcells.gBT", "tcells.gDT", "dcs.all")
fileAttrs <- c()

generateMovies(anaDir, cciaObj, uIDs, channelsToShow, popsToShow, fileAttrs,
               splitTracks = splitTracks, generateMovie = FALSE)
```

```{r}
anaDir <- "/Volumes/USER_data/Dominik/Experiments/DS_N030/ANALYSIS/IMAGE/clustering/transitions/"

# init ccia object
cciaObj <- initCciaObject(
  pID = "8BR53W", uID = "BeddcR", versionID = 1, initReactivity = FALSE #  GCAMP
)

# get experimental info
exp.info <- as.data.table(cciaObj$summary(
  withSelf = FALSE, fields = c("Attr")
))

# GCAMP
# uIDs <- exp.info[Focus == "non-clustering" & Cells == "gBT_TRITC"]$uID

uIDs <- c(
  "INw0Gd", # HSV PBS
  "n8W6bT", # HSV DTx
  # "SJfJL0" # Uninf
)

splitTracks <- list(
  live.cell.track.clusters.hmm_transitions_movement = list(
    meandering = list(values = list(0), colour = "#AA1F5E"),
    scanning = list(values = list(3), colour = "#327EBA"),
    other = list(values = list(1,2,4,5,6), colour = "#B3BCC2")
    )
  )

channelsToShow <- list(
  "gBT-CTV" = "magenta",
  "GCAMP" = "cyan",
  "TRITC" = "red"
  )
popsToShow <- list("tcells.gBT")
fileAttrs <- c("Treatment", "DTx")

generateMovies(anaDir, cciaObj, uIDs, channelsToShow, popsToShow, fileAttrs,
               splitTracks = splitTracks, fps = 20)
```

```{r}
anaDir <- "/Volumes/USER_data/Dominik/Experiments/DS_N030/ANALYSIS/IMAGE/clustering/transitions_OTI/"

# init ccia object
cciaObj <- initCciaObject(
  pID = "8BR53W", uID = "BeddcR", versionID = 1, initReactivity = FALSE #  GCAMP
)

# get experimental info
exp.info <- as.data.table(cciaObj$summary(
  withSelf = FALSE, fields = c("Attr")
))

# GCAMP
uIDs <- exp.info[Focus == "non-clustering" & Cells == "gBT_OTI"]$uID

splitTracks <- list(
  live.cell.track.clusters.hmm_transitions_movement = list(
    scanning = list(values = list(1), colour = "#327EBA"),
    other = list(values = list(0,2,3,4,5,6,7), colour = "#B3BCC2")
    )
  )

channelsToShow <- list(
  "gBT-CTDR" = "magenta",
  "OTI-CTV" = "yellow",
  "GCAMP" = "cyan"
  )
popsToShow <- c("tcells.gBT", "tcells.OTI")
fileAttrs <- c("Treatment")

generateMovies(anaDir, cciaObj, uIDs, channelsToShow, popsToShow, fileAttrs,
               splitTracks = splitTracks, fps = 20)
```
