---
title: "Run modules"
output: html_document
date: '2022-08-16'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Examples to run functions and modules

```{r}
# set test variables
pID <- "pEdOoZ"
versionID <- 2
projectsDir <- "/Volumes/Analysis_SSD/Dominik/cecelia/projects/"
hpcDir <- "/data/scratch/projects/punim1124/cecelia/USERS/schienstockd/"
```

```{r}
# HPC config
HPC_CONF <-  list(
  hpc = list(
    conf = list(
      email = "schienstockd@student.unimelb.edu.au",
      emailOnBegin = FALSE,
      emailOnEnd = FALSE,
      emailOnFail = TRUE,
      numNodes = 1,
      numTasks = 1,
      numCPUperTask = 1,
      numGPUperTask = 1,
      memory = 50,
      walltime = "00-01:00:00",
      projectPartitions = "physical",
      # projectPartitions = "shortgpgpu,gpgpu",
      projectID = "punim1124",
      # projectID = "punim1031",
      useGPU = FALSE
      # useGPU = TRUE
    )
  ),
  utils = list(
    ssh = list(
      username = "schienstockd",
      address = "spartan.hpc.unimelb.edu.au",
      keyfile = "/Users/schiend/.ssh/spartan_rsa"
    ),
    python = list(
      condaEnv = cciaConf()$python$conda$source$env,
      condaDir = cciaConf()$python$conda$dir
    )
  )
)
```

```{r}
devtools::load_all("../")
```


```{r}
# # Cecelia setup - this should only be necessary once
# devtools::load_all("../")
# 
# # setup cecelia directory
# cciaSetup("~/Desktop/DOHERTY/cecelia")
# 
# # create conda environment
# cciaCondaCreate()
# 
# # download models
# cciaModels()
```

```{r}
devtools::load_all("../")

# load cecelia directory and then it should work from here
cciaUse("~/Desktop/DOHERTY/cecelia")
```

```{r}
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "tPl6da", versionID = 2, initReactivity = FALSE
)

funParams <- list(
  pyramidScale = 4,
  dimOrder = "",
  createMIP = FALSE,
  rescaleImage = FALSE
)

cciaObj$runTask(
  funName = "importImages.omezarr",
  funParams = funParams,
  runInplace = FALSE,
  env = "hpc",
  envVars = HPC_CONF,
  hpcDir = paste(hpcDir, pID, "ANALYSIS", sep = "/"),
  taskID = 1
)
```


```{r}
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = "pEdOoZ", uID = "tPl6da", versionID = 2, initReactivity = FALSE
)

cciaObj$runTask(
  funName = "gatePopulations.createGatingSet",
  funParams = list(
    compensateZ = FALSE,
    applyReversedLog = FALSE,
    transformation = "biexponential"
  ),
  runInplace = TRUE
)
```
