---
title: "IMC analysis"
output: html_document
---

```{r setup, include=FALSE}
renv::load("~/R-workspace/cecelia/")
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# set test variables
pID <- "Lq0joh"
versionID <- 11
projectsDir <- "/Volumes/Analysis_SSD/Dominik/cecelia/projects/"
hpcDir <- "/data/scratch/projects/punim1124/cecelia/USERS/schienstockd/"
```

```{r}
# HPC config
HPC_CONF <-  list(
  hpc = list(
    conf = list(
      email = "schienstockd@student.unimelb.edu.au",
      emailOnBegin = FALSE,
      emailOnEnd = FALSE,
      emailOnFail = TRUE,
      numNodes = 1,
      numTasks = 1,
      numCPUperTask = 1,
      numGPUperTask = 1,
      memory = 50,
      walltime = "00-01:00:00",
      projectPartitions = "physical",
      # projectPartitions = "shortgpgpu,gpgpu",
      projectID = "punim1124",
      # projectID = "punim1031",
      useGPU = FALSE
      # useGPU = TRUE
    )
  ),
  utils = list(
    ssh = list(
      username = "schienstockd",
      address = "spartan.hpc.unimelb.edu.au",
      keyfile = "/Users/Dominik/.ssh/spartan_rsa"
    )
    # python = list(
    #   condaEnv = cciaConf()$python$conda$source$env
    # )
  )
)
```

```{r}
library(flowCore)
Sys.setenv(KMP_DUPLICATE_LIB_OK = "TRUE")

devtools::load_all("../")
cciaUse("~/cecelia/dev")

library(ggplot2)
library(tidyverse)
```

```{r}
# anaDir <- "/Volumes/USER_data/Dominik/Experiments/DS_N041/RESULTS/OUT/spatial/"
anaDir <- "/Volumes/Lab-Mueller/Dominik Schienstock/Notebook/Experiments/DS_N041/RESULTS/OUT/spatial/"
```

```{r fig_gating, fig.height=6, fig.width=6}
# Load cluster data
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  # pID = pID, uID = "15SFzg", versionID = versionID, initReactivity = FALSE
  pID = pID, uID = "QS9obm", versionID = versionID, initReactivity = FALSE
)

paste(cciaObj$imChannelNames(), collapse = "', '")

# cciaObj$editPopColour(
#   popType = "flow", colour = "#ff1493",
#   popID = cciaObj$popIDFromPath(cciaObj$imPopMap("flow"), "/gBT/CD69+"))

# get raster contours
p1s <- .flowPlotGatedRaster(
  cciaObj, popPath = "/gBT", labelSize = 4, labelBorder = 1.1,
  xTitleSize = 12, yTitleSize = 12,
  xAxisSize = 0, yAxisSize = 0,
  xRange = c(0, 2.5), yRange = c(0, 2.5), 
  asContours = TRUE, plotTitleSize = 0,
  # plot_width = 92, plot_height = 92,
  showPopName = FALSE, showGatePopColours = FALSE, showAnnotation = FALSE)
  # cciaObj, popPaths = "/nonDebris", labelSize = 3, asContours = TRUE, directLeaves = FALSE)

ggpubr::ggarrange(plotlist = p1s, nrow = 1, ncol = 1)

# ggsave(file.path(anaDir, "15SFzg_gating.png"), width = 2, height = 2)
# ggsave(file.path(anaDir, "15SFzg_gating.pdf"), width = 2, height = 2)
# ggsave(file.path(anaDir, "QS9obm_gating.png"), width = 2, height = 2)
ggsave(file.path(anaDir, "QS9obm_gating.pdf"), width = 2, height = 2)
```

```{r}
# crate ppp from popDT
reloadSources()

# init ccia object
cciaObj <- initCciaObject(
  file.path(
    projectsDir, pID, "ANALYSIS", versionID, "4yAwEu"
  ),
  initReactivity = FALSE
)

cciaObj$popPaths(popType = "flow", includeRoot = TRUE, includeFiltered = TRUE)
```

```{r}
# define pops
pops <- c(
  "/gBT",
  # "/gDT",
  "/gBT/CD69+",
  # "/gBT/clustered"
  "/O/TRITC"
)
popsWindow <- c(
  "/gBT", "/gDT", "/O/TRITC"
)
popsPP1 <- c(
  "/gBT/CD69+"
)
popsPP2 <- c(
  "/gBT"
)
```


```{r}
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "tYKNoG", versionID = versionID, initReactivity = FALSE
  # pID = pID, uID = "8UdLBC", versionID = versionID, initReactivity = FALSE
)

exp.info <- as.data.table(cciaObj$summary(
  withSelf = FALSE, fields = c("Attr", "oriFilepath")))

# data.table::fwrite(exp.info, file.path(anaDir, "exp_info.csv"))
# data.table::fwrite(exp.info, file.path(anaDir, "exp_info_JL.csv"))
```


```{r}
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

popDTs <- list()

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "8UdLBC", versionID = versionID, initReactivity = FALSE
)

popDTs["8UdLBC"] <- list(
  cciaObj$popDT(popType = "flow", includeFiltered = TRUE, pops = pops))

cciaObj <- initCciaObject(
  pID = pID, uID = "tYKNoG", versionID = versionID, initReactivity = FALSE
)

popDTs["tYKNoG"] <- list(
  cciaObj$popDT(popType = "flow", includeFiltered = TRUE, pops = pops))

popDT <- data.table::rbindlist(popDTs, idcol = "setID")
```


```{r}
# get ppp
# pp1 <- cciaObj$ppp(
#     windowPops = popsWindow,
#     popType = "flow", uIDs = uIDs, includeFiltered = TRUE,
#     # pops = pops, usePops = popsPP1)
#     pops = popsPP1, usePops = popsPP1)
# pp2 <- cciaObj$ppp(
#     windowPops = popsWindow,
#     popType = "flow", uIDs = uIDs, includeFiltered = TRUE,
#     # pops = pops, usePops = popsPP2)
#     pops = popsPP2, usePops = popsPP2)
```

```{r}
# # how to test for randomness
# # https://stats.stackexchange.com/q/386246
# ppx <- pp1$Pd1PSo
# ppy <- pp1$ZLEpXR
# plot(ppx)
# plot(ppy)
# 
# ppxL <- Linhom(ppx)
# ppyL <- Linhom(ppy)
# 
# plot(ppxL)
# 
# # # envelope test
# envltest <- envelope(ppy, Lest, correction = "none", nsim = 39, savefuns = TRUE)
# plot(envltest)
# 
# # density
# dens <- density(ppy, edge = FALSE, sigma = bw.ppl)
# plot(dens)
# 
# # generate envelope
# envlin <- envelope(
#   ppy, Linhom,
#   simulate = expression(rpoispp(dens)),
#   sigma = bw.ppl,
#   edge = FALSE,
#   correction = "none",
#   nsim = 39,
#   savefuns = TRUE)
# plot(envlin)
```


```{r}
library(spatstat)

for (i in names(pp1)) {
  x <- pp1[[i]]
  
  exp.info[uID == i]
  
  message(paste(">> Test CSR for", i))
  # test for randomness
  ppHK.result <- hopskel.test(x, method = "MonteCarlo", nsim = 999)
  ppCE.result <- clarkevans.test(x, method = "MonteCarlo", nsim = 999)
  
  # push back
  exp.info[uID == i,
           `:=`(
             pp1.hopskel.p = ppHK.result$p.value,
             pp1.hopskel.A = ppHK.result$statistic,
             pp1.hopskel.H = ppHK.result$statistic/(1 + ppHK.result$statistic),
             pp1.clarkevans.p = ppCE.result$p.value,
             pp1.clarkevans.R = ppCE.result$statistic
           )]
}

for (i in names(pp2)) {
  x <- pp2[[i]]
  
  exp.info[uID == i]
  
  message(paste(">> Test CSR for", i))
  # test for randomness
  ppHK.result <- hopskel.test(x, method = "MonteCarlo", nsim = 999)
  ppCE.result <- clarkevans.test(x, method = "MonteCarlo", nsim = 999)
  
  # push back
  exp.info[uID == i,
           `:=`(
             pp2.hopskel.p = ppHK.result$p.value,
             pp2.hopskel.A = ppHK.result$statistic,
             pp2.hopskel.H = ppHK.result$statistic/(1 + ppHK.result$statistic),
             pp2.clarkevans.p = ppCE.result$p.value,
             pp2.clarkevans.R = ppCE.result$statistic
           )]
}
```

```{r fig_CD69_region, fig.height = 4, fig.width = 12}
for (i in unique(popDT$uID)) {
  dataToPlot <- popDT[uID == i]
  y <- exp.info[uID == i]
  
  # plot
  ggplot(dataToPlot,
         aes(centroid_x, -centroid_y)) +
    theme_classic() +
    plotThemeDark(
      fontSize = 8,
      legend.justification = "centre"
      ) +
    # geom_point(data = dataToPlot %>% dplyr::filter(pop == "/gBT"), fill = "#4069E1", shape = 21, size = 2) +
    # geom_point(data = dataToPlot %>% dplyr::filter(pop == "/gBT/CD69+"), fill = "#01FF01", shape = 21, size = 2) +
    # geom_point(data = dataToPlot %>% dplyr::filter(pop == "/gBT/clustered"), fill = "yellow", shape = 21, size = 2) +
    geom_point(data = dataToPlot %>% dplyr::filter(pop == "/gBT"), fill = "#4069E1", shape = 21, size = 0) +
    geom_point(data = dataToPlot %>% dplyr::filter(pop == "/gBT/CD69+"), fill = "#01FF01", shape = 21, size = 0) +
    # geom_point(data = dataToPlot %>% dplyr::filter(pop == "/O/TRITC"), fill = "red", shape = 21, size = 2) +
    # geom_point(data = dataToPlot %>% dplyr::filter(pop == "/gBT/clustered"), fill = "yellow", shape = 21, size = 0) +
    geom_density_2d(
      data = dataToPlot %>% dplyr::filter(pop == "/O/TRITC"),
      contour_var = "ndensity", bins = 6,
      colour = "red") + 
    geom_density_2d(
      data = dataToPlot %>% dplyr::filter(pop == "/gBT/CD69+"),
      contour_var = "ndensity", bins = 6,
      colour = "white") + 
      # aes(fill = ..level..), geom = "polygon", colour = "white") +
    coord_fixed() +
    theme(
      legend.title = element_blank(),
      legend.position = 'bottom',
      axis.title.x = element_blank(),
      axis.text.x = element_blank(),
      axis.ticks.x = element_blank(),
      axis.title.y = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank(),
      axis.line = element_blank()
      ) +
    scale_color_brewer(palette = "Set1")
  
  # ggsave(file.path(anaDir, "clusters_15SFzg.tiff"), height = 3, width = 4)
  # ggsave(file.path(anaDir, paste0("clusters_", y$Treatment, "-", i, "_TRITC.tiff")), height = 3, width = 4)
  ggsave(file.path(anaDir, paste0("clusters_", y$Treatment, "-", i, "_TRITC_contour.tiff")), height = 3, width = 4)
  # ggsave(file.path(anaDir, "clusters_15SFzg_TRITC.tiff"), height = 3, width = 4)
  # ggsave(file.path(anaDir, "clusters_QS9obm.tiff"), height = 3, width = 4)
  # ggsave(file.path(anaDir, "clusters_QS9obm_TRITC.tiff"), height = 3, width = 4)
  # ggsave(file.path(anaDir, "clusters_15SFzg_density.svg"), height = 3, width = 4)
  # ggsave(file.path(anaDir, "clusters_QS9obm_density.svg"), height = 3, width = 4)
}
```


```{r fig_delaunay_regions, fig.height = 5, fig.width = 12}
dataToPlot <- popDT %>% left_join(exp.info)

# plot
ggplot(dataToPlot,
       aes(centroid_x, -centroid_y)) +
  theme_classic() +
  plotThemeDark(
    fontSize = 8,
    legend.justification = "centre"
    ) +
  geom_point(data = dataToPlot %>% dplyr::filter(pop == "/gBT"), color = "darkgrey") +
  geom_point(data = dataToPlot %>% dplyr::filter(pop == "/gBT/CD69+"), color = "#ff048e") +
  # geom_point(data = dataToPlot %>% dplyr::filter(pop == "/gBT/clustered"), color = "#ffb804") +
  geom_density_2d(
    data = dataToPlot %>% dplyr::filter(pop == "/gBT/CD69+"),
    contour_var = "ndensity", bins = 6,
    colour = "white") + 
    # aes(fill = ..level..), geom = "polygon", colour = "white") +
  coord_fixed() +
  theme(
    legend.title = element_blank(),
    legend.position = 'bottom'
    ) +
  facet_wrap(
    Treatment~uID+
      # paste("HK p =", pp1.hopskel.p) +
      # paste("HK H =", pp1.hopskel.H) +
      paste("CD69+ p =", pp1.clarkevans.p) +
      paste("CD69+ R =", pp1.clarkevans.R) +
      paste("CD69- p =", pp2.clarkevans.p) +
      paste("CD69- R =", pp2.clarkevans.R),
    ncol = 6) +
  scale_color_brewer(palette = "Set1")

# ggsave(file.path(anaDir, "clusters.tiff"), height = 10, width = 22)
```

```{r fig_delaunay_regions, fig.height = 4, fig.width = 12}
dataToPlot <- popDT %>% left_join(exp.info)

# plot
ggplot(dataToPlot,
       aes(centroid_x, -centroid_y)) +
  theme_classic() +
  plotThemeDark(
    fontSize = 8,
    legend.justification = "centre"
    ) +
  geom_density_2d_filled(
    data = dataToPlot %>% dplyr::filter(pop == "/gBT/CD69+"),
    contour_var = "ndensity", bins = 6,
  ) +
  geom_density_2d(
    data = dataToPlot %>% dplyr::filter(pop == "/gBT/CD69+"),
    contour_var = "ndensity", bins = 6,
    colour = "white") + 
    # aes(fill = ..level..), geom = "polygon", colour = "white") +
  coord_fixed() +
  theme(
    legend.title = element_blank(),
    legend.position = 'bottom'
    ) +
  facet_wrap(
    Treatment~uID+
      paste("HK p =", pp1.hopskel.p) +
      paste("HK H =", pp1.hopskel.H) +
      paste("CE p =", pp1.clarkevans.p) +
      paste("CE R =", pp1.clarkevans.R),
    ncol = 6) +
  scale_color_brewer(palette = "Set1")

ggsave(file.path(anaDir, "clusters_density.tiff"), height = 10, width = 22)
```

```{r fig_spatial_stats, fig.height = 3, fig.width = 3}
# plot out clark evans
dataToPlot <- exp.info %>%
  drop_na(pp1.clarkevans.R) %>%
  pivot_longer(
    cols = c("pp1.clarkevans.R", "pp2.clarkevans.R"),
    # cols = c("pp1.hopskel.H", "pp2.hopskel.H"),
    names_to = "spatial",
    values_to = "value"
  )

ggplot(dataToPlot, aes(Treatment, value, fill = spatial)) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    # width = 0.2, alpha = 1.0) +
  scale_fill_brewer(name = NULL, palette = "Set3") +
  theme(
    legend.position = "top"
    ) 
  # ylim(0, 1.5)
  # ylim(0, 1)

data.table::fwrite(dataToPlot, file.path(anaDir, "spatial_stats.csv"))
# ggsave(file.path(anaDir, "spatial_stats.tiff"), height = 2, width = 3)
```

```{r}
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)
# JL

# init ccia object
cciaObj <- initCciaObject(
  file.path(
    projectsDir, pID, "ANALYSIS", versionID, "8UdLBC"
  ),
  initReactivity = FALSE
)

uIDs <- names(cciaObj$cciaObjects())
uIDs <- uIDs[1:which(uIDs == "MwByx9")]

exp.info <- as.data.table(cciaObj$summary(
  withSelf = FALSE, fields = c("Attr")
))

# get ppp
popDT.CD69 <- cciaObj$popDT(
  popType = "flow", uIDs = uIDs, includeFiltered = TRUE,
  pops = c("/gBT", "/gBT/CD69+"))
```

```{r}
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

cciaObj <- initCciaObject(
  pID = pID, uID = "tYKNoG", versionID = versionID, initReactivity = FALSE
)

uIDs <- names(cciaObj$cciaObjects())

exp.info <- as.data.table(cciaObj$summary(
    withSelf = FALSE, fields = c("Attr")
    ))

# get ppp
popDT.CD69 <- cciaObj$popDT(
    popType = "flow", uIDs = uIDs, includeFiltered = TRUE,
    pops = c("/gBT", "/gBT/CD69+"))
```

```{r fig_CD69_stats, fig.height = 3, fig.width = 3}
summaryToPlot <- popDT.CD69 %>%
  group_by(uID, pop) %>%
  summarise(n = n()) %>%
  mutate(freq = n/sum(n)) %>%
  left_join(exp.info) %>%
  dplyr::filter(pop == "/gBT/CD69+")

ggplot(summaryToPlot, aes(
  Treatment, freq,
  fill = Treatment)) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    # position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    width = 0.2, alpha = 1.0) +
  scale_fill_brewer(name = NULL, palette = "Set3") +
  theme(legend.position = "none") +
  ylim(0, 1)

summaryToPlot$Treatment.ID <- 1
summaryToPlot[summaryToPlot$Treatment == "DTx",]$Treatment.ID <- 2

data.table::fwrite(summaryToPlot, file.path(anaDir, "CD69_all.csv"))
```

```{r fig_CD69_stats, fig.height = 1, fig.width = 1}
summaryToPlot <- popDT.CD69 %>%
  group_by(uID, flow.cell.is.clust, pop) %>%
  summarise(n = n()) %>%
  mutate(freq = n/sum(n)) %>%
  left_join(exp.info) %>%
  dplyr::filter(pop == "/gBT/CD69+", flow.cell.is.clust == FALSE)

ggplot(summaryToPlot, aes(
  Treatment, freq,
  fill = Treatment)) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    # position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    width = 0.2, alpha = 1.0) +
  scale_fill_brewer(name = NULL, palette = "Set3") +
  theme(legend.position = "none") +
  ylim(0, 1)

summaryToPlot$Treatment.ID <- 1
summaryToPlot[summaryToPlot$Treatment == "DTx",]$Treatment.ID <- 2

data.table::fwrite(summaryToPlot, file.path(anaDir, "CD69_non-clustered.csv"))
```

```{r fig_CD69_TRITC_stats, fig.height = 3, fig.width = 5}
# can you show distance of gBT CD69+/- to TRITC cells?
summaryToPlot <- popDT.CD69 %>%
  group_by(uID, pop, `flow.cell.contact#flow./O/TRITC`) %>%
  summarise(n = n()) %>%
  mutate(freq = n/sum(n) * 100) %>%
  left_join(exp.info) %>%
  dplyr::filter(`flow.cell.contact#flow./O/TRITC` == FALSE) %>%
  mutate(freq = 100 - freq)
  # group_by(uID, pop) %>%
  # summarise(freq = median(`flow.cell.min_distance#flow./O/TRITC`, rm.na = TRUE)) %>%
  # left_join(exp.info)

# ggplot(popDT.CD69 %>% left_join(exp.info),
#        aes(Treatment, `flow.cell.min_distance#flow./O/TRITC`, colour = pop)) +
ggplot(summaryToPlot, aes(Treatment, freq, colour = pop)) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    position = position_jitterdodge(jitter.width = 0.20), alpha = 1.0) +
    # width = 0.2, alpha = 1.0) +
  # geom_violin(outlier.alpha = 0, scale = "width") +
  scale_colour_brewer(name = NULL, palette = "Set1") +
  # theme(legend.position = "none") 
  ylim(0, 100)

summaryToPlot$Treatment.ID <- 1
summaryToPlot[summaryToPlot$Treatment == "DTx",]$Treatment.ID <- 2

data.table::fwrite(summaryToPlot, file.path(anaDir, "TRITC_contact.csv"))
```

```{r}
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE, projectsDir = projectsDir)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "tYKNoG", versionID = versionID, initReactivity = FALSE
)

exp.info <- as.data.table(cciaObj$summary(withSelf = FALSE, fields = c("Attr")))

# get ppp
popDT.clustered <- cciaObj$popDT(
    popType = "flow", includeFiltered = TRUE,
    pops = c("/gBT", "/gBT/clustered"))
```

```{r fig_CD69_stats, fig.height = 3, fig.width = 3}
summaryToPlot <- popDT.clustered %>%
  group_by(uID, pop) %>%
  summarise(n = n()) %>%
  mutate(freq = n/sum(n) * 100) %>%
  left_join(exp.info) %>%
  dplyr::filter(pop == "/gBT/clustered")

ggplot(summaryToPlot, aes(
  Treatment, freq,
  fill = Treatment)) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    # position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    width = 0.2, alpha = 1.0) +
  scale_fill_brewer(name = NULL, palette = "Set3") +
  theme(legend.position = "none") +
  ylim(0, 100)

summaryToPlot$Treatment.ID <- 1
summaryToPlot[summaryToPlot$Treatment == "DTx",]$Treatment.ID <- 2

data.table::fwrite(summaryToPlot, file.path(anaDir, "gBT_clusters.csv"))
```
