---
title: "Run modules"
output: html_document
date: '2022-08-16'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Examples to run functions and modules

```{r}
# set test variables
pID <- "Lq0joh"
versionID <- 11
projectsDir <- "/Volumes/Analysis_SSD/Dominik/cecelia/projects/"
hpcDir <- "/data/scratch/projects/punim1124/cecelia/USERS/schienstockd/"
```

```{r}
# HPC config
HPC_CONF <-  list(
  hpc = list(
    conf = list(
      email = "schienstockd@student.unimelb.edu.au",
      emailOnBegin = FALSE,
      emailOnEnd = FALSE,
      emailOnFail = TRUE,
      numNodes = 1,
      numTasks = 1,
      numCPUperTask = 1,
      numGPUperTask = 1,
      memory = 50,
      walltime = "00-01:00:00",
      projectPartitions = "physical",
      # projectPartitions = "shortgpgpu,gpgpu",
      projectID = "punim1124",
      # projectID = "punim1031",
      useGPU = FALSE
      # useGPU = TRUE
    )
  ),
  utils = list(
    ssh = list(
      username = "schienstockd",
      address = "spartan.hpc.unimelb.edu.au",
      keyfile = "/Users/schiend/.ssh/spartan_rsa"
    ),
    python = list(
      condaEnv = cciaConf()$python$conda$source$env,
      condaDir = cciaConf()$python$conda$dir
    )
  )
)
```

```{r}
anaDir <- "/Volumes/USER_data/Dominik/Experiments/JL-ANALYSIS/vib/RESULTS/OUT"
```

```{r}
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia")

library(ggplot2)
library(tidyverse)
```

```{r}
# Load cluster data
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "R47v2u", versionID = versionID, initReactivity = FALSE
)

cciaObj$popDT("flow", popCols = c("TRITC", "gBT-CTDR"))
```

```{r}
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "KuJu1C", versionID = versionID, initReactivity = FALSE
)

uIDs <- c(
  # "R47v2u", "NLjHAe", "PqtUCE", "aaDoip", "z2oi2l"
  "R47v2u"
)

funParams <- list(
  popType = "flow",
  maxClusterDist = 5,
  minCellNum = 4,
  popsToCluster = c("/gBT+")
)

cciaObj$runTasks(
  funName = "spatialAnalysis.cellClustersMeshes",
  funParams = funParams,
  runInplace = FALSE,
  env = "hpc",
  envVars = HPC_CONF,
  hpcDir = paste(hpcDir, pID, "ANALYSIS", sep = "/"),
  taskID = 1,
  uIDs = uIDs
)
```

```{r}
# Load cluster data
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "KuJu1C", versionID = versionID, initReactivity = FALSE
)

# define uIDs
uIDs <- names(cciaObj$cciaObjects())

# get experimental info
exp.info <- as.data.table(cciaObj$summary(
  withSelf = FALSE, fields = c("Attr"), uIDs = uIDs
))

# complete info
exp.info[uID == "R47v2u", Genotype := "B6"]
exp.info[uID == "NLjHAe", Genotype := "B6"]
exp.info[uID == "PqtUCE", Genotype := "B6"]
exp.info[uID == "aaDoip", Genotype := "IAE"]
exp.info[uID == "z2oi2l", Genotype := "IAE"]

popPaths("flow", includeFiltered = TRUE)

# get pops
popDT <- cciaObj$popDT(
  popType = "flow", includeFiltered = TRUE,
  pops = c("/gBT+", "/gBT+/clustered")
)
```

```{r fig_pops_umap, fig.height=2, fig.width=2}
library(tidyverse)

dfToPlot <- copy(popDT)

# get mean positions of clusters
meanClusterPos <- dfToPlot %>%
  group_by(pop) %>%
  summarise(
    UMAP_1 = mean(UMAP_1),
    UMAP_2 = mean(UMAP_2)
  )

# plot UMAP with paga connections
ggplot(
  dfToPlot,
  aes(UMAP_1, UMAP_2)
  ) +
  theme_classic() +
  geom_point(aes(color = pop), size = 0.5) +
  # scale_color_brewer(name = NULL, palette = "Set3") +
  scale_color_manual(values = c("black", "#00ccff", "#e10f21", "#33cc00")) +
  theme(
    axis.text = element_text(size = 15),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    legend.justification = "right",
    # legend.position = "bottom"
    legend.position = "none",
    axis.line = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
    )

ggsave(file.path(anaDir, "uamp.tiff"), width = 5, height = 5)
```

```{r}
# plot frequency of contact from clustering cells
popDT <- cciaObj$popDT(
  popType = "clust",
  # pops = c("gBT+/contact.clust.XCR1+"),
  pops = c("gBT+/clustered", "gBT+/non.clustered"),
  includeFiltered = TRUE,
  completeDT = TRUE,
  replaceNA = TRUE
)
```

```{r fig_clust_XCR1, fig.height=2, fig.width=1.5}
summaryDF <- popDT %>%
  group_by(uID, pop, `clust.cell.contact#clust.XCR1+`) %>%
  summarise(n = n()) %>%
  mutate(freq = n/sum(n) * 100) %>%
  dplyr::filter(
    `clust.cell.contact#clust.XCR1+` == TRUE
  )

summaryDF$pop.id <- 1
summaryDF[summaryDF$pop == "gBT+/clustered", ]$pop.id <- 2

ggplot(summaryDF, aes(pop, freq)) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    # position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    width = 0.3, alpha = 1.0) +
  theme(
    axis.text.x = element_text(
      angle = 45, vjust = 1, hjust = 1, size = 15),
    )

t.test(
  summaryDF[summaryDF$pop == "gBT+/clustered",]$freq,
  summaryDF[summaryDF$pop == "gBT+/non.clustered",]$freq,
  paired = TRUE
)

write.csv(summaryDF, file.path(anaDir, "XCR1-contact.csv"))
```

```{r fig_clust_TRITC, fig.height=2, fig.width=1.5}
summaryDF <- popDT %>%
  group_by(uID, pop, `clust.cell.contact#clust.TRITC+`) %>%
  summarise(n = n()) %>%
  mutate(freq = n/sum(n) * 100) %>%
  dplyr::filter(
    `clust.cell.contact#clust.TRITC+` == TRUE
  )

summaryDF$pop.id <- 1
summaryDF[summaryDF$pop == "gBT+/clustered", ]$pop.id <- 2

ggplot(summaryDF, aes(pop, freq)) +
  theme_classic() +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(
    # position = position_jitterdodge(jitter.width = 0.10), alpha = 1.0) +
    width = 0.3, alpha = 1.0) +
  theme(
    axis.text.x = element_text(
      angle = 45, vjust = 1, hjust = 1, size = 15),
    )

t.test(
  summaryDF[summaryDF$pop == "gBT+/clustered",]$freq,
  summaryDF[summaryDF$pop == "gBT+/non.clustered",]$freq,
  paired = TRUE
)

write.csv(summaryDF, file.path(anaDir, "TRITC-contact.csv"))
```

```{r fig_gating, fig.height=2, fig.width=2}
# show gating of CD69 populations
devtools::load_all("../")
cciaUse("~/Desktop/DOHERTY/cecelia", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  # pID = pID, uID = "15SFzg", versionID = versionID, initReactivity = FALSE
  pID = pID, uID = "QS9obm", versionID = versionID, initReactivity = FALSE
)

cciaObj$editPopColour(
  popType = "flow", colour = "#ff1493",
  popID = cciaObj$popIDFromPath(cciaObj$imPopMap("flow"), "/gBT+/CD69+"))

# get raster contours
p1s <- .flowPlotGatedRaster(
  cciaObj, popPaths = "/gBT+/CD69+", size = 2, color = "black",
  labelSize = 4)

ggpubr::ggarrange(plotlist = p1s, nrow = 1, ncol = 1)
ggsave(file.path(anaDir, paste0("CD69_gating_", cciaObj$getUID(), ".pdf")),
       width = 3, height = 3)
```


