---
title: "Run modules"
output: html_document
date: '2022-08-16'
---

```{r setup, include=FALSE}
renv::load("~/R-workspace/cecelia/")
knitr::opts_chunk$set(echo = TRUE)
```

## Examples to run functions and modules

```{r}
Sys.setenv(KMP_DUPLICATE_LIB_OK = "TRUE")
# set test variables
projectsDir <- "~/cecelia/projects"
```

```{r}
anaDir <- "~/GDrive/Notebook/ANALYSIS/XCR1-paper/OUT"
```

```{r}
library(flowWorkspace)

# Load cluster data
devtools::load_all("../")
cciaUse("~/cecelia/dev")

library(ggplot2)
library(tidyverse)
```

```{r}
pID <- "Lq0joh" # CD69 vib
versionID <- 11

# check distribution of CD69+ and TRITC
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "tYKNoG", versionID = versionID, initReactivity = FALSE
)

uIDs <- names(cciaObj$cciaObjects())

# Try SPIAT options
pops <- c("/gBT", "/gBT/CD69+", "/O/TRITC")

# get SPIAT object
pp1 <- cciaObj$ppp(
  popType = "flow", pops = pops, completeDT = FALSE, uIDs = uIDs, marksAsPop = TRUE)
popDT <- cciaObj$popDT(
  popType = "flow", pops = pops, completeDT = FALSE, uIDs = uIDs)
```

```{r fig_SPIAT_dist, fig.height = 5, fig.width = 5}
# compare to
# https://trigosteam.github.io/SPIAT/articles/cell-colocalisation.html#cross-k-function

y <- "/gBT/CD69+"
x <- "/O/TRITC"

pdf(file.path(anaDir, "Kcross.inhom.pdf"), height = 5, width = 5)
for (i in uIDs) {
  p1 <- ggplot(popDT[uID == i & pop %in% c(x, y)], aes(centroid_x, centroid_y, color = pop)) +
    theme_classic() +
    plotThemeDark() +
    geom_point(alpha = 0.8) +
    coord_fixed() +
    theme(
      axis.text.x = element_blank(),
      axis.ticks.x = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank(),
      axis.line = element_blank(),
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      legend.title = element_blank()
    ) +
    scale_colour_manual(values = list(
      "/gBT/CD69+" = "#01FF01", "/O/TRITC" = "red"
    ))
  plot(p1)
  
  p1 <- spatstat.explore::Kcross.inhom(pp1[[i]], x, y, correction = "border")
  
  plot(p1, main = paste(x, "v", y, "-", i))
}
dev.off()
```

```{r}
# check number of clusters for HMM
# I'm not sure how to apply this to depmixS4::fit
# you must create a helper function that takes the dataframe and number of clusters
# then returns the clustering result.. ?
# a partitioning function which accepts as first argument a (data) matrix like x, second argument, say k, k >= 2, the number of clusters desired, and returns a list with a component named cluster which contains the grouping of observations.

pID <- "8BR53W" # XCR1-DTx
versionID <- 1

# get populations and show maps
devtools::load_all("../")
cciaUse("~/cecelia/dev", initConda = FALSE)

# init ccia object
cciaObj <- initCciaObject(
  pID = pID, uID = "ZXcUMO", versionID = versionID, initReactivity = FALSE
)

# get experimental info
exp.info <- as.data.table(cciaObj$summary(withSelf = FALSE, fields = c("Attr")))
uIDs <- exp.info[Include == "Y"]$uID

# sample uIDs
# Error: vector memory limit of 16.0 Gb reached, see mem.maxVSize()
uIDs <- sample(uIDs, 6)

modelMeasurements <- c("live.cell.speed", "live.cell.angle")
set.seed(28)

# get DT for HMM fit
tracks.DT <- tracks.build.hmm.dt(
  cciaObj, uIDs, "live", c("tcells.gBT/tracked", "tcells.gDT/tracked"),
  modelMeasurements, noiseFilterMeasurements = 5
)
```


```{r}
get.hmm <- function(DT, k = 1) {
  hmm_model <- depmixS4::depmix(
    lapply(
      modelMeasurements,
      function(x) eval(parse(text = sprintf("`%s`~1", x)))
      ),
    data = tracks.DT[, ..modelMeasurements],
    nstates = k,
    ntimes = tracks.DT[, .(num.cells = .N),
                       by = .(value_name, uID, track_id)]$num.cells,
    # gaussian by default
    family = rep(list(gaussian()), length(modelMeasurements))
  )
  
  # fit
  hmm_fit <- depmixS4::fit(hmm_model)
  
  # predict
  hmm_predict <- depmixS4::posterior(hmm_fit)
  
  # add to tracks
  list(cluster = hmm_predict$state)
}

hmm.elbow <- factoextra::fviz_nbclust(tracks.DT, get.hmm, method = "silhouette")
```

```{r fig_HMM_nbclust, fig.height = 5, fig.width = 7}
pdf(file.path(anaDir, "hmm_elbow.pdf"), height = 3, width = 5)
hmm.elbow
dev.off()
```

