// Build frontend/src/icons.css — the app's icon set — from the Lucide names in
// frontend/src/lib/iconLegend.ts. Run `pixi run icons` after adding or changing a glyph there.
//
// Each glyph is the Lucide SVG inlined as a CSS mask on the class authors already write
// (`<i class="pi pi-trash">`), so it takes `color` like the icon font did and no call site changed
// when the set moved off PrimeIcons (docs/todo/PRIMEVUE_RETIRE_PLAN.md, P4). Only the glyphs the
// legend lists are vendored: the npm packages ship all ~2,000 (20–50 MB) and every install runs
// `npm install`. The output is committed; `iconLegend.test.ts` fails when it drifts from the legend.
//
// Needs network once per run: it fetches the pinned lucide-static tarball with `npm pack`.
import { execFileSync } from 'node:child_process'
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const LUCIDE = '1.49.0'
const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const legendPath = join(root, 'frontend/src/lib/iconLegend.ts')
const outPath = join(root, 'frontend/src/icons.css')

// `{ icon: 'pi-x', lucide: 'y'[, fill: true], means: …` — the entry shape iconLegend.ts declares
const ENTRY = /\{ icon: '(pi-[a-z0-9-]+)', lucide: '([a-z0-9-]+)'(, fill: true)?, means:/g
const entries = [...readFileSync(legendPath, 'utf-8').matchAll(ENTRY)]
  .map(m => ({ icon: m[1], lucide: m[2], fill: !!m[3] }))
if (entries.length < 80) throw new Error(`only ${entries.length} legend entries parsed — has the entry shape changed?`)

const tmp = mkdtempSync(join(tmpdir(), 'cc-lucide-'))
try {
  const npm = process.platform === 'win32' ? 'npm.cmd' : 'npm'
  const tgz = execFileSync(npm, ['pack', `lucide-static@${LUCIDE}`, '--silent'], { cwd: tmp, encoding: 'utf-8', shell: process.platform === 'win32' }).trim()
  execFileSync('tar', ['xzf', tgz], { cwd: tmp })

  const svgOf = (name, fill) => {
    let svg = readFileSync(join(tmp, 'package/icons', `${name}.svg`), 'utf-8')
    svg = svg.replace(/<!--[\s\S]*?-->/g, '').replace(/\s*class="[^"]*"/, '').replace(/\s+/g, ' ')
      .replace(/> </g, '><').trim()
    // a mask reads alpha only, so the paint colour is irrelevant — `currentColor` would also do
    svg = svg.replace('stroke="currentColor"', 'stroke="#000"')
    if (fill) svg = svg.replace('fill="none"', 'fill="#000"')
    return svg
  }

  // single-quote the attributes and escape only what a data URI needs — about 40% smaller than
  // encodeURIComponent, and still readable in devtools
  const dataUri = svg => 'data:image/svg+xml,' + svg.replace(/"/g, "'").replace(/[%#<>{}]/g, encodeURIComponent)
  const rules = entries.map(e =>
    `.pi-${e.icon.slice(3)} { --cc-icon: url("${dataUri(svgOf(e.lucide, e.fill))}"); } /* lucide: ${e.lucide}${e.fill ? ' (filled)' : ''} */`)

  const css = `/* GENERATED by scripts/vendor_icons.mjs from frontend/src/lib/iconLegend.ts — do not edit.
   Edit the legend, then run \`pixi run icons\`.

   Icons: Lucide ${LUCIDE} (https://lucide.dev), ISC License,
   Copyright (c) 2026 Lucide Icons and Contributors. Permission to use, copy, modify, and/or
   distribute this software for any purpose with or without fee is hereby granted, provided that the
   above copyright notice and this permission notice appear in all copies. THE SOFTWARE IS PROVIDED
   "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE.

   In the lowest layer, so any rule in the app outranks the 1rem baseline — as the icon font's did. */
@layer cc-base {
  .pi {
    display: inline-block;
    font-size: 1rem;
    line-height: 1;
    vertical-align: -0.125em;
    flex-shrink: 0;
    /* no glyph class → nothing drawn, as the font drew nothing (an unset mask shows the whole box) */
    --cc-icon: linear-gradient(transparent, transparent);
  }
  /* The glyph is painted on a pseudo-element, not the <i> itself, so the <i> stays the box the font
     glyph sat in: a rule giving it a background, padding or border-radius (a badge's backing disc)
     draws behind the glyph instead of repainting it. A block, so the <i>'s baseline stays its
     bottom edge; centred, so a wider <i> centres it as \`text-align: center\` centred the font. */
  .pi::before {
    content: '';
    display: block;
    width: 1em;
    height: 1em;
    margin: 0 auto;
    background-color: currentColor;
    -webkit-mask: var(--cc-icon) center / contain no-repeat;
    mask: var(--cc-icon) center / contain no-repeat;
  }
  .pi-spin { animation: cc-icon-spin 1s linear infinite; }
  @keyframes cc-icon-spin { to { transform: rotate(360deg); } }
  /* frozen, not removed: the glyph still says "working" */
  @media (prefers-reduced-motion: reduce) { .pi-spin { animation-duration: 1ms; } }

${rules.map(r => '  ' + r).join('\n')}
}
`
  writeFileSync(outPath, css, 'utf-8')
  console.log(`icons.css: ${entries.length} glyphs from lucide-static@${LUCIDE}`)
} finally {
  rmSync(tmp, { recursive: true, force: true })
}
